### ISSUE TITLE
"Bad message" error when trying to use DBus

### ISSUE THREAD

**Issue by mh-g** [AsamK/signal-cli#100]
I am trying to use signal-cli with the DBus interface on a Raspberry Pi. I proceed as described in "DBus service", have added a new user "signal-cli" and copied the existing configuration to `/home/signal-cli/.config/signal` and adjusted user rights to the signal-cli user and signal-cli group.
I removed the `--config /var...` part in `/etc/systemd/system/signal.service`.

`sudo systemctl daemon-reload` works fine, but `sudo systemctl enable signal.service` gives:
`Failed to execute operation: Bad message`

What does this error mean? What do I have to fix?

**Comment by AsamK** [comment]
This is a systemd error, it's an indication for a syntax error in the systemd service unit file.
`systemctl enable` only enables the service to start at boot time, it doesn't start signal-cli yet.

**Comment by mh-g** [comment]
I checked the file and fixed it. Just received the first message sent via dbus-system.

Thanks!
