### ISSUE TITLE
How to recover from "Error loading state file for user ...: Runtime reflection is not supported for LegacyContactInfo()"?

### ISSUE THREAD

**Issue by tanuva** [AsamK/signal-cli#1000]
Hi,

I have signal-cli running on my home server with one Linux user account being the Signal account owner and one Linux user account (for nagios) that is a linked device in Signal terms. Sending and receiving messages with the nagios user works nicely, that one regularly runs the "receive" command, too.

For my "personal" owner-account I failed to set up regular receiving. When I try to send a message (or receive) with it, I see the following message:
```
Error loading state file for user ...: Runtime reflection is not supported for public org.asamk.signal.manager.storage.contacts.LegacyContactInfo() (UnsupportedFeatureError)
```

I suspect the problem linked to the account not having sent/received messages in a few weeks. How can I recover from this state?

This is arm64 Signal on Debian Bullseye from [this repository](https://packaging.gitlab.io/signal-cli) and openjdk version "17.0.4" 2022-07-19.

**Comment by AsamK** [comment]
Looks like you're using the native compiled version (graalvm nativeimage), that doesn't support all use cases.
Try running the non-native version at least once, to migrate the config file.

**Comment by tanuva** [comment]
That worked very nicely. Thank you very much for the tip! \o/
