### ISSUE TITLE
Issues with libsignal-client 0.19.3 (undefined symbol: d2i_X509_CRL)

### ISSUE THREAD

**Issue by maximbaz** [AsamK/signal-cli#1001]
After upgrading `libsignal-client` to `0.19.3` I am no longer able to use `signal-cli`:

```sh
$ signal-cli listContacts
WARN  ServiceConfig - Failed to call libsignal-client: /usr/lib/libsignal_jni.so: /usr/lib/libsignal_jni.so: undefined symbol: d2i_X509_CRL
Missing required native library dependency: libsignal-client
```

Downgrading `libsignal-client` to `0.18.1` makes that command succeed.

I'm not quite sure how to debug this further, do you have some ideas?

```sh
$ signal-cli --version
signal-cli 0.10.11
```

**Comment by AsamK** [comment]
Does it work with the latest version? (signal-cli 0.11.0 and libsignal-client 0.20.0)

**Comment by maximbaz** [comment]
Unfortunately not, same problem with the new versions.

**Comment by maximbaz** [comment]
I'm on the latest Arch. Thanks for your comment, it helped me to narrow down repro steps!

The issue lies somewhere within `AUR/libsignal-client`, which I see you are a maintainer of 🙂 

If it's built using `makepkg`, the issue is not reproducible!

If however it's built in a clean chroot environment, like all official Arch packages are, isolated from my normal system, then this issue appears. 
To reproduce, you can install `devtools` package, `cd` into the folder with `PKGBUILD` of `libsignal-client`,  and run `extra-x86_64-build` command. The package will be created in the current directory, which you can then install using `pacman -U <pkg-name>` and reproduce the issue by using `signal-cli` like `signal-cli listContacts`.

I'm quite puzzled by this, to be honest 🤔  I compared build logs between the two approaches, and I can't find any meaningful difference... Since the difference is in building in isolated vs "dirty" environment, my best guess is that we are missing some `makedepends` entry... Adding an obvious `openssl` doesn't seem to be doing the trick 🤔 

The issue only appeared since `0.19.3`, and I have a hard time finding what is it between `0.19.2` and `0.19.3` that could have caused this issue...

I also reproduce it on two difference machines (asked a friend on their Arch to reproduce).

Maybe you have some ideas?

We can also move the discussion to elsewhere, if it's more appropriate, now that we know the issue is probably not within `signal-cli`.

**Comment by AsamK** [comment]
Interesting, i can indeed reproduce it. I previously built the package with `makechrootpkg` and that produced a working version.
Comparing the two packages I found this:
```
-options = !lto
+options = lto
```

Looks like the arch lto option doesn't work with libsignal-client ...
Maybe related to this: https://github.com/signalapp/libsignal/blob/2f07edaa02ea9f882c446f1366604923746026ba/java/build_jni.sh#L21

**Comment by maximbaz** [comment]
Ohh, good catch! I confirm that the latest AUR package works as expected, thanks! Will close as I guess there's not much else we can do about it for now...
