### ISSUE TITLE
Error for new recipient: Got new recipient, both uuid and number are unknown

### ISSUE THREAD

**Issue by jokebattle3** [AsamK/signal-cli#1002]
Hello,

suddenly for income messages from new, unknown contacts I receive the following error in the signal-cli.log:

2022-08-26T20:46:05.725+0200 [receive-1] DEBUG o.a.s.m.s.recipients.RecipientStore - Got new recipient, both uuid and number are unknown
2022-08-26T20:46:05.725+0200 [receive-1] DEBUG o.a.s.m.s.recipients.RecipientStore - Adding new recipient RecipientId[id=778] with address RecipientAddress[uuid=Optional[80b99162-db86-44a4-8909-REPLACED_THIS_FOR_PRIVACY_REASON], number=Optional.empty]

The Phone-Number I receive via the DBUS-Interface is this long chars-number-mix number.

I expect a phone number from signal-cli for the recipient at this point.

what could be the reason?

Thanks for your help!

**Comment by AsamK** [comment]
I think the reason is a change on Signal-Server side, where they removed the phone number from the message envelope. So signal-cli now only seed the sender's account UUID.
I need to check if there's a new way for sending/receiving phone numbers.

When you respond to a new unknown contact (and thus transfer your phone number) and then receive another message from them, then you should be able to see the phone number. (because with a profile key, the sender will send a unidentified sender message, with the encrypted sender phone number)

**Comment by ionwerz** [comment]
> When you respond to a new unknown contact (and thus transfer your phone number) and then receive another message from them, then you should be able to see the phone number. (because with a profile key, the sender will send a unidentified sender message, with the encrypted sender phone number)

This is true but only for the official clients, when I respond to unknown contact I get the phone number. But with signal-client it's not work as mentioned

**Comment by AsamK** [comment]
This scenario does work for me with signal-cli:
- A and B don't know each other
- A sends message to B (unknown phone number)
- B sends message to A (with phone number)
- A sends message to B (with phone number)

(All under the assumption that phoneNumberSharingMode is not disabled)

**Comment by ionwerz** [comment]
> This scenario does work for me with signal-cli:
> - A and B don't know each other
> - A sends message to B (unknown phone number)
> - B sends message to A (with phone number)
> - A sends message to B (with phone number)
> 
> (All under the assumption that phoneNumberSharingMode is not disabled)

At this scenario
- A is official client?
- B is signal-cli?
If yes, how do you able to answer from B (signal-cli) if you don't get the phone number from envelope but only UUID and the only option to send message is to specify the phone number.

Also in vice versa scenario:
- A is signal-cli
- B is official client
When I send message first from A to B it is Unknow, I answer from B to A, it is still Unknown, I have send more than 10 messages to each other, but official client do not get the contact phone number, I'm not able to view the safety number.

> (All under the assumption that phoneNumberSharingMode is not disabled)

How to enable/disable ```
phoneNumberSharingMode
``` in signal-cli or official client?

**Comment by AsamK** [comment]
In signal-cli you can send messages to uuids, by just using the uuid where a phone number is expected. This is just not documented yet.
The phoneNumberSharingMode is currently behind a feature flag in the official clients and in signal-cli can only be changed by editing the account file manually. So if you haven't done that it will be enabled.

**Comment by ionwerz** [comment]
So here is the result with the latest `master` build.
Scenario:
- A and B do not know each other
- A is a signal-cli client
- B is a android official client
`signal-cli -u +987654321 send -m "Test" +123456789`
Log:
```
WARN  ManagerImpl - No profile name set. When sending a message it's recommended to set a profile name wit the updateProfile command. This may become mandatory in the future.
Failed to send (some) messages:
+123456789: Untrusted Identity for "+123456789"
1661761696459
Failed to send message due to untrusted identities
```
`signal-cli -u +987654321 trust -a +123456789`
`signal-cli -u +987654321 send -m "Test" +123456789`
Android:
![photo_2022-08-29 10 44 39](https://user-images.githubusercontent.com/28632070/187161697-792f4c32-7a8f-4019-a86b-887d1e67565d.jpeg)
![photo_2022-08-29 10 44 42](https://user-images.githubusercontent.com/28632070/187162173-6b4a2e74-df01-4497-b76c-e7e1202d9f20.jpeg)

`signal-cli -u +987654321 receive` 
Log:
```
Envelope from: +123456789 (device: 1)
Timestamp: 1661761735289 (2022-08-29T08:28:55.289Z)
Server timestamps: received: 1661761739459 (2022-08-29T08:28:59.459Z) delivered: 1661761822398 (2022-08-29T08:30:22.398Z)
Received a receipt message
  When: 1661761739459 (2022-08-29T08:28:59.459Z)
  Is delivery receipt
  Timestamps:
  - 1661761735289 (2022-08-29T08:28:55.289Z)

Envelope from: +123456789 (device: 1)
Timestamp: 1661761742312 (2022-08-29T08:29:02.312Z)
Server timestamps: received: 1661761746746 (2022-08-29T08:29:06.746Z) delivered: 1661761822398 (2022-08-29T08:30:22.398Z)
Received a receipt message
  When: 1661761746746 (2022-08-29T08:29:06.746Z)
  Is delivery receipt
  Timestamps:
  - 1661761742312 (2022-08-29T08:29:02.312Z)

Envelope from: “DKJ” +123456789 (device: 1)
Timestamp: 1661761781626 (2022-08-29T08:29:41.626Z)
Server timestamps: received: 1661761781915 (2022-08-29T08:29:41.915Z) delivered: 1661761822399 (2022-08-29T08:30:22.399Z)
Sent by unidentified/sealed sender
Message timestamp: 1661761781626 (2022-08-29T08:29:41.626Z)
Profile key update
With profile key

Envelope from: “DKJ” +123456789 (device: 1)
Timestamp: 1661761781691 (2022-08-29T08:29:41.691Z)
Server timestamps: received: 1661761782081 (2022-08-29T08:29:42.081Z) delivered: 1661761822399 (2022-08-29T08:30:22.399Z)
Sent by unidentified/sealed sender
Received a receipt message
  When: 1661761781691 (2022-08-29T08:29:41.691Z)
  Is read receipt
  Timestamps:
  - 1661761742312 (2022-08-29T08:29:02.312Z)

Envelope from: “DKJ” +123456789 (device: 1)
Timestamp: 1661761802702 (2022-08-29T08:30:02.702Z)
Server timestamps: received: 1661761802856 (2022-08-29T08:30:02.856Z) delivered: 1661761822399 (2022-08-29T08:30:22.399Z)
Sent by unidentified/sealed sender
Message timestamp: 1661761802702 (2022-08-29T08:30:02.702Z)
Body: Test reply
With profile key
```
Then I have send few messages vice versa:
![photo_2022-08-29 10 44 44](https://user-images.githubusercontent.com/28632070/187162436-6b347b30-5d49-4243-80f5-d78c4a23ab4b.jpeg)

View the Unknown user profile:
![photo_2022-08-29 10 44 45](https://user-images.githubusercontent.com/28632070/187162581-d4cc57dd-0967-4f20-b2d3-f5ff42687049.jpeg)

Try to verify safety number:
![photo_2022-08-29 10 44 47](https://user-images.githubusercontent.com/28632070/187162675-1cf6e6c3-18f8-4231-a963-d4a298b5875c.jpeg)

As you can see the B still is not able to get the A phone number, what I'm doing wrong?

**Comment by AsamK** [comment]
Thanks for the detailed testing, I tried it again with a new account and could finally reproduce it. signal-cli used the wrong default value when phoneNumberSharingMode wasn't set ...
Can you try again with the latest master?

**Comment by ionwerz** [comment]
Can confirm that next scenario is working:
- A and B do not know each other
- A is a signal-cli client
- B is a android official client
- A sends message to B (unknown phone number)
- B sends message to A (with phone number)
- A sends message to B (with phone number)

Now vice versa:
- A and B do not know each other
- A is a android official client
- B is a signal-cli client
- A sends message to B (unknown phone number)
- The first answer has to be on UUID only?

**Comment by jokebattle3** [comment]
Thanks for all the work and investigation!

With signal-cli 0.10.11 i'm not able to send a message via UUID.

When sending via DBUS with UUID "XYZ-5618-4dd7-83f7-XYZ" (where as XYZ is placeholder for pricacy reason), signal-cli throws the error "Failed to send message: Unregistered user "+XYZ56184dd783f7XYZ".

How can I pass the UUID to the signal-cli via DBUS?
