### ISSUE TITLE
Wrong ELF class on Raspberry Pi

### ISSUE THREAD

**Issue by Pyrofer** [AsamK/signal-cli#1004]
I did an install which gave this error,

`OpenJDK Client VM warning: You have loaded library /tmp/resource585932640520176462.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
WARN  ServiceConfig - Failed to call libsignal-client: /tmp/resource585932640520176462.so: /tmp/resource585932640520176462.so: wrong ELF class: ELFCLASS64 (Possible cause: can't load AMD 64 .so on a ARM platform)
Missing required native library dependency: libsignal-client`

I removed it and did a build locally on the Pi, and get the same error.
If I just type "./signal-cli" It seems to run and tells me I am missing arguments. When I provide them however it fails.

**Comment by AsamK** [comment]
For the raspberrypi you need to compile the native libsignal library yourself: https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal
