### ISSUE TITLE
Register fails with "Bad response 500"

### ISSUE THREAD

**Issue by Knallcharge** [AsamK/signal-cli#1008]
Hi,

I have tried to register a phone number with signal-cli, I'm required to provide a CAPTCHA which I successfully retrieved, but the answer I'm getting (tried with different numbers) is always this:
Failed to register: [500] Bad response: 500

Any help is appreciated as this is all I'm getting, I have no other information about what might go wrong ...

**Comment by Knallcharge** [comment]
I have checked the source code for the error and found the words in RegisterCommand.java, so I guess the error must be a NonNormalizedPhoneNumberException or IOErrorException. I checked the number in several examples and it should be correct, so what would the IOError "Bad response: 500" mean? I have to use a captcha, could this error mean that there's something wrong with that (expired, wrong format, plain wrong)?

**Comment by AsamK** [comment]
There have been some changes to the register code in signal-cli and the Signal-Server, please open a new issue if the problem appears with the latest version.
