### ISSUE TITLE
Signal-cli long delay sending messages

### ISSUE THREAD

**Issue by psycle91** [AsamK/signal-cli#101]
Hi,

i have integraded signal-cli in Icinga2:

I'm calling it via script: 

 signal-cli -u +49xxxxxxx send -m  "$NOTIFICATIONTYPE  - $HOSTDISPLAYNAME - $SERVICEDISPLAYNAME is $SERVICESTATE - $SERVICEOUTPUT" $USERPAGER

I'm getting timeouts in the Icinga2 and syslog, it taking to long time. 

It is also a huge delay if i sending the alerts from the shell:

signal-cli -u +49xxxxxx send -m "Test123" +49xxxxxxxxxxx

It takes up to 30 second to send 1 message.

I'm using the signal-cli version 0.5.6 on debian 8.7 with java-7-openjdk-amd64.

Any suggestions?
----------
 java -XshowSettings:properties -version
Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    file.encoding = UTF-8
    file.encoding.pkg = sun.io
    file.separator = /
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path = .
    java.class.version = 51.0
    java.endorsed.dirs = /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/endorsed
    java.ext.dirs = /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext
        /usr/java/packages/lib/ext
    java.home = /usr/lib/jvm/java-7-openjdk-amd64/jre
    java.io.tmpdir = /tmp
    java.library.path = /usr/java/packages/lib/amd64
        /usr/lib/x86_64-linux-gnu/jni
        /lib/x86_64-linux-gnu
        /usr/lib/x86_64-linux-gnu
        /usr/lib/jni
        /lib
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.7.0_151-b01
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.7
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.7.0_151
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.7
    java.vm.vendor = Oracle Corporation
    java.vm.version = 24.151-b01
    line.separator = \n
    os.arch = amd64
    os.name = Linux
    os.version = 3.16.0-4-amd64
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.class.path = /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/resources.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/sunrsasign.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jsse.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jce.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/charsets.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rhino.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jfr.jar
        /usr/lib/jvm/java-7-openjdk-amd64/jre/classes
    sun.boot.library.path = /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64
    sun.cpu.endian = little
    sun.cpu.isalist =
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = UTF-8
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level = unknown
    user.country = US
    user.dir = /root
    user.home = /root
    user.language = en
    user.name = root
    user.timezone =

java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)
----------------

**Comment by mh-g** [comment]
There is no information about the underlying hardware (except AMD64). I had the same problem on a Raspberry Pi. Initializing Java takes ages. Have you considered using Signal with DBus? That way, you only initialize Java once and thereafter use a more lightweight language. The signal-cli Wiki page on DBus is a good manual.

I am currently working on Python scripts that allow sending to single recipients (done), sending to groups (open) and receiving from signal-cli (open).

Pythons DBus implementation has a (default?) timeout that is shorter than starting Java, so the first message is always lost.

**Comment by rotmajster** [comment]
Im having it on Raspberry, too. Sending one message takes 41 seconds:(.

**Comment by Trolldemorted** [comment]
Are you sure the delay comes from initializing java?

If your system's entropy is drained, `/dev/random` reads will block, and signal-cli stalls until enough entropy is there. I am using signal-cli in a debian vm (which is mostly idle) and it runs out of entropy very soon, perhaps you are experiencing the same issue.

**Comment by mh-g** [comment]
Using DBus, it takes one or two seconds to send a message on the same hardware. Starting up the DBus daemon takes long, but not sending the messages. IMO this is a good indicator of a Java problem. Plus, Java consumes about 60% of the RAM. I consider moving from Raspberry Pi 3 to a system with 2 GB of RAM ...

**Comment by psycle91** [comment]
Sorry for the delay, i have setup icinga-cli as a systemd service. After that i will trigger sending messages via DBus and it works great!  Thank's a lot for your support.
