### ISSUE TITLE
Enhancement: Add Payments via Dbus

### ISSUE THREAD

**Issue by mweser** [AsamK/signal-cli#1010]
What would it take to support payment functionality via dbus, or is there something that makes this not possible?

**Comment by AsamK** [comment]
If you mean the functionality corresponding to the `sendPaymentNotification` command, that should be relatively straight forward to implement as an additional method on the Signal dbus interface.

**Comment by mweser** [comment]
@AsamK Ok cool. Curious if it will be added to a release in the near future. Understandable there are other items of higher priority that likely take precedence. I would do it myself, but I'm having odd issues building and running on my M1 Mac.
