### ISSUE TITLE
Does the challenge token provided by signal-cli expire after some time has passed?

### ISSUE THREAD

**Issue by andrew-manggi** [AsamK/signal-cli#1013]
Recently I have been getting this message when sending to a particular number using signal-cli:

`<sending number>: CAPTCHA proof required for sending to "<receiving number>", available options "RECAPTCHA, PUSH_CHALLENGE" with challenge token "1216b26e-b13f-43cc-b15d-568f3acad8fa", or wait "86400" seconds.
To get the captcha token, go to https://signalcaptchas.org/challenge/generate.html
Check the developer tools (F12) console for a failed redirect to signalcaptcha://
Everything after signalcaptcha:// is the captcha token.
Use the following command to submit the captcha token:
signal-cli submitRateLimitChallenge --challenge CHALLENGE_TOKEN --captcha CAPTCHA_TOKEN
`

Sometimes I forget to run the provided command above immediately, and do so after 10 minutes or so. The command successfully executes (exit code 0), but when I tried to send another message using signal-cli to the receiving number, I still get the captcha error.

I figured that maybe, the captcha token becomes invalid after a while. But does it, after trying out the token and signal-cli still has exit code 0 when running the submitRateLimitChallenge command.

**Comment by AsamK** [comment]
The token is provided and checked by the signal server. It probably expires after some time, but you'd need to check the Signal-server for details.
