### ISSUE TITLE
No json response message when using tcp daemon mode

### ISSUE THREAD

**Issue by magiclobster** [AsamK/signal-cli#1017]
Is the following response only working when using jsonRPC with stdin and stdout?

{"jsonrpc":"2.0","result":[...],"id":"5"}

working:
`echo '{"jsonrpc":"2.0","method":"send","params":{"recipient":["+xxx"],"message":"xxx"},"id":4}' | signal-cli --account +xxx jsonRpc`

not working:
`import json
import socket

server = '127.0.0.1'
port = 4445
socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.connect((server, port))

recipient = '+xxx'
message = 'xxx'
msg_id = 55
rpc_message = {
    "jsonrpc": "2.0",
    "method": "send",
    "params": {"recipient": [recipient], "message": message, "id": msg_id}
}
send_cmd = json.dumps(rpc_message) + '\n'
socket.sendall(send_cmd.encode('utf8'))
print(socket.recv(16384))
socket.close()`

**Comment by morph027** [comment]
It's a bit tricky with newlines. Might have look at these snippets: https://github.com/AsamK/signal-cli/discussions/799#discussioncomment-1965037 or https://gitlab.com/morph027/python-signal-cli-rest-api/-/blob/main/python_signal_cli_rest_api/lib/jsonrpc/__init__.py

**Comment by magiclobster** [comment]
> It's a bit tricky with newlines. Might have look at these snippets: [#799 (comment)](https://github.com/AsamK/signal-cli/discussions/799#discussioncomment-1965037) or https://gitlab.com/morph027/python-signal-cli-rest-api/-/blob/main/python_signal_cli_rest_api/lib/jsonrpc/__init__.py

Thanks, the snippets are great. But unfortunately they doesn't solve my problem.

Even if i print the plain messages received i don't get result messages.

Tried signal versions v0.10.11 and 0.11.0 and starting with command:
signal-cli --account xxx --config yyy --output json daemon --tcp 0.0.0.0:4445 --send-read-receipts --ignore-attachments

**Comment by morph027** [comment]
So you get an response but with an empty result?

**Comment by magiclobster** [comment]
Just getting the signal message responses like:
{"jsonrpc":"2.0","method":"receive" ...

Never got any of the command result ({"jsonrpc":"2.0","result":[...],"id":"5"}) messages

**Comment by morph027** [comment]
Hm, weird. The stdin/stdout must be present in socket mode only, not tcp mode. To me, it looks like you're getting responses which are not the response to your message id, so it is a valid response, but to the request you've made. I'm comparing the response id to the request id to get a perfect match: https://gitlab.com/morph027/python-signal-cli-rest-api/-/blob/main/python_signal_cli_rest_api/lib/jsonrpc/__init__.py#L57
