### ISSUE TITLE
StatusCode 499

### ISSUE THREAD

**Issue by opensource21** [AsamK/signal-cli#1025]
Since 6 October 2022 I get 
`Error while checking account +xxxxxxxxxxxxx: StatusCode: 499`

I can't find any information about the meaning of this code.

I'm using signal-cli 0.10.0 on raspberry-pi. Unfortunately as a side effect this means that an update is really cumbersome because there are more and more native-libs in use. I tried to update to 0.10.10 (the last version where you can find pre build lib at https://github.com/exquo/signal-libs-build/releases?page=1), but then I got an exception 
`java.lang.Exception: No native library found for os.name=Linux, os.arch=armv7, paths=[/org/sqlite/native/Linux/armv7:/opt/signal-cli-0.10.10/lib]`

So can someone give me a hint what the meaning of 499 could be and if an upgrade would fix it.

**Comment by orazioedoardo** [comment]
Duplicate of https://github.com/AsamK/signal-cli/issues/1022.

**Comment by opensource21** [comment]
Thanks
