### ISSUE TITLE
Registered Phones message envelopes received twice from Groupchats

### ISSUE THREAD

**Issue by master-signal-pal** [AsamK/signal-cli#1034]
Hello AsamK, 

thanks for your great work.
I have encountered an issue with your newest signal-cli release v0.11.2
I have registered a phone via your cli. When sending messages to groupchats via that registered phone, these messages are all fetched twice when using "signal-cli receive". That means the exact identical envelop is received twice.
This only happens in group chats and only with the registered phone. All other group chat participants' messages are received only once. Also note, that the messages were sent via the registred phone (android) itself and not via the signal-cli.
In release v0.10.8 which i used before, this issue wasn't present.

I hope you could help and find a fix for this. Thank you very much!

Kind regards

master-signal-pal

**Comment by AsamK** [comment]
I can't reproduce this.
Can you provide more details, which devices send messages with which numbers (redacted)?
Would also help to have extended log output (with `--verbose`)

**Comment by master-signal-pal** [comment]
Hello AsamK,

here some more details on how I use signal-cli.

I have an AndroidPhone with Signal App installed and already registered. 

With qrencode I generate a qrcode to link the phone in order to use your signal-cli.

When the phone is linked I want to get all the new messages using the "signal-cli receive" command.

Now as written in my first comment, when receiving the messages from groupchats, all messages that originated from my linked phone are received twice.

Actually, this seems to only happen with new groupchats that are created after the linking of the phone. Older groupchats that existed before linking the phone to your signal-cli don't show this error.

In these old groupchats, every message from the linked Android Phone is received only once as it should be.

Here is redacted excerpt from the terminal output using "signal-cli receive" to get the envelopes for the linked phone.
Here you can see, that the first two envelopes are exactly the same, showing the message "Hello Test signal" which was written in the android app on the linked phone:

user@test_machine:/opt/signal-cli/bin$ ./signal-cli -o json receive

{"envelope":{"source":"#linked_phone",
"sourceNumber":"#linked_phone","sourceUuid":"uuid_linked_phone",
"sourceName":"name_linked_phone","sourceDevice":1,"timestamp":1665133794178,
"syncMessage":{"sentMessage":{"destination":null,"destinationNumber":null,"destinationUuid":null,
	"timestamp":1665133794178,"message":"Hello Test signal","expiresInSeconds":0,"viewOnce":false,
	"groupInfo":{"groupId":"group_chat_id","type":"DELIVER"}}}},
"account":"#linked_phone"} 

{"envelope":{"source":"#linked_phone",
	"sourceNumber":"#linked_phone","sourceUuid":"uuid_linked_phone",
	"sourceName":"name_linked_phone","sourceDevice":1,"timestamp":1665133794178,
	"syncMessage":{"sentMessage":{"destination":null,"destinationNumber":null,"destinationUuid":null,
	"timestamp":1665133794178,"message":"Hello Test signal","expiresInSeconds":0,"viewOnce":false,
	"groupInfo":{"groupId":"group_chat_id","type":"DELIVER"}}}},
"account":"#linked_phone"} 

{"envelope":{"source":"#first_recipient","sourceNumber":"#first_recipient","sourceUuid":"uuid_first_recipient",
	"sourceName":"name_first_recipient","sourceDevice":1,"timestamp":1665133796124,
	"receiptMessage":{"when":1665133796124,"isDelivery":true,"isRead":false,"isViewed":false,"timestamps":[1665133794178]}},
"account":"#linked_phone"}   

{"envelope":{"source":"#second_recipient","sourceNumber":"#second_recipient","sourceUuid":"uuid_second_recipient",
	"sourceName":"name_second_recipient","sourceDevice":1,"timestamp":1665133797229,
	"receiptMessage":{"when":1665133797229,"isDelivery":true,"isRead":false,"isViewed":false,"timestamps":[1665133794178]}},
"account":"#linked_phone"} 

{"envelope":{"source":"#second_recipient","sourceNumber":"#second_recipient","sourceUuid":"uuid_second_recipient",
	"sourceName":"name_second_recipient","sourceDevice":8,"timestamp":1665133801209,
	"receiptMessage":{"when":1665133801209,"isDelivery":true,"isRead":false,"isViewed":false,"timestamps":[1665133794178]}},
"account":"#linked_phone"}



I hope this helps a little bit to understand and reproduce the issue!

Kind regards!

**Comment by AsamK** [comment]
I can't reproduce it, also with a new group.
I'm pretty sure it's an issue on the sending side, can you get a debug log from the Android app?
