### ISSUE TITLE
sendMessage should return a message.timestamp and recipient addresses

### ISSUE THREAD

**Issue by leo-b** [AsamK/signal-cli#104]
I'd like to associate delivery receipts with sent messages. (My monitoring applications needs to know whether a message had been delivered, otherwise it has to fall back to sending an SMS.)
Currently it looks like there is no way to link a delivery receipt to a sent message because the timestamp of the generated message is not returned.

If sendMessage() returned the timestamp of the generated message (message.getTimestamp()) and the addresses of the recipients, delivery receipts could be assigned to the corresponding messages.

Cheers,
--leo

**Comment by gorman553** [comment]
Hi AsamK,

anything new on this enhancement feature? Because I have the same problem as leo-b, I want to use signal-cli for icinga-alerting, with a fallback to SMS.

Thanks for your great tool

Bye

gorman

**Comment by piramiday** [comment]
hey @AsamK, sorry to bump this old issue again, but the recent enhancement for reactions does require to know the timestamp of the sent message. any thoughts on this? thanks!
