### ISSUE TITLE
"Receive" Command Returns StatusCode: 499 Error

### ISSUE THREAD

**Issue by muad-dumb** [AsamK/signal-cli#1042]
When attempting to prompt Signal servers with a "receive" command, the CLI returns a 'StatusCode: 499' error [request timed out by the server].

I tried troubleshooting by update/upgrading Signal Desktop and restarting the laptop. I'mt out of my depth with this one since it seems to largely be a server-side issue, but if anyone can suggest any other troubleshooting steps to take I'd appreciate it.

Issue was also reported two days ago here: https://github.com/home-assistant/core/issues/79773 

It's since been Closed after what appears to be a patch by the Home-Assistant developers.

**Comment by muad-dumb** [comment]
Update: This issue seems to effect sending messages through the CLI; or at the least, it effects sending messages through CLI using my mass-text batch script. Urgent issue on my end!

**Comment by rfrederick** [comment]
This was reported in #1022. Update your installation of signal-cli to the latest release.

**Comment by muad-dumb** [comment]
> This was reported in #1022. Update your installation of signal-cli to the latest release.

Copy! I can close this ticket to de-clutter, if need be.
