### ISSUE TITLE
humble request for i386 prebuild binary

### ISSUE THREAD

**Issue by eexexiexit** [AsamK/signal-cli#1044]
I made a i386 build some weeks ago, which took me some time, and now face the necessity of an upgrade due to issue #1022 (the quick fix proposed there did not work for my build). 

This project is really awful and the only way known to me to get a signal on an i386 machine (except fully vitrualized android, which had its own problems and is really costly), so users of  32bit hardware around the world will probably particularly benefit from this project.

Therefore my question: how much effort is it to provide pre-build i386 binaries here?

**Comment by AsamK** [comment]
I don't have capacity to provide more binaries. I can only refer to binaries provided by others, but I don't know if there's one for i386:

https://github.com/AsamK/signal-cli/wiki/Binary-distributions
https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

**Comment by eexexiexit** [comment]
>>    This project is really awful and
>>
> Serious?

Ups, no!!! Sorry! unsufficient command of English language. I wanted to say "really cool".

**Comment by eexexiexit** [comment]
>> I don't have capacity to provide more binaries. I can only refer to binaries provided by others, but I don't know >> if there's one for i386:

Ok, thanks for the reply anyway...
