### ISSUE TITLE
How to get group-id by group-name and send to groups

### ISSUE THREAD

**Issue by egabosh** [AsamK/signal-cli#1046]
Moin,

first thanks for your great work!

I want to send messages to a group with dbus.
Using 
`dbus-send --system --type=method_call  --print-reply --dest='org.asamk.Signal' /org/asamk/Signal/${account} org.asamk.Signal.listGroups`
It looks I'm getting the group id (XXX...).:
```
      struct {
         object path "/org/asamk/Signal/_123456789/Groups/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_"
         array of bytes [
           [...]
         ]
         string "groupname"
      }
```
Trying to send to group via
`dbus-send --system --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal/_123456789 org.asamk.Signal.sendGroupMessage string:"message text" array:string: array:byte:$groupidbase64decoded`

where $groupidbase64decoded I'm trying the "XXX.."-ID or the array of bytes,

I get an error like
`Error org.asamk.Signal.Error.InvalidGroupId: Invalid group id: Invalid group id: Invalid group id of size 48`

Trying to decode the strings via
`python3 -c "import base64; print(\",\".join(str(i) for i in base64.b64decode(b\"DQwne90o4AzGehXFLD30OAaOVHpGgIt9i4bkHYt8p3w\")))"`
ends up in this error with the XXX...XXX_-String: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
```
Or it works with the "array of bytes" but sending the decoded String with the mentioned dbus-command ends up in the same error.

So what I'm doing wrong and could It be less complicated to send to groups? Maybe an option to use the Groupname without the need of searching the correct Group ID and decoding it?

Please help!

**Comment by egabosh** [comment]
Ah, found out a 
`signal-cli -u '+123456789' listGroups `
gives a bit other Group-IDs then then the dbus command
`dbus-send --system --type=method_call --print-reply --dest='org.asamk.Signal' /org/asamk/Signal/${account} org.asamk.Signal.listGroups`
Looks like charakters like =, + and / are substituted by "_". 

With the IDs got directly from signal-cli without dbus sending messages to groups works after the base64-decode. 

OK so how cat I get the correct Group IDs over dbus without the substitutions?

**Comment by morph027** [comment]
https://github.com/AsamK/signal-cli/wiki/DBus-service#send-using-dbus-send

**Comment by egabosh** [comment]
Thank you @morph027 !

https://github.com/AsamK/signal-cli/wiki/DBus-service#send-using-dbus-send:
> The byte array can be obtained from a base64-encoded string (which looks like ixZI93QgqmjNpM8V+E0= and can be found in signal-cli's config file, by default in ~/.local/share/signal-cli/data/<PHONE_NUMBER>.d/group-cache/). Note that any underscore must be converted into a slash (/) character to provide a valid base64-encoded string. To decode it to byte array, you can use python: [...]

But there is no group-cache dir in my ~/.local/share/signal-cli/data/<PHONE_NUMBER>.d/:
```
$ pwd
/home/signal/.local/share/signal-cli/data/<PHONE_NUMBER>.d
$ ls -la
total 1468
drwx------ 1 signal signal      20 Oct 17 16:19 .
drwx------ 1 signal signal      86 Sep  7 21:14 ..
-rw-r--r-- 1 signal signal 1503232 Oct 17 16:19 account.db
```
Looks like it changes with a newer release. 
So how can I get the correct Group IDs over dbus or with a workaround?

**Comment by AsamK** [comment]
The array of bytes in the `listGroups` output is what you need.
Just make sure to prefix the bytes with `0x` when using the send command, otherwise `dbus-send` interprets them as decimals.

```
org.asamk.Signal.sendGroupMessage string:"message text" array:string: array:byte:0x82,0x77,0x42,0x03,0x71,0x6d,0xf7,0xf5,0x3b,...
```

**Comment by egabosh** [comment]
Thank you, it works with:
groupid=$(dbus-send --system --type=method_call --print-reply --dest='org.asamk.Signal' /org/asamk/Signal/_ACCOUNT org.asamk.Signal.listGroups | grep "GROUPNAME" -B3 | head -n2 | perl -pe 's/\n//g; s/ +/ /g; s/ /,0x/g; s/^,//')
