### ISSUE TITLE
Line breaks in message to send

### ISSUE THREAD

**Issue by lancechua** [AsamK/signal-cli#105]
Is it possible to add newlines in the message?
I'm hoping to use the program like this:
`signal-cli -u +XXXXXXXX send -m "message with a \n new line" +XXXXX`

**Comment by AsamK** [comment]
signal-cli itself doesn't do any unescaping, you need to pass the newline directly. You can use shell escaping to do one of the following:
```sh
signal-cli -u +XXXXXXXX send -m 'foo
bar' +XXXXX
```
```sh
signal-cli -u +XXXXXXXX send -m "`echo -e 'foo\nbar'`" +XXXXX
```
```sh
echo -e 'foo\nbar' | signal-cli -u +XXXXXXXX send +XXXXX
```

**Comment by lancechua** [comment]
Thanks for responding. I'm using windows 10 and the workaround I found was to replace line breaks with:
`&& echo`

e.g. 
`(echo hello && echo world && echo another line) |  signal-cli -u +XXXXXXXX send +XXXXX`

I'm honestly not familiar with shell commands and escaping, but there can't be a  ")" in the message using the workaround above.

**Comment by mueller-ma** [comment]
Try `echo -e 'Hello\nWorld` | signal...`

**Comment by fvonberg** [comment]
I guess this changed, over dbus I have no issues anymore with line breaks. Standard \n can be used and is displayed correctly in the signal app.

**Comment by dcwm-tech** [comment]
reopening this issue as it is again a problem:
echo -e 'foo\nbar' | /opt/signal-cli-0.11.4/bin/signal-cli -u +49xxxxx send +49yyyyyy
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
Sending empty message is not allowed, either a message, attachment or sticker must be given.

any clue?
