### ISSUE TITLE
Debian 11 Java Version

### ISSUE THREAD

**Issue by foxylad** [AsamK/signal-cli#1053]
Thanks for using your skills for such good work.

The latest Debian (11 - Bullseye) default-jre is JRE11, so the Quickstart install instructions don't work. 

Perhaps update the prerequisites section like this:

- Debian 11: sudo apt-get install openjdk-17-jre
- Ubuntu 22.04: sudo apt install openjdk-18-jre
- Arch Linux: pacman -S jre-openjdk
- Older distributions: Google how to install JRE17

Cheers!
Greg.

**Comment by AsamK** [comment]
Thanks, the Quickstart is a wiki page, so feel free to update it yourself :)

**Comment by foxylad** [comment]
Good suggestion - I've updated the page.
