### ISSUE TITLE
Update breaks signal-cli

### ISSUE THREAD

**Issue by peter-langer** [AsamK/signal-cli#1054]
So far, I have been using `signal-cli-0.10.2` (prebuild Linux from Release page) but was recently affected by the error 499 issue, too. So I tried upgrading to [`signal-cli-0.11.3`](https://github.com/AsamK/signal-cli/releases/download/v0.11.3/signal-cli-0.11.3-Linux.tar.gz) but now receive "number not registered" errors:

```
$ signal-cli-0.11.3/bin/signal-cli -u +49123456789 receive

User +49123456789 is not registered.
```
(number intentionally obfuscated)

So I tried a few more versions:
- `signal-cli-0.10.3`: `Error while checking account +49123456789: StatusCode: 499`
- `signal-cli-0.10.4` to `signal-cli-0.10.11`: `Error loading state file for user +49123456789: Config file was created by a more recent version! (IOException)`
- `signal-cli-0.11.0` to `signal-cli-0.11.3`: `User +49123456789 is not registered.`

I do have a lot of files in `~/.local/share/signal-cli/data/` and my number is also listed in `acounts.json` therein.

What am I missing?

**Comment by peter-langer** [comment]
Resolved this by re-registering the number. Now I am affected by https://github.com/AsamK/signal-cli/issues/1045 which is not resolved in the current version - despite the issue being closed.

**Comment by AsamK** [comment]
That issue will be fixed in the next version.
