### ISSUE TITLE
Cannot register via voice

### ISSUE THREAD

**Issue by MatejKovacic** [AsamK/signal-cli#106]
Hi,

I have sucessfully installed application and run:
signal-cli -u USERNAME register

USERNAME in my case is a phone number without the capability of receiving SMS messages. I have waited for a several minutes, but there was no voice call saying verification code.

Is this expected behaviour?

**Comment by Trolldemorted** [comment]
Yes, as the [manpage ](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#register)tells you `register` requests a verification sms, and `register -v` requests a verification call.

**Comment by MatejKovacic** [comment]
Thanks, it works.
