### ISSUE TITLE
Line Break does not work

### ISSUE THREAD

**Issue by dcwm-tech** [AsamK/signal-cli#1061]
Hello,
do i something wrong? it is again not working in latest release:

echo -e 'foo\nbar' | /var/lib/nagios/signal-cli-0.11.4/bin/signal-cli -u +4962419709909 send +4915730252442
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
Sending empty message is not allowed, either a message, attachment or sticker must be given.

**Comment by dcwm-tech** [comment]
See also Issue #105

**Comment by AsamK** [comment]
The syntax has changed, you need to add `--message-from-stdin` now.
See https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md#0110---2022-10-02

**Comment by wagner-austin** [comment]
THANK YOU!!!! Anyone else having their messages cut off in signal at newlines. This is the solution ^^. You need to use "--message-from-stdin". Thank you!
