### ISSUE TITLE
Access all messages (with attachments) of existing group

### ISSUE THREAD

**Issue by HenningWaack** [AsamK/signal-cli#1063]
Hi, 

is it possible to access all messages (and attachments) of an existing group?

My use-case is exporting all images from a given group, so that I can process these images locally on my computer.

Thanks!

**Comment by AsamK** [comment]
No, signal-cli doesn't store any received messages. Attachments are stored in the `attachments` folder of the config directory, but there's no information from which group or contact they were sent.
If you just want to export the images manually, you can do that in the official apps, at least in the android version.
