### ISSUE TITLE
Additional Dbus debug output when using json format

### ISSUE THREAD

**Issue by whlk** [AsamK/signal-cli#1064]
Since upgrading to v11.4 from 10.5 i noticed this additional output being produced even when using the `-o json` flag:

    INFO  TransportBuilder - Using transport dbus-java-transport-native-unixsocket to connect to unix:path=/var/run/dbus/system_bus_socket

sample call with system bus daemon running:

    $ signal-cli -o json --dbus-system  receive

The additional output hinders the direct parsing of the response to JSON. Possible culprit is the dbus-java library.

**Comment by AsamK** [comment]
Yeah, that's from the dbus-java library. It shouldn't affect JSON parsing, as log output is printed on stderr and JSON is printed on stdout.

**Comment by whlk** [comment]
Thanks for the hint with the different Channels -> I didn't notice that the INFO message is on stderr.
