### ISSUE TITLE
Cannot start DBUS from custom config dir

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1065]
Running a deamon with daemon or jsonRpc param is working fine.
But if you use the --config command you get this:
```
INFO  DaemonCommand - Starting daemon in multi-account mode
INFO  TransportBuilder - Using transport dbus-java-transport-native-unixsocket to connect to unix:path=/run/user/1001/bus
INFO  DaemonCommand - DBus daemon running on SESSION bus: org.asamk.Signal
WARN  ReceiveHelper - Connection closed unexpectedly, reconnecting in 100 
```

Seems like you have to use the default location for the config in order to run a deamon.

Can this be fixed?

**Comment by AsamK** [comment]
There's no difference in the app when using a none default location. Only difference can be in the account data in that location.
What exactly isn't working? Also a --verbose output could be helpful.

**Comment by Tsjippy** [comment]
oops, found my error. I was testing with an account used somewhere else too, resulting in two master devices connected to the same number. 

So it is fixed

Thanks!
