### ISSUE TITLE
Contacts colors

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#1072]
Is there a way to get the value of a contact's profile `color` parameter?

Color is one of the contacts' (and groups') profile entries, and it is present in the tables in signal-cli's `account.db` file. But the `listContacts` and `listGroups` commands (which print out profiles information) do not include `color` in the output. Likewise, there does not seem to exist a DBus interface call that would return a contact's color.

**Comment by AsamK** [comment]
It's not possible currently, but shouldn't be hard to add, at least for cli/json output.
For DBus a lot more contact information is also missing. I had planned to export those as separate object, similar to the groups, but haven't had time for that yet.

**Comment by exquo** [comment]
Thank you for adding this!

However, all of my contacts show `Color: null`..

In signal-desktop/mobile, every contact's "avatar circle" (for contacts without an avatar picture) has a different color. I guess that's what a "contact's color" means? In Chat settings there is also a "Chat color" option, but that's the color of their *message boxes* in their chats.
