### ISSUE TITLE
Updated signal-cli, now "User +xxxxxxxxxx is not registered"

### ISSUE THREAD

**Issue by tjswe** [AsamK/signal-cli#1073]
Hi!

This is due to a big leap in the previous version running (0.6.8), and the issue with new certificates that are emerging.

I know this is probably not a Signal issue and most certainly not signal-cli... but the pre-paid sim-card and phone used 5 years ago to register the account is long gone in a box somewhere.

Am i screwed or is there a magical command to bring this account back to life without having access to the phone number?

**Comment by AsamK** [comment]
You can just try to run the `register` command, it will first try to reactivate the account if it still exists on the server.
If that doesn't work, you're out of luck and need to find the sim again to receive the verification sms.

**Comment by tjswe** [comment]
That did not work :(

Even if i find the sim, the number is dead by now after 5 years.

A lesson learned.

Big thanks for quick response as always!

**Comment by meejah** [comment]
I have similar situation (although still have access to the number). Running "register" produces no output, but "receive" still says "...is not registered". Same with "--reregister".

A paired Desktop instance to the account has been working (but has the "run on your phone" error/warning).

Any hints? Thanks!
