### ISSUE TITLE
Dbus multi account mode onreceive find target

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1075]
How do I get to know to which phonenumber a message was send in multi account mode?
On receive signal does not give that as parameter

**Comment by AsamK** [comment]
In the dbus interface you can subscribe for each account object separately.
In json output mode there's already a field "account", I'll also add that to the plain text output.

**Comment by Tsjippy** [comment]
Thanks!

how does that work: `In the dbus interface you can subscribe for each account object separately. `

**Comment by Tsjippy** [comment]
I dont see the account:
signal time=1667046490.978273 sender=:1.1 -> destination=(null destination) serial=7 path=/org/asamk/Signal; interface=org.asamk.Signal; member=MessageReceivedV2
   int64 1667046490494
   string "+SOMENUMBER"
   array [
   ]
   string "Hi"
   array [
      dict entry(
         string "isViewOnce"
         variant             boolean false
      )
      dict entry(
         string "expiresInSeconds"
         variant             int32 0
      )
   ]

**Comment by AsamK** [comment]
Your listener is on the main path /org/asamk/Signal, you can instead add it to the account object /org/asamk/Signal/_1234567890 to only receive messages for a single account, that's currently the only way to distinguish it in tbe dbus Interface.

**Comment by Tsjippy** [comment]
Awesome thanks, confirmed working
