### ISSUE TITLE
echo message | signal-cli send #Fail

### ISSUE THREAD

**Issue by mmhere** [AsamK/signal-cli#1076]
Recent versions (not sure when this started) now require the unwieldy `--message-from-stdin` cmdline arg to accept sending message text present on signal-cli's stdin.

Why?

This broke a whole bunch of scripts.

The appropriate cmdline arg has been added in those scripts;  not sure they've all been found.

A compatibility break like this causes lots of problems.

Why not leave it alone?  What was the motivation for this?

Can accepting message text on stdin be reinstated without requiring this cmdline arg?

**Comment by mmhere** [comment]
https://github.com/AsamK/signal-cli/commit/4120630309979c1c952691a3b000b79b727a8d39

That change (28 August) is when this first appeared.

**Comment by AsamK** [comment]
The old behavior was surprising for new user, where signal-cli appeared to be stuck when no `-m` message was given. Especially when attempting to send a message with an attachment, but no text.

https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md#0110---2022-10-02

**Comment by mmhere** [comment]
Well, I'll keep using it as is, but respectfully disagree.  Many unix commands accept stdin as default input so this is pretty normal.  Ones that require a designation of stdin consumption (or writing data to stdout) often accept a '-' argument to a command line switch to indicate that stdin/out should be explicitly selected.  One example is wget's `-O` switch that takes `-` as an arg to indicate writing to stdout.  There are similar examples for stdin designation.

The command line switch currently used, `--message-from-stdin` is non-standard and quite unwieldy.  That's just my opinion.
