### ISSUE TITLE
Certification error?

### ISSUE THREAD

**Issue by FransVeldman** [AsamK/signal-cli#1077]
I'm running Signal-Cli 0.7.2 for two years now, and it fits my purpose.

Suddenly it stopped working:

"[main] ERROR org.asamk.signal.Main - Error while checking account: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

I tried to upgrade Signal-Cli to a newer version, but then I get:

"Error: LinkageError occurred while loading main class org.asamk.signal.Main
	java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0"

I tried to install a new Java Runtime but the newest I could get on Ubuntu 18.xxx LTS is still too old.

I tried to find an older Signal-Cli that works with my Java Runtime, but I can't download anything before 11.5 or something.

It seems I'm stuck here. Any ideas how I can get Signal-Cli to work again?
The computer running Ubuntu 18.xxx LTS is a machine that runs a variety of software and it would take quite some time and effort to set it all up on a newer OS. I'm hoping for a quick solution without having to upgrade the whole thing.
Any suggestions?

**Comment by mh-g** [comment]
Starting shortly after Oct 26th, 17:00 UTC, I have the same (original) issue. signal-cli 0.8.4.1 on Raspbian 10:

```
Oct 30 00:01:02 mediaberry signal-cli[4613]: WARN Manager - Failed to get sender certificate, ignoring: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Oct 30 00:01:02 mediaberry signal-cli[4613]: WARN Manager - Failed to retrieve profile, ignoring: java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Oct 30 00:01:02 mediaberry signal-cli[4613]: WARN Manager - Failed to get sender certificate, ignoring: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

```

Receive is not working at all, most of the transmit tries cause this three-line-block of error messages.

**Comment by mh-g** [comment]
This one has been solved in another thread. If you do not want to recompile signal or upgrade, follow this instruction:

https://github.com/AsamK/signal-cli/issues/1067#issuecomment-1295204655

Worked fine in the setup described a few minutes ago by me.

**Comment by FransVeldman** [comment]
There are multiple solutions mentioned (and the TS said they don't work), which one worked for you?

**Comment by mh-g** [comment]
To update the lib.jar with a new whisper.store as AsamK proposed.

**Comment by FransVeldman** [comment]
Ok, there was no lib.jar but a signal-cli.0.7.2,jar and replacing the whisper.store solved the problem for me.
Thanks!
