### ISSUE TITLE
Sending messages is slow

### ISSUE THREAD

**Issue by MatejKovacic** [AsamK/signal-cli#108]
I have registered a phone number with signal-cli and I am sending messages.

However, it takes a several minutes to receive a message on the recipient device.

On the other side, I have another installation of signal-cli on another computer, where I have linked signal-cli as a linked device (primary device here is my phone). When I send messages from this instance of signal-cli, they are delivered almost instantly.

Why is the first instance so slow? Is it because it is not using GCM? It is possible to "speed it up"?

**Comment by kdeenkhoorn** [comment]
I'd think you have to add  -Djava.security.egd=file:/dev/urandom to the command line of java.
This helped me.

Java has some times problems with the random nummer generator while using encryption.

**Comment by MatejKovacic** [comment]
This is so wrong on many levels.

Why you don't just set DEFAULT_JVM_OPTS="-Djava.security.egd=file:/dev/./zero"

I am pretty sure it will work much faster... :-) 

If you know what I mean.

**Comment by z4nD4R** [comment]
Hi all,

the same problem over here. Sending messages takes ages like 12minutes. Any ideas?

Y

**Comment by z4nD4R** [comment]
Hello,

is this thread still alive?

MS

**Comment by streaps** [comment]
You could try [haveged](http://www.issihosts.com/haveged/)

**Comment by MatejKovacic** [comment]
Hmm, is there any development on this software or is there any alternative? Because CLI Signal could be very usable...

**Comment by streaps** [comment]
If I understand the problem correctly, the only way to prevent that problem for everyone is to use /dev/urandom instead of /dev/random on Linux. I'm not really into that cryptographic stuff, but it seems using /dev/random doesn't make the encrypted messages easy to decrypt.

https://www.2uo.de/myths-about-urandom/
https://en.wikipedia.org/wiki//dev/random#Linux

Also installing haveged is a no brainer. Just install the package and /dev/random doesn't block anymore.

**Comment by dbrowndan** [comment]
For anyone reading this later, streaps is correct.

Originally, when I tried to send several messages in a row, it was taking 3-4m for each one to go through. All I did was `sudo apt-get install haveged` (on Ubuntu) and my messages send instantly now.

Disclaimer: I don't know a ton about cryptography either, so I'm not sure if this changes the privacy of your messages in any way.

**Comment by MatejKovacic** [comment]
haveged package is Linux entropy source using the HAVEGE algorithm. More about this can be found here: https://github.com/jirka-h/haveged

It seems quite OK. However, I thing that better solution would be to use [ChaosKey](https://keithp.com/blogs/chaoskey/) - hardware True Random Number Generator.

However, ChaosKey seems a little expensive, so some guys gathered around Slovenian IT portal Slo-Tech.com started the development of cheaper version of ChaosKey (hardware and software is opensourced), and someone developed a hardware true random number generator for RaspberryPi. Source code and Gerber files will be published here: https://github.com/Mambix?tab=repositories

Currently RPi TRNG is not working very well (giving only 12kB/sec of random data). But some preliminary tests for USB TRNG has shown that it can give 30kB/s and probably it would be possible to get up to 60kB/s.

So, it seems the entropy is a problem, and this problem could be resolved with haveged or with TRNG hardware devices.

I will keep you posted.

**Comment by jax-404** [comment]
What's the equivalent process on Windows?

> For anyone reading this later, streaps is correct.
> 
> Originally, when I tried to send several messages in a row, it was taking 3-4m for each one to go through. All I did was `sudo apt-get install haveged` (on Ubuntu) and my messages send instantly now.
> 
> Disclaimer: I don't know a ton about cryptography either, so I'm not sure if this changes the privacy of your messages in any way.
