### ISSUE TITLE
Image attachments are not shown as image

### ISSUE THREAD

**Issue by Worren** [AsamK/signal-cli#109]
Whenever I send an jpg image with signal-cli to my android phone (signal app), the image is not shown as image. Only a litte icon with the filetype (jpg), the filename of the image and the correct size is shown.

Is there some way to send an image, that is shown in the signal app? 

By the way:
When I send an image from android signal app to signal-cli, the image data can be received, but the filename is lost and the data is saved without extension. If I rename the file, the image can be displayed.

**Comment by Worren** [comment]
"Attachments other than pictures or videos ... cannot be opened"

But I want to send an jpg image ...

**Comment by Trolldemorted** [comment]
Are you sure it works with them? Nevermind then, sorry.

**Comment by Worren** [comment]
No I am not sure, All I know is the information in the ticket mentioned.
I used another textsecure command line implementation https://github.com/janimo/textsecure which isn't working anymore.  In this implementation it was possible to send pictures and see them instantly.

**Comment by Trolldemorted** [comment]
I have sent a png to myself (direct message) right now and it worked. Did you only try jpegs?

**Comment by Worren** [comment]
Yes, i tried a png - same result. Unfortunately i cannot test it right now. I used version 0.5.6 from the binary files. Perhaps something changed since then?

**Comment by AsamK** [comment]
The signal app uses the mime type to distinguish if it shows the attachment as a picture in the app or not. signal-cli uses a java function to determine the mime type of a file and includes that in the message.  I think this function is platform dependent. Which OS are you using?

**Comment by Worren** [comment]
I am using signa-cli on a synoloy linux nas to send messages to the android app.

**Comment by Worren** [comment]
Same result when I send the message to an ios client.

**Comment by Quantum1337** [comment]
I had the same problem. I solved it with a '**sudo pacman -S shared-mime-inf**o' on an arch linux system running signal-cli. I think on an debian system the package has the same name. But not be sure.

Greetings

**Comment by NightMachinary** [comment]
How do I send an attachment in the first place? I don’t see an option in the manpage.

**Comment by matthew-piziak** [comment]
Sadly installing `shared-mime-info` on NixOS does not resolve this issue on that platform.

**Comment by Worren** [comment]
shared-mime-info doesn't solve the problem for me.
