### ISSUE TITLE
How to downgrade signal-cli

### ISSUE THREAD

**Issue by MatzFan** [AsamK/signal-cli#1096]
I had previously installed `signal-cli` v0.11.5 and have just tried to downgrade from v0.11.5 to v0.11.4 (until #1093 is fixed) by downloading and installing v0.11.4. I now have:
```
$ signal-cli --version
signal-cli 0.11.4
```
However, when I try to execute a command (e.g. `signal-cli -a [number] register`) I receive the following error:
`Error loading or creating state file: java.sql.SQLException: Database has been updated by a newer signal-cli version (RuntimeException)`
This appears to be triggered [here](https://github.com/AsamK/signal-cli/blob/49aaff2bbe1ec6ed6cdbd26200ec806c46b16489/lib/src/main/java/org/asamk/signal/manager/storage/Database.java#L63).

Is it possible to overcome this and downgrade the database version to the same as the user version?

**Comment by AsamK** [comment]
Downgrading is not possible if the account file version or the database scheme version has changed.
At your own risk, you could attempt to undo the last migration (https://github.com/AsamK/signal-cli/blob/49aaff2bbe1ec6ed6cdbd26200ec806c46b16489/lib/src/main/java/org/asamk/signal/manager/storage/AccountDatabase.java#L291) and decrease the sqlite user_version.

**Comment by morph027** [comment]
For the future, before upgrading probably create a backup :see_no_evil: (ran into this too earlier): https://packaging.gitlab.io/signal-cli/backup/#manual

@AsamK probably add the backup snippet into the readme or wiki? Just let me know, i can add it.

**Comment by AsamK** [comment]
Yeah, would be good to have that in the wiki, thanks!

**Comment by morph027** [comment]
=> https://github.com/AsamK/signal-cli/wiki/Quickstart#backup
