### ISSUE TITLE
Failed to register: chat.signal.org: Name or service not known

### ISSUE THREAD

**Issue by ostasevych** [AsamK/signal-cli#1098]
Recently I found an error: when trying to register with signal-cli I am getting error 
"Failed to register: chat.signal.org: Name or service not known
java.net.UnknownHostException: chat.signal.org: Name or service not known"

What may this mean?

**Comment by AsamK** [comment]
That looks like a network or dns name resolution problem on your device.

**Comment by ostasevych** [comment]
> That looks like a network or dns name resolution problem on your device.

Everything is fine with the domain resolution. The thing may be that the certificate at chat.signal.org is self-signed 
![image](https://user-images.githubusercontent.com/5199030/201210495-d1f98920-0ed3-44eb-9299-04e37a6b5ec5.png)
