### ISSUE TITLE
Invalid device link uri

### ISSUE THREAD

**Issue by lancechua** [AsamK/signal-cli#110]
I don't think this is a duplicate of #28. I tried to link a device using the command below

`signal-cli -u +123456789 addDevice --uri tsdevice:/?uuid=XXXX&pub_key=XXXX`

But I get the error message below:

```
Exception in thread "main" java.lang.RuntimeException: Invalid device link uri
        at org.asamk.signal.Manager.addDeviceLink(Manager.java:451)
        at org.asamk.signal.Main.handleCommands(Main.java:249)
        at org.asamk.signal.Main.main(Main.java:80)
'pub_key' is not recognized as an internal or external command,
operable program or batch file.
```

I'm linking a signal-cli device to another signal-cli device. The URI is just the output from the other device when running

`signal-cli link -n "ABC"`

I'm using windows 10 on both devices. Please let me know if I'm missing anything . Thanks.

Edit:  Sorry for the spam. Both devices running version 0.5.6

**Comment by brad2014** [comment]
Is this a quoting issue?  Perhaps 
```signal-cli -u +123456789 addDevice --uri 'tsdevice:/?uuid=XXXX&pub_key=XXXX'```

**Comment by lancechua** [comment]
I feel stupid now. Works perfectly. Thanks!

**Comment by thirs** [comment]
I have the same issue here, even with quotes. I'm on an old windows 7 (did the same on a debian and it worked perfectly...). Any clues?

**Comment by Trolldemorted** [comment]
Do you use powershell or cmd?

**Comment by thirs** [comment]
Powershell, I believe.

**Comment by Trolldemorted** [comment]
Powershell has [very odd escaping rules](https://stackoverflow.com/questions/36142786/how-to-escape-ampersands-semicolons-and-curly-braces-in-command-line-powershel), if you just want a quick solution use cmd.

If you find out how do do it with powershell, it would be nice if you'd share it here - the last time I registered I just resorted to cmd because I was lazy.

**Comment by thirs** [comment]
It worked, thanks a lot for your help!
