### ISSUE TITLE
Dbus received mention problem

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1100]
When I reveive a mention the name and uuid both contain the uuid. The mention number is empty. How do I check if someone mentioned me? I do not know my uuid as the accounts file is not accessible by my program

**Comment by AsamK** [comment]
The mention field should contain the phone number if it is known signal-cli, which in case of your own number should always be the case.
Can you verify that mentioning yourself contains the phone number there?
If not it would help to know your exact setup with signal-cli including the version.

**Comment by Tsjippy** [comment]
So when someone mentions the signal user I am listening to I see this:

```
[16-Jan-2023 09:26:46 UTC] stdClass Object
(
    [envelope] => stdClass Object
        (
            [source] => SOURCEPHONENUMBER
            [sourceNumber] => SOURCEPHONENUMBER
            [sourceUuid] => SOURCEPHONEUUID
            [sourceName] => SOURCEPHONENAME
            [sourceDevice] => 1
            [timestamp] => 1673861203516
            [dataMessage] => stdClass Object
                (
                    [timestamp] => 1673861203516
                    [message] => ? prayer
                    [expiresInSeconds] => 0
                    [viewOnce] => 
                    [mentions] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [name] => MYUUID
                                    [number] => 
                                    [uuid] => MYUUID
                                    [start] => 0
                                    [length] => 1
                                )

                        )

                    [groupInfo] => stdClass Object
                        (
                            [groupId] => GROUPID
                            [type] => DELIVER
                        )

                )

        )

    [account] => MYACCOUNTPHONENUMBER
)
```

So the number is empty but it should contain MYACCOUNTPHONENUMBER.

I am on version 0.11.6

I run signal-cli in DBUS mode using this crontab entry:
`@reboot export DISPLAY=:0.0; export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus;/home/simnige1/web/simnigeria.org/public_html/wp-content/signal-cl>`

**Comment by AsamK** [comment]
Haven't been able to reproduce this.
