### ISSUE TITLE
Signal Pin over Phone service not working?

### ISSUE THREAD

**Issue by piratenpanda** [AsamK/signal-cli#1101]
I am not sure if this is related to signal-cli, might not be, but I'm still trying to get some input. I finally got the phone call in out lab but it said "Sorry, an error occured, bye" or something like that. I guess it's just the phone service that's buggy and not signal-cli? Anyone else having this problem?

**Comment by mattwr18** [comment]
I have been trying to register two different phone numbers and I'm not getting a call at all. Tried for the last couple hours and no phone call.

**Comment by orazioedoardo** [comment]
Does it work with the app?

**Comment by mattwr18** [comment]
@orazioedoardo I just tested on my android device with dual app for both numbers, requested a phone call, and received none for either. The phone numbers I am using are woopla numbers, which have call forwarding set up to my number and I've double checked that calling the numbers I am able to receive the call on my device.

**Comment by Costly** [comment]
we are experiencing the same issues. Once we get the call a voice says: "An application occured. Bye". Signal Registration RIP?

**Comment by piratenpanda** [comment]
There is no other way to register landline numbers, right?

**Comment by morph027** [comment]
Hm, just registered a new account (sipgate) yesterday (using the builtin JSON-RPC service).

**Comment by piratenpanda** [comment]
just tried and it seems to be working again. Lets see if it works for me at work tomorrow

**Comment by piratenpanda** [comment]
By checking at home I was thinking it should work at work too but it didn't so I started investigating. The culprit was that I didn't have a locale set in my WSL ubuntu install, so it was C.UTF-8. After setting my correct locale to de_DE I got a phone call from a german number, got my pin and everything is working fine again

**Comment by AsamK** [comment]
Thanks for analyzing, I've added a fallback locale for this scenario.
