### ISSUE TITLE
Failed to register: [413] Rate limit exceeded: 413

### ISSUE THREAD

**Issue by ostasevych** [AsamK/signal-cli#1102]
After reinstalling docker I found that I lost the registration. While trying to register I am getting the error specifically for my number:
_Failed to register: [413] Rate limit exceeded: 413_

Are any rate limitations for registration? Which are the ways to reset these limitations? Thanks!

**Comment by piratenpanda** [comment]
I think it's three times a day or so and defined by the signal server. I don't think a client can change this unfortunately.
