### ISSUE TITLE
Possible to update the binary distribitions for this package?

### ISSUE THREAD

**Issue by anisjonischkeit** [AsamK/signal-cli#1108]
Hi, prior to the 499 problem I was installing signal-cli via the http://dl-cdn.alpinelinux.org/alpine/edge/testing repo. Would it be possible to push a new build up for alpine (and probably also the others listed here https://github.com/AsamK/signal-cli/wiki/Binary-distributions)? I've tried to run the packaged version from the releases page but am getting a shared library error:

```
Failed to call libsignal-client: /tmp/resource11362899653367276444.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/resource11362899653367276444.so)
Missing required native library dependency: libsignal-client
```

**Comment by AsamK** [comment]
The binary packages there are maintained by community volunteers
