### ISSUE TITLE
Add contacts

### ISSUE THREAD

**Issue by redshiftzero** [AsamK/signal-cli#111]
It would be great if a user could add a contact via the CLI (instead of [manually editing the config](https://github.com/AsamK/signal-cli/issues/12#issuecomment-220733780)). The reason being that currently in Signal Desktop there is no way to add the contact names for numbers. Ideally the contacts added via the CLI would then get synced to the associated devices. 

Related ticket: #12

**Comment by RachelHendy** [comment]
This, pretty please :)
