### ISSUE TITLE
SW_HARDENING NEEDED on GitHub Actions

### ISSUE THREAD

**Issue by chetbox** [AsamK/signal-cli#1111]
I use `signal-cli` with JSON RPC on GitHub Actions and today I've started seeing this error:

```
java.security.SignatureException: Quote status is: SW_HARDENING_NEEDED and advisories are: [INTEL-SA-00615, INTEL-SA-00334] (IOException)
```

[Here](https://github.com/chetbox/brighton-explorers-signal/actions/runs/3576959839/jobs/6015388081) is a workflow run that failed.

This is using `signal-cli` version 0.11.2.

A quick Google let me here, which may gives some insights, although I don't know if this code is used in Signal CLI: 
https://github.com/signalapp/ContactDiscoveryService/blob/main/service/src/main/java/org/whispersystems/contactdiscovery/client/IntelClient.java

**Comment by AsamK** [comment]
Please test if it works in the latest version 0.11.5.1
There's been a change in the libsignal-client library that might resolve this.

**Comment by chetbox** [comment]
That seems to work. Thanks for the swift response. :)
