### ISSUE TITLE
How to link signal-cli without being kicked out from the desktop and mobile app?

### ISSUE THREAD

**Issue by RasmonT** [AsamK/signal-cli#1115]
Hello,

I have registered my phone number to my server (signal-cli -u $PHONE_NR register --captcha signalcaptcha://signal-recaptcha-v2.someshortercode.registration.someverylongcode), but unfortunately it removed my session on mobile and PC. So I linked it back, but it disconnected my server session. Now when I try to register on the server. I will receive this message "Failed to register: [413] Rate limit exceeded: 413."

How to link my server device without being kicked from desktop and app? Because even if I register through the command again, it will remove my session on desktop and app...

**Comment by AsamK** [comment]
You need to use the `link` command instead.
