### ISSUE TITLE
[Question] use libsignal directly

### ISSUE THREAD

**Issue by digr8wanka** [AsamK/signal-cli#1116]
Obviously it would require a lot of work but in theory would it be possible to use `libsignal` directly instead of using `libsignal-service-java`? That would open the possibility to drop java alltogether and write the application fully in rust which in turn would minimize startup times and memory footprint.

**Comment by AsamK** [comment]
It's possible and others are already doing that (https://github.com/whisperfish/libsignal-service-rs and https://github.com/whisperfish/presage). It is however a lot more work to reimplement the functionality that libsignal-service-java already provides.

**Comment by digr8wanka** [comment]
Thank you for the links!
