### ISSUE TITLE
phone gets id

### ISSUE THREAD

**Issue by yjeanrenaud** [AsamK/signal-cli#1119]
from time to time, I receive a message where the senders phone looks like `724ce61e-AAAA-BBBB-CCCC-b0d2340c2492`
how come?
I am on signal-cli v0.11.5.1 using --dbus-system

**Comment by AsamK** [comment]
That's caused by a change in the Signal-Server. Every registered account has an additional account id (UUID). That account id is used for the first messages. Only after responding to the incoming message, you will see the sender's phone number.
