### ISSUE TITLE
Add subcommand to remove known identities

### ISSUE THREAD

**Issue by mejo-** [AsamK/signal-cli#112]
Thanks for developing signal-cli, it's a very helpful tool!

I'm missing a subcommand to manage - especially: remove - known identities. This is for privacy reasons. I don't want to keep all contacts I sent a message in my signal-cli configuration forever. This `removeIdentity` would need to remove any traces of the identity (at least all related sessions and messages).

Would you consider to add such a subcommand?

Also, is there anything that can be done on the signal servers to remove traces to those contacts? I don't think so, as signal doesn't store a social graph, right?

**Comment by AsamK** [comment]
Implemented in 7e7e4150e19a65c646bb3f4ec33b5ec87224f8cf with `removeContact --forget`
