### ISSUE TITLE
[complete idiot] Python DBus not working

### ISSUE THREAD

**Issue by tizu69** [AsamK/signal-cli#1122]
Whenever running the example DBus script, I get the following error message.
```
Traceback (most recent call last):
  File "/home/admin/Documents/Bots/Signal/main.py", line 11, in <module>
    signal = bus.get('org.asamk.Signal')
  File "/home/admin/.local/lib/python3.10/site-packages/pydbus/proxy.py", line 44, in get
    ret = self.con.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)
```
I have to note that I followed this guide, but it seems to be almost the exact same to the normal one. https://fabiobarbero.eu/posts/signalbot/

Using the provided `signal-cli --dbus send -m "Message" [RECIPIENT [RECIPIENT ...]] [-a [ATTACHMENT [ATTACHMENT ...]]]` and `dbus-send --session --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:MessageText array:string: string:RECIPIENT
` works without any problems.

**Comment by AsamK** [comment]
I guess your python script is trying to connect to the system bus, but signal-cli is running on the session bus.
Try replacing `bus = SystemBus()` with `bus = SessionBus()`
