### ISSUE TITLE
read replies?

### ISSUE THREAD

**Issue by tizu69** [AsamK/signal-cli#1123]
![Screenshot_20221210-185349](https://user-images.githubusercontent.com/60812901/206868753-c821b195-562a-4aaf-8793-2047388fd687.png)
Can I somehow see if the message is replying to another one and, if yes, read that message?
~~btw this projects awesome, I'm just somewhat missing a community discord (or some other social media) for questions, as these are, well, "issues".~~ Just found out about the "Discussions" tab, I'll use that for future questions.

**Comment by AsamK** [comment]
You need to subscribe to the `MessageReceivedV2` event, that has an extras field which among other things contains the quote information: https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/Signal.java#L189
It's unfortunately not documented yet.
