### ISSUE TITLE
[Feature Request] Read profile

### ISSUE THREAD

**Issue by SlugFiller** [AsamK/signal-cli#1125]
There's a command for updating a profile, but oddly, no command for reading a profile, and/or attempting to sync it from the network. It really should be as simple as serializing the output of ProfileHelper.getSelfProfile. Although it might be nice to have it for getRecipientProfile in general.

I don't see any logical reason why this information should be write-only.

**Comment by AsamK** [comment]
The `listContacts` command can be used for that, it also returns the profile information.
`signal-cli listContacts -a +NUMBER`

**Comment by SlugFiller** [comment]
Hm. Yes. It appears with 'all-recipients'. But without avatars. Not even an indication if an avatar exists or not.
