### ISSUE TITLE
Backward compatible

### ISSUE THREAD

**Issue by nkray2704** [AsamK/signal-cli#1137]
Hi Team,

This code is backward compatible or every time we need to get latest code from Github. I have downloaded signal code in approx april 2022 and some changes in this code according to me but not working. Again download code in November but see on Github again release is upgraded. So please clearify the code is backward compatible or every time we need to download latest release.

Thanks !!

**Comment by AsamK** [comment]
Depends on what you mean with backward compatible.
signal-cli can open files created by previous signal-cli versions.
But old signal-cli versions will stop working at some point, when the Signal-Server has breaking changes.

**Comment by nkray2704** [comment]
If we use latest version(v0.11.6) of Signal Cli code then we need to need to again upgrade Signal Cli when you again upgrade the Signal Cli release.
