### ISSUE TITLE
blocked&expiry timer sync is coming to the official android clients

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#115]
https://github.com/WhisperSystems/libsignal-service-java/commit/c8d7c3c00445a81b81e0a7305151cda4534ba299

It would be great if signal-cli would use it too

**Comment by daniel-sch** [comment]
I started working on blocking contacts (see https://github.com/daniel-sch/signal-cli/tree/blocking) and setting and syncing the blocked property to the desktop client seems to work very nicely.

However, I'm not sure how messages from blocked contacts should be handled by signal-cli itself. Should the messages be displayed with the body replaced by e.g. "This message was blocked" or should they be completely omitted from the output?

**Comment by AsamK** [comment]
nice, I think messages from blocked contacts should be ignored completely.

If someone has a use-case where blocked messages are of interest, we could possibly add some configuration to also handle blocked messages in the future.

**Comment by daniel-sch** [comment]
The basic functionality (setting the blocked status for contacts and groups in cli using `block` and `unblock` commands, hiding blocked messages, pushing blocked property to other clients in the `sendContacts` and `sendGroups` methods) should work now.

The only remaining part now is to store the blocked property in received sync messages. Do you have a link to a good documentation of the Signal protocol?
