### ISSUE TITLE
PHONE_NUMBER_PRIVACY - hide phone number - hide who is registred and soon username (ready on staging server)

### ISSUE THREAD

**Issue by xyz-nobody** [AsamK/signal-cli#1151]
I tried to search in the source code of signal-cli, but I can't find these two options:

![signal-2023-01-07-155100](https://user-images.githubusercontent.com/6586244/211159353-50bc1533-3f2f-4e6e-bd52-747f93638259.jpeg)

It depends on these parameters that must be activated in the source code

And if you are on the staging server and activate this parameter, you can even have the user names.

How can I activate this in signal-cli?

https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/util/FeatureFlags.java

  /**
   * Whether phone number privacy is enabled.
   * IMPORTANT: This is under active development. Enabling this *will* break your contacts in terrible, irreversible ways.
   */
  public static boolean phoneNumberPrivacy() {
    return getBoolean(PHONE_NUMBER_PRIVACY, true);

Need to change false to true.

Very soon we will have the usernames at signal in productions :)

With signal-cli you can already receive and send messages to a person who has activated these settings on Android

![image](https://user-images.githubusercontent.com/6586244/211160655-2a3eb440-ec38-4aba-abf9-c8a60eab0b07.png)

![image](https://user-images.githubusercontent.com/6586244/211160869-a4130d28-f48a-4e92-a3c5-b26ff99dc90f.png)

So now I'm just trying to figure out, how could we activate this on the signal-client side to be able to send messages without the number being displayed.

This would allow to leave signal-cli in master and finally to have real Android Slave clients with this option, while preserving the security of our phone number :)

In any case soon this same parameter will be useful for the choice of user names (For the moment the usernames are blocked on the main server, it is just active on the staging server)

![image](https://user-images.githubusercontent.com/6586244/211161119-c05103dc-f252-4063-a512-aeaf66d88d0a.png)

**Comment by AsamK** [comment]
Those options aren't officially supported yet, so there's no interface to activate them in signal-cli. If you want to experiment with them, you need to enable them manually in the signal-cli account file.
