### ISSUE TITLE
First message received comes through with null sourceNumber

### ISSUE THREAD

**Issue by ced-b** [AsamK/signal-cli#1156]
When receiving a message from someone for the first time on Signal CLI, the `sourceNumber` property shows up as `null`. Once you send them a message the number starts showing up. 

I stepped through the code and got so far as to see that once the envelope gets decrypted, it does only have a UUID for the sender, but no actual phone number.

Oddly, I can pull all the profile data of the sender using the UUID, just not the phone number.

I am not sure if this is intended behavior or if I am missing something.

**Comment by AsamK** [comment]
That's normal, the Signal-Server doesn't include the phone number anymore in normal messages anymore. Only later messages that are then sent as unidentified sender messages include the phone number by default.

**Comment by ced-b** [comment]
Ok, makes sense.
