### ISSUE TITLE
Wiki link to signalbot?

### ISSUE THREAD

**Issue by pippcat** [AsamK/signal-cli#116]
Hey,

I wrote a small python script which uses signal-cli to send signal group messages either via mail or SMS. My usecase is that we have some people without smartphone/signal which also want to have the informations discussed in our group. Maybe you want to put the link into the wiki although it's in a rather early stage of development?
https://github.com/pippcat/signalbot/

Cheers!

**Comment by AsamK** [comment]
I've added it to the wiki, you could also edit the page yourself ;)

**Comment by pippcat** [comment]
Oh, didn't know that. Thanks anyhow :)
