### ISSUE TITLE
Update Group command not working properly

### ISSUE THREAD

**Issue by nkray2704** [AsamK/signal-cli#1160]
signal-cli 0.11.5

$ java -version
jdk-17.0.2
Server
Apache Tomcat/9.0.43
OS : LInux(Ubantu)
When create a group using Update Group command. Checking group is created and member is added or not using "listGroups" command then member is showing in pendingMembers 
"pendingMembers": [
      {
        "number": "+918207889104",
        "uuid": "ed16b518-14b6-4f40-aa21-7d1ec92556ba"
      }
    ]

Please help to resolve this issue.

**Comment by AsamK** [comment]
It's working as expected. If you don't have the other user's profile key from previous messages, the user can only be invited to the group and must accept the invitation before becoming a member.

**Comment by nkray2704** [comment]
How can move pending member list to member list.

**Comment by AsamK** [comment]
as mentioned above:
> the user [...] must accept the invitation before becoming a member.

If the member is using signal-cli himself, she can use the `updateGroup` command to add herself: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#updategroup
