### ISSUE TITLE
Cannot Receive After Update to 22.04

### ISSUE THREAD

**Issue by muad-dumb** [AsamK/signal-cli#1170]
Unclear if this is related to an apparent DNS issue on my 22.04 (which has proved intractable so far), but posting in hopes it can be resolved separately. I can't open reddit on the device so I will share pictures of outputs.    
    
ISSUE: Attempts to Receive (have already redownloaded / relinked) fail.   
    
Verbose Recieve:
![IMG_20230124_184742](https://user-images.githubusercontent.com/93455703/214446742-509b5bf7-c9e6-4c5e-8048-af1038c44e9f.jpg)
![IMG_20230124_185053](https://user-images.githubusercontent.com/93455703/214446761-171c429c-4d2d-402e-9f65-51485fdadda0.jpg)
![IMG_20230124_184110](https://user-images.githubusercontent.com/93455703/214446831-07e4b357-fd92-49c9-9a19-1706a3c982bb.jpg)

**Comment by muad-dumb** [comment]
Update: This was caused at least in part due to a DNS issue that appears to have been caused by using a Wifi Hotspot from an Android Phone. The DNS issue appears to have been resolved by accessing public wifi, but further problems exist, detailed in a new Issue here: https://github.com/AsamK/signal-cli/issues/1171

**Comment by AsamK** [comment]
There's nothing interesting in the logs above.
The websocket connection was established and then after a 3 seconds of receiving no messages it was closed again.
The only thing to try could be to increase the receive timeout `--timeout` to a few more seconds, in case the server or network is slow.
