### ISSUE TITLE
Signal-Batch Fails; submitRateLimitChallenge Not Working 

### ISSUE THREAD

**Issue by muad-dumb** [AsamK/signal-cli#1177]
OS: Ubuntu 22.04 [Fully up to date with apt before encountering issue]
Signal-CL Version: 0.11.6.
Signal-Desktop Version: 6.4.1

Attempting to use Signal Batch to send a message with 150+ recipients:

Signal-CLI returns following errors:
1. WARN  SendHelper - Failed to send message due to IO exception: java.net.ProtocolException: unexpected end of stream
2. WARN  SendHelper - Sending failed due to rate limiting from the signal server: [413] Rate limit exceeded: 413
3. Failed to send (some) messages:

**Result:** 
All messages failed to send.

**Attempted Fix:**

Attempts to submit a rate limit challenge do not seem to be working. Following the instructions provided at https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc to best of my ability.

**Assumptions:**
1. The "challenge token" is the number spit out by signal-cli at the very end of the fail messages, in the format of: "1675635489684". No other possibility is apparent through the CLI output.   

2. The "captcha result" is found in after navigating to the https://signalcaptchas.org/challenge/generate.html , completing the captcha, and then from the completed Captcha page hitting F12 and navigating to "Console", copying every character after signalcaptcha:// into an input in the following format:

./signal-cli submitRateLimitChallenge --challenge 1675635489684 --captcha "characters following signalcaptcha://"

No other potential options for the "challenge token" or the captcha generated characters are apparent.

**Attempted Fix Result:**

The CLI seems to accept the input, it displays no more messages and returns to the basic prompt at signal-cli/bin $ , but after reattempting to use the batch script, the same original issue occurs.

Process has been attempted 3 times. Tried both by going straight to the batch script after submitting the challenge, and also by submitting the challenge and then doing a "receive" command before attempting the batch script.

**Comment by Tsjippy** [comment]
I think you are misunderstanding it.
If reach the limit, i don't know what the limit is, then you have to submit the rate challenge to be able to send messages at all.

Apparently 150+ is too much. You submit the rate challenge and then you send again 150, causing another rate limit.

You should split them in 50? and try that

**Comment by muad-dumb** [comment]
Sending with only 50 recipients returns a similar result. The only fail output before the message indicating that messages have failed to send is the following:

WARN  SendHelper - Failed to send message due to IO exception: java.net.ProtocolException: unexpected end of stream

And all messages fail.

**Comment by muad-dumb** [comment]
The system will successfully send messages that are smaller in characters than the full message I would like to send to each phone number. For example, I can send messages saying "this is a troubleshooting message, don't respond". 

But the full message, which is 2,439 characters, triggers this failure. While I can see potential workarounds and will employ them for the moment, this is very less than ideal for my workflow. 

To note: I have been using this system to send messages like this--- of similar length, using the batch script, and to this many recipients ---for a number of years, so I'm assuming this is some new issue either in signal-cli, signal-desktop (or Signal's character count requirements?), or in the Java structure that signal-cli uses. I don't personally have the technical know-how to diagnosis any of those suspicions, unfortunately.
