### ISSUE TITLE
libsignal-service-java has been archived - move to libsignal

### ISSUE THREAD

**Issue by kmille** [AsamK/signal-cli#1181]
https://github.com/signalapp/libsignal-service-java has been marked as archived. https://github.com/signalapp/libsignal is the new library.
> libsignal-protocol: Implements the Signal protocol, including the [Double Ratchet algorithm](https://signal.org/docs/). A replacement for [libsignal-protocol-java](https://github.com/signalapp/libsignal-protocol-java) and [libsignal-metadata-java](https://github.com/signalapp/libsignal-metadata-java).

Do you plan to migrate to the new library? I couldn't find anything in the docs.

**Comment by AsamK** [comment]
Signal-cli uses a forked version already https://github.com/Turasa/libsignal-service-java
