### ISSUE TITLE
`removeContact --forget` error

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#1183]
Runinng `removeContact --forget` prints an error (including the `--verbose` output below):

	[main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:156: Initializing libsignal version:0.21.1
	[main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
	[main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
	[main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@40f70521
	[main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
	[main] WARN  LibSignal - [PhoneNumberFormatter]: Got local CC: US
	[main] DEBUG o.a.s.m.s.recipients.RecipientStore - Deleting recipient data for RecipientId[id=57]
	[main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
	[main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
	java.lang.RuntimeException: Expected a row in result set, but none found.
		at org.asamk.signal.manager.storage.Utils.executeQuerySingleRow(Utils.java:79)
		at org.asamk.signal.manager.storage.recipients.RecipientStore.resolveRecipientAddress(RecipientStore.java:104)
		at org.asamk.signal.manager.storage.SignalAccount.removeRecipient(SignalAccount.java:420)
		at org.asamk.signal.manager.ManagerImpl.deleteRecipient(ManagerImpl.java:739)
		at org.asamk.signal.commands.RemoveContactCommand.handleCommand(RemoveContactCommand.java:37)
		at org.asamk.signal.App.handleLocalCommand(App.java:289)
		at org.asamk.signal.App.init(App.java:229)
		at org.asamk.signal.Main.main(Main.java:60)

The contact is deleted successfully however, despite the error. Running `removeContact` without `--forget` works, and does not produce an error.

**Comment by exquo** [comment]
Also, even with the `--forget` flag, the contact is not "completely" forgotten: after receiving another message from them, they are automatically added back to the contacts list (get included in `listContacts`). In contrast, when a message is received from a new contact, the contact is not added to the contacts list automatically, but needs first to be "accepted" first (see #1184). 

I guess this means there is some residual information left about the contact somewhere. Although for all I know, that might be the way it's supposed to work and how signal shares contacts data.

**Comment by AsamK** [comment]
I'll make a fix for the error above.

Do you have a linked device? Currently signal-cli can't delete the contact information from the linked device, which would then cause the contact to reappear.

**Comment by exquo** [comment]
Yes, this is on a linked device. That makes sense, thank you!
