### ISSUE TITLE
Accepting a new contact

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#1184]
Signal-desktop allows to "Accept" a new (unknown) contact after they message you.

![signal-desktop-contact-req](https://user-images.githubusercontent.com/62397152/219284206-14d33ca7-2a00-4228-871f-fe806a049c08.png)

After accepting in signal-desktop, the contact is included in signal-cli's `listContacts`.
Would it be possible to accomplish the same thing with signal-cli alone?

**Comment by exquo** [comment]
> After accepting in signal-desktop, the contact is included in signal-cli's `listContacts`.

Just a small correction: I have tried this again, with another contact, and after clicking "Accept" the contact does not yet show up in `listContacts`. Nor after sending a message to it from signal-desktop. Only after getting my sent message on the contact's device (and getting a corresponding delivery receipt on my device) the contact has shown up in `listContacts`.

I'm guessing signal-cli needs to get a message from a contact, which also includes contact's profile.

**Comment by sparrowme** [comment]
> Would it be possible to accomplish the same thing with signal-cli alone?

I too am looking for this part.  

A message from a new contact has been received and can be seen with the receive...

```	{
			"envelope": {
				"source": "b0a1beed-088d-xxxx-xxxx-xxxxx071f3e0",
				"sourceNumber": null,
				"sourceUuid": "b0a1beed-088d-xxxx-xxxx-xxxxx071f3e0",
				"sourceName": "Mr User",
				"sourceDevice": 2,
				"timestamp": 1705690646746,
				"dataMessage": {
					"timestamp": 1705690646746,
					"message": "asdf",
					"expiresInSeconds": 0,
					"viewOnce": false
				}
			},
			"account": "+11234567890"
		}
```

However, the sourceNumber is null, presumably because I have not "accepted" the new contact (as I can in Desktop).  And now I can't yet reply via the cli

Am I overlooking a command for accepting a new contact?

**Comment by sparrowme** [comment]
Seems this is mentioned in some closed issues like...

https://github.com/AsamK/signal-cli/issues/1002#issuecomment-1229798819

Just send the uuid instead :wink:

**Comment by AsamK** [comment]
In the next version the `sendMessageRequestResponse` command can be used to accept/delete message requests like in the official apps (fd671576a4aef0e5f9ef795b1985930cf02bcb84).
