### ISSUE TITLE
Sender's old profile name in `sourceName` 

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#1185]
The messages received from a new/unknown contact have an empty string in the `sourceName` (the contact's profile name), until they are opened in signal-desktop. The contact does not have to be "accepted" in signal-desktop (see #1184), just getting the messages appears to be sufficient for the `sourceName` to start to be shown in envelopes received by signal-cli. 

Dose signal-desktop request more of the contact's profile? Should signal-cli do so also?

**Comment by AsamK** [comment]
signal-cli should also get the user's profile information directly in that case. Do you have a log of that happening?

**Comment by exquo** [comment]
I have attempted to reproduce this, and it turns out the issue is slightly different: the profile name does not get *updated* after it is received for the first time. 

That is, if the sender's profile was empty the first time they have sent me a message, and afterwards they have changed their profile name to something else, that change won't be shown in signal-cli for the subsequently received messages: the `sourceName` will be shown the same as in the first message.

Testing with a new number this time, I have first set their profile name *before sending the first message*; signal-cli  correctly shows this name in the received envelope's `sourceName`. Then I changed the profile with `updateProfile` (the sender is also a signal-cli), and then sent several more messages. Signal-cli (receiver) shows the old profile name in `sourceName`.

Here are the logs.
	
Daemon command (on the receiving end): 

	 signal-cli --verbose --scrub-log --output json daemon 


<details>
<summary>Getting the first message:</summary>

	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - New message received from server
	[receive-0] INFO  LibSignal - [libsignal]: rust/protocol/src/session_cipher.rs:438: decrypted PreKey message from ********-****-****-****-**********50.1 with current session state (base key 861656b7408215f78750fb20d57eeabb861aca3ca39b288b7c4c299bf7a1593a)
	{"envelope":{"source":"<SENDER_ID>","sourceNumber":null,"sourceUuid":"<SENDER_ID>","sourceName":"Original Name","sourceDevice":1,"timestamp":1676821431128,"dataMessage":{"timestamp":1676821431128,"message":"First message","expiresInSeconds":0,"viewOnce":false}},"account":"+123456789"}
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Creating message with serial 5
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Appending sig: yyyy data: [108, 4, 0, 1]
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Appending sig: ua(yv) data: [6, [[1, [o, /org/asamk/Signal/_123456789]], [2, [s, org.asamk.Signal]], [3, [s, MessageReceived]], [8, [g, xsaysas]]]]
	[DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceived - Appending sig: xsaysas data: [1676821431128, ********-****-****-****-**********50, [], With output=json, []]
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Creating message with serial 6
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: yyyy data: [108, 4, 0, 1]
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: ua(yv) data: [7, [[1, [o, /org/asamk/Signal/_123456789]], [2, [s, org.asamk.Signal]], [3, [s, MessageReceivedV2]], [8, [g, xsaysa{sv}]]]]
	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceived(0,6) { Path=>/org/asamk/Signal/_123456789, Interface=>org.asamk.Signal, Member=>MessageReceived, Signature=>xsaysas } { 1676821431128, ********-****-****-****-**********50, [], With output=json, [] }
	[DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: xsaysa{sv} data: [1676821431128, ********-****-****-****-**********50, [], With output=json, {isViewOnce=[false], expiresInSeconds=[0]}]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceivedV2(0,7) { Path=>/org/asamk/Signal/_123456789, Interface=>org.asamk.Signal, Member=>MessageReceivedV2, Signature=>xsaysa{sv} } { 1676821431128, ********-****-****-****-**********50, [], With output=json, {isViewOnce=[false], expiresInSeconds=[0]} }

</details>

<details>
<summary>After changing the sender's profile name:</summary>

	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - New message received from server
	[receive-0] INFO  LibSignal - [libsignal]: rust/protocol/src/session_cipher.rs:438: decrypted PreKey message from ********-****-****-****-**********50.1 with current session state (base key 861656b7408215f78750fb20d57eeabb861aca3ca39b288b7c4c299bf7a1593a)
	{"envelope":{"source":"<SENDER_ID>","sourceNumber":null,"sourceUuid":"<SENDER_ID>","sourceName":"Original Name","sourceDevice":1,"timestamp":1676821665004,"dataMessage":{"timestamp":1676821665004,"message":"after update prof","expiresInSeconds":0,"viewOnce":false}},"account":"+123456789"}
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Creating message with serial 7
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Appending sig: yyyy data: [108, 4, 0, 1]
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Appending sig: ua(yv) data: [8, [[1, [o, /org/asamk/Signal/_123456789]], [2, [s, org.asamk.Signal]], [3, [s, MessageReceived]], [8, [g, xsaysas]]]]
	[DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceived - Appending sig: xsaysas data: [1676821665004, ********-****-****-****-**********50, [], after update prof, []]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceived(0,8) { Path=>/org/asamk/Signal/_123456789, Interface=>org.asamk.Signal, Member=>MessageReceived, Signature=>xsaysas } { 1676821665004, ********-****-****-****-**********50, [], after update prof, [] }
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Creating message with serial 8
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: yyyy data: [108, 4, 0, 1]
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: ua(yv) data: [9, [[1, [o, /org/asamk/Signal/_123456789]], [2, [s, org.asamk.Signal]], [3, [s, MessageReceivedV2]], [8, [g, xsaysa{sv}]]]]
	[DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: xsaysa{sv} data: [1676821665004, ********-****-****-****-**********50, [], after update prof, {isViewOnce=[false], expiresInSeconds=[0]}]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceivedV2(0,9) { Path=>/org/asamk/Signal/_123456789, Interface=>org.asamk.Signal, Member=>MessageReceivedV2, Signature=>xsaysa{sv} } { 1676821665004, ********-****-****-****-**********50, [], after update prof, {isViewOnce=[false], expiresInSeconds=[0]} }
	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server

</details>

<details>
<summary>After restarting signal-cli daemon (receiving client):
</summary>


	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - New message received from server
	[receive-0] INFO  LibSignal - [libsignal]: rust/protocol/src/session_cipher.rs:438: decrypted PreKey message from ********-****-****-****-**********50.1 with current session state (base key 861656b7408215f78750fb20d57eeabb861aca3ca39b288b7c4c299bf7a1593a)
	{"envelope":{"source":"<SENDER_ID>","sourceNumber":null,"sourceUuid":"<SENDER_ID>","sourceName":"Original Name","sourceDevice":1,"timestamp":1676821762495,"dataMessage":{"timestamp":1676821762495,"message":"after daemon restart on receiver","expiresInSeconds":0,"viewOnce":false}},"account":"+123456789"}
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Creating message with serial 5
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Appending sig: yyyy data: [108, 4, 0, 1]
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Appending sig: ua(yv) data: [6, [[1, [o, /org/asamk/Signal/_123456789]], [2, [s, org.asamk.Signal]], [3, [s, MessageReceived]], [8, [g, xsaysas]]]]
	[DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceived - Appending sig: xsaysas data: [1676821762495, ********-****-****-****-**********50, [], after daemon restart on receiver, []]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceived(0,6) { Path=>/org/asamk/Signal/_123456789, Interface=>org.asamk.Signal, Member=>MessageReceived, Signature=>xsaysas } { 1676821762495, ********-****-****-****-**********50, [], after daemon restart on receiver, [] }
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Creating message with serial 6
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: yyyy data: [108, 4, 0, 1]
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: ua(yv) data: [7, [[1, [o, /org/asamk/Signal/_123456789]], [2, [s, org.asamk.Signal]], [3, [s, MessageReceivedV2]], [8, [g, xsaysa{sv}]]]]
	[DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: xsaysa{sv} data: [1676821762495, ********-****-****-****-**********50, [], after daemon restart on receiver, {isViewOnce=[false], expiresInSeconds=[0]}]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceivedV2(0,7) { Path=>/org/asamk/Signal/_123456789, Interface=>org.asamk.Signal, Member=>MessageReceivedV2, Signature=>xsaysa{sv} } { 1676821762495, ********-****-****-****-**********50, [], after daemon restart on receiver, {isViewOnce=[false], expiresInSeconds=[0]} }
	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server

</details>

<details>
<summary>After restarting the sender client (also happens to be a signal-cli daemon in this test, a primary device):</summary>

	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - New message received from server
	[receive-0] INFO  LibSignal - [libsignal]: rust/protocol/src/session_cipher.rs:438: decrypted PreKey message from ********-****-****-****-**********50.1 with current session state (base key 861656b7408215f78750fb20d57eeabb861aca3ca39b288b7c4c299bf7a1593a)
	{"envelope":{"source":"<SENDER_ID>","sourceNumber":null,"sourceUuid":"<SENDER_ID>","sourceName":"Original Name","sourceDevice":1,"timestamp":1676822205718,"dataMessage":{"timestamp":1676822205718,"message":"after daemon restart on sender","expiresInSeconds":0,"viewOnce":false}},"account":"+123456789"}
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Creating message with serial 7
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Appending sig: yyyy data: [108, 4, 0, 1]
	[receive-0] DEBUG org.asamk.Signal$MessageReceived - Appending sig: ua(yv) data: [8, [[1, [o, /org/asamk/Signal/_123456789]], [2, [s, org.asamk.Signal]], [3, [s, MessageReceived]], [8, [g, xsaysas]]]]
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Creating message with serial 8
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: yyyy data: [108, 4, 0, 1]
	[DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceived - Appending sig: xsaysas data: [1676822205718, ********-****-****-****-**********50, [], after daemon restart on sender, []]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceived(0,8) { Path=>/org/asamk/Signal/_123456789, Interface=>org.asamk.Signal, Member=>MessageReceived, Signature=>xsaysas } { 1676822205718, ********-****-****-****-**********50, [], after daemon restart on sender, [] }
	[receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: ua(yv) data: [9, [[1, [o, /org/asamk/Signal/_123456789]], [2, [s, org.asamk.Signal]], [3, [s, MessageReceivedV2]], [8, [g, xsaysa{sv}]]]]
	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Handling message actions
	[receive-0] DEBUG o.a.s.manager.helper.ReceiveHelper - Checking for new message from server
	[DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceivedV2 - Appending sig: xsaysa{sv} data: [1676822205718, ********-****-****-****-**********50, [], after daemon restart on sender, {isViewOnce=[false], expiresInSeconds=[0]}]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceivedV2(0,9) { Path=>/org/asamk/Signal/_123456789, Interface=>org.asamk.Signal, Member=>MessageReceivedV2, Signature=>xsaysa{sv} } { 1676822205718, ********-****-****-****-**********50, [], after daemon restart on sender, {isViewOnce=[false], expiresInSeconds=[0]} }

</details>

After waiting about 10 minutes and restarting signal-cli daemon (receiver), again: still the `sourceName` in the received envelope is the one originally set.

After changing the name with `updateProfile` the second time and sending another message: still the original name in `sourceName`.

After launching signal-desktop (linked with the receiver; receiver is also a linked device; primary is signal-android) and getting another message: still the original profile name in `sourceName`.. After opening the chat in signal-desktop, scrolling down the messages, and clicking on the profile picture: no change.. 
Restarted the signal-cli daemon (receiver) again: no change.
Signal-desktop itself does correctly show the latest set profile name; tried changing again - signal-desktop does display it.

So I guess it's not signal-desktop that has helped to get the updated profile name last time.. But not sure what did it.

**Comment by AsamK** [comment]
Ah, thanks for clarifying. signal-cli caches profiles for 6h before downloading them again.
Refreshing a contact's profile information can be forced with the listContacts command: `signal-cli listContacts RECIPIENT`

**Comment by exquo** [comment]
I see, thanks! I don't know why launching signal-desktop last time has seemed to fix it.. Maybe the 6 hours timeout has elapsed at the same time? In my memory, it was shorter than that, but I can't be sure now.

Would it be possible / reasonable to mirror signal-desktop's behaviour, displaying the profile updates right away? If there's some kind of a "sync" message that is sent by signal servers, maybe signal-cli could get it and update the profile. In that case, this is a "feature request". Otherwise, feel free to close this.

**Comment by AsamK** [comment]
There's no sync or notification message for updated profiles.
The official clients just update the profile when the user opens a specific thread/contact. signal-cli doesn't have the concept of opening a thread ...

**Comment by exquo** [comment]
Makes sense, thanks!

And if any of signal-cli's downstream projects have an equivalent of signal-desktop's "opening thread" behavior, they can reproduce its behavior with the `listContacts RECEPIENT` command you've mentioned.
