### ISSUE TITLE
`--scrub-log` does not mask some of the values

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#1189]
Running `signal-cli --scrub-log daemon`, some of the identifying info still gets printed in several places:

- When signal-cli is launched in multi-account mode (without `--account`), in constructions with the dbus paths: `/org/asamk/Signal/_<PHONE_NUM>`.
- Group IDs and account phone number in group objects' paths:
	```
	[dbus-init] DEBUG o.asamk.signal.dbus.DbusSignalImpl - Exported dbus object: /org/asamk/Signal/_<PHONE_NUM>/Groups/<GROUP_ID_WITH_UNDERSCORES>
	```
- ... Maybe more 

From the source code, looks like the regex patterns in [Scrubber.java](https://github.com/AsamK/signal-cli/blob/2e63c3b4f7f9575b972938aea447eee51469e22d/src/main/java/org/asamk/signal/logging/Scrubber.java) matches for phone numbers in E164 format (with a leading `+` rather than `_`); and the UUIDs with `-` rather than `_`.

**Comment by exquo** [comment]
Related, #1190: sensitive info in the printed envelopes themselves (on stdout rather than the logs on stderr)

**Comment by exquo** [comment]
Some more: 

- Group IDs in byte-array format

		[DBus Sender Thread-2] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(9,5) { Path=>/org/asamk/Signal, Interface=>org.asamk.Signal, Member=>getGroup, Destination=>org.asamk.Signal, Signature=>ay } { [-223, -69, -296, -226, -29, 3, -296, 56, -8, -39, -293, 35, 89, 68, 59, -22, 226, 66, 32, 55, -222, -36, 59, 39, 55, -2, -82, -82, 223, 228, 86, 228] }

- Group names

		[DBusConnection [listener=false]] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming error: Error(0,72) { Error Name=>org.asamk.Signal.Error.GroupNotFound, Reply Serial=>6, Destination=>:1.4962, Sender=>:1.4902, Signature=>s } { Group not found: User is not a member in group: <GROUP_NAME> (<GROUP_ID>) }

**Comment by AsamK** [comment]
I've extended the scrubbing for group IDs now.
The dbus logs are hard to scrub reliably, so I've their log level to only output when very verbose logging is used `-vvv`.
