### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by ghost** [AsamK/signal-cli#119]
Hi @AsamK,

I plan to create and maintain a Docker image dedicated to packaging signal-cli. It would be almost identical to what @MichaelBitard did at https://github.com/agileek/docker/blob/master/signal-cli/Dockerfile which is also available [from the docker hub](https://hub.docker.com/r/agileek/signal-cli/).

The only improvement would be to build the image from sources, that is re-creating the .jar from sources instead of downloading binaries that were created in a non-reproducible way from the [maven central repository](https://maven.org). It is more re-assuring in contexts where security is a concern.

Please let me know if you have thoughts, reservations or ideas regarding this idea.

Cheers

P.S. For the record, it would be better to package signal-cli for Debian GNU/Linux but this is not possible at the moment because the upstream of two dependencies, libsignal-service-java and libsignal-protocol-java is not amicable to the idea. See [the corresponding issue for more context](https://github.com/AsamK/signal-cli/issues/117).

**Comment by alexanderadam** [comment]
If anybody looking for this stumbles over this issue:

There's [a PR ongoing](https://github.com/AsamK/signal-cli/pull/94) and @LoveIsGrief created a Docker image at Docker Hub that you can use until it's merged.

You can find it [here](https://hub.docker.com/r/bisentenialwrug/signal-cli#contextNav) or simply run

```
docker run -v $HOME:/home/gradle --rm -it bisentenialwrug/signal-cli -h
```

**Comment by MichaelBitard** [comment]
For the record I did not get the binary from the maven central repository, but directly from asamk release page. But I agree, a docker which build the jar would be better.

**Comment by morph027** [comment]
FYI, a ready to use docker image (amd64 + arm64) plus Debian packages can be found [here](https://gitlab.com/packaging/signal-cli/container_registry) ([Docs](https://packaging.gitlab.io/signal-cli/installation/docker/), [Repo](https://gitlab.com/packaging/signal-cli)).

**Comment by AsamK** [comment]
I'm not planning to add a Dockerfile to the repo, but I've created a wiki page, which links to morph027's repo: https://github.com/AsamK/signal-cli/wiki/Binary-distributions
