### ISSUE TITLE
Deleting a group after having already quit it

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#1192]
Is it possible to remove a group from `listGroups`, *after* I have already quit it? (Quit either from signal-cli, with `quitGroup` *without* `--delete`, or from a master or a linked device)

Running `quitGroup --delete` works (i.e., removes the group from the list), if it is run while I am *still a member of the group*. But after I've already quit the group, how can I delete it?

Same issue? #638

On a hunch, I have tried to run `removeContact [--forget]` with the group ID as an argument. It did not report errors and exited with the `0` code, but the group was not removed.
Apparently, there used to be a [`deleteGroup` command](https://github.com/AsamK/signal-cli/issues/924), but I guess it was replaced by `quitGroup`?

Related question: should removing a group be synchronized across linked devices? That is, after deleting a group in e.g. signal-desktop, should signal-cli also remove such group from its list?

**Comment by AsamK** [comment]
You can use `quitGroup --delete` also when you're not a member of that group anymore. Or do you get an error there?

There's no deleteGroup command, there's just a deleteGroup method in the DBus interface.

As far as I know there's no way to delete old groups in the official clients, just group threads can be deleted. It may be possible to synchronize group deletion with the signal storage, but signal-cli doesn't support writing to that yet (https://github.com/AsamK/signal-cli/issues/604)

**Comment by exquo** [comment]
> You can use `quitGroup --delete` also when you're not a member of that group anymore. Or do you get an error there?

Yes, sorry I forgot to include the error in the original report:

	❯ signal-cli -a <PHONE_NUM> daemon &
	❯ signal-cli --dbus quitGroup -g '<GROUP_ID>' --delete

	INFO  TransportBuilder - Using transport dbus-java-transport-native-unixsocket to connect to unix:path=/run/user/1000/bus
	Group not found: Group not found: User is not a member in group: <GROUP_NAME> (<GROUP_ID>)

	❯ echo $?
	2


<details>
<summary>--verbose logs</summary>

	[main] DEBUG o.f.d.c.transports.TransportBuilder - Found provider 'NativeTransportProvider' named 'dbus-java-transport-native-unixsocket' providing bustype 'UNIX'
	[main] INFO  o.f.d.c.transports.TransportBuilder - Using transport dbus-java-transport-native-unixsocket to connect to unix:path=/run/user/1000/bus
	[main] DEBUG o.f.d.t.j.NativeUnixSocketTransport - No alternative ISocketProvider found, using built-in implementation
	[main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 1
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [1, [[1, [o, /org/freedesktop/DBus]], [6, [s, org.freedesktop.DBus]], [2, [s, org.freedesktop.DBus]], [3, [s, Hello]]]]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,1) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>Hello, Destination=>org.freedesktop.DBus } { }
	[DBusConnection [listener=false]] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(1,1) { Reply Serial=>1, Destination=>:1.4962, Sender=>org.freedesktop.DBus, Signature=>s } { :1.4962 }
	[DBusConnection [listener=false]] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(1,1) { Reply Serial=>1, Destination=>:1.4962, Sender=>org.freedesktop.DBus, Signature=>s } { :1.4962 }
	[DBusConnection [listener=false]] DEBUG o.f.d.s.m.InputStreamMessageReader - => DBusSignal(1,2) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>NameAcquired, Destination=>:1.4962, Sender=>org.freedesktop.DBus, Signature=>s } { :1.4962 }
	[DBusConnection [listener=false]] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming signal: DBusSignal(1,2) { Path=>/org/freedesktop/DBus, Interface=>org.freedesktop.DBus, Member=>NameAcquired, Destination=>:1.4962, Sender=>org.freedesktop.DBus, Signature=>s } { :1.4962 }
	[DBus-Signal-Receiver-1] DEBUG o.f.dbus.messages.DBusSignal - Converting signal to type: class org.freedesktop.dbus.interfaces.DBus$NameAcquired
	[main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 2
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [2, [[1, [o, /org/asamk/Signal]], [6, [s, org.asamk.Signal]], [2, [s, org.asamk.SignalControl]], [3, [s, listAccounts]]]]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,2) { Path=>/org/asamk/Signal, Interface=>org.asamk.SignalControl, Member=>listAccounts, Destination=>org.asamk.Signal } { }
	[DBusConnection [listener=false]] DEBUG o.f.d.s.m.InputStreamMessageReader - => Error(0,69) { Error Name=>org.freedesktop.dbus.errors.UnknownMethod, Reply Serial=>2, Destination=>:1.4962, Sender=>:1.4902, Signature=>s } { The method `org.asamk.SignalControl.listAccounts' does not exist on this object. }
	[DBusConnection [listener=false]] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming error: Error(0,69) { Error Name=>org.freedesktop.dbus.errors.UnknownMethod, Reply Serial=>2, Destination=>:1.4962, Sender=>:1.4902, Signature=>s } { The method `org.asamk.SignalControl.listAccounts' does not exist on this object. }
	[DBus-Signal-Receiver-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Creating message with serial 3
	[DBus-Signal-Receiver-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Appending sig: yyyy data: [108, 4, 0, 1]
	[DBus-Signal-Receiver-1] DEBUG o.f.d.interfaces.DBus$NameAcquired - Appending sig: ua(yv) data: [4, [[1, [o, /org/freedesktop/DBus]], [2, [s, org.freedesktop.DBus]], [3, [s, NameAcquired]], [8, [g, s]]]]
	[main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 4
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [4, [[1, [o, /org/asamk/Signal]], [6, [s, org.asamk.Signal]], [2, [s, org.asamk.Signal]], [3, [s, getSelfNumber]]]]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,4) { Path=>/org/asamk/Signal, Interface=>org.asamk.Signal, Member=>getSelfNumber, Destination=>org.asamk.Signal } { }
	[DBusConnection [listener=false]] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(0,70) { Reply Serial=>4, Destination=>:1.4962, Sender=>:1.4902, Signature=>s } { +*********59 }
	[DBusConnection [listener=false]] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(0,70) { Reply Serial=>4, Destination=>:1.4962, Sender=>:1.4902, Signature=>s } { +*********59 }
	[main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 5
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending arguments with signature: ay
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [5, [[1, [o, /org/asamk/Signal]], [6, [s, org.asamk.Signal]], [2, [s, org.asamk.Signal]], [3, [s, getGroup]], [8, [g, ay]]]]
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ay data: [[-223, -69, -296, -226, -29, 3, -296, 56, -8, -39, -293, 35, 89, 68, 59, -22, 226, 66, 32, 55, -222, -36, 59, 39, 55, -2, -82, -82, 223, 228, 86, 228]]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,5) { Path=>/org/asamk/Signal, Interface=>org.asamk.Signal, Member=>getGroup, Destination=>org.asamk.Signal, Signature=>ay } { [-223, -69, -296, -226, -29, 3, -296, 56, -8, -39, -293, 35, 89, 68, 59, -22, 226, 66, 32, 55, -222, -36, 59, 39, 55, -2, -82, -82, 223, 228, 86, 228] }
	[DBusConnection [listener=false]] DEBUG o.f.d.s.m.InputStreamMessageReader - => MethodReturn(0,71) { Reply Serial=>5, Destination=>:1.4962, Sender=>:1.4902, Signature=>o } { /org/asamk/Signal/Groups/<GROUP_ID> }
	[DBusConnection [listener=false]] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming method return: MethodReturn(0,71) { Reply Serial=>5, Destination=>:1.4962, Sender=>:1.4902, Signature=>o } { /org/asamk/Signal/Groups/<GROUP_ID> }
	[main] DEBUG o.f.dbus.messages.MethodCall - Creating message with serial 6
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: yyyy data: [108, 1, 0, 1]
	[main] DEBUG o.f.dbus.messages.MethodCall - Appending sig: ua(yv) data: [6, [[1, [o, /org/asamk/Signal/Groups/<GROUP_ID>]], [6, [s, org.asamk.Signal]], [2, [s, org.asamk.Signal.Group]], [3, [s, quitGroup]]]]
	[DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MethodCall(0,6) { Path=>/org/asamk/Signal/Groups/<GROUP_ID>, Interface=>org.asamk.Signal.Group, Member=>quitGroup, Destination=>org.asamk.Signal } { }
	[DBusConnection [listener=false]] DEBUG o.f.d.s.m.InputStreamMessageReader - => Error(0,72) { Error Name=>org.asamk.Signal.Error.GroupNotFound, Reply Serial=>6, Destination=>:1.4962, Sender=>:1.4902, Signature=>s } { Group not found: User is not a member in group: <GROUP_NAME> (<GROUP_ID>) }
	[DBusConnection [listener=false]] DEBUG o.f.d.c.impl.DBusConnection - Handling incoming error: Error(0,72) { Error Name=>org.asamk.Signal.Error.GroupNotFound, Reply Serial=>6, Destination=>:1.4962, Sender=>:1.4902, Signature=>s } { Group not found: User is not a member in group: <GROUP_NAME> (<GROUP_ID>) }
	[main] DEBUG o.f.d.c.impl.DBusConnection - Disconnecting Abstract Connection
	[main] DEBUG o.f.d.connections.ReceivingService - Shutting down executor: MethodCallExecutor
	[main] DEBUG o.f.d.connections.ReceivingService - Shutting down executor: SignalExecutor
	[main] DEBUG o.f.d.connections.ReceivingService - Shutting down executor: ErrorExecutor
	[main] DEBUG o.f.d.connections.ReceivingService - Shutting down executor: MethodReturnExecutor
	[main] DEBUG o.f.d.c.impl.DBusConnection - Notifying 0 method call(s) to stop waiting for replies
	[main] DEBUG o.f.d.c.impl.DBusConnection - Shutting down SenderService
	[main] DEBUG o.f.d.t.j.NativeUnixSocketTransport - Disconnecting Transport
	[main] DEBUG o.f.d.s.m.OutputStreamMessageWriter - Closing Message Writer
	Group not found: Group not found: User is not a member in group: <GROUP_NAME> (<GROUP_ID>)
	org.asamk.Signal$Error$GroupNotFound: Group not found: Group not found: User is not a member in group: <GROUP_NAME> (<GROUP_ID>)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at org.freedesktop.dbus.errors.Error.getException(Error.java:111)
		at org.freedesktop.dbus.errors.Error.throwException(Error.java:138)
		at org.freedesktop.dbus.RemoteInvocationHandler.executeRemoteMethod(RemoteInvocationHandler.java:146)
		at org.freedesktop.dbus.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:206)
		at jdk.proxy2/jdk.proxy2.$Proxy6.quitGroup(Unknown Source)
		at org.asamk.signal.dbus.DbusManagerImpl.quitGroup(DbusManagerImpl.java:222)
		at org.asamk.signal.commands.QuitGroupCommand.handleCommand(QuitGroupCommand.java:55)
		at org.asamk.signal.App.handleLocalCommand(App.java:303)
		at org.asamk.signal.App.initDbusClient(App.java:412)
		at org.asamk.signal.App.init(App.java:149)
		at org.asamk.signal.Main.main(Main.java:60)

</details>

I have tried this again now, but without running a `daemon`:

	❯ signal-cli quitGroup -g '<GROUP_ID>' --delete
	INFO  QuitGroupCommand - User is not a group member

and it has worked - the group is no longer listed in `listGroups`.
So this issue seems to be *specifically about the daemon mode / dbus interface*.


> There's no deleteGroup command, there's just a deleteGroup method in the DBus interface.

I guess you're referring to the methods in the [source code](https://github.com/AsamK/signal-cli/blob/3206639778ed265ef42e72c6e89d4ccd43d486b5/src/main/java/org/asamk/signal/dbus/DbusSignalImpl.java#L1208). I first thought this is "a dbus method of the signal-cli dbus service", but it is not in the [methods listing](https://github.com/AsamK/signal-cli/issues/1186#issuecomment-1435920074) or the [dbus manual](https://github.com/AsamK/signal-cli/blob/3206639778ed265ef42e72c6e89d4ccd43d486b5/man/signal-cli-dbus.5.adoc).

There is a [`quitGroup` method](https://github.com/AsamK/signal-cli/blob/3206639778ed265ef42e72c6e89d4ccd43d486b5/man/signal-cli-dbus.5.adoc#L482) for the group's dbus object, but it does not have an equivalent of the CLI `--delete` option. Perhaps that's the cause of the current issue?

> As far as I know there's no way to delete old groups in the official clients, just group threads can be deleted. 

Yes, just to confirm, I've checked what the "Delete" option does in the official clients: it removes the group/contact from the contacts list, and deletes the conversation history. It does not quit the group, and the conversation can be restarted by clicking on the "New message" button, and then on the "deleted" chat. 

In my first message, I should have said: "after deleting a group in an official client, should signal-cli print a sync message reporting that?". Currently, signal-cli does not print any messages when the group is deleted on a linked device. But maybe signal-desktop does not send any, I don't know..

> It may be possible to synchronize group deletion with the signal storage, but signal-cli doesn't support writing to that yet (https://github.com/AsamK/signal-cli/issues/604)

👍 Looks like that will enable quite a few features!
