### ISSUE TITLE
contacts store and sync

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#12]
Hello,

i have noticed commit https://github.com/AsamK/signal-cli/commit/32beb8a0bd51d2bd13b9687168ed08cad3b8eca1 but could not figure out how to use it.

could you update the readme to cover contact handling?

**Comment by AsamK** [comment]
the contact handling is very rudimentary at the moment. When pairing signal-cli with another Signal instance, e.g. on a phone, signal-cli requests the contacts list from the other device and stores them in its config file. Also when it receives a contacts request it sends the list to paired devices.
That's all contact handling currently does, contacts are not shown anywhere yet, to see them you have to open the config file.
Showing contact names alongside the phone numbers is on my TODO list.

**Comment by Trolldemorted** [comment]
my problem is that i do not own a smartphone, and the Signal Chrome App cannot yet add contacts.

i suppose i could add new contacts manually to the config into the ```contactStore``` section? if yes, could please you provide a sample contact? i dont care about showing contacts, but being unable to create any is quite annoying :)

also, my two chrome apps are not always running (and rarely at the same time) and are having trouble to synchronize conversations. could i start signal-cli periodically on a server to give them the ability to sync with signal-cli, and thus with each other?

**Comment by AsamK** [comment]
Yes, you can manually add contacts to the config file. The trickier part is to actually send the contacts to the other devices. The chrome app only requests the contacts when pairing the first time. To send contacts later, you need to add a call to sendContacts() in the source code, e.g. at the end of the load() method. I'll probably add a command line option for that in the future.
Sample contacts:
```json
  "contactStore" : {
    "contacts" : [ {
      "name" : "Some Name",
      "number" : "+4XXXXXXXX"
    }, {
      "name" : "Some Other Name",
      "number" : "+5XXXXXXXX"
    } ]
  }
```

The chrome apps don't synchronize conversations among themselves. Instead the sender of a message explicitly sends the message to both devices. Having both apps running at the same time is not necessary, so running signal-cli doesn't help in that case. If messages are missing in one app it must be some other bug.

**Comment by Trolldemorted** [comment]
adding sendContacts to the end of load() works like a charm, thanks for your quick help!

are the receiving clients merging their contacts, or does sendContacts override the "remote" contact list? if i remove contacts from the config, do they get removed from the other clients' lists too?

**Comment by AsamK** [comment]
I don't know how the Desktopp clients behave, you'd have to look at their source code.  signal-cli merges the contacts when it receives a new list, and doesn't remove contacts.

**Comment by Trolldemorted** [comment]
thanks for your patience and support!

you might want to add the contact workaround to the readme, as others are likely to encounter the same problem.
im assuming "adding users to group" is already on your todo-list? otherwise i'd like to propose it, since the desktop app cant do it either.

**Comment by shenanig** [comment]
great that one can use signal-cli and signal-desktop together without a smartphone. I am doing it on a Linux machine, where signal-cli is now the master and installed system-wide as described [here](https://github.com/AsamK/signal-cli#install-system-wide-on-linux).  If I want to follow your advice of 

> adding sendContacts to the end of load()

in which configuration file should I actually do it? I can't figure out...

**Comment by Trolldemorted** [comment]
No one said config files, you have to edit the source code.

**Comment by RachelHendy** [comment]
Honestly, even just merely a command line option to force-send contacts would be of great, enormous help

**Comment by dfroger** [comment]
I've installed `signal-cli` like this: https://github.com/AsamK/signal-cli#install-system-wide-on-linux

Do I need to rebuild it from source (https://github.com/AsamK/signal-cli#building), or can I [patch](https://reverseengineering.stackexchange.com/a/8925) a `.jar` file?

Thanks

**Comment by dfroger** [comment]
So I'm trying to pach the source code instead, ie the [load](https://github.com/AsamK/signal-cli/blob/cf972e5b6c6ae51aeb8a3d4cad95d9da75b42968/src/main/java/org/asamk/signal/storage/SignalAccount.java#L64) method. How do I can a reference to the [Manager](https://github.com/AsamK/signal-cli/blob/78474453d7de5fa50c32c460e18877485bc26f78/src/main/java/org/asamk/signal/manager/Manager.java#L71), so I can call its [sendContacts](https://github.com/AsamK/signal-cli/blob/78474453d7de5fa50c32c460e18877485bc26f78/src/main/java/org/asamk/signal/manager/Manager.java#L1335) method?

It would be nice to post the diff here.

**Comment by dfroger** [comment]
Ok, this seems to be just that (I was looking in the `load` implementation instead of where it is called:

```
diff --git a/src/main/java/org/asamk/signal/manager/Manager.java b/src/main/java/org/asamk/signal/manager/Manager.java
index 575dde6..d66aeee 100644
--- a/src/main/java/org/asamk/signal/manager/Manager.java
+++ b/src/main/java/org/asamk/signal/manager/Manager.java
@@ -126,6 +126,7 @@ public class Manager implements Signal {
             return;
         }
         account = SignalAccount.load(dataPath, username);
+        sendContacts();
 
         migrateLegacyConfigs();
```
