### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by solariz** [AsamK/signal-cli#120]
Hi,

is there a way to send emojis in the message? Collon encoded doesnt work also the normal encoding seems not to work.

Thanks !

**Comment by AsamK** [comment]
signal-cli supports all unicode characters, also including emojis. Support for collon encoded emojis is not implemented. To send emojis from the command line, your terminal must also support unicode characters.
This works on Linux with a utf-8 locale, to send a snowman:
`signal-cli -u +USER send +RECEIVER -m "⛄️"`
