### ISSUE TITLE
Migration to libsignal-client

### ISSUE THREAD

**Issue by lbialy** [AsamK/signal-cli#1200]
Hi, just a quick question: is there a plan to migrate away from [libsignal-service-java](https://github.com/WhisperSystems/libsignal-service-java)? It's been archived a year ago and the current, maintained - albeit not supported for out-of-signal-clients use - solution is [libsignal](https://github.com/signalapp/libsignal).

**Comment by AsamK** [comment]
Duplicate of #1181
