### ISSUE TITLE
Alphanumeric pins

### ISSUE THREAD

**Issue by slithernix** [AsamK/signal-cli#1204]
Appears to be unsupported.

**Comment by AsamK** [comment]
please provide more information of what you're trying to achieve.

**Comment by slithernix** [comment]
Sorry for being so short I was in kind of a rush, this is a placeholder I was going to try to create a PR for you- Signal supports alphanumeric PINs now. Obviously, alphanumeric PINs are much more secure than strictly numeric PINs. I'll try to scope out this area of code later in the week and see what I can come up with, though I haven't written a lick of Java in nearly 20 years.

**Comment by AsamK** [comment]
It's possible to set alphanumeric pins with the `setPin` command.
