### ISSUE TITLE
Accepting group invitations through the DBus interface

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#1208]
Is there a DBus command for accepting an invitation to join a group?

The CLI interface has [`updateGroup`](https://github.com/AsamK/signal-cli/blob/15630356e18f59e8f4d29a5c9f215003ad07402e/man/signal-cli.1.adoc#updateGroup) with

> If the user is a pending member, this command will accept the group invitation

But there does not seem to be a dbus equivalent. (DBus interface has a [`joinGroup`](https://github.com/AsamK/signal-cli/blob/15630356e18f59e8f4d29a5c9f215003ad07402e/man/signal-cli-dbus.5.adoc#user-content-group-related-methods) command, but it is a different functionality: joining a group by URI).

**Comment by exquo** [comment]
Related: https://github.com/AsamK/signal-cli/issues/1184 (accepting new *individual* contacts).

**Comment by AsamK** [comment]
Accepting a group invitation should work by adding yourself to the group, using the `addMembers` method on the Group object: https://github.com/AsamK/signal-cli/blob/15630356e18f59e8f4d29a5c9f215003ad07402e/man/signal-cli-dbus.5.adoc#signalgroup-interface

**Comment by exquo** [comment]
It worked, thanks!

However, this usage seems to be non-obvious. It would probably be helpful to have this pointer in the docs.

Might even be useful to have an additional "convenience" method like `acceptGroupInvite` (as basically an alias for the same command above).
