### ISSUE TITLE
java.io.IOException: unexpected end of stream on Connection

### ISSUE THREAD

**Issue by plomlompom** [AsamK/signal-cli#121]
Receiving messages has suddenly stopped working, as below (I have hidden my phone number under `+XXXXXXXXX`):
```
$ signal-cli -u '+XXXXXXXXX' receive
Error loading state file "/home/plom/.config/signal/data/+XXXXXXXXX": java.io.IOException: unexpected end of stream on Connection{textsecure-service.whispersystems.org:443, proxy=DIRECT hostAddress=textsecure-service.whispersystems.org/52.20.12.194:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
```
Maybe a problem not with signal-cli but the whispersystems server? I get this result with the latest stable release as well as with a build from the most recent source code.

**Comment by jpbarraca** [comment]
I'm also getting that issue.

**Comment by Trolldemorted** [comment]
The signal servers are down

**Comment by plomlompom** [comment]
Servers up again, everything is now working fine, so it was not much of a signal-cli issue.
