### ISSUE TITLE
After update: Sending to some groups failing

### ISSUE THREAD

**Issue by DL6ER** [AsamK/signal-cli#1231]
After updating from an older version of `signal-cli` to the most recent release, I cannot use `signal-cli` to send messages to *certain* groups which has worked for years. One out of six existing groups fails.

I was able to reproduce this with an altogether newly created group:
```
$ ~/signal-cli-0.11.7/bin/signal-cli --config ~/.local/share/signal-cli -u +49123456840 updateGroup -n "ABC234" -m +495678912301 --admin +495678912301

Created new group: "A...E="
1682160515038
```

---

### Used numbers

The number `+49123456840` is the registered account used by `signal-cli`. The other number `+495678912301` is my mobile phone.

Sending directly via
```
~/signal-cli-0.11.8/bin/signal-cli --config ~/.local/share/signal-cli -u +49123456840 send +495678912301 --message-from-stdin <<< "Test"
1682161530952
```
works absolutely fine as does sending messages to the other five groups this account is member of.

---

### Failure to send to the newly created group

```
$ ~/signal-cli-0.11.8/bin/signal-cli --config ~/.local/share/signal-cli -u +49123456840 send "A.....E=" --message-from-stdin <<< "Test"

Failed to send (some) messages:
+4912345686+: Unregistered user "+4912345686+"
1682160672407
Failed to send message
```

This strange number `+4912345686+` with the plus at the end is obviously not member of the group we created just above:

```
$ ~/signal-cli-0.11.8/bin/signal-cli --config ~/.local/share/signal-cli -u +49123456840 listGroups -d -g A...E=

Id: A...E= Name: ABC123 Description:  Active: true Blocked: false Members: [+49123456840, +495678912301] Pending members: [] Requesting members: [] Admins: [+49123456840, +495678912301] Banned: [] Message expiration: disabled Link: -
```

**HOWEVER** it is basically identical to the actual account number (only the last two digits are different: `40` vs. `6+`).

### Unable to test with older version

Unfortunately, I cannot test with older versions because of
```
$ ~/signal-cli-0.11.3/bin/signal-cli --config ~/.local/share/signal-cli -u +49123456840 send "A...E=" --message-from-stdin <<< "Test"
Error loading state file for user +49123456840: Config file was created by a more recent version: 6 (IOException)
```

---

### Possible relation to other issue

The error described here is somewhat similar to #1223  `+3187654321: Unregistered user "+3187654321"`, however, I see it also for at least one group that has certainly worked for years. The fact that we see some number mangling here might hint towards a config file format issue? (entirely guessing though)

**Comment by DL6ER** [comment]
I made a copy of my `~/.local/share/signal-cli` directory and reverted the update steps manually to be able to use older `signal-cli` versions. I do get the same error down to 0.11.2 (before doesn't work because of StatusCode 499).

Interestingly enough, the mentioned number `Unregistered user "+4912345686+"` is ***not*** found in the configuration:
```
grep "+4912345686+" -aR ~/.local/share/signal-cli_downgraded
```
whereas there are results for all the legit numbers (like my phone's `+495678912301`) in `account.db`.

**Comment by DL6ER** [comment]
I tried creating a new group on my phone in the Signal App, getting the new group ID via `receive` and then sending to this new group: It is affected by the same issue so the defect is not related to groups created using `signal-cli` but only with sending *from* `signal-cli`. I created four groups for testing, all show the same issue.

**Comment by AsamK** [comment]
Can you provide a verbose log of the not working group send and the working normal send? That might shed some light into what's going on here.

`signal-cli --scrub-log -vv`

**Comment by DL6ER** [comment]
Thanks for mentioning the `-vv` option, it made me realize that there was more of a difference between my two groups that I was thinking. Cutting a long story short: it boils down to having included `-g....` for all the "old" group ID variables and having forgotten about this in the newly created groups. In this case, `signal-cli` tried to somehow decode the group ID itself into a phone number and this failed. This became obvious with `-vv`

Case closed, thanks for the very valued hint!
