### ISSUE TITLE
A connection to https://chat.signal.org/ was leaked

### ISSUE THREAD

**Issue by AntipatternCorp** [AsamK/signal-cli#1236]
Hi! No one knows why such a warning sometimes comes out?

`WARNING:WARN  OkHttpClient - A connection to https://chat.signal.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);`

**Comment by AsamK** [comment]
It means a response body wasn't closed correctly by libsignal-service. 
You can run signal-cli in verbose mode, with `-vvv`, to get a stack trace with more information, where the error occurs.
