### ISSUE TITLE
`getUserStatus` now fails

### ISSUE THREAD

**Issue by chetbox** [AsamK/signal-cli#1239]
Calling `getUserStatus` over JSON RPC fails since a few hours ago. I am using `signal-cli` version 0.11.6.

```
Error: Unable to check if users are registered: [404] Not found (NotFoundException)
    at JSONRPCClient.<anonymous> (./node_modules/json-rpc-2.0/dist/client.js:115:66)
    at step (./node_modules/json-rpc-2.0/dist/client.js:33:23)
    at Object.next (./node_modules/json-rpc-2.0/dist/client.js:14:53)
    at fulfilled (./node_modules/json-rpc-2.0/dist/client.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by AsamK** [comment]
You probably need to update signal-cli to the latest version

**Comment by chetbox** [comment]
> With `signal-cli` 0.11.9.1 I now get `Unable to check if users are registered: StatusCode: 4008 (CdsiResourceExhaustedException)`

@AsamK Any ideas? I have a regular job that manages Signal groups that is now failing :(

**Comment by chetbox** [comment]
On further investigation _sometimes_ I can use `getUserStatus` successfully with hundreds of numbers but sometimes I can't even query 5 numbers. When it fails, the error I see is always:

```
Error: Unable to check if users are registered: StatusCode: 4008 (CdsiResourceExhaustedException)
```

My hunch is there's some new rate limiting on the server side?

I tried running `getUserStatus` multiple times for each number but I end up with the same error or a much more obvious rate limit error:

```
Error: Unable to check if users are registered: java.net.ProtocolException: Expected HTTP 101 response but was '429 Too Many Requests' (IOException)
```
