### ISSUE TITLE
deserialization / LegacyRecipientStore2 error

### ISSUE THREAD

**Issue by meejah** [AsamK/signal-cli#1248]
Trying to use v0.11.10 results in a stacktrace ending with:

```
Error loading state file for [REDACTED]: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.asamk.signal.manager.storage.recipients.LegacyRecipientStore2$Storage` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (FileInputStream); line: 2, column: 3] (RuntimeException)
```

I then tried to use the latest v0.10.x build to see if that would work, but it complains that "Database has been updated by a newer signal-cli version"

Thanks for any help

**Comment by AsamK** [comment]
Are you using the graalvm native build? If so you could try to run the normal java version once to do the migration.

**Comment by meejah** [comment]
I used the download without "native" in it, if that's what you mean?

Could "skipping" versions trigger this issue...?

**Comment by AsamK** [comment]
I've pushed a commit that should fix the issue.
You can try the development version from here: https://github.com/AsamK/signal-cli/actions/runs/4996592184

I try to keep the ability to migrate from older versions. But with time regressions can occur in the migration code.

**Comment by meejah** [comment]
Thanks!

I've tried all three artifacts there and see this now (different class it seems):

```
Cannot construct instance of `org.asamk.signal.manager.storage.groups.LegacyGroupStore$Storage$GroupV2` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.asamk.signal.manager.storage.groups.LegacyGroupStore$Storage["groups"]) (IllegalArgumentException)
```

I do have recent backups and could try on that too if you think that could be an issue (e.g. if the past few runs may have messed with some of the data).

**Comment by AsamK** [comment]
There were some more places with the same issue, please try again: https://github.com/AsamK/signal-cli/actions/runs/5012507533

**Comment by meejah** [comment]
Sorry for the delay in testing this, and thanks for your efforts here!

This version works (I tested the "native" one first). If you want more information or testing, happy to provide that.
