### ISSUE TITLE
Change storage directory name to avoid conflicts

### ISSUE THREAD

**Issue by 2-4601** [AsamK/signal-cli#125]
In my `~/.config/` directory I have a
* `Signal` directory for _Signal Desktop_
* `signal` directory for _signal-cli_

Not an issue with ext4fs but maybe it's an issue on some file system? (Haven't used a Mac for a while but last time I used it the default file system was case insensitive.)

**Comment by five-c-d** [comment]
~/.config/Signal 
~/.config/Signal\ Beta
~/.config/sig-cli

Would be my preference.  Lowercase and abbreviated avoids inadvertently suggesting any Signal(TM) official-ness of this client. And if I've installed multiple copies of sig-cli, under the same Linux username, then it would be ideal to have them versioned and individualized:  

~/.config/sig-cli-v0.6.0-xxxx
~/.config/sig-cli-v0.6.0-yyyy
~/.config/sig-cli-v0.5.6-zzzz

I don't have a good suggestion for how to automagically specify xxxx, yyyy, and zzzz  ;-)   I could always just install one copy of sig-cli-v0.6.0 executable, and specify which data-folder I wanted it to use when launched, if I wanted to minimize the diskspace used by the various side-by-side versions.
