### ISSUE TITLE
Docs/examples for using TextStyles with dbus, jsonRpc, plaintext CLI

### ISSUE THREAD

**Issue by mweser** [AsamK/signal-cli#1250]
Hello, I'm curious if there is any documentation around how to make use of TextStyles (I've looked, but maybe I'm missing something). And if not, an example of how to use styles would be much appreciated. 

Thanks!

**Comment by AsamK** [comment]
TextStyles are not implemented yet for sending.

**Comment by mweser** [comment]
@AsamK Thanks! As always, I appreciate your work.
