### ISSUE TITLE
Trust request fails with JSON-RPC

### ISSUE THREAD

**Issue by mc2contributor** [AsamK/signal-cli#1260]
I'm getting an error when trying to trust a number:

Request:
```
{"method":"trust","params":{"number":"+5512345678901"},"jsonrpc":"2.0","id":1686069747}
```

Response:
```
{"code":-1,"message":"Invalid phone number 'null': Null String passed as number.","data":null}
```

Either a bug, or unclear requirements for the use of the "trust" method.

**Comment by AsamK** [comment]
The param is called `recipient` not `number`

> usage: signal-cli trust [-h] [-a | -v VERIFIED_SAFETY_NUMBER] recipient
positional arguments:
  recipient              Specify the phone number, for which to set the trust.
