### ISSUE TITLE
Error when polling for new messages

### ISSUE THREAD

**Issue by ced-b** [AsamK/signal-cli#1261]
Since version 0.11.9, when I call `receive` on the http API, I get the following response:

```
JsonRpcError(code=-32600, message=Cannot construct instance of `org.asamk.signal.commands.ReceiveCommand$ReceiveParams` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; byte offset: #UNKNOWN], data=null)
```

It seems like this `ReceiveParams` class is not set up for serialization.

@AsamK Maybe you already have an idea what this is all about? Otherwise I can dig in send you a merge request.

**Comment by AsamK** [comment]
Indeed, only an issue with the native build, the ReceiParams class is missing from the graalvm reflect config.
You could run the jvm signal-cli version with the graalvm native image agent to update the config and create a PR if you want, see https://github.com/AsamK/signal-cli/issues/848#issuecomment-1001138141
