### ISSUE TITLE
User is not registered

### ISSUE THREAD

**Issue by schonex** [AsamK/signal-cli#1262]
Trying to use an old main/root account that i have configured from a couple years back and no matter what I do it says `User is not registered`.  Problem is, I have a few linked accounts to this main account that i've been using for years, daily, and they all work.  I message daily many times a day and it all works and is registered.

**Comment by AsamK** [comment]
Maybe your account data is still stored in one of the old locations? see https://github.com/AsamK/signal-cli/blob/master/CHANGELOG.md#090---2021-09-12
