### ISSUE TITLE
Trouble calling dbus-send via Cron

### ISSUE THREAD

**Issue by teatower** [AsamK/signal-cli#1265]
I have added a trouble shooting advice on the dbus-wiki-pages after having trouble calling dbus-send via Cron.
As wiki pages have no pull-request mechanism, I kindly ask you to please review it that I have used the correct terms for what I am describing. I hope, it is of some help.
Me myself got the solution [from another website](https://coldfix.de/2018/10/09/dbus-cronjob/). Is it possible to give [credits to Thomas](https://coldfix.de/about/)?
Thank you.
teatower

**Comment by AsamK** [comment]
Thanks, sure, just add a link there.
