### ISSUE TITLE
How to change my account phone number?

### ISSUE THREAD

**Issue by jackfoks** [AsamK/signal-cli#1269]
I have registered an account in the signal to a virtual number. There is no access to the number at the moment. Is there any way to change the phone number?

**Comment by bublath** [comment]
I'm not aware of any way to change the number, but you can have multiple numbers at the same time. Simply register with a new number and use that one with the "-a" parameter going forward. The old one will remain and you can access it with the appropriate -a parameter at any time.

**Comment by AsamK** [comment]
It's not implemented in signal-cli yet, see #1240
