### ISSUE TITLE
Proper use of jsonrpc via C#?

### ISSUE THREAD

**Issue by Mathero11** [AsamK/signal-cli#1278]
Hello,
Yes im a noob with this, i've been trying to get it working for the past 5 hours.
I have configured the signal-cli on docker, port 7583, just like the manual says.
When using the docker exec command (I use actual phone numbers):
`echo '{"jsonrpc":"2.0","method":"send","params":{"recipient":["+31xxxxxx"],"message":"MESSAGE","account":["+31xxxxxx"]},"id":500}' | signal-cli jsonRpc`
It works, message gets send.
When I use C# , using a TcpClient on the ip and port (using exact json string as the example above, I checked it) I get this error:
`{"jsonrpc":"2.0","error":{"code":-32602,"message":"Specified account does not exist","data":null},"id":5}`
And when removing the account param I get:
`{"jsonrpc":"2.0","error":{"code":-32602,"message":"Method requires valid account parameter","data":null},"id":5}`

So am I doing something that isn't possible, or is it something else?

**Comment by AsamK** [comment]
The account field is just a string, not an array.
