### ISSUE TITLE
Updating beyond revision 02d4cb4a1 introduces limit to size of messages sent to users

### ISSUE THREAD

**Issue by mweser** [AsamK/signal-cli#1280]
I recently updated my codebase to make use of 409a707ba . However, users were not receiving messages beyond a particular length. 

Upon reverting to 02d4cb4a1, the issue was no longer present. 

Last good commit:
02d4cb4a1 2023-07-14 | Update libsignal-service-java [AsamK]

I'm guessing it has something to do with the versions beyond library("signalservice", "com.github.turasa", "signal-service-java").version("2.15.3_unofficial_74"), although I could be wrong.

**Comment by AsamK** [comment]
Should be fixed now on master with another libsignal-service-java update.
