### ISSUE TITLE
Prevent sending sticker together with message 

### ISSUE THREAD

**Issue by muffl0n** [AsamK/signal-cli#1290]
I ran into https://github.com/signalapp/Signal-Android/issues/11883 while sending a sticker together with a message.

Given that the sticker sent together with a message won't be displayed (at least on Android, don't know about iOS), messages and stickers should be mutually exclusive.

Edit: let a friend check on iOS. There, the sticker sent together with a message is displayed, the message is suppressed. Also the sticker can be deleted and the app does not crash.
Nevertheless, sending stickers together with a message makes no sense and should be prevented, imho.

**Comment by AsamK** [comment]
This issue is already mentioned in the man page: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#send
I don't want to prevent that, as the protocol allows it.
