### ISSUE TITLE
Contact sync issue

### ISSUE THREAD

**Issue by alexlab2017** [AsamK/signal-cli#1293]
**First of all thanks for this great client! This is really useful.**

### System data

- Ubuntu Server version `22.04.2 LTS`
- `open-jdk` version `19.0.2 2023-01-17`
- `signal-cli` version `0.11.11`

### Description

I registered a phone number with `signal-cli` as master device and I use Signal Desktop official client on another computer (Windows).

I've set up the DBUS deamon and then another service to automatically react, reply, send new messages based on a custom python function to be executed `onMessageReceived`, everything works smoothly with no issue at all.

I set contact names with `signal-cli --dbus-system updateContact <phone_number> --given-name John --family-name Doe` and tried also shutting down DBUS deamon and using `signal-cli updateContact <phone_number> --given-name John --family-name Doe`.

In both cases the command succeeded and then I used `sendContacts` but the contact names never show up on the Desktop app that instead insists in showing only profile names. What is weird is that if I search for a name in the desktop app it shows the correct number so the name is somehow registered but not shown.

If I use command `listContacts` I see the right names, as I set them.

I opened `~/.local/share/signal-cli/data/864867.d/account.db` and saw that there is an empty `username` column in the `recipient` table so I tried to set that value before sending the contacts, that did not work.

No clue on if I am doing something wrong or where to look at in order to debug this problem. Any suggestion or help to point me in the right direction will be much appreciated.

**Comment by AsamK** [comment]
The username column is for the new username feature and will currently always be empty.
Is there an option in signal-desktop to prefer profile names?

**Comment by alexlab2017** [comment]
Understood on the username column.

I re-checked all the GUI settings of the desktop app and I see no option for preferring profile names.

Per what I see in my application on Android and on Linux (my personal number, not the one I use with signal-cli) the standard behavior is to show the contact name instead of the profile name when there is one saved.

**Comment by AsamK** [comment]
I checked and signal-cli is sending the contact name in the contact sync message.
Maybe Signal-Desktop now ignores that and only uses the contact name from the server storage, which signal-cli doesn't support yet (#604)

**Comment by alexlab2017** [comment]
Thanks for looking into it. I can keep an eye on this because I use `signal-cli` and Signal Desktop constantly every day, if the behavior changes I'll update this issue. Anyway if you decide to close it it will be fine for me.

**Comment by alexlab2017** [comment]
Just to let you know: for some reason now contacts are correctly synced. I did not do anything different, just noticed it today but might have happened also some time ago. I am using `signal-cli` version `0.13.1` and Signal Desktop is `7.4.0` (Windows).
