### ISSUE TITLE
Native libsignal-client added but still getting an error

### ISSUE THREAD

**Issue by rhk** [AsamK/signal-cli#1295]
Running on RasPi3. 
Linux tammi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1deb11u1, mixed mode, sharing)

Old version of signal-cli worked fine (I think it was 0.9.something) but I accidentially deleted it (autch..) and can't set up v0.12.0. I also tried 0.11.11 a couple of days ago, but hoped at least 12 would solve. But no, so decided to raise an issue. 

```
rhk@hostname:~/signal $ wget https://github.com/AsamK/signal-cli/releases/download/v0.12.0/signal-cli-0.12.0-Linux.tar.gz
<----clip---->
rhk@hostname:~/signal $ tar zxf signal-cli-0.12.0-Linux.tar.gz
rhk@hostname:~/signal $ cd signal-cli-0.12.0/lib/
rhk@hostname:~/signal/signal-cli-0.12.0/lib $ curl -Lo libsignal_jni.so "https://gitlab.com/packaging/libsignal-client/-/jobs/artifacts/${version}/raw/libsignal-client/${architecture}/libsignal_jni.so?job=libsignal-client-${architecture}"
<----clip---->
rhk@hostname:~/signal/signal-cli-0.12.0/lib $ zip -d libsignal-client-0.30.0.jar libsignal_jni.so
deleting: libsignal_jni.so
rhk@hostname:~/signal/signal-cli-0.12.0/lib $  zip libsignal-client-0.30.0.jar libsignal_jni.so
  adding: libsignal_jni.so (deflated 86%)
rhk@hostname:~/signal/signal-cli-0.12.0/lib $ unzip -l libsignal-client-0.30.0.jar|grep libsignal_jni
 11234368  2023-07-20 21:46   libsignal_jni.dylib
    57127  2023-08-11 10:37   libsignal_jni.so
rhk@hostname:~/signal/signal-cli-0.12.0/lib $ cd ../bin


rhk@hostname:~/signal/signal-cli-0.12.0/bin $ ./signal-cli -vvvv -a +358xxxxxxxx send +358YYYYYYY -m "Test"
2023-08-11T10:39:01.341+0300 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.0
2023-08-11T10:39:01.489+0300 [main] WARN  org.asamk.signal.manager.Manager - Failed to call libsignal-client: /tmp/13566032161534269510libsignal_jni.so: /tmp/13566032161534269510libsignal_jni.so: virheellinen ELF-otsikko
Missing required native library dependency: libsignal-client
rhk@hostname:~/signal/signal-cli-0.12.0/bin $
```

Is it me doing something wrong? I think this is how I added the library to old version too and it worked.

**Comment by AsamK** [comment]
You need to replace the libsignal so file in the lib jar file, see https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

**Comment by rhk** [comment]
Yes, that I have understood and as per my understanding that's exactly what I did there.

**Comment by AsamK** [comment]
Right, please check the content of the libsignal so file, 57kb seems way too small for it.

**Comment by rhk** [comment]
Awesome, that was it, works now!

I got a working library from here: https://github.com/exquo/signal-libs-build/ (for RasPi using the aarch64-linux-gnu, download/release page here: https://github.com/exquo/signal-libs-build/releases

This one doesn't seem to provide libraries any more?
https://gitlab.com/packaging/libsignal-client/
