### ISSUE TITLE
sendMessage - exit code for rate limit

### ISSUE THREAD

**Issue by matuskosut** [AsamK/signal-cli#1301]
Hi,

I was wondering if it would be possible to add specific exit code for rate limit failure?
I think it would be useful since one needs to handle this error in specific way, so if automating some steps it would be easier to catch it.

https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#exit-codes

**Comment by AsamK** [comment]
Sounds like a good idea.

**Comment by sparrowme** [comment]
@AsamK does this rate limit exit code apply ONLY to the sending account or will all accounts be affected that the cli handles when in multi-account mode?   I'm trying to plan appropriate sending throughput from a single cli client managing multiple accounts as to not abuse the signal system or cause a cascade of failures..
