### ISSUE TITLE
Incomplete DBus interface??

### ISSUE THREAD

**Issue by mh-g** [AsamK/signal-cli#1312]
Using signal-cli 0.12.0 and libsignal-client 0.31.0 on a Raspberry Pi4 64bit and openjdk 17.0.7 2023-04-18 via system-dbus I get the following error:
```
dbus-send --system --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:MessageText array:string: string:+49xxx
Error org.freedesktop.dbus.errors.UnknownMethod: The method `org.asamk.Signal.sendMessage' does not exist on this object.

```

Indeed,
`dbus-send --system --type=method_call --print-reply --dest=org.asamk.Signal /org/asamk/Signal org.freedesktop.DBus.Introspectable.Introspect
`
does not list sendMessage as a function. (Neither send, sendGroupMessage nor onMessageReceived.)

The same functions are missing when using pydbus to query the signal instance:

```
>>> from pydbus import SystemBus
>>> bus = SystemBus()
>>> signal=bus.get('org.asamk.Signal')
>>> signal
<DBUS.<CompositeObject>(org.asamk.SignalControl+org.freedesktop.DBus.Introspectable+org.freedesktop.DBus.Peer) object at 0x7fa0c414f0>
>>> dir(signal)
['GetMachineId', 'Introspect', 'Ping', '_Introspect', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_bus', '_bus_name', '_object', '_path', 'finishLink', 'getAccount', 'link', 'listAccounts', 'register', 'registerWithCaptcha', 'startLink', 'verify', 'verifyWithPin', 'version']

```

Installation was as per https://github.com/AsamK/signal-cli/wiki/DBus-service#system-bus

**Comment by AsamK** [comment]
If you start the signal-cli service without an account number you need to use the dbus account object with dbus-send:

>     dbus-send --session --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal/_33123456789 org.asamk.Signal.sendMessage string:MessageText array:string: string:RECIPIENT

**Comment by mh-g** [comment]
Thanks, that solved the issue.
