### ISSUE TITLE
JSON no longer matches wiki

### ISSUE THREAD

**Issue by selfbc** [AsamK/signal-cli#1313]
I'm not sure if this is intentional or just another mistake in this codebase, but the JSON has changed in 0.12.0 to no longer conform to the wiki.

Where it was:
<code>
{"jsonrpc":"2.0","method":"receive","params":{"envelope":{"source":"+33123456789","sourceNumber":"+33123456789","sourceUuid":"uuid","sourceName":"name","sourceDevice":1,"timestamp":1631458508784,"dataMessage":{"timestamp":1631458508784,"message":"foobar","expiresInSeconds":0,"viewOnce":false,"mentions":[],"attachments":[],"contacts":[]}}}}
</code>

it is now
<code>
{"jsonrpc":"2.0","method":"receive","params":{"subscription":0,"result":{"envelope":{"source":"+33123456789","sourceNumber":"+33123456789","sourceUuid":"uuid","sourceName":"name","sourceDevice":1,"timestamp":1631458508784,"dataMessage":{"timestamp":1631458508784,"message":"foobar","expiresInSeconds":0,"viewOnce":false"mentions":[],"attachments":[],"contacts":[]}}}}
</code>

**Comment by AsamK** [comment]
Thanks, not intentional. Only the format for explicit receive subscriptions should have changed.
