### ISSUE TITLE
Notifications delivered quietly when sent to groups

### ISSUE THREAD

**Issue by chris-fj** [AsamK/signal-cli#1317]
Hello,

Thanks for the awesome work!

I have found that notifications are delivered quietly to iOS when sent to a group. Quietly as in "doesn't trigger the counter", "doesn't show up until I open the application" which makes me miss some important events on my automation setup. Things that I have tested:

- Added to the notifications group an android and they receive the messages sent to the group (notifications work as expected on the Android)
- Sent direct message from Android to iPhone (notifications work as expected on the iPhone)
- Sent message in the notifications group from Android (notifications work as expected on the iPhone)

Only thing that doesn't work is sending the message from the API to the group, which notifies the Android but not the iPhone. Tried reinstalling, updating iOS, etc... and the problem still stays. This may be a long shot but if you know how to help me, that would be great.

I have tested with [apprise](https://github.com/caronc/apprise) which uses [signal-cli-rest-api](https://github.com/bbernhard/signal-cli-rest-api) behind the scenes, which uses this repo behind the scenes (isn't software dependency great?) and I have experienced the problem above. I have also tried with this command (from this repo)

```bash
curl -X POST -H "Content-Type: application/json" 'http://ip:port/v2/send' \                                                                     
           -d '{"message": "Test via Signal API!", "number": "+xxx", "recipients": [ "group.xxx=" ]}'
```

and have also experienced this. 

iOS notifications are OK as in not muted from neither iOS settings nor Signal settings, as I have received notifications from other accounts (the Android) and the Android notifies when the server sends a message. Is there any "silent" mode underlying that is only interpreted by the iOS client? 

Any help to trace this problem is appreciated

system info
I'm using bbernhard/signal-cli-rest-api:0.67 which in turn uses signal-cli 0.11.11, the device not being notified is an iPhone 12 Pro running iOS 16.6 and Signal client 6.39.0.11 (up to date as of writing)

**Comment by kingfisher77** [comment]
We experience the same by using [signal-cli-rest-api](https://github.com/bbernhard/signal-cli-rest-api). Sending a message to a number creates a notification on macOS and Android client. Sending to a group just silently delivers the message.

Number - Notification fired
curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' -d '{"message": "Test via Signal API!", "number": "+499999999999", "recipients": [ "+49888888888" ]}'

Group- Notification not fired:
curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' -d '{"message": "Test via Signal API", "number": "+499999999999", "recipients": [ "group.RkFCT0M5dGRuUWllaE5Vc2YLNnRZWkxrQVZqQlRSdTk4VVpiSkJOeHNLYz0=" ]}'

Settings in the group are as usual. Not muted.

**Comment by matthiasdg** [comment]
Are you sure this is about Android vs iOS? I would expect that the iOS device's number is used to send the signal-cli messages, which means sync messages for other clients with that number are sent as well, hence you get no notifications there. (If you'd use the Android's number for sending with signal-cli, you'd pbly get notifications on the iOS, but not on the Android). Issues that may be related: https://github.com/bbernhard/signal-cli-rest-api/issues/472, https://github.com/AsamK/signal-cli/issues/1087

**Comment by matthiasdg** [comment]
In signal-cli-rest-api, this is fixed for me now, so could be that it's no longer an issue here as well.

**Comment by jdve** [comment]
I think this was fixed in https://github.com/Turasa/libsignal-service-java/commit/dd0c4d61740af7592d4712041333a01c566ea74d which is part of [v2.15.3_unofficial_106](https://github.com/Turasa/libsignal-service-java/releases/tag/v2.15.3_unofficial_106), and signal-cli was [recently updated](https://github.com/AsamK/signal-cli/commit/19dc2d446b753460c5e89ec3ea23fa3fae5b89c6) to `2.15.3_unofficial_108` which I think also includes this fix.
