### ISSUE TITLE
Signal desktop not showing quotes of audio messages (mobile works fine)

### ISSUE THREAD

**Issue by incognico** [AsamK/signal-cli#1318]
Small issue I have encountered, with signal-cli I am replying to voice messages (quoting them) using `--quote-timestamp` and `--quote-author`. I omit `--quote-message` because there is no message text in a incoming voice msg. For some reason it displays fine on mobile, both Android and iOS, but on Signal Desktop for Windows, it shows as lone message without the quoted message on top. Generally Signal Desktop can show it, if I quote a voice message on my phone it shows fine on desktop. Not sure what is missing to make that work.

**Comment by AsamK** [comment]
I think this is a bug in Signal-Desktop, if it knows the quoted message it could also show the quote bubble.
In the next version you can use the `--quote-attachment audio/aac` parameter and it will also show audio quotes in Signal-Desktop.
