### ISSUE TITLE
Linking Device in JSON-RPC Mode

### ISSUE THREAD

**Issue by filipre** [AsamK/signal-cli#1319]
Hi, 

I'd be very interested in being able to [link a device in JSON-RPC](https://github.com/AsamK/signal-cli/discussions/679#discussioncomment-1308612) mode as it would extend the [signal-cli-rest-api](https://github.com/bbernhard/signal-cli-rest-api/issues/354#issuecomment-1701696977) project and simplify the setup of my projects by quite a bit.

I was wondering what it would take to implement this and if you could provide some hints on how to achieve this? I might want to try it out to implement it myself but I have no idea how to start. Is there a specific reason or problem why this function does not exist in the json-rpc mode? I'd love to hear any pointers :)

Best!

**Comment by AsamK** [comment]
The `jsonRpc` command currently only supports single account mode, so method like registering and linking aren't available. However the `daemon` command also supports JSON-RPC (with `--socket`/`--http`/`--tcp`) and also supports multi account mode with registering/linking.
So the functionality is there already just not in the `jsonRpc` command, but that should be easy to extend.

**Comment by AsamK** [comment]
I've extended the `jsonRpc` command you can now run signal-cli with `signal-cli jsonRpc` to use register/link commands.
I've also updated the documentation: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli-jsonrpc.5.adoc

**Comment by filipre** [comment]
Wow! That's awesome. Thank you very much!
