### ISSUE TITLE
CLI can't decrypt messages sent from primary device

### ISSUE THREAD

**Issue by Riamse** [AsamK/signal-cli#132]
signal-cli is linked to my phone. If I run `signal-cli daemon -u +my-number` and then try to send a message from my phone, signal-cli prints the following envelope that represents the message I just sent:

```
Envelope from: “” +my-number (device: 1)
Timestamp: 1527155810733 (2018-05-24T09:56:50.733Z)
Exception: No valid sessions. (InvalidMessageException)
Failed to decrypt message.
```

(I'm not sure if this is just me or if this is an actual issue.)

**Comment by Trolldemorted** [comment]
This happens when the session breaks. Did you leave your signal-cli offline for a longer time?

**Comment by Riamse** [comment]
I guess? I only ever start running signal-cli when I'm at my computer. I tried sending `-e`, and resetting the secure session from my phone, but it still doesn't work.

**Comment by Trolldemorted** [comment]
If you reset the session, do you see the session reset message in signal-cli receive's output?
