### ISSUE TITLE
Send attachments fails with "No recipients given" error

### ISSUE THREAD

**Issue by therealjuanmartinez** [AsamK/signal-cli#1320]
It would seem that when using the "-a" for attachments, for sending - the CLI interface does not recognize the recipient number

```
./signal-cli -u +15555555555 send -m "Your message text"  +15555555555   #THIS WORKS

./signal-cli -u +15555555555 send -m "Your message text" -a "${DATA_URI}" +15555555555  #FAILS
No recipients given

./signal-cli -u +15555555555 send -m "Your message text" -a /home/ubuntu/file.m4a +15555555555  #FAILS
No recipients given
```

Unless this isn't the correct format, which the Wiki seems to support, I think it's a simple bug where not all the CLI parameters are getting consumed

**Comment by AsamK** [comment]
You need to put the number in front of the -a flag, otherwise it gets interpreted as a second attachment file.
That's a somewhat unusual behavior of the cli argument parsing library I'm using.

**Comment by therealjuanmartinez** [comment]
Cheers
