### ISSUE TITLE
Attachment sending currently broken: Content uploaded <value> bytes compared to expected!

### ISSUE THREAD

**Issue by wdormann** [AsamK/signal-cli#1321]
Current signal-cli attachment sending is broken due to an expected size mismatch.
signal-cli 0.12.1 works just fine.

<img width="1473" alt="Screenshot 2023-09-05 at 4 42 49 PM" src="https://github.com/AsamK/signal-cli/assets/14325582/30ca08de-550f-4927-b361-d6ad686ad91d">

**Comment by m-ueberall** [comment]
@wdormann: (a) Are you using the master branch, since release 0.12.1 you refer to is already the newest one? (b) The above screenshot shows that you're using libsignal 0.32.0--did you retry this with libsignal 0.30.0 that has originally been packaged with release 0.12.1?

**Comment by wdormann** [comment]
Yeah, I'm on the master branch, retrieved via "git clone"
And yes, I had tried libsignal 0.30.0 as well with the master branch to no avail.
<img width="1483" alt="Screenshot 2023-09-05 at 4 41 02 PM" src="https://github.com/AsamK/signal-cli/assets/14325582/69afc351-ec83-4865-b282-e7075dc34709">

**Comment by wdormann** [comment]
Reverting to the 0.12.1 release version, as opposed to the master branch, works fine.
<img width="1480" alt="Screenshot 2023-09-06 at 8 07 45 AM" src="https://github.com/AsamK/signal-cli/assets/14325582/d7982c92-f474-4206-aa1f-7f01c9e586ce">

**Comment by AsamK** [comment]
This should work again in the latest master.
