### ISSUE TITLE
Specify the emoji, should be a single unicode grapheme cluster.

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1325]
I see this sentence in the manuals: 

> Specify the emoji, should be a single unicode grapheme cluster.

I am not sure what this means and I also don't know where to get those.
Can someone explain?

thanks!

**Comment by Tsjippy** [comment]
this does not work:
`signal-cli sendReaction -e "🦘" -a PHONENUMBER -t SOME TIMESTAMP PHONENUMBER `

I get an timestamp back, but the emoji never shows up

**Comment by Tsjippy** [comment]
> > this does not work:
> > `signal-cli sendReaction -e "🦘" -a PHONENUMBER -t SOME TIMESTAMP PHONENUMBER`
> > I get an timestamp back, but the emoji never shows up
> 
> @Tsjippy: Did you just delete your above comment because you got it working in the meantime? I managed to send a snowman (see [this comment](https://github.com/AsamK/signal-cli/issues/120#issuecomment-369727005)) using the current version of `signal-cli` from a Linux terminal.

Yes, I found out the LANG variable was not set on my server:(

But sending a reaction via dbus does not work: `sendMessageReaction string:🦘 boolean:false string:$recipient int64:$timestamp string:$recipient"`

**Comment by m-ueberall** [comment]
> But sending a reaction via dbus does not work: `sendMessageReaction string:🦘 boolean:false string:$recipient int64:$timestamp string:$recipient"`

Using the above function on the command line results in `signal-cli:  error:  invalid  choice:  'sendMessageReaction'`; using the following, the group gets to see a (small) kangaroo, though (it's indented, so I guess this represents a reaction?):
`signal-cli --dbus-system sendReaction -e 🦘 -a +49[…] -t 1695029972540 --group […]=`

```

**Comment by AsamK** [comment]
A grapheme cluster is a user-perceived character, it's part of the unicode standard: https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries

For signal it's just an emoji, that can consists of one or multiple unicode code points.

When sending a reaction via dbus-send, the command would look like this:
```
dbus-send --type=method_call --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessageReaction string:🦘 boolean:false string:+49[…] int64:1696956744492 array:string:+49[…]
```
