### ISSUE TITLE
For the last 3 days execution of "signal-cli.bat jsonRpc" interrupted with exception

### ISSUE THREAD

**Issue by owbeg** [AsamK/signal-cli#1329]
Hi,
for the last 3 days execution of "signal-cli.bat jsonRpc" is always interrupted with exception:
Exception in thread "receive-0" java.lang.NullPointerException: Cannot invoke "org.asamk.signal.manager.storage.messageCache.CachedMessage.loadEnvelope()" because "cachedMessage[0]" is null

After startup signal-cli.bat is executed for several minutes (and received some set of messages) but then terminated with specified exception. Log file with debug messages is attached

Thanks,
Oleg 
[debug_0923_03.zip](https://github.com/AsamK/signal-cli/files/12706030/debug_0923_03.zip)

**Comment by AsamK** [comment]
This log line is interesting:
`2023-09-23T11:58:04.219+0300 [receive-0] WARN  o.a.s.m.s.messageCache.MessageCache - Failed to store encrypted message in disk cache, ignoring: C:\Users\Oleg\.local\share\signal-cli\data\352007.d\msg-cache\66\1695459484219_1695335412789 (Access is denied)`

Does that file or its parent folder (`66`) exist? If yes you could try to delete it and retry.

**Comment by owbeg** [comment]
There is no folder 66 under msg-cache, but I monitored contents of the msg-cache folder and saw that folder 66 was created and then deleted again

**Comment by owbeg** [comment]
I executed signal-cli.bat today several times and for the last run (when it extracted all historic messages for the previous days) it executed without any errors for several hours...

**Comment by AsamK** [comment]
Behavior should be improved in the latest version
