### ISSUE TITLE
DBus - getGroupIds() not published

### ISSUE THREAD

**Issue by KRtekTM** [AsamK/signal-cli#133]
Hello everybody,

I'm trying to read groups ids for my Signal bot (in C# mono framework) but the method getGroupIds which should be in DBus interface is not published.
I'm inspecting my system bus via qdbusviewer and the method is not present in the list of published methods.
Is it known issue? Can I solve somehow?

Big thanks!

**Comment by AsamK** [comment]
the getGroupIds function is only available in the master branch, it was merged after the 0.6 release.
