### ISSUE TITLE
update signal-cli  v0.11.11 to v0.12.2

### ISSUE THREAD

**Issue by xyz-nobody** [AsamK/signal-cli#1331]
I have just updated my signal-cli and now I have this error

Missing required native library dependency: libsignal-client
WARN  Manager - Failed to call libsignal-client: /tmp/9280884456586879776libsignal_jni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/9280884456586879776libsignal_jni.so)

any idea ? I use debian 11

**Comment by AsamK** [comment]
You either need to update your OS or use a different libsignal_jni.so build, see https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal
