### ISSUE TITLE
After editing a message, the received status is not returned by signal-cli to the sender

### ISSUE THREAD

**Issue by hondogitsune** [AsamK/signal-cli#1332]
![grafik](https://github.com/signalapp/libsignal/assets/75497157/6bf1eaf8-364e-428f-8955-ca2d206d7594)
![grafik](https://github.com/signalapp/libsignal/assets/75497157/c3926b05-1e03-407e-b9b4-b5f75bb895d1)

As you can see regular messages have the 2 received by backend and destination circles. However an edited message will only display it was received by the Signal backend, and not the destination. The signal-cli logs indicate though the edited message is hitting the destination and thus was in-fact received.

**Solution:** Return the received status even for edited messages, as per protocol spec.

Can this discrepancy be patched in a future update please? I could think of various reasons where it would be useful to edit a command even when talking to just a bot running signal-cli than having to retype and send all.

Cheers!

**Edit:**
signal-cli 0.12.2
libsignal 0.32.1
signal-desktop 6.32.0
were used in these screens

**Comment by hondogitsune** [comment]
![grafik](https://github.com/AsamK/signal-cli/assets/75497157/20f40510-f578-4ba7-be02-8c166508f374)

![grafik](https://github.com/AsamK/signal-cli/assets/75497157/799e2d83-bdeb-4efd-8df5-20589cd4647d)

![grafik](https://github.com/AsamK/signal-cli/assets/75497157/60bd83f8-6cfa-412b-8d32-5143ca6f8c03)

Furthermore this affects dbus too, as the edited message is only received by signal-cli but also not forwarded to services listening on the IPC. Sorry for the bump, I just wanted to make sure the extend of this issue goes beyond notification circles.

**Comment by AsamK** [comment]
The received status is fixed in the latest master.
The dbus part is a separate issue.

**Comment by hondogitsune** [comment]
Thank you for your work! I will monitor the changelogs silently until then, knowing you track dbus internally as it is a complex separate issue that requires time.
