### ISSUE TITLE
libsignal-client seems to be missing or otherwise misconfigured in macOS binary release 0.12.2

### ISSUE THREAD

**Issue by nicholastulach** [AsamK/signal-cli#1334]
When i download and run the `bin/signal-cli` (v0.12.2), i get the following error message:

```
WARN  Manager - Failed to call libsignal-client: /private/var/folders/nq/07kx68910gg29rs93vb0_3vh0000gn/T/6694404714135683097libsignal_jni.dylib: dlopen(/private/var/folders/nq/07kx68910gg29rs93vb0_3vh0000gn/T/6694404714135683097libsignal_jni.dylib, 0x0001): tried: '/private/var/folders/nq/07kx68910gg29rs93vb0_3vh0000gn/T/6694404714135683097libsignal_jni.dylib' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/nq/07kx68910gg29rs93vb0_3vh0000gn/T/6694404714135683097libsignal_jni.dylib' (no such file), '/private/var/folders/nq/07kx68910gg29rs93vb0_3vh0000gn/T/6694404714135683097libsignal_jni.dylib' (not a mach-o file)
Missing required native library dependency: libsignal-client
```

When i run with the v0.12.1 release, it works as intended. Seems like something is wrong with the latest build on macOS. 

Note: I am running macOS Sonoma 14.0 on an M1 MacBook Pro 13".

**Comment by AsamK** [comment]
Indeed the artifact url seems to have changed, I'll fixs that for the next version.
For now you can use the Linux version, that actually also contains the lib for macOS and windows: https://github.com/AsamK/signal-cli/releases/download/v0.12.2/signal-cli-0.12.2-Linux.tar.gz
