### ISSUE TITLE
Feature Request - Browse / Peek Messages

### ISSUE THREAD

**Issue by synman** [AsamK/signal-cli#1336]
I have a use case that currently requires me to run multiple signal-cli instances (using up my 4 devices) supporting a 3D Printer / CNC use case managing multiple machines.

https://youtu.be/UjMrgx2to1s

Once a message is received from a signal-cli instance, it is removed from the message "stack" and if multiple clients are connected, only one of them receives the message.   

It would be really cool if we had a browse / peek receive derivative to go along with receive.  This would enable clients in a many to one scenario to selectively choose which messages are meant for them (using criteria such as group ids / etc) and only remove them from the receive "stack" when that criteria is met.

This would (ideally) be implemented preserving backwards compatibility by introduction of a new "browse / peek" command.

**Comment by AsamK** [comment]
This is not something I'm planning to implement.
You could maybe write a custom wrapper that stores messages or use linked devices (`link`/`addDevice`). Every linked device has a separate message queue on the server with all messages. Though there's a server limit of three or four linked devices.
