### ISSUE TITLE
Verify error(code 400)

### ISSUE THREAD

**Issue by cloudengineer89** [AsamK/signal-cli#1339]
Hi everyone,

I'm trying to register a new device on Ubuntu 22.04 with a captcha.  After I received a verification code on my phone and executed the command: `signal-cli -a $PHONE_NR verify 123456` I got an error in the terminal: `Verify error: StatusCode: 400`
btw I'm working with 0.12.2 cli version

I was hoping you could help me to figure out where the problem is.

**Comment by AsamK** [comment]
A verbose log with `-v` might provide more information.

**Comment by cloudengineer89** [comment]
> A verbose log with `-v` might provide more information.

thx, after getting additional information and research the problem was solved
