### ISSUE TITLE
Feature request - Method to return security code

### ISSUE THREAD

**Issue by KRtekTM** [AsamK/signal-cli#134]
Hello everybody,

Is it possible to get security code between signal-cli and another user (preferred is dbus)?

I'm creating a signal bot which will have a web interface so I want to show the security code to the logged user.

Big thanks for any suggestions.

**Comment by AsamK** [comment]
The security code can be seen with the `listIdentities` command.
However that shows the security codes for all known users and doesn't work over dbus yet.

**Comment by AsamK** [comment]
issue for listIdentities over dbus: #195
