### ISSUE TITLE
Messages doesn't sends via dbus service

### ISSUE THREAD

**Issue by cloudengineer89** [AsamK/signal-cli#1340]
It seams I configured all good with dbus service.
Here is my `systemctl status dbus`:
```
dbus.service - D-Bus System Message Bus
     Loaded: loaded (/lib/systemd/system/dbus.service; static)
     Active: active (running) since Mon 2023-10-09 06:02:55 UTC; 1h 38min ago
TriggeredBy: ● dbus.socket
       Docs: man:dbus-daemon(1)
   Main PID: 360 (dbus-daemon)
      Tasks: 1 (limit: 1091)
     Memory: 1.8M
        CPU: 69ms
     CGroup: /system.slice/dbus.service
             └─360 @dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
```
I use this comment to send a test message: 
`dbus-send --system --type=method_call  --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:'test message' array:string: string:'+380112223344'`

After executing the command nothing happened.

Please help me figure out where the problem is.
Many thanks!

**Comment by AsamK** [comment]
Please have a look a the wiki how to run signal-cli on the dbus system bus: https://github.com/AsamK/signal-cli/wiki/DBus-service#system-bus
Your dbus-send command is correct if the signal-cli daemon is running on the dbus system bus.
