### ISSUE TITLE
Receiving self-sent messages?

### ISSUE THREAD

**Issue by frnsys** [AsamK/signal-cli#135]
Is there a way to retrieve the contents of messages sent to self? 

When using:

```
signal-cli -u ${SIGNALNUM} receive --json
```

messages sent to myself only output something like:

```
{"envelope":{"source":"<MY NUMBER>","sourceDevice":1,"relay":null,"timestamp":1528490958862,"isReceipt":false,"dataMessage":null,"syncMessage":{"sentMessage":null,"blockedNumbers":null,"readMessages":[{"sender":"<MY NUMBER>","timestamp":1528490422858}]},"callMessage":null}}
```

That is, there's no `message` key containing the message body.

**Comment by Trolldemorted** [comment]
Which client do you use to send these messages?

**Comment by frnsys** [comment]
They're sent with the Signal Android app.

**Comment by Trolldemorted** [comment]
Vanilla Signal-Android does not send selfmessages to slave devices. https://github.com/signalapp/Signal-Android/issues/7631

**Comment by frnsys** [comment]
Ah ok, thank you for clarifying.
