### ISSUE TITLE
JDK 21 switch

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#1365]
openjdk 21 just was released and is not integrated in widely used distributions.
I'm representing a 100+ user base that uses signal-cli on Raspberry Pi for home automation. People typically don't upgrade quickly ("never touch a running system"). Majority of my users are on "bullseye" - a significant number still on "buster".
Bullseye just added openjdk 17 not that long ago - version 21 is not in sight and "bookworm" is still beta for Raspberry.

Can't we at least keep Java 17 compatiblity?
I fear many users will have to stay on signal-cli 0.12.4 for the time being as they will rather not update signal-cli than having to update their system (or find a third party Java - and many just know "apt" as a way to install something). This may result in additional support issues/effort.

What is the motivation to go for Java 21 so quickly?

**Comment by orazioedoardo** [comment]
Yeah switching to Java 21 will leave behind a lot of users, unless they use a container. While Bookworm is released for Raspberry Pi, `openjdk-21-jre-headless` is only in Debian testing and Ubuntu 23.04 (so no LTS). Older signal-cli versions will likely continue to work for a while but upcoming usernames and phone number hiding could break it.

**Comment by piechologist** [comment]
There's no JDK 21 for RHEL in EPEL 8 and 9 yet. 

How about future signal-cli GraalVM Native Binaries built with Java 21? Will they run on all those platforms?

**Comment by AsamK** [comment]
Java 21 provides new language features, that allow writing code safer and shorter.
Java 21 is a LTS release and already included in some distributions like Arch and Debian testing.
On older Debian versions it can already be installed from Debian testing. Otherwise there are various ways to install it like [SDKMAN](https://sdkman.io/install) or directly from another openjdk distribution like [Azul](https://docs.azul.com/core/zulu-openjdk/install/debian) or [Corretto](https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/generic-linux-install.html).

The GraalVM Native Binaries don't need a java runtime environment, so they will run on any system with a recent enough glibc library.

**Comment by m-ueberall** [comment]
> How about future signal-cli GraalVM Native Binaries built with Java 21? Will they run on all those platforms?

**For the record:** Regardless whether you use GraalVM CE v17.0.8+7-jvmci-22.3-b22 (JDK17) or v21.0.1+12-jvmci-23.1-b19 (JDK21) on an Ubuntu 20.04 host to compile the current `signal-cli` release 0.12.4, the respective `objdump` outputs show that the resulting native binaries by themselves only require glibc 2.17; it's a call to `statx` in the embedded `libsignal_jni.so` library that "raises the bar" to glibc 2.28 which (AFAIK) should be fine for RHEL+EPEL8/9.

**Comment by int2018** [comment]
Hi,
for average/semi-nerd users it is really hard to compile signal-cli on/for raspberry. and the "old" java 17 version makes it impossible to catch up with the latest updates/features. Is there any chance to make the process simple/r? 
Which version can be compiled on (or for) paspberry 4 with bullseye? signal-cli-0.13.1 seems too far ahead...
Is there a source for pre-built binaries for raspberry?
Thanks

**Comment by morph027** [comment]
> Hi, for average/semi-nerd users it is really hard to compile signal-cli on/for raspberry. and the "old" java 17 version makes it impossible to catch up with the latest updates/features. Is there any chance to make the process simple/r? Which version can be compiled on (or for) paspberry 4 with bullseye? signal-cli-0.13.1 seems too far ahead... Is there a source for pre-built binaries for raspberry? Thanks

There are packages available at https://gitlab.com/packaging/signal-cli/, at least for arm64, which should match Pi 4.

If you like, you can also dig into the build scripts. They are using docker w/ qemu for cross compilation.

**Comment by bublath** [comment]
There are binary distributions for most platforms, so you can install Java 21. The only platform I found missing was armv7l - if you need that, I made an effort to create a version that can be found here: https://github.com/bublath/FHEM-Signalbot/tree/main/java
You could even use my installation script at https://github.com/bublath/FHEM-Signalbot/blob/main/signal_install.sh
The script installs a few things you might not need, but that also won't hurt and afterwards, you should have signal-cli 0.13 running on your Raspberry as a service.
