### ISSUE TITLE
The --text-style parameter does not suggest mixed formatting (e.g., part of the phrase BOLD and the other part of the phrase ITALIC)?

### ISSUE THREAD

**Issue by spezialist1** [AsamK/signal-cli#1366]
Dear support,
As far as I understand after reading the manuals and practical testing, the command line _--text-style_ parameter does not suggest mixed formatting (e.g., part of the phrase BOLD and the other part of the phrase ITALIC: "_Test_ **message**")?
Did I get that right or not?
Very thanks for the support.

**Comment by m-ueberall** [comment]
@spezialist1: This _is_ supported (just use multiple `start:length:style` triples to test this yourself, e.g. `signal-cli […] --message ABCDEFGHIJKLMNOPQRSTUVWXYZ --text-style 2:2:BOLD 8:3:ITALIC 12:4:STRIKETHROUGH`). FYI: The [signal-cli-rest-api](https://github.com/bbernhard/signal-cli-rest-api) downstream project adds a wrapper which supports Markdown like syntax, see [here](https://github.com/bbernhard/signal-cli-rest-api/issues/382#issuecomment-1712003007).

**Comment by spezialist1** [comment]
Dear @m-ueberall,
I realized, the reason is the incorrect manual https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc, which implies that formatting should be enclosed in double quotes:
> e.g.: -m "Something BIG!" --text-style "10:3:BOLD"
This of course works fine, but when trying to mixed formatting we get an error, for example:
> signal-cli […] --message ABCDEFGHIJKLMNOPQRSTUVWXYZ --text-style "0:5:BOLD 7:4:ITALIC"
> Invalid style: BOLD 7:4:ITALIC
But if the formatting is not enclosed in double quotes, then indeed mixed formatting works fine, just like in your example.
Very thanks for the support.

**Comment by AsamK** [comment]
The quotes are just shell syntax, each formatting part needs to be passed as a separate argument, so this would also work: `--text-style "0:5:BOLD" "7:4:ITALIC"`
