### ISSUE TITLE
The current machine does not support all of the following CPU features

### ISSUE THREAD

**Issue by jpr105** [AsamK/signal-cli#1370]
Hello,

I'm trying to install Signal without a smartphone on an old laptop (Aspire-5750G) configured under Linux Mint 21.2 Cinnamon.

I updated JRE and ran the command `./signal-cli -u +33xxxxxxxxx register`.

Then I got this message: 
```
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.
```

Is this complicated to solve? 
My Linux knowledge is OK but not expert

Thanks a lot for your great job 🙏
Regards - Jean-Paul

**Comment by AsamK** [comment]
You're trying to run the graalvm native build, which requires a more recent CPU, see also this thread: #1363
The normal java version (non native) should work.
