### ISSUE TITLE
If the --text-style parameter with mixed formatting is followed by the recipient number (not the group), the error: No recipients given

### ISSUE THREAD

**Issue by spezialist1** [AsamK/signal-cli#1372]
Dear support,

Today discovered probably a bug when sending a message to a recipient (not a group). If the _--text-style_ parameter with mixed formatting is followed by the recipient number (not the group), the error: **No recipients given**. For example:

`$ signal-cli -a +xxxxxxxxxxxx send -m Test_message --text-style "0:3:BOLD" "5:3:ITALIC" +yyyyyyyyyyyy`
`$ No recipients given`

However, if you do not apply mixed formatting to the _--text-style_ parameter (`$ signal-cli -a +xxxxxxxxxxxx send -m Test_message --text-style "0:3:BOLD" +yyyyyyyyyyyy`), the above example works fine. Also, the above example with mixed formatting for _--text-style_ works fine when sending a message to a group (_-g_ parameter).

So far I have been able to resolve the above error by re-sorting the parameters on the command line so that the recipient number is not after the _--text-style_ parameter. This way, for example, the command with mixed formatting works fine:

`$ signal-cli -a +xxxxxxxxxxxx send +yyyyyyyyyyyy -m Test_message --text-style "0:3:BOLD" "5:3:ITALIC"`

Very thanks for the support.

**Comment by AsamK** [comment]
That's how argument parsing is handled by argparse4j, which signal-cli uses. You can either reorder the arguments or use `--` to separate the recipient number.
`$ signal-cli -a +xxxxxxxxxxxx send -m Test_message --text-style "0:3:BOLD" "5:3:ITALIC" -- +yyyyyyyyyyyy`
