### ISSUE TITLE
this is a heads-up for usernames in signal, be prepared.

### ISSUE THREAD

**Issue by zylzyz** [AsamK/signal-cli#1378]
this is a heads-up for usernames in signal, be prepared.

usernames are coming to the signal protocol. well this is just that developers and users should be prepared for this when this happens. so, transition would be easy and quick for users. i don't expect quick rollout, maybe early 2024 might be a target.

[https://community.signalusers.org/t/usernames-in-signal/9157/1](https://community.signalusers.org/t/usernames-in-signal/9157/1)
[https://community.signalusers.org/t/public-username-testing-staging-environment/56866](https://community.signalusers.org/t/public-username-testing-staging-environment/56866)

**Comment by AsamK** [comment]
signal-cli has preliminary undocumented support for usernames, that can be tested on the staging environment.
Use `updateAccount --username USERNAME` to set a username and `send u:USERNAME.XX` to send a message to a username, but that could still change in a future release.
There's also support for not sharing the phone number, but that's not exposed yet and would require to manually modify the database.
