### ISSUE TITLE
DBus receive always outputs messages as plaintext, even with --json

### ISSUE THREAD

**Issue by joh6nn** [AsamK/signal-cli#138]
It looks like it should be a pretty simple fix: just need to add `if (!ns.getBoolean("json"))` at [Main.java:427](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/Main.java#L427) and [Main.java:445](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/Main.java#L445), and then output the JSON in the `else`. Sadly, my Java is super weak and none of my patches compile, or this would be a PR instead of an Issue.

**Comment by KRtekTM** [comment]
Issue #127?

**Comment by joh6nn** [comment]
Opposite problem: `signal-cli --dbus receive --json` does not output JSON. This is true in both release 0.6.0 and if I build from current master. Having built from master, I can get  `signal-cli daemon --json` to output JSON, but `signal-cli --dbus receive --json` still only outputs as plain text. (So, as an aside, it seems that #127 is resolved.)

I tried to outline where I think the issue is above, but apologies if it wasn't clear. Also I'm no good with Java so I could just be wrong. That said, it looks like [Main.Java:422-463](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/Main.java#L422-L463) are responsible for handling `--dbus receive`, but there's no check for the `receive` command's `--json` option, and you can see that it always writes plain text. The `--json` option is only checked for and handled down on [Main.java:479](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/Main.java#L479), which only executes if `--dbus` was not passed.

I hope that's more clear?

**Comment by KRtekTM** [comment]
I see. I think that's by design.

When you want to use methods from signal.service dbus interface, you should create your own dbus client and then, you'll have access to dbus action OnMessageReceived which has all properties you want (as in json). You can handle it by your own method directly inside your application.
If you're calling signal-cli --dbus for each operation on signal.cli, it has influence on machine's performace as you're starting new java instance for each call.

**Comment by joh6nn** [comment]
I don't believe it's by design; the current man page gives no indication that `--json` is not valid in combination with `--dbus`. If it is by design, then the man page needs to be updated to reflect this.

Also, the `receive` command causes signal-cli to stay running and wait for new messages from dbus, so there is no issue with starting a new JVM for each call :)
