### ISSUE TITLE
Address all nulls in contact JSON.

### ISSUE THREAD

**Issue by rkjnsn** [AsamK/signal-cli#1385]
Using signal-cli 0.12.4 as a linked device, when receiving a contact with `-o json receive`, all of the fields are properly populated in the output except for the address, which is all nulls:

```
"address":[{"type":"HOME","label":null,"street":null,"pobox":null,"neighborhood":null,"city":null,"region":null,"postcode":null,"country":null}]
```

This occurs whether the contact is part of a received message or a synced sent message.

**Comment by AsamK** [comment]
Thanks for reporting, this just wasn't implemented correctly.
