### ISSUE TITLE
AddDevice fails with some QR codes (URI's with % encoded symbols)

### ISSUE THREAD

**Issue by meldavis** [AsamK/signal-cli#139]
I am using Code Two QR Code Desktop Reader to scan the QR code from Signal Desktop. Then I use the "tsdevice://..." to add the device. 

Whenever the URI in the QR code contains a % symbol, the signal-cli addDevice command fails with an exception:
```
org.whispersystems.libsignal.InvalidKeyException: Bad key length: 18
        at org.whispersystems.libsignal.ecc.Curve.decodePoint(Curve.java:42)
        at org.asamk.signal.Manager.addDeviceLink(Manager.java:464)
        at org.asamk.signal.Main.handleCommands(Main.java:292)
        at org.asamk.signal.Main.main(Main.java:84)
```

I have to tell the Desktop to generate a new QR code until I get one without a percent sign.  Then it works.  

Below is an example of a failing tsdevice
```
tsdevice:/?uuid=OTnYTaeEeLn4u0jRcqMI8g&pub_key=BbA%2Bcxv%2F6RK9r2QcnolbFSkR7kKo%2B9O8za0u9vKzmVRN
```

I don't think the problem is with Code Two. But I don't know enough about QR Code and signal URIs to know for sure.

**Comment by Trolldemorted** [comment]
Which shell and operating system are you using?

**Comment by meldavis** [comment]
Windows 10.   Shell is TCMD/TCC.  I did not think to try cmd.exe.  I'll try that later today and let you know.

**Comment by meldavis** [comment]
Wow. I switched to CMD.exe and it worked.  Thanks for the help.
