### ISSUE TITLE
Signal voice calls?

### ISSUE THREAD

**Issue by Vic3198** [AsamK/signal-cli#141]
It would be cool if signal-cli handled Signal voice calls!

I'm building a home automation and security system with Raspberry Pis, and already use signal-cli for sending me alerts about it (thanks a lot for that, it's so useful and simple!), but now I have the project to build an intercom that would call me via Signal when someone rings and I'm not at home, so that I could answer to whoever is standing in front of my door. ;)

Thanks,
Vic

**Comment by AsamK** [comment]
I'll close this in favor of #80, which is also about webrtc voice calls.
