### ISSUE TITLE
Prebuilt AUR Package for signal-cli-native (signal-cli-native-bin)

### ISSUE THREAD

**Issue by skr4n** [AsamK/signal-cli#1416]
It is great that signal-cli provides GraalVM native builds.
While there is an AUR package "signal-cli-native", it builds the native binary from source.
An AUR package such as "signal-cli-native-bin" that pulls the binary builds provided with the repo would improve their availability and utilization.

Thank you for the useful project.
skr4n

**Comment by AsamK** [comment]
I won't provide a -bin package in AUR, but you're free to create and maintain that yourself.
The non -bin package has the advantage, that it also works on ARM systems.
