### ISSUE TITLE
signal-cli dependency on GLIBC_2.33

### ISSUE THREAD

**Issue by billatq** [AsamK/signal-cli#1423]
I recently went to upgrade to a newer signal and was greeted with the following message on Ubuntu 20.04 (built with glibc 2.31):

```
WARN  Manager - Failed to call libsignal-client: /tmp/7882414178320057348libsignal_jni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/7882414178320057348libsignal_jni.so)
Missing required native library dependency: libsignal-client
```

It looks like the issue is that this build of `libsignal_jni.so` depends upon a newer GLIBC. It looks like the library as-built here does not have this problem: https://github.com/exquo/signal-libs-build

It looks like it tries to use the glibc 2.28, since this will run on older systems: https://github.com/exquo/signal-libs-build/blob/main/generate_matrix.py

Would it be possible to build the `libsignal_jni.so` in a similar way?

**Comment by m-ueberall** [comment]
@billatq: This has been asked and answered before (see [here](https://github.com/AsamK/signal-cli/issues/1247#issuecomment-1549950218)/issue #1247) – at the time of writing, your only choice is to use third-party builds (e.g., as listed [in the wiki](https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal#pre-built)).
