### ISSUE TITLE
ERROR App - Error loading or creating state file: Incorrect file format: expected parameter axolotlStoreot found

### ISSUE THREAD

**Issue by rurkowsky** [AsamK/signal-cli#1434]
Hello I have problem when I try to register number with captcha ERROR App - Error loading or creating state file: Incorrect file format: expected parameter axolotlStore not found

**Comment by AsamK** [comment]
axolotlStore is not used anymore, which signal-cli version are you trying to run?
Also provide a verbose log with `-v` for more details.
