### ISSUE TITLE
account data location of root user on linux

### ISSUE THREAD

**Issue by 818814** [AsamK/signal-cli#1437]
Where is it please?

**Comment by AsamK** [comment]
https://github.com/AsamK/signal-cli?tab=readme-ov-file#storage

**Comment by 818814** [comment]
/signal-cli does not exists in my system and $HOME/.local/share/signal-cli/data/accounts.json contains only 2 meaningless lines.

searched entire system with catfish, I don't get it. Where is root user pulling credentials from?
