### ISSUE TITLE
0.12.7 - signal-cli version is too old for the Signal-Server, please update.

### ISSUE THREAD

**Issue by BOFH90** [AsamK/signal-cli#1439]
I´m unable to send messages using signal-cli 0.12.7 since about half an hour. 
The server tells me the following:

Error while checking account +XXXXX: signal-cli version is too old for the Signal-Server, please update.

I´m using the "bbernhard/signal-cli-rest-api" Docker-Container with 0.12.7 embedded.

**Comment by Flottegurke** [comment]
i got the same problem since the same time

**Comment by mmhere** [comment]
Yeah, I had only just yesterday upgraded to 0.12.7 (with Java 21 on Debian 12) and now this message returned.

Error while checking account NNNNNNNNN signal-cli version is too old for the Signal-Server, please update

**Comment by ced-b** [comment]
Looks like the dependencies have been updated 4 days ago. But there is no build yet:

https://github.com/AsamK/signal-cli/commit/7fb263fdf0eccd5fcd77819bc5cfe2f77e8a975b

**Comment by mmhere** [comment]
Is there a way to know ahead of time when Signal swervers will begin blocking certain client versions so that the client(s) can be updated ahead of time?

**Comment by hostmasterT** [comment]
> I created a fork that built the latest version. And it works with my preliminary tests.
> 
> So on your own risk and with no further guarateed support you can use the following binaries
> 
> https://github.com/key-lime-box/signal-cli/releases/tag/v0.12.7_patch2
> 
> or the following image:
> 
> ghcr.io/key-lime-box/signal-cli:0.12.7_patch2

Thank, for me signal-cli-0.12.8-SNAPSHOT worked, jdk-21-oracle-x64 and native lib 0.39.2 https://github.com/signalapp/libsignal/releases/

**Comment by reinob** [comment]
With the 0.12.7_patch2 version I get
```Error: LinkageError occurred while loading main class org.asamk.signal.Main
	java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0```

This is with debian bookworm/12, with the default jre/jdk (openjdk-17-jre-headless).

**Comment by eddielthomas** [comment]
Hi, I am getting this error: 
root@724399cc0e13:/usr/bin/lib# signal-cli
Error: Could not find or load main class org.asamk.signal.Main
Caused by: java.lang.ClassNotFoundException: org.asamk.signal.Main

what are the steps to install?  Do i just overwrite the signal-cli executable in /usr/bin then drop the lib folder in the /usr/bin ?

**Comment by dolomiti70** [comment]
> With the 0.12.7_patch2 version I get
> 
> ```
> Error: LinkageError occurred while loading main class org.asamk.signal.Main
> 	java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a 
> more recent version of the Java Runtime (class file version 65.0), this version of the Java
> Runtime only recognizes class file versions up to 61.0
> ```
> 
> This is with debian bookworm/12, with the default jre/jdk (openjdk-17-jre-headless).

Same here

**Comment by m-ueberall** [comment]
> ```
> Error: LinkageError occurred while loading main class org.asamk.signal.Main
> 	java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a 
> more recent version of the Java Runtime (class file version 65.0), this version of the Java
> Runtime only recognizes class file versions up to 61.0
> ```
> This is with debian bookworm/12, with the default jre/jdk (openjdk-17-jre-headless).

_This is to be expected_ as [upstream snapshots produced by the `signal-cli CLI` workflow](https://github.com/AsamK/signal-cli/actions/workflows/ci.yml) that are based on the master branch are using **JDK 21** ([cf. here](https://github.com/AsamK/signal-cli/actions/runs/7787245887/job/21233947893#step:3:15) and [here](https://github.com/AsamK/signal-cli/blob/bea659f9484a2aba47c4d8dad503f18b0aaff19b/build.gradle.kts#L16)).
The same goes for the fork mentioned above [which only differs with respect to the image registry, workflow URI](https://github.com/AsamK/signal-cli/compare/master...key-lime-box:signal-cli:master).

**Comment by mbrand1** [comment]
> With the 0.12.7_patch2 version I get
> 
> ```
> Error: LinkageError occurred while loading main class org.asamk.signal.Main
> 	java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a 
> more recent version of the Java Runtime (class file version 65.0), this version of the Java
> Runtime only recognizes class file versions up to 61.0
> ```
> 
> This is with debian bookworm/12, with the default jre/jdk (openjdk-17-jre-headless).

In my environment (debian bullseye/11), I had to manually download the openjdk-21 build (from here: https://jdk.java.net/21/), untar that into /usr/local and put the 'bin' directory into my PATH (PATH="/usr/local/jdk-21.0.2/bin:$PATH"), and then I was able to run the patched version.

`$ signal-cli --version
signal-cli 0.12.8-SNAPSHOT`

**Comment by mmhere** [comment]
> With the 0.12.7_patch2 version I get
> 
> ```
> Error: LinkageError occurred while loading main class org.asamk.signal.Main
> 	java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a 
> more recent version of the Java Runtime (class file version 65.0), this version of the Java
> Runtime only recognizes class file versions up to 61.0
> ```
> 
> This is with debian bookworm/12, with the default jre/jdk (openjdk-17-jre-headless).

I think it is stated in another issue that Java 21 is required by 0.12.7.

**Comment by mmhere** [comment]
> I created a fork that built the latest version. And it works with my preliminary tests.
> So on your own risk and with no further guarateed support you can use the following binaries
> https://github.com/key-lime-box/signal-cli/releases/tag/v0.12.7_patch2
> or the following image:
> ghcr.io/key-lime-box/signal-cli:0.12.7_patch2

Thanks!

In my environment (details above) I was able to unpack `https://github.com/key-lime-box/signal-cli/releases/download/v0.12.7_patch2/signal-cli-0.12.7_patch2.tar.gz` into `/opt/.`, do `rm -f -v /usr/local/bin/signal-cli; ln -s -v /opt/signal-cli-0.12.8-SNAPSHOT/bin/signal-cli /usr/local/bin/signal-cli`, and then continue running straight away.

When 0.12.8 is officially released, I'll do a similar couple of steps.

**Comment by msedv** [comment]
> I created a fork that built the latest version. And it works with my preliminary tests.
> 
> So on your own risk and with no further guarateed support you can use the following binaries
> 
> https://github.com/key-lime-box/signal-cli/releases/tag/v0.12.7_patch2
> 
> or the following image:
> 
> ghcr.io/key-lime-box/signal-cli:0.12.7_patch2

Great - but would it eventually also be possible to do a second build like signal-cli_ubuntu2004_amd64.gz without the "aggressive CPU optimisations"-problem (see <https://github.com/AsamK/signal-cli/issues/1363>)? :-) Tnx!

**Comment by mmhere** [comment]
> > I created a fork that built the latest version. And it works with my preliminary tests.
> > So on your own risk and with no further guarateed support you can use the following binaries
> > https://github.com/key-lime-box/signal-cli/releases/tag/v0.12.7_patch2
> > or the following image:
> > ghcr.io/key-lime-box/signal-cli:0.12.7_patch2
> 
> Great - but would it eventually also be possible to do a second build like signal-cli_ubuntu2004_amd64.gz without the "aggressive CPU optimisations"-problem (see #1363)? :-) Tnx!

I see 0.12.7_patch2 as a [functional] stopgap until there is time for 0.12.8 to be fully vetted and released officially.  Just my humble observation.

**Comment by AsamK** [comment]
I just released version 0.12.8, which just updates the user agent.

**Comment by mmhere** [comment]
> I just released version 0.12.8, which just updates the user agent.

Thanks so much for the quick response.  When you server stops signaling you, you get twitchy.  ;-)

**Comment by mmhere** [comment]
note, upon using the patch, then using official 0.12.8, this error occurs:

```
ERROR AccountDatabase - Database has been updated by a newer signal-cli version
Error loading state file for user +15032240052: java.sql.SQLException: Database has been updated by a newer signal-cli version (RuntimeException)
```

so apparently the internal versioning doesn't quite agree, with the patch posted earlier representing itself as a "newer" version than the official release.

So if you went from 0.12.7 to 0.12.8 I imagine you'd be OK, but if you used 0.12.8_patch2 after 0.12.7 then tried to go to 0.12.8, you will have problems.  At least I did.

**Comment by mmhere** [comment]
> Note, upon using the patch, then using official 0.12.8, this error occurs:
> 
> ```
> ERROR AccountDatabase - Database has been updated by a newer signal-cli version
> Error loading state file for user +15032240052: java.sql.SQLException: Database has been updated by a newer signal-cli version (RuntimeException)
> ```
> 
> Apparently the internal versioning doesn't quite agree, with the patch posted earlier representing itself as a "newer" version than the official release.
> 
> So if you went from 0.12.7 to 0.12.8 I imagine you'd be OK, but if you used 0.12.8_patch2 after 0.12.7 then tried to go to 0.12.8, you will have problems. At least I did.
> 
> I thus had to go back to the 0.12.7_patch2 version and will continue using it until some future time.

I cannot use 0.12.8 without re-registering, it seems.  any workaround for this?

I think maybe this issue should stay open for a bit.

**Comment by slithernix** [comment]
there is no git tag for v0.12.8... is that an oversight or ?

**Comment by disaster123** [comment]
Is there any fix for debian bullseye available? Due to #1363 the official version does no longer work.

**Comment by disaster123** [comment]
@msedv did you find any solution for older hosts?

**Comment by disaster123** [comment]
@m-ueberall any chance to get a new version here? https://media.projektzentrisch.de/temp/signal-cli/

**Comment by m-ueberall** [comment]
@disaster123: Yes, these are currently being tested. With a bit of luck, they should be publicly available within an hour.

**Comment by timaschew** [comment]
I've switch to the debian docker image: `registry.gitlab.com/packaging/signal-cli/signal-cli-jre` and it works fine and even easiert

**Comment by matthew-piziak** [comment]
Okay, listen, I know I'm going to sound a bit crazy here.

If I go to [this page](https://github.com/AsamK/signal-cli/releases/) in Firefox and click the link for 
`signal-cli-0.12.8-Linux-native.tar.gz`, I get a tarball called `signal-cli-0.12.7-Linux-native.tar.gz`. [sic, 0.12.7 instead of 0.12.8]

If I hit "copy link" and say `wget https://github.com/AsamK/signal-cli/releases/download/v0.12.8/signal-cli-0.12.8-Linux-native.tar.gz`, I get the correct `signal-cli-0.12.8-Linux-native.tar.gz` tarball.

Spooky, probably not relevant, but figured I'd say something.

**Comment by reinob** [comment]
The file name is provided with the URL (https://objects.githubusercontent.com/..filename%3D**signal-cli-0.12.8-Linux-native.tar.gz**), but the server sends also as response header
```
Content-Disposition: attachment; filename=signal-cli-0.12.7-Linux-native.tar.gz
```

The browser takes the latter, while wget takes the former, apparently.

**Comment by matthew-piziak** [comment]
Looks like AsamK's fixed it! https://github.com/AsamK/signal-cli/issues/1443
