### ISSUE TITLE
Register does not work

### ISSUE THREAD

**Issue by cfra** [AsamK/signal-cli#144]
1. I have downloaded `signal-cli-0.6.0.tar.gz` from the release page and unpacked it to `/opt`.
1. I have installed a JRE using `apt-get install openjdk-7-jre` (system is Debian Jessie)
1. I ran `./signal-cli -u '+49123456789' register`

Expected Result:
The `signal-cli register` call terminates. I receive a text message at the given extension to verify my phone.

Actual Result:
The `signal-cli register` call doesn't terminate and doesn't output anything. I don't receive a text message. It just seems to hang.

**Comment by Trolldemorted** [comment]
Could your system be out of entropy?

**Comment by cfra** [comment]
Yea, that was it, thank you.

I had the thought initially, but dismissed it. Thanks for bringing it up again. Once I installed and started `haveged`, the register which had been running since 30min finished instantly.

Not sure if other people ran into this problem too, maybe some small debug output would be useful.
