### ISSUE TITLE
v0.12.8 release file has incorrect name

### ISSUE THREAD

**Issue by chetbox** [AsamK/signal-cli#1443]
[Release v0.12.8](https://github.com/AsamK/signal-cli/releases/tag/v0.12.8) contains a file named [`signal-cli-0.12.7-Linux-native.tar.gz`](https://github.com/AsamK/signal-cli/releases/download/v0.12.8/signal-cli-0.12.7-Linux-native.tar.gz) but I believe it should be `signal-cli-0.12.8-Linux-native.tar.gz`.

**Comment by AsamK** [comment]
Thanks for the hint, fixed.
