### ISSUE TITLE
Manifest couldn't be decrypted

### ISSUE THREAD

**Issue by orazioedoardo** [AsamK/signal-cli#1446]
Got this error while setting up v0.12.8. I originally ignored it so I can't tell you exactly what I was doing but it was related with managing groups and members, and possibly the profile itself. I also noticed that the profile picture and image wouldn't show up to other members so I thought `sendSyncRequest` could help. It did (or I just had to wait for changes to propagate) but when running that I also got the error in the issue title.

**Comment by AsamK** [comment]
Might be fixed in the next version 0.13.0, there have been many changes for the storage code (which uses the manifest).

**Comment by MatzFan** [comment]
FYI I Just got `WARN  StorageHelper - Manifest couldn't be decrypted.` after adding a device with `signal-cli -u +xxxxxxxxxxxx addDevice --uri "sgnl://linkdevice?uuid=xxxx...`. Everything seems to work OK, I'm only reporting in case there is some action I should take after seeing this.

signal-cli 0.13.18 on Linux Mint 22.1
