### ISSUE TITLE
Setup on macOS

### ISSUE THREAD

**Issue by Lokeh** [AsamK/signal-cli#145]
Getting signal-cli and DBus setup and running signal-cli with it seems to be a real PITA. I still haven't figured it out.

Steps I've done so far (amongst many hours of troubleshooting):

- Download latest release, uncompress it into ~/Downloads

Fixing Java "unlimited security" issue:
- Edited `$JAVA_HOME/jre/lib/security/java.security` and set `crypto.policy=unlimited`

Installing libunix-java.so:
- `git clone https://github.com/abstractj/libmatthew-java`
- `cd libmatthew-java && make && make install`
- `cp libunix/target/libunix-java.so $JAVA_HOME/jre/lib/libunix-java.dylib`

Fixing "missing jni_md.md" error when trying to install the above (I don't even know):
- `cp $JAVA_HOME/include/darwin/jni_md.h $JAVA_HOME/include`

Installing dbus:
- `brew install dbus`
- `brew services start dbus`
- Restart machine

So far I have been able to link signal-cli with my phone and send/receive messages, but dbus currently is giving me fits.

Right now, simply running `./signal-cli -u <phone#> daemon` results in:

```
org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address
	at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:244)
	at org.asamk.signal.Main.handleCommands(Main.java:675)
	at org.asamk.signal.Main.main(Main.java:84)
```

Trying to use the system dbus results in:

```
./Downloads/signal-cli-0.6.0/bin/signal-cli -u <phone#> daemon --system
org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus No such file or directory
```

Trying to use `dbus-run-session` results in:

```
dbus-run-session ./Downloads/signal-cli-0.6.0/bin/signal-cli -u <phone#> daemon
dbus-daemon[2202]: Failed to start message bus: Check-in failed: No such process

dbus-run-session: EOF reading address from bus daemon
```

I'm able to run `dbus-monitor` and `dbus-test-tool` and see messages show up.

Some notes:
- dbus from homebrew seems to configure dbus to start up a session at login and save the socket to `DBUS_LAUNCHD_SESSION_BUS_SOCKET`

```
echo $DBUS_LAUNCHD_SESSION_BUS_SOCKET
/private/tmp/com.apple.launchd.32ZzPZXKnO/unix_domain_listener```

**Comment by binarious** [comment]
@Lokeh Any success? Having this issues as well.

**Comment by Lokeh** [comment]
No, after receiving no help I gave up.

**Comment by timaschew** [comment]
For me it's also not working, actually I'm getting same errors in a unix docker container.
But here is my output on a mac:
```
$ signal-cli -u +xxxx daemon
org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address
	at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:244)
	at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:50)
	at org.asamk.signal.Main.handleCommands(Main.java:126)
	at org.asamk.signal.Main.main(Main.java:61)

$ signal-cli --dbus-system daemon
Missing native library dependency for dbus service: no unix-java in java.library.path
```

I have no clue how to install the native library. I was expecting that it will work automatically if I install signal-cli via homebrew, but that didn't change anything.

**Comment by AsamK** [comment]
Latest master now doesn't require a native library for dbus anymore (#285)
