### ISSUE TITLE
ProtocolInvalidKeyIdException : while receive the message on signal-cli

### ISSUE THREAD

**Issue by Koushal-123** [AsamK/signal-cli#1450]
I'm encountering the error 'InvalidKeyIdException: No such signed pre key record' in the Signal protocol library. Could someone please provide guidance on resolving this issue?

![Screenshot from 2024-02-07 17-07-01](https://github.com/AsamK/signal-cli/assets/159256540/2efc6fbe-a57e-4f60-ba65-29d5dc4f5adc)

**Comment by AsamK** [comment]
Does it only affect older message that are being received? Then it might be an overly eager pre key cleanup, that will be fixed in 0.13.0.
This should also resolve itself after sending a message to the sender of this message.

**Comment by Koushal-123** [comment]
"Thank you for your response, @AsamK. However, I encountered an error on my server when a user sends a message to my Signal number via the chat bot I created using signal-cli. According to your suggestion, the error should resolve itself by sending a message to the sender first. However, it's impractical to manually send a message to each sender, especially if there are a large number of users (for example, if 1000 users are sending messages). Can you provide an alternative solution for resolving this issue automatically?"

**Comment by goshi** [comment]
Dear @Asamk. We have encountered the same issue with the latest version 0.12.8: after upgrading two weeks ago server from the 0.11.x to 0.12.8 all seems to be fine. But yesterday our clients reported, that the new installs of the Signal mobile applications (both iOS and Android) cannot communicate with the bot on 0.12.8 version. Also, the new client apps installs on the already trusted numbers (in the TRUSTED_UNVERIFIED status) become broken too. 
We are using dockerized version of the signal-cli application (bbernhard/signal-cli-rest-api) and we have migrated to it from the host-version with reusing the old config without any issues.
The error message, that signal-cli reports, is: 
```
{
  "exception": {
    "message": "org.signal.libsignal.protocol.InvalidKeyIdException: No such signed pre key record: 12738070",
    "type": "ProtocolInvalidKeyIdException"
  },
  "envelope": {
    "source": "73f9125a-a34f-459c-b301-89fc00528988",
    "sourceNumber": null,
    "sourceUuid": "73f9125a-a34f-459c-b301-89fc00528988",
    "sourceName": "",
    "sourceDevice": 1,
    "timestamp": 1708056683535
  }
}
```
As you can see - the signal-cli does not show source number, so we cannot verified it dynamically.
When we are trying to send direct message to the number, which has been sent this message, then we are getting the rate limit error.
With numbers which previously used the bot and not removed the application from the devices we don't see any problems and they are working fine.
The TRUST MODE for the bot-number configured as "always".

Do you have any ideas how it could be fixed now or how it could be aligned in your next updates?

**Comment by AsamK** [comment]
There was an issue with receiving messages to the PNI address, should be fixed with fd671576a4aef0e5f9ef795b1985930cf02bcb84

**Comment by marcos-morar** [comment]
Since updating Signal-CLI to version 0.13.12, I’ve been constantly encountering this error with most of my messages:

`Exception: org.signal.libsignal.protocol.InvalidKeyIdException: No such kyber pre key record: 986276 (ProtocolInvalidKeyIdException)`

**Comment by skipper-83** [comment]
Hey there!

Thanks for this awesome tool! I seem to get a similar error, running in json-rpc mode in a docker container. On SOME messages I get 

 Exception: org.signal.libsignal.protocol.InvalidKeyIdException: No such signed pre key record: 607855 (ProtocolInvalidKeyIdException)

But not all of them, I cant seem t figure out what the difference between devices causing it is (we thaught apple/android, but that isnt the case). I tried re-registering but that didnt help. Any clue what could cause this?

Kind regards,
Albert van Andel
