### ISSUE TITLE
Message delivered or read status ?

### ISSUE THREAD

**Issue by tj57** [AsamK/signal-cli#1456]
Is it possible to verify that a specific message has been delivered or read by the recipient?
If not, I would like to report such functionality

**Comment by sparrowme** [comment]
from my experience, read status is controllable by the user... if they allow read receipts, you can/will receive them otherwise you can't.

**Comment by tj57** [comment]
Yes, I know about user settings, but which command I can check the receipt status of a given message?

**Comment by AsamK** [comment]
You get receipts with the `receive` command

e.g.:
```
Envelope from: “” +XXX (device: 2) to +YYY
Timestamp: 1708285141830 (2024-02-18T19:39:01.830Z)
Server timestamps: received: 1708285141953 (2024-02-18T19:39:01.953Z) delivered: 1708285142925 (2024-02-18T19:39:02.925Z)
Sent by unidentified/sealed sender
Received a receipt message
  When: 1708285141830 (2024-02-18T19:39:01.830Z)
  Is read receipt
  Timestamps:
  - 1708285134389 (2024-02-18T19:38:54.389Z)
```
