### ISSUE TITLE
updateProfile for other parameters

### ISSUE THREAD

**Issue by xyz-nobody** [AsamK/signal-cli#1461]
When using Signal-cli as a master.
Slave clients (e.g. Molly / Signal-Desktop). Respects what the master has registered on Signal's servers. It used to be possible to bypass parameters with a slave client, but this is no longer possible.

Unless I'm mistaken:

It is not possible to deactivate signal-cli as master in the user profile:

Read Receipt : Off / On
Typing Indicator: Off / On

nb: With version 7 of signal, coming soon, we'll have the same problem with the parameters :

Phone Number 
- Who can see my phone number : Everyone / Nobody
- Who can find me by number : Everyone / Nobody

_I know that when we use signal-cli to write, we're not concerned. But many people use signal-cli as master and use slave versions to write (Signal-Desktop - Molly)._

Would it be possible to manage these parameters via commands in updateProfile?

After all, this is all part of the profile stored on Signal's servers.

**Comment by AsamK** [comment]
You can set the read receipt and typing indicators with the updateConfiguration command and the phone number privacy options with the updateAccount command.
Both settings are not part of the profile.
See https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc
