### ISSUE TITLE
dbus: method sendMessage does not exist?

### ISSUE THREAD

**Issue by joed74** [AsamK/signal-cli#1462]
Nearly the same as #420 (but with signal-cli 0.12.8)

I have array:string: on it and that's what i get:

```
dbus-send --system --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:MessageText array:string: string:+[mynumber]
Error org.freedesktop.dbus.errors.UnknownMethod: The method `org.asamk.Signal.sendMessage' does not exist on this object.
```

**Comment by joed74** [comment]
`signal-cli --dbus-system send -m "Test" +[mynumber]` works, but no chance with dbus-send (and python)

**Comment by AsamK** [comment]
You're probably running signal-cli in multi account mode.
You either need to add the account phone number to the path `/org/asamk/Signal/_PHONE_NUMBER` or start the daemon in single account mode `signal-cli -a +PHONE_NUMBER daemon --dbus-system`.
