### ISSUE TITLE
Allow explicitly setting username number suffix

### ISSUE THREAD

**Issue by chaoticbear** [AsamK/signal-cli#1469]
It would be nice if setting the username-number explicitly was an option, like Signal Desktop Beta. Or if it is an option, perhaps it can be documented clearly in the help notes.

Signal Desktop Beta allows setting the username number suffix explicitly.

When using signal-cli with:
`signal-cli -a +XXXXXXXXXXX updateAccount --username xxxxxxx`

The response is:
`Your new username: xxxxxxx.83 (https://signal.me/#eu/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)`

Help notes currently read:

```
  -u USERNAME, --username USERNAME
                         Specify a username that can then be used to contact this account.
```

**Comment by AsamK** [comment]
Would indeed be nice and simple to implement.
With this development build you can set an explicit discriminator with `updateAccount --username xxxx.83`:
https://github.com/AsamK/signal-cli/actions/runs/8009618151
