### ISSUE TITLE
Do not allow to be found by phone number 

### ISSUE THREAD

**Issue by gregor-hh** [AsamK/signal-cli#1484]
Hello, since the last official signal update for the Iphone you can set that you can not be found by the phone number (checkbox)

Can this also be set with signal-cli?

If so, what is the command, or can this please be implemented?

Best regards

**Comment by AsamK** [comment]
See the updateAccount command: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc

**Comment by gregor-hh** [comment]
> See the updateAccount command: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc

Thank you, but I am a bit confused:

--discoverable-by-number {true,false}
Enable/disable if the account should be discoverable by phone number

is exactly what I would like to set to false.

But it comes:

"unrecognized arguments"
Is it not implemented?

**Comment by AsamK** [comment]
You need the latest version for this to work:
`signal-cli -a +XXXX updateAccount --discoverable-by-number=false`
