### ISSUE TITLE
Using signal-cli with built version of Signal Server

### ISSUE THREAD

**Issue by jgnoonan** [AsamK/signal-cli#1487]
I have my own instance of Signal Server up and running on AWS. I want to use signal-cli to test the server's functions. Is there a way to configure signal-cli to point at my server instance, and if so, what are the instructions? Thanks!

**Comment by AsamK** [comment]
This is currently not supported by signal-cli.
For testing you could modify the constants in the code and recompile it.
https://github.com/AsamK/signal-cli/blob/master/lib/src/main/java/org/asamk/signal/manager/config/LiveConfig.java

**Comment by jgnoonan** [comment]
Thanks @AsamK!  I'll give it a try!
