### ISSUE TITLE
[QUESTION] Why does it now require Java 21?

### ISSUE THREAD

**Issue by Miniontoby** [AsamK/signal-cli#1493]
Hi,

I see that since v0.13.0 signal-cli now requires Java 21...

Signal updates their servers too much and too often, it is hard to keep up. 

But now with the requirement of java 21 on my raspberry pi 4 with ARM Architecture, there is [no java 21 available](https://adoptium.net/temurin/releases/?os=linux&arch=arm&package=any&version=21).

This would mean that I would no longer be able to use signal-cli...

So I would like to know why signal-cli now requires java 21...

*P.s. for now I can still use v0.12.8 since that one is still supported by the signal servers, but I do not know for how long...*

**Comment by bublath** [comment]
That was already discussed a couple of times, and the signal-cli author decided to stay with the JDK 21 requirement. Something we will need to accept.
As I was in the same situation as you, I helped myself and compiled my JDK 21 for armv7l:
https://github.com/bublath/FHEM-Signalbot/tree/main/java
Hope that helps.

**Comment by Miniontoby** [comment]
Oke thanks, I think I just created an issue without looking at the rest, like I normally do...

But yeah, thanks for the build.
