### ISSUE TITLE
Sending messages to usernames

### ISSUE THREAD

**Issue by marsavar** [AsamK/signal-cli#1495]
I am using a Rust application to drive `signal-cli`, sending a message to a known number.
The Rust application listens for incoming messages and would normally reply back using the number included in the JSON-RPC response. However, due to the recent Signal changes that hide numbers by default, `envelope.sourceNumber` can now be null, and this is the response that I get when `signal-cli` receives a text:

```
Object {
    "account": String("***REDACTED***"), 
    "envelope": Object {
        "dataMessage": Object {
            "expiresInSeconds": Number(0), 
            "message": String("Hello world"), 
            "timestamp": Number(1709896383757), 
            "viewOnce": Bool(false)
            }, 
        "source": String("84a58df5-***"), 
        "sourceDevice": Number(1), 
        "sourceName": String("***REDACTED***"), 
        "sourceNumber": Null,
        "sourceUuid": String("84a58df5-***"), 
        "timestamp": Number(1709896383757)
        }
    }
```

i.e. `event.sourceNumber` is now nullable (used to be a real phone number), and if it's not there, `envelope.source` becomes a uuid (a duplicate of `envelope.sourceUuid`). 
Since it is now no longer possible to capture phone numbers in the JSON-RPC response (unless the sender changes the visibility of their phone number), are there any plans to support sending messages to usernames instead?

**Comment by AsamK** [comment]
That's already supported. You can send a message to the uuid just like you would send to a phone number.
Sending to a username works with the `username` field of the `send` command: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#send
