### ISSUE TITLE
[documentation] new release 0.13.2 includes `libsignal-client` 0.40.1

### ISSUE THREAD

**Issue by m-ueberall** [AsamK/signal-cli#1499]
The [changelog](https://github.com/AsamK/signal-cli/blob/v0.13.2/CHANGELOG.md) does not mention that release 0.13.2 now uses/depends on `libsignal-client` version 0.40.1

**Comment by AsamK** [comment]
Thanks for the hint, I've updated the CHANGELOG in master and added the hint to the release.
