### ISSUE TITLE
I think I tried to register to many times?

### ISSUE THREAD

**Issue by charlieporth1** [AsamK/signal-cli#150]
I think I tried to register to many times?
``` 
Verification failed! This number is locked with a pin. Hours remaining until reset: 166
Use '--pin PIN_CODE' to specify the registration lock PIN
```

**Comment by AsamK** [comment]
Hm, I'm not aware that multiple registrations can trigger a pin lock.
This message should only appear, if you have manually set a PIN code after registration for this account.

**Comment by five-c-d** [comment]
The registration-lock-pin feature has to be manually enabled.  That is what the "166 hours remaining" thing is about.  

However, there IS a <a href="https://github.com/signalapp/Signal-Android/blob/master/res/values/strings.xml#L1424 ">rate-limit specific to the case</a> where registration-lock-pin is enabled for +12223334444, AND you have tried to (re)-register that number multiple times with the wrong/incorrect registration-unlock-pin.  

```
<string name="RegistrationActivity_you_have_made_too_many_incorrect_registration_lock_pin_attempts_please_try_again_in_a_day">You\'ve made too many incorrect Registration Lock PIN attempts. Please try again in a day.</string>
```

This is distinct from the too-many-registration-attempts-in-a-row error, for which <a href="https://github.com/signalapp/Signal-Android/issues/7819">signal-server returns HTTP 413</a>.
