### ISSUE TITLE
Group messages not seen after being added to the group second time

### ISSUE THREAD

**Issue by k-bx** [AsamK/signal-cli#1506]
My account was removed from the group and added back. I can see messages on Signal Android app, but signal-cli doesn't receive them.

**Comment by AsamK** [comment]
Please check the signal-cli verbose log (`-v`) if there's some warning when receiving a message from that group.

**Comment by k-bx** [comment]
Let me close this one and just create issues with stack traces I'm seeing, I'm pretty sure one of them is upon this condition.
