### ISSUE TITLE
Quoted replies do not include quotation information in JSON

### ISSUE THREAD

**Issue by eadmund** [AsamK/signal-cli#151]
Signal has had a quoted replies feature for awhile now. I've noticed that if there's a message which quotes another, `signal-cli` doesn't include the quotation in the JSON output of dæmon-mode.

**Comment by matthew-piziak** [comment]
Yeah, this would be great. As it is right now, it is received as a standalone message, with no reference to the text being cited.

**Comment by AsamK** [comment]
implemented in 58db3cbd53f3faec94ddfcd5e029865a380e6242

**Comment by Atomic-Bean** [comment]
Commit 58db3cb only added it for regular output and not daemon mode as seen [here](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/json/JsonDataMessage.java#L109). I believe PR #396 was supposed to add this for daemon, but it would be a bit out of date ATM. Same goes for #383.

**Comment by heinrich-ulbricht** [comment]
I'm currently experimenting with DBus messaging in daemon mode from a .NET Core application. In the terminal I see quoted messages printed by the daemon (good), from the application I seem to be unable to access it (not so good).

The post from @Atomic-Bean indicates that the quote info is not accessible via DBus. Is this still the case?
