### ISSUE TITLE
ListGroups returns empty fields "name" and "description"

### ISSUE THREAD

**Issue by Serhii-zp-ua** [AsamK/signal-cli#1517]
Hi Asam.
multi-account mode.
When I make ListGroups command, in response only id fields are has values, all other are null or 0 or false. And it doesn't usefull, because I can't identify which id I need, because I know needed group name, but not id. When I try make sendSyncRequest it return empty result and has no any effect.

example
 "jsonrpc": "2.0",
  "result": [
    {
      "id": "lY9b9M3lIu1YoglzTCv2H1DlX4UfGXBnV1234567890=",
      "name": null,
      "description": null,
      "isMember": false,
      "isBlocked": false,
      "messageExpirationTime": 0,
      "members": [],
      "pendingMembers": [],
      "requestingMembers": [],
      "admins": [],
      "banned": [],
      "permissionAddMember": "EVERY_MEMBER",
      "permissionEditDetails": "EVERY_MEMBER",
      "permissionSendMessage": "EVERY_MEMBER",
      "groupInviteLink": null
    },
...

**Comment by AsamK** [comment]
This should be fixed in the version, except for groups you're no longer a member of.
