### ISSUE TITLE
Don't store passwords and cryptographic keys in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by rpdelaney** [AsamK/signal-cli#152]
This behavior is a deviation from the XDG directory standard with serious security implications. XDG_CONFIG_HOME is intended to store configuration files only, which means many users may accidentally back up this sensitive data via insecure means to insecure locations.

A much better place to put passwords and cryptographic keys would be in $XDG_DATA_HOME (on my system this is `/home/ryan/.local/share`).

Further reading: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by AsamK** [comment]
good point, I'll probably change the path to `$XDG_DATA_HOME/signal-cli`.
