### ISSUE TITLE
Defunct link in README and clarification about libsignal

### ISSUE THREAD

**Issue by IacobusKopiirefuto** [AsamK/signal-cli#1522]
In `README.md` the link to location of libsignal-service-java inside Signal-Android source code now results in `404 - page not found`.

```markdown
extracted from the [Signal-Android source code](https://github.com/signalapp/Signal-Android/tree/main/libsignal/service).
```

Related question, could you clarify the situation with the `libsignal-service-java`? 

The official Signal's repository has been archived since Feb 12, 2022 and has been replaced by [libsignal](https://github.com/signalapp/libsignal) it [seems](https://github.com/signalapp/libsignal-service-java/issues/83#issuecomment-883483182).

`README.md` mentions that `signal-cli` uses [patched libsignal-service-java](https://github.com/Turasa/libsignal-service-java) and this @Turasa 's repository is still updated.

But when Signal official `libsignal-service-java` **where do you get updates for it**? Could @AsamK or somebody else who knows it clarify this?

Given lack of information it raises question of how and for how long can `signal-cli` catch up to official Signal development - when it fact everything might be just fine and only the `README.md` is outdated. : )

**Comment by AsamK** [comment]
The directory for upstream libsignal-service-java inside Signal-Android has changed, I just updated the [link](https://github.com/signalapp/Signal-Android/tree/main/libsignal-service) in the README. Thanks for the hint.

The upstream libsignal-service-java ist just a module in Signal-Android. I'm using a script to get the changes from there and add them to the patched libsignal-service-java fork. The fork repository also has an upstream branch (https://github.com/Turasa/libsignal-service-java/tree/upstream) which just contains the copied unpatched upstream libsignal-service, with just some additional build files.

libsignal is a lower level library, that's used internally by the libsignal-service module.

**Comment by IacobusKopiirefuto** [comment]
Thanks a lot for a prompt reply and explanation. : )

**Comment by IacobusKopiirefuto** [comment]
Just to double check. So before 2022 Signal had one big library for Android called [libsignal-service-java](https://github.com/signalapp/libsignal-service-java) but now they split it to [libsignal-service](https://github.com/signalapp/Signal-Android/tree/main/libsignal-service) with Android/Java specif code and platform-agnostic APIs of [libsignal](https://github.com/signalapp/libsignal) which is used by `libsignal-service` as well as other services of other platforms.

And `signal-cli` takes the upstream of `libsignal-service` and because of this also uses the `libsignal` as well, right?

**Comment by AsamK** [comment]
Yes. Signal created libsignal to share code between their different platforms and then replaced the corresponding code in libsignal-service.
