### ISSUE TITLE
JsonRpc: getUserStatus returns error -32603

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1529]
The following command:
`{"jsonrpc":"2.0","method":"getUserStatus","params":{"number":["+MYNUMBER"]},"id":1715611543}` 

Returns :
`{"jsonrpc":"2.0","error":{"code":-32603,"message":null,"data":null},"id":1715611543}`

I think the command has a bug

**Comment by AsamK** [comment]
The parameter is called recipient.

`{"jsonrpc":"2.0","method":"getUserStatus","params":{"recipient":["+MYNUMBER"]},"id":1715611543}`

**Comment by Tsjippy** [comment]
Then we should update the docs:
```
getUserStatus
Uses a list of phone numbers or usernames to determine the statuses of those users. Shows if they are registered on the Signal Servers or not. In json mode this is outputted as a list of objects.

[NUMBER [NUMBER …​]]
One or more numbers to check.

[--username [USERNAME …​]]
One or more usernames to check.
```
