### ISSUE TITLE
Update profile picture via cli

### ISSUE THREAD

**Issue by Jamie-Troup** [AsamK/signal-cli#1536]
Hiya, I managed to register an account happily (fan of the tool), just wondered if someone could signpost me to docs/instructions on how to update the profile picture/username of a newly made account.

Cheers

**Comment by AsamK** [comment]
The avatar (profile picture) can be set with [updateProfile](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#updateprofile) and the username with [updateAccount](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#updateaccount)
