### ISSUE TITLE
"Invalid account (phone number), make sure you include the country code."

### ISSUE THREAD

**Issue by Geremia** [AsamK/signal-cli#1547]
When I try registering with a new number, I get this:

    Invalid account (phone number), make sure you include the country code.

<sup>signal-cli 0.13.2-SNAPSHOT</sup>

**Comment by m-ueberall** [comment]
Do you see the same error with the current version (0.13.4)? Also, can you provide a verbose log (by adding "-vv" on the command line)? Without the latter, nobody is able to help you find the possible reason of your problem.

**Comment by Geremia** [comment]
@m-ueberall I get the issue with signal-cli 0.13.5-SNAPSHOT, too:

```
$ signal-cli -a +XXXXXXXXXXX -vv register
2024-06-29T16:42:26.223-0700 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.5-SNAPSHOT
2024-06-29T16:42:26.409-0700 [main] TRACE org.asamk.signal.manager.Manager - Expected exception when checking libsignal-client: Failed to deserialize zkgroup::api::groups::uuid_ciphertext::UuidCiphertext
2024-06-29T16:42:26.409-0700 [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
Invalid account (phone number), make sure you include the country code.
```
<sup>(+XXXXXXXXXXX redacted)</sup>

**Comment by donovanglover** [comment]
Captcha issue sounds like https://github.com/AsamK/signal-cli/issues/1491

**Comment by Geremia** [comment]
@donovanglover Indeed. It does.

**Comment by AsamK** [comment]
What do you get when you try to validate your phone number on this page (it's using the same phone number library as Signal):
https://libphonenumber.appspot.com/

**Comment by Geremia** [comment]
@AsamK

```
Phone Number entered: XXXXXXXXXX

Default Country entered: 01

Language entered: en

An error occurred while parsing the input: Error type: INVALID_COUNTRY_CODE. Missing or invalid default region. 
```
<sup>(phone # redacted; I typed 10 digits.)</sup>

**Comment by nomansial** [comment]
If your number is already registered with Signal via the mobile app, you don't need to go through the registration process again with Signal-CLI. Instead, you can link Signal-CLI to your existing Signal account.

Here’s how you can link Signal-CLI to your existing Signal account:

1. Generate a Linking QR Code
Open Command Prompt and navigate to the Signal-CLI directory:

bash
Copy code
cd path\to\signal-cli
Run the following command to generate a QR code for linking Signal-CLI as a device:

bash
Copy code
signal-cli -u +92325278158 link -n "Signal-CLI"
Replace +92325278158 with your registered phone number. The -n "Signal-CLI" part allows you to name the device you are linking.

This command will output a QR code in the terminal or save it to a file (depending on the terminal capabilities).

**Comment by AsamK** [comment]
If the libphonenumber site says that the number is invalid, then it's not a signal-cli issue. Something with the number format is wrong.

**Comment by vergenzt** [comment]
Thanks for the reference to the libphonenumber site. I ended up pasting into `hexdump` and discovering that the UI where I had copied my VoIP phone number from included a couple extra (invisible) unicode characters in there. And those invisible characters had persisted every time I pasted the number.🤦🏻‍♂️

What that looked like (redacted):
```console
$ pbpaste | hexdump -C
00000000  2b 31 e2 80 aa ██ ██ ██  ██ ██ ██ ██ ██ ██ ██ e2  |+1...██████████.|
00000010  80 ac                                             |..|
00000012
```
