### ISSUE TITLE
User's phone # not showing up in message envelope in group chat

### ISSUE THREAD

**Issue by vbrilon** [AsamK/signal-cli#1550]
I am working on a bot that sits in a Signal group, listens for key words, and then DMs the person who sent the keywords. In general it's working, except that for some people in the group, their message comes back with an envelope that only shows their display name and a UUID of sorts, but no phone numbers.

Is that by design? if so, is there a way to DM those people without having their phone number, just the display name and the UUID?

I am using signal-cli with a python wrapper around the executable.

**Comment by vbrilon** [comment]
After doing some testing, it appears that users who have no DM'ed with the bot, are the ones showing up w/o their number in the envelope. I guess that's a security feature? Or am I doing something wrong here?

**Comment by AsamK** [comment]
It's a Signal privacy feature, users can opt in to hide their phone number.
You can send them a message, just by using the uuid instead of the phone number in signal-cli commands.

**Comment by vbrilon** [comment]
@AsamK from what I see via the man page, signal-cli only accepts the phone number of the recipient. I don’t see where a UUID can be used.

**Comment by AsamK** [comment]
Then I guess I'll need to update the man page😅

The uuid can be used in all places where the man page mentions a recipient's phonenumber.
