### ISSUE TITLE
Question: How long is it OK to leave the primary offline?

### ISSUE THREAD

**Issue by JulienPalard** [AsamK/signal-cli#1553]
First thanks for signal-cli!

Holidays are near, and my primary device is a laptop that I won't bring with me.

Reading the README:

> The Signal protocol expects that incoming messages are regularly received (using daemon or receive command). This is required for the encryption to work efficiently and for getting updates to groups, expiration timer and other features.
I understand that *some* signal feature needs for the primary to connect from time to time.

Reading [the signal website](https://support.signal.org/hc/en-us/articles/360007320551-Linked-Devices):

> Your phone does not have to be online for the linked device to work, but it will unlink after 30 days of inactivity.

Which I translate to "Your primary device does not have to be online for your secondary device to work".

So it feels like it's OKish to have it's primary offline for a week or two as long as one does not use features like group chats. Has anyone tried this so we could enhance the README about that point?

**Comment by exquo** [comment]
I've had no issues not touching my "primary" device for *months* at a time. No issues when using the linked signal-cli and signal-desktop.

**Comment by AsamK** [comment]
Yeah, the primary can be offline for longer. At some point the Signal-Server will mark it as unregistered. I think it's a year, but I'm not sure.
