### ISSUE TITLE
Error: unable to delete messages in group chats via linked devices

### ISSUE THREAD

**Issue by 07artem132** [AsamK/signal-cli#1555]
I am encountering an issue where messages sent through the API to a group cannot be deleted via linked devices. However, I am able to delete my messages in private chats without any problems.

**Steps to Reproduce:**
Send a message to a group chat using the signal-cli API.
Attempt to delete the sent message from a linked device (e.g., Signal Desktop or Signal on phone).
**Expected Behavior:**
The message should be deleted from the group chat across all devices.

**Actual Behavior:**
The message remains in the group chat and cannot be deleted via linked devices. Deletion works as expected in private chats.

Additional Information:
Signal-cli version:  v0.13.4
Linked devices: Signal Desktop(7.15.0),  Signal client ios (7.17)
API request used for sending the message:  
```
{
   "jsonrpc":"2.0",
   "method":"send",
   "id":"test-id",
   "params":{
      "groupId":"group_id",
      "message":"mesToSend"
   }
}
```
Request for Help:
Any insights or suggestions on how to resolve this issue would be greatly appreciated. If additional information is needed, please let me know.

**Comment by AsamK** [comment]
It's related to a new feature flag, that will be included in the next signal-cli version (5ff66728e32237a23fdffda4515031d24dad7cf0)
If you want you can try running the latest development build and see if it works: https://github.com/AsamK/signal-cli/actions/runs/9681344917

**Comment by 07artem132** [comment]
Thank you, I’ll wait for the release, since I’m using the signal-cli-rest-api wrapper project.

**Comment by 07artem132** [comment]
Hello!
The issue was resolved for a while, but it is now relevant again in the latest version. If possible, please fix it. Thank you!
