### ISSUE TITLE
Use as interactive curses client for chatting?

### ISSUE THREAD

**Issue by alxpettit** [AsamK/signal-cli#156]
I have a big thing for minimal CLI-compatible clients, so I wonder if this could be adapted to be usable as one. If it can't be with the current codebase, how do you recommend I go about making my own minimal client?

**Comment by jwoglom** [comment]
I've actually taken a shot at this... take a look if you're interested: https://github.com/jwoglom/signal-curses

**Comment by five-c-d** [comment]
See also the design-discussion here, https://community.signalusers.org/t/roll-your-own-desktop-client-using-signal-cli-as-a-backend-bad-idea/4158

**Comment by remembertoremind** [comment]
[There is also this](https://github.com/isamert/scli)

**Comment by AsamK** [comment]
closing this, as a full curses client is out of scope for signal-cli itself
