### ISSUE TITLE
please help, i am lost...

### ISSUE THREAD

**Issue by thlkmoeller** [AsamK/signal-cli#1575]
Hello,
I am sorry to write here, but I am really lost.
Yesterday there was suddenly a bug in Signal Desktop, which caused, that I lost my complete chat history. You can compare here:

https://github.com/signalapp/Signal-Desktop/issues/6996

Now I have to link the updated Signal Desktop app again to my signal-cli, as I did about two years ago. I guess, I used v0.7.4 that time.

But when I go to my /home/thlk/Downloads/signal-cli-0.7.4/bin and then I type the following
./signal-cli -u +491601111111 listDevices

I get the error message:
ERROR App - Error while checking account +491601111111: java.net.UnknownHostException: textsecure-service.whispersystems.org: Der Name oder der Dienst ist nicht bekannt

The last sentence means "Name or service is not known"
I cannot add a new device either

I tried to save the folder ~/.local/share/signal-cli and I copied it to another laptop

then I tried to install the newest version of signal-cli, but I am already failing in the first step:

when i enter (as described in the installing instructions) "export VERSION=<0.13.5>", i get the message 
bash: Syntaxfehler beim unerwarteten Wort »newline«

that means syntax error with an unexpected word
on the original machine i also had the version 0.11.7 and i tried it with that, but i get the following error

Fehler: Beim Laden der Klasse org.asamk.signal.Main ist ein LinkageError aufgetreten
  java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

Please can someone help me? i just want to use my account again, i have to re-link my signal desktop, that is why i have to use signal-cli for it

which version should i use?

i would be so greatful for any help

by the way i also don't know about this:
Provide native lib for libsignal

Do i have to care about that, too?

on both laptops i use Linux Mint

**Comment by cuu508** [comment]
> when i enter (as described in the installing instructions) "export VERSION=<0.13.5>", i get the message
bash: Syntaxfehler beim unerwarteten Wort »newline«

The angle brackets in the instructions mean "this is a placeholder for an actual value". The command you run in the terminal should look like this:

```
export VERSION=0.13.5
```

**Comment by AsamK** [comment]
Also the UnsupportedClassVersionError error means, you need a newer java version (at least Java 21)
