### ISSUE TITLE
Full CDSI recipients refresh failed

### ISSUE THREAD

**Issue by cuu508** [AsamK/signal-cli#1576]
I see warnings in logs when signal-cli 0.13.5 process starts up:

On the primary device:

```
WARN  RefreshRecipientsJob - Full CDSI recipients refresh failed, ignoring: You must have a token if you have previousE164s! (IllegalArgumentException)
```

On linked devices:

```
WARN  RefreshRecipientsJob - Full CDSI recipients refresh failed, ignoring: org.signal.libsignal.net.NetworkException: IO error: connection reset (IOException)
```

Other than the warnings, signal-cli appears to be working fine. Are these warnings a potential problem, or can they be ignored?
Thanks!

**Comment by AsamK** [comment]
The errors are not critical, it means signal-cli can't check the list of known numbers for unregistered or reregistered accounts.
The first message seems to be an inconsistent state, I'll add a workaround in the next version for it.

The second one, I'm not sure if it's related to the first error, or an unrelated network issue. Is there a proxy used on the linked device?
