### ISSUE TITLE
"Running daemon command without explicit mode is deprecated. Use --dbus to use the dbus interface."

### ISSUE THREAD

**Issue by tv21** [AsamK/signal-cli#1579]
Thank you for this very useful software!  I am just having one small issue. When I run **signal-cli -u<PHONE NUMBER> daemon** I get a warning message:

"Running daemon command without explicit mode is deprecated. Use --dbus to use the dbus interface."

I don't understand what this means, or how to avoid getting this message.  Everything seems to work, so should I just ignore it, or is there a different option I should be using (other than **daemon**)?  Please don't assume any prior knowledge on my part, I am just trying to get this to work and finally had success.  This is running on Ubuntu Linux 24.04.

**Comment by AsamK** [comment]
Use `signal-cli -u XXX daemon --dbus` to get rid of the warning.
Using the `daemon` command without `--dbus` will stop working in a future version.
