### ISSUE TITLE
Correct way to move master device to new server?

### ISSUE THREAD

**Issue by tjswe** [AsamK/signal-cli#158]
Hi!

What would be the correct way to move the "master device"? 

Currently running 0.5.6 on a server which is being shut down and need to move all functions to a new server (both running Ubuntu 16.04)

Im trying to wrap my head around the correct way, but reading the man-page gives that i can add devices but my current installation will still be the "master device" which i want to move. Assign "master" status to the new server? Can i just copy the config-directory?

Any hints appreciated!

Also big thanks for this awesome app!

**Comment by AsamK** [comment]
Yes, you can just copy the config directory `~/.config/signal` to the new server. signal-cli doesn't store data anywhere else.
Copying the files is also the only way to achieve this. The signal server doesn't allow to change the master/slave status of devices.

Only make sure the old server doesn't run signal-cli anymore, after copying the files. The saved session state in the config directory will get mixed up, if two signal-cli instances run using the same config directory.

**Comment by jholdorff** [comment]
I registered a number and am using the signal-cli (0.8.1) without problems but the /.config/signal directory does not exist.

**Comment by AsamK** [comment]
Newer version store the data in `.local/share/signal-cli`
