### ISSUE TITLE
Error -32603 when doing actions to specific group via json rpc

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#1581]
I have this weird problem since 2 days for the sendTyping and send command.
The command 
`'{"jsonrpc":"2.0","method":"sendTyping","params":{"recipient":"+SOMENUMBER","groupId":"SOMEGROUPID"},"id":"12345"}\n' | socat UNIX-CONNECT:/home/simnige1/sockets/signal -`

Works fine for most groups, but for one specific group I get this result since 2 days:
`{"jsonrpc":"2.0","error":{"code":-32603,"message":null,"data":null},"id":"12345"}`

Any idea?

I am on version 0.13.5

**Comment by AsamK** [comment]
`-32603` is an internal error, please provide the log output of the signal-cli daemon process, that might show more information.

**Comment by Tsjippy** [comment]
thank you.

The problem seems to be solved now. I already had restarted the server that did not make a difference, but when I added the 'verbose' parameter to the service file and restarted the signal-cli service it started behaving normal
