### ISSUE TITLE
ClassNotFoundException: org.asamk.signal.Main

### ISSUE THREAD

**Issue by PastCoder** [AsamK/signal-cli#1583]
In updated today via apt update / apt upgrade.

Since then signal-cli reports the following error:
```
Fehler: Hauptklasse org.asamk.signal.Main konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: org.asamk.signal.Main
```

**Comment by AsamK** [comment]
Please report it to the deb package creator.
Not a general issue with signal-cli.

**Comment by PastCoder** [comment]
@AsamK 
I can do, if I know what/where the "deb package creator" is. I have to admit that I am more or less a stupid user of the signal-cli.

**Comment by m-ueberall** [comment]
@PastCoder: `apt-cache policy <package_name>` (the latter is likely `signal-cli`) should show you the location of the repository where you downloaded the `.deb` package in question. Maybe it's one of the repositories listed under https://github.com/AsamK/signal-cli/wiki/Binary-distributions#linux-packages?

**Comment by morph027** [comment]
FYI: https://gitlab.com/packaging/signal-cli/-/issues/23

**Comment by morph027** [comment]
btw, i've added some extra string to the version indicator to make clear the package has been pulled from my repo instead of upstream, so probably future issues like this will be reported to me directly.

```
signal-cli --version
signal-cli 0.13.6+morph027+4
```

**Comment by m-ueberall** [comment]
Sounds like a good idea – I'll add a suffix as well in future builds.
