### ISSUE TITLE
no callback for registration attempt of landline phone number 

### ISSUE THREAD

**Issue by borisneubert** [AsamK/signal-cli#160]
Hi,

others successfully registered a German landline phone number but I could not.

Neither

`signal-cli-0.6.0/bin/signal-cli -u +49xxxxxxxxxx  register --voice`

nor 

`signal-cli-0.6.0/bin/signal-cli -u +49xxxxxxxxxx  register`

result in a call back or SMS delivery within days (I can receive SMS on my landline, a voice reads it to me).

I tried it under Raspbian Stretch 9.4 on a Raspberry Pi 3 and under Ubuntu 18.04 Bionic Beaver on amd64. Outgoing connections through firewall are unrestricted. Internet access is dual stack light, i.e. native IPv6 with carrier-grade NAT for IPv4. 

What can I do to debug the registration process?

Best regards,
Boris

**Comment by MatejKovacic** [comment]
I have found out that I cannot register Slovenian landline number (+386xxxxxxx) on Android phone anymore. Since I am trying to register landline, no SMS does come. But when I click to "call me", I never get the call.

So there is a possibility that Signal servers now does not support landlines at all?

**Comment by five-c-d** [comment]
@borisneubert , there is a signalUsers forum-thread about call verification taking forever in +49 numbers, can you post info about your carrier/operator over there?  https://community.signalusers.org/t/call-verification-takes-forever/4479  Have you tried registering the +49 landline with a normal stock signal4smartphone on a normal stock android or ios device, to rule out the possibility of any sigCLI or linux-OS-related troubles?  (And yes, my understanding is that 'authorization failed' just means you entered a 6-digit conf-code which either signal-server or sigCLI no longer believe is the "current" one.)  

@MatejKovacic , "there is a possibility that Signal servers now does not support landlines at all?"  No, they are definitely still supported, and <a href="https://community.signalusers.org/t/robocall-to-register-seriously-delayed-slovenia-landline-among-others/4745/2">at least some people</a> registering with Telekom Slovenije landlines recently were successful.  Your particular inability-to-receive-robocall-to-+386-landline is something else, not sure what it is exactly just yet

**Comment by borisneubert** [comment]
Became part of discussion at the signal users community.

**Comment by borisneubert** [comment]
My issue is solved. It just worked as advertised last Sunday. There was a likely an intermittent problem on the server-side for several days last week. See [signal forum thread](https://community.signalusers.org/t/call-verification-takes-forever/4479/12) for details. I encourage @MatejKovacic to retry.

I am grateful fot @five-c-d's help!
