### ISSUE TITLE
listGroups not showing new groups

### ISSUE THREAD

**Issue by Joly0** [AsamK/signal-cli#1602]
Hey guys, i am running signal-cli using the docker image from here https://github.com/bbernhard/signal-cli-rest-api
The image has the plain signal-cli and i tried listing all my groups (i am trying to send messages to a new group that i am the only member of)
The problem is, running `signal-cli -u OBFUSCATED listGroups` shows all my groups, except a new created one.
I have searched for this issue and found someone mentioning, someone else needs to write a message in the group first, so i added another phone to the group, let it send a message and still using the command above the group is not showing up.
Someone else mentioned the signal-cli needs to be restarted, so i restarted the container but still the group is not showing up.
I  also checked if the signal-api was still connected to my device, and it was, i can send messages to myself, just this one group is not showing up

As additional information, the signal-cli version shows this:
```
signal-api@29ee9e88877f:/$ signal-cli --version
signal-cli 0.13.7
```

**Comment by AsamK** [comment]
Try sending a message to the group from another device and then run `signal-cli -u XXX receive` in the container. Does it show the message and does it show the group id and name?

**Comment by Joly0** [comment]
Hey, yes. Although it took some time to receive all messages, the message showed up and afterwards the listGroups command worked.
Another way i figured which works without having a second user join the group is run `signal-cli -u OBFUSCATED sendSyncRequest` after creating the group.

**Comment by Joly0** [comment]
Hm, but its weird, i deleted the test groups i created and they still show up when running listGroups. Even after running the sendSyncRequest command or the receive command

**Comment by AsamK** [comment]
Then it works as expected. The signal propagates this information via messages, that's why it expects all devices to receive messages regularly.
The signal protocol doesn't support deleting groups. You can delete group messages and leave a group, but the group data itself isn't deleted.
