### ISSUE TITLE
"updateContact --expiration" doesn`t work

### ISSUE THREAD

**Issue by red9hawk** [AsamK/signal-cli#1605]
Hello,

the function "... updateContact --expiration {seconds}..." for direct messages doesn't work on IOS. It doesn't work on Android either if you have an logged in Signal Desktop client at the same time. It will reset the config immediately if you send another message. You can follow this on the desktop client. If you use this feature on a standard signal client IOS/Android it works fine. With signal-cli it only works with groups.

Best Regards
Redhawk

**Comment by AsamK** [comment]
Can reproduce this as well.
Relevant log line: `[SynchronizeExpiration] Ignoring expire timer update with old version. Received: 1, Current: 2`
I guess signal-cli needs to implement support for VersionedExpirationTimer for this to work now.
