### ISSUE TITLE
send from stdin seems to be broken

### ISSUE THREAD

**Issue by sidhussmann** [AsamK/signal-cli#1607]
Sending a message via `stdin` seems to be broken in version 0.13.7:

```
echo "hello world" | signal-cli send +XXX
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
Sending empty message is not allowed, either a message, attachment or sticker must be given.
```

While the `-m` option still works:
```
signal-cli send +XXX -m "hello world"
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
1728977706991
```

I tried with the following installation methods:
- `nix-env -i signal-cli`
- https://flathub.org/apps/org.asamk.SignalCli
- https://packaging.gitlab.io/signal-cli/installation/standalone/

**Comment by AsamK** [comment]
You need to use the `--message-from-stdin` parameter in recent signal-cli versions.
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#send
