### ISSUE TITLE
Is there a way to receive already read messages?

### ISSUE THREAD

**Issue by yuriikonovalov** [AsamK/signal-cli#1608]
Want to ask is there's a way to get already read messages? For example, I linked a desktop Singal app for my account and haven't been open the desktop app for a while. When I open it, all the read messages are loaded. I'm curious how it's done. Or it's just the CLI that does not provide such functionality?

**Comment by AsamK** [comment]
The `signal-cli receive` command will receive all messages that were sent, regardless if the messages were already read on another device.
However the message queue on the signal server will remove older messages after a few weeks, if the receive command is not executed regularly.
