### ISSUE TITLE
Correctly handle contacts with no phone number

### ISSUE THREAD

**Issue by christian-oudard** [AsamK/signal-cli#1617]
I originally made this issue because I couldn't figure out how to get avatar information on a contact with no phone number. It turns out you have to put the source UUID into the `--profile` parameter. Please improve the documentation on this, as it only mentions phone number.

**Comment by AsamK** [comment]
-> https://github.com/AsamK/signal-cli/commit/77a5c454b7fea9375de9fbaa4adf6f5f22f6a5ae
