### ISSUE TITLE
Message with leading "-" is probably parsed as flag

### ISSUE THREAD

**Issue by g0ierli** [AsamK/signal-cli#1621]
When using signal-cli to send a message that begins with a hyphen (-), such as:

`signal-cli -u "+xxxxxxxxx" --output=json send -m "-test" --group-id "sdfsdfsfdsfsd"
`
the command fails with the following error:
```
usage: signal-cli send [-h] ... [recipient [recipient ...]]
signal-cli: error: argument -m/--message: expected one argument
```

Removing the initial hyphen (-) from the message resolves the issue, indicating that signal-cli interprets the hyphenated message as an unrecognized flag or argument, rather than part of the message content.

Observed Behavior
The command fails, as signal-cli interprets the message text as an argument rather than message content.

**Additional Information**
signal-cli version: 0.13.9
libsignal-client version: 0.58.2 (self-compiled)
Operating System: Debian

**Comment by AsamK** [comment]
Yes, every argument that starts with `-` is interpreted as a flag. You can use the `-m=-test` syntax instead.
