### ISSUE TITLE
Username support for updateGroup and updateContact

### ISSUE THREAD

**Issue by loxK** [AsamK/signal-cli#1625]
`updateContact` and `updateGroup` do not support usernames. I configured my personal account to only work using the username. As a result signal-cli replies with an "`is not registered`" error when I use the phone number. I thus have to use the username. And it works fort sending messages.

I am now trying to add myself to a group :

```
signal-cli -a "[redacted]" updateGroup -n "[redacted]" --username="[redacted]"
signal-cli: error: unrecognized arguments: '--username=[redacted]'
```

I thought I could modify the contact adding the phone number and then use the phone number as I have it in my contacts : 

```
# signal-cli listContacts
Number:  ACI: [redacted] Name:  Profile name:  Username: [redacted] Color:  Blocked: false Message expiration: disabled
```

But I found no way to modify the contact to add the phone number.

**Comment by AsamK** [comment]
You can use the ACI in all places where you would otherwise use the phone number.
You can also use the alternative username syntax `u:username.000` instead of the `--username` parameter.

**Comment by loxK** [comment]
The alternative username syntax works. Thanks.
