### ISSUE TITLE
DBus python script get sender name

### ISSUE THREAD

**Issue by Vic3198** [AsamK/signal-cli#163]
Hi,
The Python script to receive messages on the DBus setup wiki page is amazing, but is there a way to get the Signal username of the sender? You can get the group name with `signal.getGroupName (groupID)`, but I didn't see anything about the user profile name he/she set on the Signal app.
Thanks,

Vic

**Comment by AsamK** [comment]
Not yet. signal-cli hasn't implemented user profiles yet.

**Comment by AsamK** [comment]
duplicate of #98
