### ISSUE TITLE
synchronization of setting for disappearing messages not working

### ISSUE THREAD

**Issue by eggenbef** [AsamK/signal-cli#1633]
i am running signal-cli version 0.13.9 on ubuntu 24.04 linked to signal client version 7.37 on an iOS phone. 
for the purpose of a test i changed the "disappearing messages" setting for messages sent to myself on my phone to 30s. after the test i changed it back to "off" so that disappearing messages should have been disabled again for any message i send to myself with any of the linked devices.

on my phone this is fine. the messages sent by signal-cli to myself, however, keep on disappearing on all linked devices after 30 seconds ever since i carried out the above.  i therefore re-disabled the setting on the phone and as this didn't help also changed the setting on the ubuntu system with 'signal-cli updateContact -e 0 [myphonenumber]'. the latter seems to work but only until the next sync through 'signal-cli receive'. i also tried with another ubuntu instance but experienced the same issue. the synchronization of signal-cli with the setting for disappearing messages of a signal contact on iOS doesn't seem to work as expected. 

any hint/suggestion? thank you!

**Comment by AsamK** [comment]
It's a bug in libsignal-service, related to versioned expiration timers, will be fixed in the next version.
