### ISSUE TITLE
[Documentation update request] Ubuntu 18.04 no need for additional enable unlimited strenght crypto

### ISSUE THREAD

**Issue by igor2x** [AsamK/signal-cli#164]
Using Ubuntu 18.04. Following prerequisites from On page https://github.com/AsamK/signal-cli/wiki/HowToUbuntu I installed default-jre package. After installing it, I have checked the JRE version with: `java -version` and it is: `10.0.2.`

Now following to the second prerequisite on StackOverflow forum, on the same thread there is two answers fellow info: _With Java 9, Java 8u161, Java 7u171 and Java 6u181 the limitation is now disabled by default._ So second step is not required anymore.

**My suggestion:** For second step prerequisite write something like: Check the installed Java version with command: `java -version` Newer versions of Java have unlimited strength crypto enabled by default, but if you are using Java version older then Java 8u161, Java 7u171 or Java 6u181 then see the StackOverflow how to enable it.

**Comment by AsamK** [comment]
It's a wiki page, feel free to update it :)

**Comment by igor2x** [comment]
I changed second option in "Prerequisites" from:
* For older Java Runtime Environments: configure unlimited strength crypto (follow download links and instructions on [[StackOverflow|http://stackoverflow.com/a/6481658]])

to new:
* signal-cli requires _unlimited strength crypto_ in Java Runtime Environment to be turned on. Newer versions of Java have this feature already turned on by default. But for Java versions older then Java 8u161, Java 7u171 or Java 6u181 see the [[StackOverflow|http://stackoverflow.com/a/6481658]] how to enable it. You can check your current installed Java Runtime Environment with command: `java -version`

If you don't like the change, no hard feelings, just change to the way you prefer and then close this bug request.

**Comment by AsamK** [comment]
thanks.
