### ISSUE TITLE
Sending a message via HTTP daemon (JSON-RPC) containing emojis results in error

### ISSUE THREAD

**Issue by innotime32** [AsamK/signal-cli#1647]
When using JSON-RPC interface (via HTTP daemon), if I go to send a message via the HTTP daemon containing an emoji I get this error:

`{"jsonrpc":"2.0","error":{"code":-32700,"message":"Unexpected end-of-input in VALUE_STRING\n at [Source: REDACTED 
(`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 301]","data":null},"id":null}`

For example if I send this:

`{"jsonrpc":"2.0","method":"send","params":{"recipient":["+****"],"message":"How's your day going so far? 🤗"},"id":1}`

When sending HTTP POST request I used this as options:

```
// Create the options for the HTTP POST request
const options = {
    hostname: 'localhost',
    port: 8080,
    path: '/api/v1/rpc',
    method: 'POST',
    headers: {
        'Content-Type': 'application/json; charset=UTF-8',
        'Content-Length': postData.length
    }
};

```
I tried both UTF-8 and UTF-16 or no charset and I get the same error.

Can send emojis via CLI via terminal fine, but not via the HTTP daemon. 

Do you think this is a bug? Perhaps the server is not expecting emojis and is failing to parse the incoming request?

Any help would be greatly appreciated, thanks! x

**Comment by AsamK** [comment]
That message works for when sending via HTTP POST request.
How exactly are you setting the `postData` variable?
The signal-cli http daemon always expects its input to be UTF-8 encoded.

**Comment by innotime32** [comment]
When I run this command it succeeds (sends emojis fine):

`signal-cli -a +*** send -m "Test message 😊" +***`

When I am run the HTTP daemon like this:

`signal-cli -a +*** daemon --http`

And then execute this code:

```
// Define the JSON-RPC request payload
const rpcRequest_respond = {
    jsonrpc: "2.0",
    method: "send",
    params: {
        recipient: '+***',
        message: "Test message 😊"
    },
    id: 2
};


sendRPCRequest(rpcRequest_respond);


function sendRPCRequest(rpcRequest) {
    const url = 'http://localhost:8080/api/v1/rpc';

    // Convert the payload to a JSON string
    const postData = JSON.stringify(rpcRequest);
    console.log(postData);

    const test = JSON.parse(postData);
    console.log('VERIFIED', postData);

    // Create the options for the HTTP POST request
    const options = {
        hostname: 'localhost',
        port: 8080,
        path: '/api/v1/rpc',
        method: 'POST',
        headers: {
            'Content-Type': 'application/json; charset=UTF-8',
            'Content-Length': postData.length
        }
    };

    // Create the HTTP request
    const req = http.request(options, (res) => {
        console.log(`statusCode: ${res.statusCode}`);
        res.on('data', (chunk) => {
            process.stdout.write(chunk);
        });
    });

    // Handle any errors that occur during the request
    req.on('error', (error) => {
        console.error(error.message);
    });

    // Send the JSON-RPC request payload
    req.write(postData);

    // End the request
    req.end();
}
```

I get this console output:

```
{"jsonrpc":"2.0","method":"send","params":{"recipient":"+***","message":"Test message 😊"},"id":2}
VERIFIED {"jsonrpc":"2.0","method":"send","params":{"recipient":"+***","message":"Test message 😊"},"id":2}
statusCode: 200
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Unexpected end-of-input within/between Object entries\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 108]","data":null},"id":null}
```


Hope this helps, thank you x

**Comment by AsamK** [comment]
Ok, the issue is the `Content-Length` header, that you're setting. That header specifies the number of bytes in the request body. But `postData.length` returns the number of UTF-16 codepoints in the `postData` string and the postData is sent in the request body in UTF-8 encoding.
The emoji in the message is two UTF-16 codepoints, but only 4 bytes in UTF-8 encoding, so the number in the `Content-Length` header is too small, resulting in a cut off request body.

You need to either just omit the `Content-Length` header or set it to the actual byte length:
```js
    const encoder = new TextEncoder();
    const bytes = encoder.encode(postData);

    // Create the options for the HTTP POST request
    const options = {
        hostname: 'localhost',
        port: 8080,
        path: '/api/v1/rpc',
        method: 'POST',
        headers: {
            'Content-Type': 'application/json; charset=UTF-8',
            'Content-Length': bytes.length
        }
    };

    // Send the JSON-RPC request payload
    req.write(bytes);
```
