### ISSUE TITLE
[Documentation update request] Add into --voice switch for land numbers registration

### ISSUE THREAD

**Issue by igor2x** [AsamK/signal-cli#165]
On web page https://github.com/AsamK/signal-cli and https://github.com/AsamK/signal-cli/wiki/HowToUbuntu there is info how to register the number
like: ./signal-cli -u +4915151111111 register

Many users using singal-cli as administrator tool to send messages, probably already have Signal app installed on mobile phone (where signal-cli is going to send message), so they need some other number to register. One of the nice option is to register land line number. But in this case SMS is not possible to receive. One option is to use above registration and wait for 2 minutes, because SMS will fail and voice is going to be triggered, the other option is to jump directly to the voice call.

**My suggestion:**
Somewhere after the "registration" command add info like:

Note: You can register Signal using a land line number. In this case you can skip SMS verification process and jump directly to the voice call by adding the` --voice `switch at the end of register command.

**Comment by AsamK** [comment]
It's a wiki page, feel free to update it :)

**Comment by igor2x** [comment]
I have updated https://github.com/AsamK/signal-cli/wiki/HowToUbuntu but I see no Edit button on https://github.com/AsamK/signal-cli site. Maybe because this is official project web page it can only be changed by maintainer itself and not general public.

May I kindly ask you to add the following:

You can register Signal using a land line number. In this case you can skip SMS verification process and jump directly to the voice call verification by adding the `--voice` switch at the end of above register command.

right after the command  `signal-cli -u USERNAME register` and then close down this feature request.
Thanks

**Comment by AsamK** [comment]
Thanks, done.
You can also edit that page (via a PR) when you go to the README.md page directly:
https://github.com/AsamK/signal-cli/blob/master/README.md
