### ISSUE TITLE
Receiving notifications on Linux mobile

### ISSUE THREAD

**Issue by RasheedAZ** [AsamK/signal-cli#1655]
Hi. I managed to link device and get it working : )

Is it possible for signal-cli to continuously receive notifications for calls and messages?

I tried the receive command but it retrieves events and then stops...

I'm using the flatpak package with postmarketOS 24.06

Thanks.

**Comment by AsamK** [comment]
The `receive` command has a `--timeout`/`-t` flag that can be used to disable the default receive timeout and continuously receive messages.
`signal-cli receive -t-1`
