### ISSUE TITLE
Copying config to another user

### ISSUE THREAD

**Issue by MatejKovacic** [AsamK/signal-cli#166]
I registered Signal-CLI user (telephone number) on a Debian server for a specific user (let's say matej). Now I try to copy config to another user.

I copied everything from .config/signal. So:
```
scp -r /home/matej/.config/signal /home/nobody/.config
chown -R nobody:nogroup /home/nobody/.config
```
When I tey to send a message I get error message: `User is not registered.`

Any idea why? Is user somehow encoded in Signal configuration?

**Comment by AsamK** [comment]
That looks like signal-cli doesn't find the users config file. (The unix user doesn't matter to signal-cli, as long as the file permissions are correct)
By default signal-cli stores config files in `$HOME/.config/signal/data`, each file name corresponds to the telephone number.
You can also specify the config directory explicitely when starting signal-cli:
`signal-cli --config /home/nobody/.config/signal -u +XXX receive`

**Comment by MatejKovacic** [comment]
OK, from "my" user I say:
`/home/matej/signal-cli/bin/signal-cli --config /home/matej/.config/signal -u +XXX send -m "test" +YYY`

Then I login as nobody:
`sudo -u nobody bash`

and say:

`/home/matej$ /home/matej/signal-cli/bin/signal-cli --config /home/matej/.config/signal -u +XXX send -m "test" +YYY`

And got:
`User is not registered.`

So it is not the problem of config. It should be something else....

**Comment by MatejKovacic** [comment]
I got some new information...

OpenVPN run client-connect script which contains this:
`sudo -u signal /home/signal/signal-cli/bin/signal-cli --config /home/signal/.config/signal -u +XXX send -m "Connection to VPN established" +YYY >> /etc/openvpn/signal.log 2>&1`

If I run this command from commandline, everything works just fine. Also it works if I run the notify script manually.

But if this script is run by OpenVPN, I get this error:

```
Error occurred during initialization of VM
java.lang.OutOfMemoryError: unable to create new native thread

```
Any idea?

**Comment by MatejKovacic** [comment]
Any solution?
