### ISSUE TITLE
Document requirements for keeping registration

### ISSUE THREAD

**Issue by cfra** [AsamK/signal-cli#169]
I am using signal-cli to send out alerts to a signal group from one of our monitoring servers.

I went through the registration process with signal-cli and was able to send messages just fine.

At some point in time, this stopped working. Looking at the server, I see that transmission of messages now fails stating we are unregistered.

So apparently I lost the registration at some point.

I did not add another mobile device to the E164 number used.

Why did I lose the registration? What is needed to keep it?

Do I need to regularly call receive or perform any other actions?

**Comment by AsamK** [comment]
I don't know what causes the Signal Server to unregister users. I've never had that issue before.
Maybe you need to fetch messages from time to time.
