### ISSUE TITLE
accepting new identities

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#17]
signal-cli does not decrypt messages from clients with a new identity (which is reasonable) and prints a UntrustedIndentityException.

can i remove the contact from the identityKeyStore and signal-cli will sort it out and accept the new identity?

nevertheless, it would be great if the readme would cover this, as others will run into the same problem sooner or later,

**Comment by AsamK** [comment]
Yes, removing the contact from the identity key store will work, then signal-cli behaves as if it is a new contact and trust its key (tofu).

The future plan for signal-cli is to provide a command line interface to compare and accept new identities. Messages with new keys will then be either stored until the identity is accepted or decrypted anyway and marked as untrusted. Not sure yet which is better.

**Comment by kb100** [comment]
In the use case of my https://github.com/kb100/signal-authenticator, it would be really helpful if signal-cli itself provided a `signal-cli -u USERNAME -d DELETEME` to delete identities from the store properly.

**Comment by AsamK** [comment]
I'm currently working on a feature to set different trust levels for identities. This will then allow to trust new keys from contacts.
