### ISSUE TITLE
PKIX path validation fails

### ISSUE THREAD

**Issue by mh-g** [AsamK/signal-cli#172]
Hello,

since about two weeks I get irregularly the following error when transmitting multimedia attachments:

GLib.Error: g-io-error-quark: GDBus.Error:org.freedesktop.dbus.exceptions.DBusExecutionException: Error Executing Method org.asamk.Signal.sendMessage: sun.security.validator.ValidatorException: PKIX path validation failed: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate signature. (36)

Any idea on what to check?

System: 
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
Linux media-live 3.16.60-28 #1 SMP PREEMPT Thu Nov 15 06:06:45 -02 2018 aarch64 aarch64 aarch64 GNU/Linux
on an Odroid C2
Java:
lrwxrwxrwx 1 root root 22 Aug 25 05:49 /usr/bin/java -> /etc/alternatives/java
lrwxrwxrwx 1 root root 46 Sep 28 10:33 /etc/alternatives/java -> /usr/lib/jvm/java-8-openjdk-arm64/jre/bin/java

The system is time-synchronized using ntp.

**Comment by AsamK** [comment]
Haven't seen that error before.
