### ISSUE TITLE
Add HTTP/socket-based API

### ISSUE THREAD

**Issue by skorokithakis** [AsamK/signal-cli#173]
Would it be possible to add a simple API, like the DBus API but either HTTP or TCP based? DBus is currently a bit fussy to set up and it doesn't work across machines, an HTTP or TCP API would be rather more convenient.

**Comment by AsamK** [comment]
signal-cli now has a `jsonRpc` command for a stdin/stdout based json API (https://github.com/AsamK/signal-cli/discussions/679) and the next version will have a unix socket and tcp based json api for the `daemon command: https://github.com/AsamK/signal-cli/discussions/799
