### ISSUE TITLE
Profile-Avatar?

### ISSUE THREAD

**Issue by zonk0101** [AsamK/signal-cli#174]
Hi!

is it possible to set a profile-avatar via CLI?

**Comment by AsamK** [comment]
no, profiles aren't implemented in signal-cli yet.

**Comment by mynameisflorian** [comment]
It would be very useful to be able to receive profiles from other users. Are there plans to add this feature in the near future?

**Comment by AsamK** [comment]
Setting a profile avatar is implemented now with `updateProfile` command

**Comment by technillogue** [comment]
I would also be interested in a way to receive profiles from other users.
