### ISSUE TITLE
Can't send group messages.

### ISSUE THREAD

**Issue by taigrr** [AsamK/signal-cli#175]
`signal-cli -u +14xxxxxxxxx send -g X6zhFaxBxC99bK583Ub95w==  -m "test from cli"`
Results in:

> No recipients given
> Aborting sending.

Which is the same error when I don't specify a group at all. I think the check for a valid recipient happens without checking to see if the -g/--group parameter is set.

I'm completely new to this, and I haven't written java in years. Can someone else verify they have the same issue? 

`signal-cli -v`
> signal-cli 0.6.1

**Comment by Herohtar** [comment]
I'm having the same issue. I can send messages to a specific user with no problem, but groups tell me that I haven't specified a recipient. Interestingly, if I give it a number AND a group it tells me _"You cannot specify recipients by phone number and groups a the same time"_ (sic) so at least part of the check seems to be working.

**Comment by taigrr** [comment]
@Herohtar right, that's what happens for me as well. I'd bet that check happens after the recipient check.

**Comment by Herohtar** [comment]
Well, I see the problem: https://github.com/AsamK/signal-cli/blob/7e897fa6d0aaa87646b51efa3ee1a5ecfaa3865e/src/main/java/org/asamk/signal/commands/SendCommand.java#L49-L53

This check happens before anything else when processing the `send` command, and the check for whether it's a group message is at the very end of that section.

The part of the code that checks for phone number and group at the same time happens elsewhere, so it's unrelated.
