### ISSUE TITLE
[Request] add instructions on how to install to system directory

### ISSUE THREAD

**Issue by kb100** [AsamK/signal-cli#18]
Hi AsamK,

I'm writing https://github.com/kb100/signal-authenticator and since the first step of my project is to install yours, I would like to streamline the process as much as possible. Could you add instructions on how to install signal-cli to, e.g., /usr/local/bin in your README?

**Comment by Trolldemorted** [comment]
i extracted signal signal-cli to /usr/local/bin and added a simple bash file to pass the arguments:
```
#!/bin/bash

/usr/local/bin/signal-cli-0.4.0/bin/signal-cli "$@"
```

and i added an alias to my bashrc:
```
alias signal-cli='signal-cli -u +49XXXXXX'
```
so i dont have to type my own number over and over again.
