### ISSUE TITLE
singal-cli link output not recognized by android signal app (4.31.6)

### ISSUE THREAD

**Issue by hokreb** [AsamK/signal-cli#182]
I tried to link the signal-cli to an existing signal android app. I use qrencode on a armbian deivce to encode the "tsdevice:/?uuid=...&pub_key..." as an qr code, but the signal app does not recognize it as an device. 
I use the signal-cli-0.6.2.tar.gz found at the github repo. 

Is the link command supposed to work?

**Comment by AsamK** [comment]
yes, the link command should work.
Can you check with another qr scanner app, if the content of the qr code matches the "tsdevice:/..." link from signal-cli.

**Comment by hokreb** [comment]
oh, a noob error :-(. You are right, the encoded string was not the completed link, it was shortend. With the correct setting for the qr encoding now everything works. Thank you very much for the help!
