### ISSUE TITLE
Export every registered user as dbus object

### ISSUE THREAD

**Issue by terenc3** [AsamK/signal-cli#183]
Instead of running multiple daemons for multiple users like implied with [signal-cli@.service](https://github.com/AsamK/signal-cli/blob/master/data/signal-cli%40.service) it could be better to run one daemon and export ever user as object so that we can call.

```
dbus-send --session --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal/<user number> org.asamk.Signal.sendMessage string:MessageText array:string: string:RECIPIENT
```

**Comment by AsamK** [comment]
This is now implemented in ca86c421ebb1a3930fa309a2d95a4090108c2e62
