### ISSUE TITLE
race condition safety

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#19]
can i use multiple instances of signal-cli in parallel without corrupting (or partially reverting) the local storage?

at the moment i am forking signal-cli via cron, and i wonder what happens if two instances want to write e.g. a new known key to disk at the same time.

**Comment by AsamK** [comment]
No, running two instances in parallel is not safe and might completely corrupt the data file. You would have to build your own locking scheme to make that safe. Maybe I'll add that to signal-cli directly at some point.
I'm planning on improving the daemon mode to make it race free, so messages can be sent and received via dbus without problems.

**Comment by Trolldemorted** [comment]
i assumed that when i was browsing through your sourcecode... wouldn't [putting a FileChannel lock around everything](http://stackoverflow.com/a/128168) suffice?

for easy integration into e.g. nagios this would be simpler than having to deal with dbus ;)

**Comment by AsamK** [comment]
Nice, the FileChannel lock looks like a good solution.
