### ISSUE TITLE
"Linking Device Failed"

### ISSUE THREAD

**Issue by ventz** [AsamK/signal-cli#190]
Hi,

Coming from the scli project -- linking is the first part in order to "link" against an existing mobile device.

Using: `Version 0.6.2`

Followed steps to getting the `tsdevice:/?uuid=...&pub_key=...`
```
signal-cli link
```

Then, creating the QR code:
```
qrencode '$output-from-link' -o qrcode.png
```

When I scan the qr code on my phone with Signal, getting:

```
Linking Device Failed
Request failed: not found (404)
```

Verified that I can link a chrome extension. Asked a few co-workers to try this -- they are running into the same problem.

**Comment by ventz** [comment]
Discovered the answer myself - it looks like when you run the `link`, and get the tsdevice output, after copying it, you can't "end" the command to run the qrcode in the same terminal -- that is, you need to leave it backgrounded (or running in another window) -- so that you can have it "receive" the link request. This was what was causing the problem.

**Comment by bonnebulle** [comment]
Not working... thanks for the clue
my situation :
https://github.com/AsamK/signal-cli/issues/1276#issuecomment-2827042502
