### ISSUE TITLE
dbus send attachment

### ISSUE THREAD

**Issue by bsddemon** [AsamK/signal-cli#192]
I am able to send messages using the code below.
# echo "Hello World" | ./std-in-to-user.py
from pydbus import SystemBus
import sys
data = sys.stdin.read()
bus = SystemBus()
signal = bus.get('org.asamk.Signal')
signal.sendMessage(data, [], ['+xxxxxxx'])

But how can I sent attachments using dbus?

**Comment by OlivierNeyret** [comment]
Use the second argument of signal.sendMessage, it expects a list of filenames.
For example: 
```
signal.sendMessage(data, ['/home/user/picture.jpg'], ['+xxxxx'])
```

**Comment by bsddemon** [comment]
Great. Thanks.
