### ISSUE TITLE
How to use staging server?

### ISSUE THREAD

**Issue by abeluck** [AsamK/signal-cli#193]
I want to use the whisphersys staging server, because I'm developing a Signal-related tool.

I can't find an option in signal-cli to change the server. Is this possible?

The staging endpoint is `https://textsecure-service-staging.whispersystems.org/v1`

**Comment by cyphar** [comment]
There isn't an option for it, but you could probably change [this file](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/manager/BaseConfig.java) to use the staging server URL.
