### ISSUE TITLE
Cannot link device. tsdevice:// not generated...

### ISSUE THREAD

**Issue by Vic3198** [AsamK/signal-cli#197]
Hi everyone,
I have a problem linking a device. I recently made a simple script to auto-install signal-cli and the dbus service. I used it dozens of times to install signal-cli on several Raspberry Pis and it used to work very well, until tonight.
I wanted to install signal-cli on a fresh install of Raspbian on a Raspberry Pi, but it hangs at linking the device. In fact, the command `signal-cli --config /var/lib/signal-cli link -n "MyDevice"` doesn't output anything... It just hangs, it does not release the terminal. I waited more than 3min but nothing.
Is there something I am doing wrong?

Thanks,
Vic

**Comment by Trolldemorted** [comment]
Could it be that your system's entropy is low, and reads from /dev/random are blocking?

**Comment by Vic3198** [comment]
It was this indeed. I just checked (after many attempts of `signal-cli --config /var/lib/signal-cli link -n "MyDevice"`) and it was at 11...
I can't understand why as it was a fresh install of Raspbian, I just booted, ran `apt-get update`, `apt-get upgrade`, `apt-get install openjdk-8-jre`

So I just made another fresh install, but didn't run `apt-get upgrade` before installing Java and then Signal... This time it worked...

Thanks a lot!

(And sorry for not having searched enough, issue #144 already referenced this problem...)
