### ISSUE TITLE
Registering a user de-registered my other clients

### ISSUE THREAD

**Issue by matthew-piziak** [AsamK/signal-cli#198]
It caused my secret numbers to change when I re-registered them. Is that normal?

**Comment by AsamK** [comment]
There can only be one main client registered at the same time for a given number. If you want to use multiple clients, you can link up to 2 clients to your main client (with `link` or `addDevice` commands in signal-cli)

If the secret numbers change after re-registering depends on the client implementation, signal-cli should reuse the old secrets it used for the first registration.

**Comment by matthew-piziak** [comment]
Perfect, thank you so much!
