### ISSUE TITLE
Add signal-cli as a secondary device

### ISSUE THREAD

**Issue by david4096** [AsamK/signal-cli#199]
The readme describes how to add signal-cli as the primary device. This deregisters your phone. Is there a way to register signal-cli as a secondary device?

**Comment by asafonov** [comment]
You can use
`signal-cli link`
https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)

to generate a qrcode as you would do on signal-desktop, you may use something like that

```
signal-cli link -n `hostname` > /tmp/signal.txt&
sleep 5
qrencode -t ANSI `cat /tmp/signal.txt`
```

**Comment by oren** [comment]
I also noticed that my phone got unregisterd.
1. What does primary actually means?
1. How to ensure I can use both my phone and the CLI without unregistering my phone?
1. Do I also need to install the desktop app for achieving that?
1. I am newb. Can someone give me a step by step instructions for connecting both my phone and my CLI?

Thanks!

**Comment by rdtech2020** [comment]
how to get linked device information
I tried with below command but I got only one primary device information.

`signal-cli -u USERNAME listDevices`

but I need all link device which i linked by qr code

could you help me. @AsamK Boss
