### ISSUE TITLE
support custom dbus configuration paths

### ISSUE THREAD

**Issue by aguestuser** [AsamK/signal-cli#200]
I intend to open a PR to resolve this issue. The purpose of this issue is to check in with @AsamK to make sure the PR would be welcome and to check to see if there are any misplaced assumptions in my design thinking...

________________

## Motivation / Use Case

- a signal-cli user (for example [this project](https://github.com/team-friendo/signalboost)) would like to be able to run multiple instances of a signal-cli daemon, each of which runs on a different phone number
- right now it is impossible for both daemons to run on the same (non-isolated) system because of contention over the dbus interface namespace (ie: they both want the path `org.asamk.signal` and both may not have it)

## Proposed fix

- add a `--dbus-objectpath` and `--dubus-busname` argument to the `parseArgs` namespace and parse dbus config objectpath and busname from them in `Main.parseArgs`
- in `Main.handleCommands` and `DaemonComand.handleCommand`, replace the lookup for static values of  `DbusConfig.SIGNAL_OBJECTPATH` and `DbusConfig.SIGNAL_BUSNAME` with attempts to read these values from `namespace`. If not such values are found, fall back to the static values provided by `DbusConfig`

_____

Note: here is where and how I would propose making the above changes:
https://github.com/team-friendo/signal-cli/commit/0375aedd05a426f116b144e9f3edfe936ab55873

**Comment by justa9** [comment]
Is there any progress on this feature request, or any sample implementation? 

Thank you.

**Comment by AsamK** [comment]
I've implemented an alternative way to deal with multiple users: ca86c421ebb1a3930fa309a2d95a4090108c2e62
The `daemon` command can now be used without `-u +XXXXX` flag, in which case it will export all users in the data directory as separate dbus objects, instead of `/org/asamk/Signal` it will be exported as `/org/asamk/Signal/_XXXXX` for example.
