### ISSUE TITLE
Cannot register Android phone : Getting Request verify error: Bad response: 402 Payment Required

### ISSUE THREAD

**Issue by Taisgeal** [AsamK/signal-cli#201]
Hello,

I have downloaded and untarred signal-0.6.2 to /usr/local/bin/ on Debian 8.11 as per the instructions. I have also installed haveged and my java version is 1.7.0_201.  
My server is based in the UK, so is the Android phone I am trying to register and (not that it matters for my current purposes) so am I.

However, when i try to register my phone, I get this :

./signal-cli -u +44123456789 register
Request verify error: Bad response: 402 Payment Required

I have searched for this issue and can't find any reference to it. 

Please let me know what other information I need to provide and any and all help greatly appreciated. For reference, I am trying to use signal-cli on my xymon server so that I can get admin alerts on my smartphone.

Thank you.

Kind Regards.

**Comment by takemeonatour** [comment]
I am also having this issue no matter where I register the number

**Comment by dumar** [comment]
same problem here

**Comment by dumar** [comment]
It happened to me as well when I tried to register number from server with IP address from other country than the mobile phone number.

**Comment by dumar** [comment]
It happened to me as well when I tried to register from server with IP address pointing to different country than used mobile phone number.

**Comment by elegomf** [comment]
Same situation

**Comment by dumar** [comment]
I had the same issue when I requested registration using IP from different country than mobile phone. It worked when registered from same.

**Comment by Taisgeal** [comment]
I requested registration using an IP address  in the same country as the mobile phone. It didn't work. 
I then tried with an IP address from a different country and it didn't work.
In both cases, I got the same error:
Request verify error: Bad response: 402 Payment Required

**Comment by solariz** [comment]
Same Same...

```
signal-cli -u +3464450XXXXX register
Request verify error: Bad response: 402 Payment Required
```

**Comment by BedoM** [comment]
Same Same can i fix it ?

**Comment by BedoM** [comment]
> 
> 
> I had the same issue when I requested registration using IP from different country than mobile phone. It worked when registered from same.

I live in french and my server is in french but i have the same problem Request verify error: Bad response: 402 Payment Required

**Comment by BedoM** [comment]
Do you have one solution ?

**Comment by Trolldemorted** [comment]
Can you register with that number on the official signal clients?

**Comment by BedoM** [comment]
Yes I have tested and not work.

**Comment by BedoM** [comment]
> Can you register with that number on the official signal clients?

Yes ... but not with signal-cli...

**Comment by AsamK** [comment]
fixed in recent signal-cli versions, that support captchas for registration if required.
