### ISSUE TITLE
signal-cli stops sending message and no error

### ISSUE THREAD

**Issue by jmgurney** [AsamK/signal-cli#202]
Today, I noticed that I was suppose to have received a message that my computer sent to me.  I attempted to run signal-cli to send a message:
echo foobar | signal-cli -u +1<sending> send +1<dest>

and there was no error, no console messages to explain that it didn't send, yet I never received the message.

It appears that because I send messages frequently, but don't receive them, that the sender exhausted the keys used to send messages and started refusing to send messages.  After I did a signal-cli -u +1<sending> receive and got a bunch of messages, then sending started working again.

What is worse is that the messages that failed to send were not queued up either (I don't run daemon mode), so at a minimum, the send command HAS to exit with an error if the message is not sent.

Steps to reproduce: only send messages and not check to see if any are received, and see that it will "successfully" send messages but actually ends up black holing those messages.

**Comment by AsamK** [comment]
I've added a note to the man page that the `receive` command needs to be executed regularly.
