### ISSUE TITLE
Fast message send with RasPi (daemon)

### ISSUE THREAD

**Issue by suppenfritz** [AsamK/signal-cli#205]
Hy,

First, it's possible to send a message from a RasPi shortly also compareable eg.: Smartphone to Smartphone in few seconds?

I read, in wiki and INet, when i use "daemon (+dbus)", it's possible but i can't run or installed successfully on it?

Mybe can you help me, we i correctly intalled, by step for step, the signal-cli daemon on RasPi with link to Smartphone(Master)?

My constallation:
SmartPhone: Signal Master
PC-Desktop: Link => Master
RasPi: Link => Master

WebServer(HP) => called by URL RasPi-WebServer(PHP->ShellExec->signal-cli-->send message) it work's, but the sending time is over 2min!

eg.: user forget password and WebServer send new password over RasPi to Signal-User ...

So if it possible to send important messages shortly by use daemon or?

If, can you post here any solution, we i correctly installed signal-cli (daemon?)!

GTHX, suppenfritz!

**Comment by skulumani** [comment]
Hello, I use Signal on a raspberry pi. I also utilize the dbus method to speed up the processing of the Jave virtual environment.

* I use this [script](https://github.com/skulumani/signal-cli/blob/master/setup_signal.sh) to setup Signal. It basically just installs the dependencies, downloads the release version, then copies the daemon files and restarts
* Once that's setup and you've created a config (linked your CLI app to registered it) you can use [these](https://github.com/skulumani/signal-cli/blob/master/bash_signal.sh) bash functions to send/receive using dbus

Again these are just copied from the documentation here
