### ISSUE TITLE
Receive message doesn't publish to DBus

### ISSUE THREAD

**Issue by earksiinni** [AsamK/signal-cli#207]
I'm running signal-cli as a daemon and it doesn't appear to be publishing messages to DBus when I receive a message on Signal. The [example Python script in the wiki](https://github.com/AsamK/signal-cli/wiki/DBus-service#receive-messages-from-signal-cli-daemon) just sits in a loop and doesn't display anything. Running `dbus-monitor` doesn't show any DBus signals received when I receive a new message.

**Comment by earksiinni** [comment]
Looks like the problem is here: https://github.com/AsamK/signal-cli/blob/7e897fa6d0aaa87646b51efa3ee1a5ecfaa3865e/src/main/java/org/asamk/signal/JsonDbusReceiveMessageHandler.java#L35

The code expects a `SignalServiceDataMessage`, whereas in my testing I'm receiving instances of the type `SignalServiceSyncMessage`. I'm not familiar with the Signal's protocol's architecture; have "data messages" been replaced with "sync messages"? I looked upstream at [libsignal-service-java](https://github.com/signalapp/libsignal-service-java) and noticed that sync signals seem to be under the "multidevice" directory.

**Comment by nunocastromartins** [comment]
I can confirm the same behaviour. @earksiinni, is your `signal-cli` linked to a different device, or is it registered as the main device?

In my case I've linked `signal-cli` to my phone (the phone being the main device), and I confirm the behaviour you've described: received messages are not transmitted to the DBus (even though they appear in the daemon output).

I haven't tested registering `signal-cli` as the main device, but I believe that might be the root cause of the issue.

**Comment by earksiinni** [comment]
@nunocastromartins, just seeing your message. Unfortunately, this issue was a dealbreaker for me and I haven't used `signal-cli` for months. I will try to take a look again if I have more time.

That said, if your hypothesis is correct, that would be very strange indeed. I would assume that the phone is the main device for 99% of people using Signal, it would be odd if this use case weren't supported by default. I still wonder whether there was a protocol change that may have resulted in this breakage.

**Comment by AsamK** [comment]
There's now a SyncMessageReceived signal, where received sync messages are published, see #289.

**Comment by beimoe** [comment]
I updated from 0.11.2 to 0.12.0 and I now do not get dbus messages for received messages.
I am using ARMv7 (raspberry pi) libsignal_jni.so-v0.31.0-armv7-unknown-linux-gnueabihf.tar.gz (before it was 0.18.0)

Earlier it showed:
2023-08-26T09:00:11.594+0200 [receive-0] DEBUG org.asamk.Signal$MessageReceivedV2 - Creating message with serial 122
2023-08-26T09:00:11.594+0200 [DBus Sender Thread-1] DEBUG org.asamk.Signal$MessageReceived - Appending sig: xsaysas data: [1693033210498, +49xxxxxx, [], /, []]
2023-08-26T09:00:11.595+0200 [DBus Sender Thread-1] DEBUG o.f.d.s.m.OutputStreamMessageWriter - <= MessageReceived(0,122) { Path=>/org/asamk/Signal/_49yyyyyyyy, Interface=>org.asamk.Signal, Member=>MessageReceived, Signature=>xsaysas } { 1693033210498, +49xxxxxxx, [], /, [] }


Now the [DBus Sender Thread-1] entries are missing. Nothing on dbus on a receieved message. The rest looks the same. Any suggestions?
