### ISSUE TITLE
Possible to rebase to javascript?

### ISSUE THREAD

**Issue by h3artbl33d** [AsamK/signal-cli#208]
**Introduction**

As an OpenBSD user, it took some time to resolve dependency issues that are required by `signal-cli`. The main hassle came from libmatthew, [that I'd eventually got running by porting it over](https://h3artbl33d.nl/communication/2019/05/20/signal-openbsd/).

I am very grateful to @AsamK for creating `signal-cli` in the first place. It gave "us" OpenBSD users a way to use Signal on our boxes. Electron is not supported on OpenBSD (neither on FreeBSD - though there has been some progress on the latter one) - which I don't consider to be undesirable from a security viewpoint.

**Question**

As mentioned before, I am very grateful to @AsamK for creating `signal-cli`. This is in no way a demand, claim or whatever. Just a question with an elaborate logic behind it.

It seems that the [javascript version of libsignal](https://github.com/signalapp/libsignal-protocol-javascript) got more mature over the past months and perhaps years. 

Would it be feasible and logic to rebase from the java library to the javascript library? 

I'd like to think that this would take away some complexity and perhaps even the requirement for a `dbus`-alike setup. Java has had major security vulnerabilities in the end and available runtime environments differ greatly per OS.

**I am not a javascript developer, nor do I have experience with nodejs - so please forgive any stupidity and/or outrageous thoughts.**

**Comment by AsamK** [comment]
nice work, porting to OpenBSD!

Unfortunately Java and Javascript are quite different languages, despite the similar name (which was just due to marketing...)
Implementing signal-cli on top of the java script is probably possible but would be a complete reimplementation. The existing java code couldn't be reused, it could just be used for inspiration.
