### ISSUE TITLE
Bad response: 402 Payment Required

### ISSUE THREAD

**Issue by BedoM** [AsamK/signal-cli#209]
Hello i have this error for my mobile phone and land line number.

signal-cli -u +336xxxxxxxx register
signal-cli -u +336xxxxxxxx register --voice

my server is in Paris and i living on France

**Comment by BedoM** [comment]
I want help but I'm  lost in the code :

**Comment by BedoM** [comment]
I post an issue on the original API

**Comment by BedoM** [comment]
https://github.com/signalapp/libsignal-service-java/issues/74

**Comment by AsamK** [comment]
duplicate of #201
