### ISSUE TITLE
Control raspberry pi with signal-cli

### ISSUE THREAD

**Issue by hollysheep** [AsamK/signal-cli#216]
Can i control my raspberry pi with signal-cli running in background and waiting for incoming message? I can do this using telegram-cli where every incoming message can be using to run a command depending on the user or the content. Telegram-cli used lua for this feature. But telegram works very slow.

**Comment by Tilendor** [comment]
You can use the DBus interface exposed by Signal Cli to respond to commands using anything that can use DBus.

See https://github.com/Tilendor/SignalCommunityManager for an example of a chat bot using python.

**Comment by hollysheep** [comment]
I tried to follow the "howto" but i failed after installing several python modules. There was some error messages that i couldn't fix.

Is there no way to realize that without any additional software just using signal-cli? i could not find anything how to use that dbus thing. all i want is to send messages from my signal client on my smartphone to myself. i've realized that with telegram cli, here the message is sent to a simple shell script and that script starts several commands depending on the text. This is what i want to do do with signal cli.

**Comment by daniel-sch** [comment]
You can find a very simple example [here](https://github.com/mh-g/python-signal-cli), does this help to solve your problem?

**Comment by hollysheep** [comment]
Sorry, i understand nothing. this is only a python script. There is no howto to install or use it. I followed the link to install the dbis service. and now? i have copied the files and started the service. What to do now? I don't want to send messages from signal i want thats its running in background and waints for INCOMING messages and then do something depending on the message.

The easiest way for me is to send this message to a shell script, because i'm not a python programer.

**Comment by florianrusch** [comment]
@hollysheep dbus is like a message queue, where you can subscript to some kind of topic to listen on new messages. signal-cli has an interface which sends incoming messages to dbus.

you can write a program (in every language you like) to listen on the topic. a example implementation can you find at this page for python: https://github.com/AsamK/signal-cli/wiki/DBus-service#receive-messages-from-signal-cli-daemon

If you like to implement that stuff in shell, then this page could be good for you: https://unix.stackexchange.com/questions/80143/how-to-create-a-daemon-which-would-be-listening-to-dbus-and-fire-script-on-messa

There is no clearly described how to for each single use case...but you can adopt from the examples.
