### ISSUE TITLE
Use signal-cli on 2 devices

### ISSUE THREAD

**Issue by mooooonbaby** [AsamK/signal-cli#217]
I want to use signal-cli on my desktop with ubuntu and my raspberry pi using raspbian. at the moment it works on the desktop. I've tried linking to another device (https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning), but i don't understand what to do exactly. on which device do i need to run this commands? is the link something like a verification code that i create on one device and copy it to the other? i tried this (creating the code on the pi and running the second command on ubuntu - no luck).

**Comment by AsamK** [comment]
yeah, that's how it should work. If your desktop is already registered, that's your master device.
Run the `link` command on the raspberrypi to get the `tsdevice://` link.
Then use that with the `addDevice` command on your desktop. Make sure to put the link in quotation marks (`"`) and that there is no white space around the link

**Comment by hollysheep** [comment]
I creates the link in my desktop and then run the second on the pi. I will try it again.

**Comment by mooooonbaby** [comment]
Was is the difference between the master device and the other? Lets say the raspi is the master and i have linked the desktop to it. When i turn off the raspi and use it never again. What will happen then?

**Comment by AsamK** [comment]
the signal-cli on the desktop will continue to work, the master and secondary devices are independent in that regard.
But additional signal instances can only be linked with the master instance.
