### ISSUE TITLE
Send Message with line break ?

### ISSUE THREAD

**Issue by suppenfritz** [AsamK/signal-cli#220]
Hy,

It's possible to send a message with line break on cli respectively from script(bash,pyhton) and with smiley's ?

e.g.: signal-cli -u USERNAME send -m "This is a message \n new row \n new row :wink: (wink- smiley's)" RECIPIENT

if so, how should the input be made?

GTHX & gz!

**Comment by AsamK** [comment]
yep, it's possible. See this issue: #105
For smileys you can just copy paste the unicode emojis (e.g. from https://emojipedia.org/)
