### ISSUE TITLE
How to confirm message was sent

### ISSUE THREAD

**Issue by ra-rock** [AsamK/signal-cli#221]
Hi, 

Because I'm unable to use any dbus javascript libraries to interface with signal-cli in dbus mode, I'm going to try to wrapping `signal-cli --dbus` calls in javascript, and listen to `signal-cli daemon` stdout to try to listen to messages (I don't know how else to listen to dbus signals without library support....). 

My question is, how can I confirm messages I send via `signal-cli --dbus send` are successful? Do all failures throw an exception?

Thanks!

**Comment by AsamK** [comment]
yeah, if the send command doesn't throw an exception, the message was transferred successfully to the signal servers.

**Comment by ra-rock** [comment]
thanks!
