### ISSUE TITLE
Request documentation change

### ISSUE THREAD

**Issue by charlierlee** [AsamK/signal-cli#222]
Request documentation change:
https://github.com/AsamK/signal-cli/wiki/Manage-trusted-keys

change from:
signal-cli -u USERNAME trust -v FINGER_PRINT NUMBER
to:
signal-cli -u USERNAME trust -v SAFETEY_NUMBER NUMBER

**Comment by AsamK** [comment]
fixed, thanks.
you can also fix the documentation yourself, everyone can edit the wiki.
