### ISSUE TITLE
Sending attachments works in one environment, but not in another

### ISSUE THREAD

**Issue by sunnysidevibes** [AsamK/signal-cli#233]
Hi! 

This one is tricky. Please bear with me as I try to explain the scenario.

I'm running the same code in my local environment (a debian based Mint linux distro) (let's call this device _LOCAL_) and also on an AWS EC2 Ubuntu instance (_REMOTE_). _LOCAL_ and _REMOTE_ are working as linked devices to a master mobile device (_MOBILE_). Let's call the shared number I'm using USER.

If I send an image IMAGE_A from _LOCAL_ to USER, the image is properly displayed on MOBILE (in the "Note to Self" conversation on the app). If I send an image IMAGE_B from _REMOTE_ it's not properly displayed. Instead it shows a "bin" icon, the filename and file size. My _MOBILE_ device is unable to open this file as an image in any way.

I'm using the following code:
```
signal-cli --dbus send USER -m "" -a ATTACHMENT
```

Of course, _LOCAL_ and _REMOTE_ are also receiving each other's attachments. 

The funny thing is, after receiving IMAGE_B from _REMOTE_, if I send it again from _LOCAL_, it will be correctly displayed on MOBILE.

This makes me believe there is a mime-type issue on _REMOTE_. Perhaps the environment is missing some packages?

When I inspect the image files on both _LOCAL_ and _REMOTE_ using the `file` command,  both environments show the same information.

Are you able to suggest any way for me to investigate the issue further? I'd like to inspect the actual mime-type used when sending the attachment through the libsignal-service-java.

**Comment by AsamK** [comment]
looks like the same issue as #109 
you probably need to install the `shared-mime-info` package.
signal-cli uses the `java.nio.file.Files.probeContentType` method to determine the mime type.

**Comment by sunnysidevibes** [comment]
I actually checked and the package is already installed in the remote environment (version 1.9-2).

**Comment by sunnysidevibes** [comment]
I confirmed `probeContentType` is returning null. I did some digging around and found the following resources:

Similar Issue in production servers: https://stackoverflow.com/questions/19711956/alternative-to-files-probecontenttype
List of solutions: https://stackoverflow.com/questions/51994837/find-out-mime-type-of-compressed-files-downloaded-from-s3-for-java

According to the first source there are different implementations of the method in different environments, and alludes to the method not working because some implementations only look at the file extension. In the second link the post attempts to address the issue and actually says that when the file has no file extension (our use case) the method should always work. Obviously I found this is not the case.

Given that over in #109 there are two other people who also weren't able to solve the issue with installing `shared-mime-info` I'm wondering which other solution you would be willing to entertain. And I'd be happy to try and implement it.

**Comment by sunnysidevibes** [comment]
Quick update: 

(1) It wouldn't necessarily be easier to save attachments with a file extension because we'd have to accomplish something similar: finding a file extension from the mime type. This is not trivial. A few sources say Apache Tika is the best library to accomplish this, but if we were adding that as a dependency, we might as well just solve the original issue (finding mime type without extension reliably in all environments) with the library.

(2) I've gone ahead and replaced `createAttachment` in `Utils` to use `URLConnection.guessContentTypeFromInputStream`. It's not a perfect solution and only supports a handful of mime types (doesn't support application/pdf for example). However, in my specific use case, where I mostly work with images, it will do.

My temporary solution:
```
    static SignalServiceAttachmentStream createAttachment(File attachmentFile) throws IOException {
        InputStream bufferedStream = new BufferedInputStream(new FileInputStream(attachmentFile));
        String mime = URLConnection.guessContentTypeFromStream(bufferedStream);
        if (mime == null) {
            mime = "application/octet-stream";
        }
        bufferedStream.close();

        InputStream attachmentStream = new FileInputStream(attachmentFile);
        final long attachmentSize = attachmentFile.length();
        // TODO mabybe add a parameter to set the voiceNote, preview, width, height and caption option
        Optional<byte[]> preview = Optional.absent();
        Optional<String> caption = Optional.absent();
        Optional<String> blurHash = Optional.absent();
        return new SignalServiceAttachmentStream(attachmentStream, mime, attachmentSize, Optional.of(attachmentFile.getName()), false, preview, 0, 0, caption, blurHash, null);
    }
```

**Comment by Worren** [comment]
Thank you very much! With your change I can send images again from my system.

One Addition: You need to add the libraries to the Utils.java:
```
import java.net.URL;
import java.net.URLConnection;
import java.io.BufferedInputStream;
```
