### ISSUE TITLE
Unable to find acceptable protocols

### ISSUE THREAD

**Issue by Lilooman** [AsamK/signal-cli#234]
Hello,
I'm pretty new to signal and GitHub so I might write senseless sentences (I mean I don't understand properly how everything works).

As you have seen in the title I'm facing this issue after using signal-cli -u +33111111111 register :  
`Request verify error: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, TLS_AES_128_CCM_SHA256, TLS_AES_256_CCM_8_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256], tlsVersions=[TLS_1_3, TLS_1_2], supportsTlsExtensions=true)], supported protocols=[TLSv1.2]`

I'm currently using this java version : 
```
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.12.04.3)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
```
I'm not sure it is entirely / partially **signal-cli** related but if you have any ideas on how to fix this issue I'd be glad to hear them.

**Comment by Lilooman** [comment]
After hours of web browsing and tests, I started losing hope. I tried to go back to the 0.6.2 thinking it wouldn't change anything... but now it works lol.
I haven't this issue with the 0.6.2 version.

**Comment by Trolldemorted** [comment]
It could be signal-cli requires java 1.8 now: https://github.com/AsamK/signal-cli/commit/9aa13e92fed26cb2cc5c90045becac9e1502b36c
