### ISSUE TITLE
Read Receipt not identifiable in Json-Output

### ISSUE THREAD

**Issue by n0emis** [AsamK/signal-cli#235]
When receiving receipts in cleartext-mode the cli shows:
```
Envelope from: “n0emis test” +49******** (device: 1)
Timestamp: 1572608417622 (2019-11-01T11:40:17.622Z)
Got receipt.
```
And a read-receipt is formatted as follows:
```
Envelope from: “n0emis test”  +49******** (device: 1)
Timestamp: 1572608435739 (2019-11-01T11:40:35.739Z)
Received a receipt message
 - When: 1572608435739 (2019-11-01T11:40:35.739Z)
 - Is read receipt
 - Timestamps:
    1572608417622 (2019-11-01T11:40:17.622Z)
```

When using the JSON-Output the two messages get display as following:
```
{"envelope":{"source":" +49********","sourceDevice":1,"relay":null,"timestamp":1572608417622,"isReceipt":true,"dataMessage":null,"syncMessage":null,"callMessage":null}}
{"envelope":{"source":" +49********","sourceDevice":1,"relay":null,"timestamp":1572608435739,"isReceipt":false,"dataMessage":null,"syncMessage":null,"callMessage":null}}
```
Both messeages can't be related to a message with this output and the read-receipt isn't even marked as `isReceipt`.

**Comment by AsamK** [comment]
the first receipt message (delivery receipt) can be mapped to the corresponding message by its timestamp, which is the same as the timestamp of the original message.
(the message timestamps are used as message identifiers by signal)

json output for read receipts is already implemented in the master branch: 7e267f1ebb17dd8e6b9ea007c2d65305fea0fb05
will be part of the next release.
