### ISSUE TITLE
Support sealed sender messages

### ISSUE THREAD

**Issue by xoxovm** [AsamK/signal-cli#239]
Hi,

with the version signal-cli 0.6.4 I get the following error message.

signal-cli -u + 49xxxxxxxxxx receive
Envelope from: (device: 0)
Timestamp: 1572726486758 (2019-11-02T20: 28: 06.758Z)
Sent by unidentified / sealed sender
Unknown message received

System: Arch Linux Linux 5.3.8-arch1-1

What is the problem here?

thanks

**Comment by AsamK** [comment]
Looks like you managed to get a message from an unidentified sender. signal-cli doesn't support those completely yet. They should also be opt-in, so not sure how you got one.
Supporting them completely is on my TODO list.

**Comment by xoxovm** [comment]
Everything works fine with version 0.6.3. As soon as an update to version 0.6.4 (pacman -u) is done, this error message appears.

**Comment by xoxovm** [comment]
They are both numbers register, and still I get this error message.

**Comment by kpcyrd** [comment]
I don't think this is Arch Linux specific, any way the title can be changed to "Sealed sender support"?

I have the same issue, I'm currently stuck writing a chat bot because the sender info is unavailable, sealed senders are enabled by default in signal 2.45.2.0 with no way to disable them.

**Comment by kpcyrd** [comment]
I haven't tested this since I'm lacking a java development environment, but it seems instead of:
```
// envelope is SignalServiceEnvelope
envelope.getSourceAddress().getNumber()
```
you'd simply use:
```
// content is SignalServiceContent
content.getSender().getNumber()
```

**Comment by AsamK** [comment]
Version 0.6.5 now supports receiving sealed sender messages
