### ISSUE TITLE
support for sending files/locations

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#24]
It would be great if signal-cli was able to send files and locations like the android client!

Maybe you could put this on your long-time todo-list ;)

**Comment by AsamK** [comment]
Sending files, i.e. attachments, is already implemented. Sending works for all types of files, but the android client will only show attachements, that are videos, pictures or audio.

        signal-cli -u USERNAME send -m "test" -a ATTACHMENT_FILE

I've never used the location sending of the android client, which I think uses some google play APIs to generate an image of the current location. Not sure how useful it would be in signal-cli. Usually PCs don't know their own location, so the user would have to provide the latitude, longitude coordinates by hand.

**Comment by Trolldemorted** [comment]
oh, sorry i completed missed that you could use -a with messages too.

Providing lat/lng is exactly what i had in mind, since i'd like to send positions of pokemon-go's pokemon to a number of recipients. But with -a i can build a workaround, so you probably shouldn't bother about this. Maybe i'll do it within signal-cli and submit a pull request.

**Comment by AsamK** [comment]
I'm closing this, it's something that's easy enough to do outside of signal-cli.

**Comment by rdtech2020** [comment]
how to send only attachment 
I am trying below command but not working - 
signal-cli -u USER send -a xyz.pdf Receipent
could you help me

**Comment by AsamK** [comment]
Yeah the interface is not optional there, you need to specify an empty message, otherwise signal-cli will aren't too read the message from stdin.
`signal-cli -u USER send -m"" -a xyz.pdf Receipent`

**Comment by rdtech2020** [comment]
> Yeah the interface is not optional there, you need to specify an empty message, otherwise signal-cli will aren't too read the message from stdin. `signal-cli -u USER send -m"" -a xyz.pdf Receipent`

thanks boss
