### ISSUE TITLE
signal-cli script reports error, does not find java executable

### ISSUE THREAD

**Issue by brad2014** [AsamK/signal-cli#240]
When running signal-cli, the default java is no longer found (CentOS 7).
I'm running signal-cli release 0.6.4

## Error:
```
/usr/local/bin/signal-cli: line 188: /usr/lib/jvm/java-11-openjdk/bin/java: No such file or directory
```

In 0.6.3, JAVACMD defaults to `java` (signal-cli line 100).  In 0.6.4, it defaults to `/usr/lib/jvm/java-11-openjdk/bin/java`, which does not exist (the very next line tests for existance of java rather than JAVACMD).

## Workaround:
Explicitly set the JAVA_HOME that contains bin/java
```
% JAVA_HOME=/usr signal_cli ...
```

**Comment by AsamK** [comment]
Looks like this is caused by an issue with the arch linux gradle package: https://bugs.archlinux.org/task/64230?project=5&string=gradle
I'll build a new archive with a fixed starter script.

**Comment by AsamK** [comment]
Fixed: https://github.com/AsamK/signal-cli/releases/download/v0.6.4/signal-cli-0.6.4.tar.gz
