### ISSUE TITLE
Auto select `-u USERNAME` if only one user is registered

### ISSUE THREAD

**Issue by mueller-ma** [AsamK/signal-cli#241]
Is it possible to have signal-cli auto select the `-u USERNAME` parameter if only one number is registered?

Edit: I'm using signal-cli in a script, so my bashrc and possible alias aren't sourced.

**Comment by Joedang** [comment]
One reasonable workaround would be to make an alias. For example, `alias signal-cli="signal-cli -u USERNAME"` in your `.bashrc` file. (Though, building the suggested behavior into `signal-cli` still seems like a pretty sensible feature, IMO.)

**Comment by darkporpoise** [comment]
This would be useful. I have added an alias to save typing but with a different name (`signal`) so I can still run commands that don't take an user. Native support would be easier.

**Comment by tsunulukai** [comment]
@AsamK Alternatively, a default signal username and config path could be read from a default configuration file.
eg: `/etc/default/signal-cli`

The file layout could be as follows:
`# SIGNAL CLI CONFIGURATION`
`CONFIG=/usr/share/signal-cli/`
`USERNAME=+<phonenumber>`

Such a feature would make the use of signal-cli much easier to send notifications from unattended devices.

**Comment by AsamK** [comment]
This is now implemented in ca86c421ebb1a3930fa309a2d95a4090108c2e62
