### ISSUE TITLE
Messages received from DBUS with no source

### ISSUE THREAD

**Issue by riazm** [AsamK/signal-cli#245]
I have the following which I use to print out who has sent me a message

`def msgRcv (timestamp, source, groupID, message, attachments):

   contact = signal.getContactName(source)
   if (not contact):
      if (source):
         contact = source
      else:
         contact = "Unknown"`

But  I've started getting many messages coming in from "unknown" contacts with no source. 

Freshly updated my Ubuntu 18.04 and I have updated my signal-cli to 0.6.5 

Does anyone have any pointers as to what I should begin to look for to sort this? I've not yet tried re-linking mydevice (because I hate doing that) and also because my config file has the "unknown" users in there, with their phone numbers. It seems like the dbus message just doesn't contain any "source" information

GroupID and the message itself seems to work fine however.

**Comment by matthew-piziak** [comment]
Oh, thank goodness, I'm not the only one.

`signal-cli daemon` exhibits a number of behaviors (I use `--json`):
- sometimes `{"envelope": {"source": <is populated>}}` :+1: 
- sometimes the source is an empty string, but the next payload is a Receipt with at a populated source, which allows a client to reconstitute it. :anger: 
- sometimes the source is empty and there is no following receipt :fire:

If anyone has advice I'd love to hear it.

**Comment by matthew-piziak** [comment]
I have determined that:
- this sources have started going missing even without `daemon`
- this can be reproduced on 0.6.5 and 0.6.3

Anyone know what's going on?

**Comment by matthew-piziak** [comment]
@AsamK Are you seeing this behavior on your own client? Has there been some upstream breaking behavior change from the Signal host?

**Comment by matthew-piziak** [comment]
@riazm Are you still seeing this behavior on your end?

**Comment by riazm** [comment]
Correct.
--
Riaz Moola

**Comment by matthew-piziak** [comment]
This issue persists, and makes `signal-cli` unusable for me. My running theory is that this is an upstream breaking change. I've opened a ticket with the Signal team last week but have received no response. Does anyone know how to get more support from them?

**Comment by Trolldemorted** [comment]
The official clients have begun to always send sealed sender messages, I guess that's related.

**Comment by matthew-piziak** [comment]
Thank you @Trolldemorted! That definitely seems plausible. [Announcement](https://signal.org/blog/sealed-sender/) for reference.

if that's the case, @AsamK, how should we be handling this protocol change?

**Comment by matthew-piziak** [comment]
@riazm See https://github.com/AsamK/signal-cli/pull/243.

Can you still reproduce this on 0.6.5? After compiling that version I'm able to get senders again. Thank you @AsamK!

**Comment by AsamK** [comment]
closing as receiving sealed sender messages should work now.
