### ISSUE TITLE
Failure when sending a message with attachment

### ISSUE THREAD

**Issue by yoandyshyno** [AsamK/signal-cli#249]
Sending an receiving messages works.

signal-cli -u USERNAME send -m "This is a message with an image " RECIPIENT -a /home/user/boo.jpg

_when adding an attachment I receive the error below:_

Failed to send message: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

NOTE: I am behind a firewall.

**Comment by Trolldemorted** [comment]
Is your firewall intercepting TLS traffic with a self-signed cert?

**Comment by yoandyshyno** [comment]
indeed it was the firewall messing with the TLS traffic.
