### ISSUE TITLE
Error: Could not find or load main class org.asamk.signal.Main

### ISSUE THREAD

**Issue by the4ndy** [AsamK/signal-cli#25]
I set up a fresh install of Ubuntu 14.04, installed default-jre-headless on the machine and then installed the signal-cli per the instructions. however i get this error when running signal-cli

`Error: Could not find or load main class org.asamk.signal.Main`  
  
let me know how I can resolve this....I am guessing I am using the wrong jre for linux, but then again, i wish this cli didnt have to have java as a dependency and instead used something more common to servers like python or bash

**Comment by AsamK** [comment]
signal-cli should work with any jre 7 or 8, your issue looks like the start script doesn't find the java jar files. Does it work if you run `/opt/signal-cli-0.4.1/bin/signal-cli` directly?
Make sure `/opt/signal-cli-0.4.1/lib/` contains `signal-cli-0.4.1.jar` and other .jar files.

**Comment by AsamK** [comment]
I assume you were able to fix it, if not feel free to reopen.
