### ISSUE TITLE
org.whispersystems.signalservice.api.push.exceptions.CaptchaRequiredException when registering

### ISSUE THREAD

**Issue by tbsaunde** [AsamK/signal-cli#251]
when I run ./bin/signal-cli -u <my phone number> register, it fails with the message 'Rquest verify error: null'.  When I change Register.java to print the full exception I see that its of type org.whispersystems.signalservice.api.push.exceptions.CaptchaRequiredException.  Is the captcha requirement new? is this still supposed to work?

**Comment by hacktor** [comment]
You forgot the phone number to register:

signal-cli -u USERNAME register
where USERNAME is your phone number

**Comment by BedoM** [comment]
I have the same issue ...

**Comment by alexthefifth** [comment]
Having the same issue on a digitalocean server

root:~# signal-cli -u +1xxx.... register -v
Captcha required for verification (null)

signal-cli 0.6.6

**Comment by mskwarek** [comment]
The same issue still persits in 0.6.7 version:

```console
x@y:~$ signal-cli -u +4(...) register
Captcha required for verification (null)
x@y:~$ signal-cli -v
signal-cli 0.6.7
```

**Comment by BedoM** [comment]
same problem with 0.6.7

```
r@SRV-%%%:/opt# signal-cli -u +334(..)  register --voice
Captcha required for verification (null)
r@SRV-%%%/opt# signal-cli -v
signal-cli 0.6.7
```

**Comment by alexthefifth** [comment]
It seems some signal users are getting this but not all

https://www.reddit.com/r/privacytoolsIO/comments/fg3pkt/signal_private_messenger_is_using_google_recaptcha/

https://www.reddit.com/r/signal/comments/dmc9me/why_does_signal_block_users_with_a_google_captcha/


Note that a similar project to signal-cli, signald, seems to have recently implemented support for registration captchas so maybe there's things that can be learned from them: https://gitlab.com/thefinn93/signald/issues/8

**Comment by dinoqqq** [comment]
I had the same issue when connecting over a VPN IP address. Using an IP address other than my VPN just registered me immediately.
