### ISSUE TITLE
new iPad App can't be added as slave device

### ISSUE THREAD

**Issue by poggenpower** [AsamK/signal-cli#252]
There is now a iPad app (since begin of December), that supports signal like the desktop app, but if I try to link this app to my signal-cli user, I get an error message on the iPad that my signal version is outdated and doesn't support QR-Code scanning. Linking the recent Windows desktop version worked like a charm.  
signal-cli version 0.6.5

**Comment by AsamK** [comment]
should work with version 0.6.7, which uses a new libsignal-service version with the required support.
