### ISSUE TITLE
Cannot Resolve Session Bus Address

### ISSUE THREAD

**Issue by mi-gri** [AsamK/signal-cli#258]
I'm trying to run signal-cli v 0.6.5 on Ubuntu (from https://github.com/AsamK/signal-cli/releases) in daemon mode:

$ signal-cli  -u '+xxxxxxxxx' daemon
org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address
        at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:244)
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:50)
        at org.asamk.signal.Main.handleCommands(Main.java:126)
        at org.asamk.signal.Main.main(Main.java:61) 

dbus seems to be up and running:

$ (dbus-launch)
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-qzF6Pvv8bH,guid=b4486b04598e8fc9ce4ce7515e219aea
DBUS_SESSION_BUS_PID=26823

**Comment by djusHa** [comment]
possibly missing the Package "libunixsocket-java" ?

**Comment by mi-gri** [comment]
nope. 
$dpkg -l libunixsocket-java
[..]
ii  libunixsocket-java                 0.7.3-1ubuntu1         amd64                  Unix socket API and bindings for Java

**Comment by AsamK** [comment]
dbus-launch doesn't check if dbus is running, it starts a new dbus instance.
If your distribution uses systemd user sessions, you can check if dbus is running with `systemctl --user status dbus.service`

**Comment by elsehow** [comment]
I'm experiencing the same issue. I can see that dbus is running with `systemctl --user status dbus.service`, and also have libunixsocket-java. 

@AsamK Should we be stopping dbus to run signal-cli as a daemon?

**Comment by mi-gri** [comment]
@AsamK That is not the cause of the issue:

~$ systemctl --user status dbus.service
● dbus.service - D-Bus User Message Bus
   Loaded: loaded (/usr/lib/systemd/user/dbus.service; indirect; vendor preset: enabled)
   Active: active (running) since Sa 2020-05-16 12:12:02 CEST; 1 weeks 0 days ago
     Docs: man:dbus-daemon(1)
  Process: 24106 ExecReload=/usr/bin/dbus-send --print-reply --session --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig (code=
 Main PID: 22897 (dbus-daemon)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dbus.service
           └─22897 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation

**Comment by AsamK** [comment]
Then it looks like the dbus environment variable is not set up correctly.
You can check the output of `echo $DBUS_SESSION_BUS_ADDRESS`. On a default installation that should print `unix:path=/run/user/USERID/bus`.
The exact path can be seen in the dbus.socket unit: `systemctl --user status dbus.socket`

**Comment by elsehow** [comment]
Thanks for your help here, @AsamK. I can see my dbus session bus address:

```
➜  ~ systemctl --user status dbus.socket
 dbus.socket - D-Bus User Message Bus Socket
   Loaded: loaded (/usr/lib/systemd/user/dbus.socket; static; vendor preset: enabled)
   Active: active (running) since Sun 2020-05-24 10:26:20 PDT; 1min 3s ago
   Listen: /run/user/1000/bus (Stream)
  Process: 2002 ExecStartPost=/bin/systemctl --user set-environment DBUS_SESSION_BUS_ADD
   CGroup: /user.slice/user-1000.slice/user@1000.service/dbus.socket
```

I set `DBUS_SESSION_BUS_ADDRESS` to match:
```
➜  ~ DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus 
```

But I receive the same error:

```
➜  ~ signal-cli -u "[my username]" daemon
Exception in thread "main" java.lang.RuntimeException: Cannot Resolve Session Bus Address
	at org.freedesktop.dbus.connections.impl.DBusConnection.lambda$getConnection$1(DBusConnection.java:257)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:165)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:228)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:184)
	at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:51)
	at org.asamk.signal.Main.handleCommands(Main.java:181)
	at org.asamk.signal.Main.handleCommands(Main.java:132)
	at org.asamk.signal.Main.main(Main.java:64)
```

**Comment by AsamK** [comment]
you need to export the variable 
`export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus `
or set it on the same line
`DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus signal-cli -u "[my username]" daemon`

**Comment by elsehow** [comment]
This solved my problem. Thank you!
