### ISSUE TITLE
Cannot send attachment to multiple recipients

### ISSUE THREAD

**Issue by bbernhard** [AsamK/signal-cli#259]
Hi, 

first of all, thanks a lot for the great tool and the hard work you've put into maintaining the tool. That's very much appreciated! I've recently created a small REST API wrapper around your commandline tool [1] and added the signal integration to Home Assistant [2] - so your `signal-cli` commandline tool is now used by many Home Automation enthusiasts around the world. :)

[1] https://github.com/bbernhard/signal-cli-rest-api
[2] https://www.home-assistant.io/integrations/signal_messenger/

Unfortunately, there seems to be a problem with sending an attachment to multiple recipients (not sure if this is a regression in one of the latest signal-cli versions).

**When I invoke `signal-cli` like this, everything works:** 
```
./signal-cli --config /path/to/config/ -u +mynumber send -m "Hello World" "+recipient1" "+recipient2"
```
Both recipients get the text message. 

**This works also:** 
```
./signal-cli --config /path/to/config/ -u +mynumber send -m "Hello World" "+recipient1" -a "/path/to/image.png"
```

`recipient1` gets the text message and the image. 

**But this doesn't work:** 
```
./signal-cli --config /path/to/config/ -u +mynumber send -m "Hello World" "+recipient1" "+recipient2" -a "/path/to/image.png"
```

When executing the above command, I got the following error: 

```Failed to send message: java.net.ConnectException: Failed to connect to cdn.signal.org/2600:9000:20ac:a00:1d:4f32:50c0:93a1:443```

The one thing that looked a bit odd to me was, that `signal-cli` tried to reach the signal server via IPV6 (although IPV6 isn't configured in my network). I then remembered, that IPV6 is per default enabled on my Ubuntu machine. So I disabled it by adding: 

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

to `/etc/sysctl.d/99-sysctl.conf` followed by executing `sysctl -p`. 

After disabling IPV6 on my machine, I invoked `signal-cli` again, but got the following error this time: 

`Failed to send message: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR`

Do you have an idea what could be the error here?

Thanks,
Bernhard

**Comment by AsamK** [comment]
I don't know what causes the ipv6 issue, but I've fixed the second issue with the `stream was reset`.

It occurred because signal-cli tried to upload the attachment twice, but for the second upload, the file stream was already closed. Now it just uploads the attachment once and sends the same pointer to both recipients.

**Comment by bbernhard** [comment]
Just tried it and its working great! :tada: 

Many many thanks for the fast bugfix - very much appreciated! 

(I am using `signal-cli` now for almost a year in my Home Automation setup and it never let me down. Thanks a lot for creating & maintaining the tool over all the years!) 

Have a nice day,
Bernhard
