### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by xyz-nobody** [AsamK/signal-cli#261]
Good morning, sir,

I wanted to use signal-cli with Tails.

But I can't figure out how to configure the proxy?

With signal-desktop you can use : 

export WSS_PROXY=socks5://127.0.0.1:9150 
export HTTPS_PROXY=socks5://127.0.0.1:9150 
export ALL_PROXY=socks5://127.0.0.1:9150 

How to do with signal-cli?

**Comment by kpcyrd** [comment]
I don't think there's official support, you'd need to run it with torify.

**Comment by nullxyz07** [comment]
Nice idea but when i try i have this :

torify signal-cli -u +XXXXXXXXXX register --voice
1579680608 WARNING torsocks[9714]: [syscall] Unsupported syscall number 229. Denying the call (in tsocks_syscall() at syscall.c:605)
1579680609 PERROR torsocks[9714]: socks5 libc connect: Argument invalide (in socks5_connect() at socks5.c:202)
Request verify error: java.net.ConnectException: Failed to connect to textsecure-service.whispersystems.org/54.175.130.206:443



‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Atomic-Bean** [comment]
Looking at the code. Commands like `receive` call a bunch of stuff, but ultimately they make a `WebSocketConnection` object and then `connect()` it. This seems to be a custom object defined in the fork of "libsignal-service-java" over [here](https://github.com/Turasa/libsignal-service-java/blob/master/service/src/main/java/org/whispersystems/signalservice/internal/websocket/WebSocketConnection.java#L74).

However, I'm not that familiar with networking code so I'm not sure what it would take to enable proxy support, if this `WebSocketConnection` object can even allow that.

**Comment by AsamK** [comment]
#614 got it working with torsocks and `export JAVA_TOOL_OPTIONS="-Djava.net.preferIPv4Stack=true"`.
