### ISSUE TITLE
quitGroup does not work

### ISSUE THREAD

**Issue by timaschew** [AsamK/signal-cli#266]
```
Failed to send to group: Group not found: k++XXXF4CDM4cI6W/zOMza==
Aborting sending.
```

But the group is listed when I run `receive`:
```
Group info:
  Id: k++XXXF4CDM4cI6W/zOMza==
```

The group is not listed when running `listGroups`, but I can send messages to that group.

Another group is listed for `listGroups`. I've tried to quit that one and here is the output:

```
$ signal-cli -u +4915152518273 listGroups
Id: fLOCnc9AiVD/XXXg7h6GvC== Name: bot test  Active: false
$ signal-cli -u +4915152518273 quitGroup -g "fLOCnc9AiVD/XXXg7h6GvC=="
$ signal-cli -u +4915152518273 listGroups
Id: fLOCnc9AiVD/XXXg7h6GvC== Name: bot test  Active: false
$ signal-cli -u +4915152518273 quitGroup -g "fLOCnc9AiVD/XXXg7h6GvC=="
Failed to send to group: User is not a member in group: bot test (fLOCnc9AiVD/XXXg7h6GvC==)
Update the group on another device to read the user to this group.
Aborting sending.
$ signal-cli -u +4915152518273 listGroups
Id: fLOCnc9AiVD/XXXg7h6GvC== Name: bot test  Active: false
```

List group is still listing it even after I've quit the group. And if I look with my other account the user (via signal-cli) is still there.

**quitGroup** seems to be totally broken.

**Comment by Trolldemorted** [comment]
Is that a real group id? You should not disclose group ids!

**Comment by timaschew** [comment]
Okay, changed the ids.

**Comment by AsamK** [comment]
The quitGroup command doesn't remove the group, it just removes the user from the member list.
With `listGroups --detailed` command you can see the member list as well.

signal-cli can only quit a group, if it has the necessary group information, without that it wouldn't know to whom it needs to send the quit message. When it receives a group message from an unknown group it automatically sends a group information request to the sender, looks the like the sender didn't respond to that message here...
