### ISSUE TITLE
Cannot verify number due to PIN_CODE

### ISSUE THREAD

**Issue by oh4** [AsamK/signal-cli#268]
After installation, I registered a US number as follows:

`./signal-cli -u +15555556789 register`

I then received the verification code via SMS and proceeded to verify my number as follows:

`./signal-cli -u +15555556789 verify 123-456`

However, I get the following error:

> Verification failed! This number is locked with a pin. Hours remaining until reset: 153
> Use '--pin PIN_CODE' to specify the registration lock PIN

I then attempted to provide my pin as follows:

`./signal-cli -u +15555556789 verify 123-456 --pin 12345678`

...and also tried it this way per the positional arguments from the help output:

`./signal-cli -u +15555556789 verify -p 12345678 123-456`

However, I still get the same error message regardless:

> Verification failed! This number is locked with a pin. Hours remaining until reset: 153
> Use '--pin PIN_CODE' to specify the registration lock PIN

Am I doing something wrong here with the registration process? How should I proceed?

**Comment by AsamK** [comment]
Signal has implemented a new version of the pin lock functionality (called KBS).
signal-cli hasn't implemented support for this yet.

**Comment by oh4** [comment]
> Signal has implemented a new version of the pin lock functionality (called KBS).
> signal-cli hasn't implemented support for this yet.

Well, that explains it. Thanks a bunch for pointing that out :)

**Comment by habebit** [comment]
When is the new pin functionality supported in signal-cli?

**Comment by AsamK** [comment]
I had a look at it, but didn't get it to work yet. Here's the work in progress branch: https://github.com/AsamK/signal-cli/commits/wip/kbs-pin-lock

One issue is that it uses the argon2 hashing algorithm. The android app is using a java wrapper around the native library, but I'd prefer a pure java implementation for easier deployment. The only library I found is incomplete and not production ready ...

**Comment by aicherm** [comment]
Is there a workaround e.g. that lets me disable the pin lock and re-enable it later again?
Or any other way to register at the moment?
Thank you for your work!

**Comment by AsamK** [comment]
You could register with the Signal-Android app, disable pin lock and then register with signal-cli.
