### ISSUE TITLE
Unable to post messages in some groups (in Signal Desktop)

### ISSUE THREAD

**Issue by hjek** [AsamK/signal-cli#269]
Hiya,

When using **Signal Desktop**, I'm unable to post messages in certain groups. The issue has been discussed [here](https://github.com/signalapp/Signal-Desktop/issues/3921). The problem seems to be that a group has been "left" for some reason, even though the group is still present in the contact list and incoming messages can be read.

I do feel a bit silly for opening an issue here for a bug I encountered in **Signal Desktop** but a Signal developer indicated that this could potentially have something to do with `signal-cli`:

> Lastly, you should know that we don't test at all with signal-cli and it's likely the cause of this issue you've reported here. 

I don't really care who has "caused" the issue but it seems unlikely that this will be fixed in **Signal Desktop** so I might as well try here.

Is it possible to "un-leave" groups with `signal-cli`? Could `signal-cli` have possibly caused me to *partially leave* some groups?

**Comment by AsamK** [comment]
`signal-cli` currently doesn't set the `active` flag, so by default it's `false`.
I'll adapt the code to match the behavior expected by Signal Desktop here.

**Comment by hjek** [comment]
Thank you so much for fixing this!
