### ISSUE TITLE
support for disappearing messages

### ISSUE THREAD

**Issue by carnott-redhat** [AsamK/signal-cli#27]
currently when you enable disappearing messages signal-cli simply disables this feature. While this is much better than breaking outright (thanks a bunch for that, much appreciated), it would be nice if you could support using that the other end selects, or even allow setting of the disappear length.

**Comment by der-Daniel** [comment]
Can you please explain how to use this feature. It still seems to overwrite my settings on android.

For Frodo

**Comment by Trolldemorted** [comment]
do you have your client `receive` before you send a message after changing the setting on droid?
