### ISSUE TITLE
Question: What is the opposite of "trust -v"?

### ISSUE THREAD

**Issue by bubi1311** [AsamK/signal-cli#270]
Hi @AsamK,

first of all: Thank you for your great signal-cli!

I've a question: How do I untrust a user? What is the opposite of `signal-cli -u USERNAME trust -v SAFETEY_NUMBER NUMBER`?

The background is that one of my contacts has a new phone (same phone number, different hardware).
When I list the identities the specific contact is shown two times. One entry shows the old fingerprint and safety number and the other entry shows the new one. Both are `TRUSTED_VERIFIED`.

I'm using Version 0.6.5.

Thank you for your help!

PS: Sorry, I did not figure out how to flag it as a question.

**Comment by AsamK** [comment]
There's currently no command to untrust an identity.
I think the correct behavior would be to untrust all existing identities, when trusting a new identity key.
That's also the behavior of the android client.

**Comment by AsamK** [comment]
related: #112

**Comment by bubi1311** [comment]
Thank you! Then I'll untrust all existing identities.
