### ISSUE TITLE
Authorization failed, was the number registered elsewhere?

### ISSUE THREAD

**Issue by hollysheep** [AsamK/signal-cli#271]
Hi,

i become this error every time when i do something on my two devices where i use signal-cli. This worked some weeks ago. also

`signal-cli -u NUMBER listDevices`

don't work. I can't remeber which of the devices is the slave. Is there any way to "clean" all setting so that i can register the user again and link the other device? I couldn't find a solution for that error.

**Comment by AsamK** [comment]
you can delete the config file for your account, then you can register again.
By default that's stored in `~/.local/share/signal-cli/NUMBER`
