### ISSUE TITLE
How to send group messages via dbus-send?

### ISSUE THREAD

**Issue by hasdf** [AsamK/signal-cli#272]
Can somebody explain how to send group messages via dbus-send?

This works great for sending to a single recipient: 

`dbus-send --session --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:MessageText array:string: string:RECIPIENT`

I found ` void sendGroupMessage` in [Signal.java](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/Signal.java), but I'm not sure how to pass that group ID to dbus-send.

Thank you!

**Comment by exquo** [comment]
Sending to a group can be done with a similar command:
```
dbus-send --session --type=method_call  --print-reply --dest=org.asamk.Signal /org/asamk/Signal org.asamk.Signal.sendGroupMessage  string:'The message goes here'  array:string:'/path/to/attachmnt1','/path/to/attachmnt2'  array:byte:139,22,72,247,116,32,170,104,205,164,207,21,248,77,185
```
where the byte array at the end is the groupId in the bytes form. It can be obtained from the list of groupIds:
```
dbus-send --session --type=method_call  --print-reply --dest='org.asamk.Signal' /org/asamk/Signal org.asamk.Signal.getGroupIds
```
To get the group name corresponding to a groupId, run
```
dbus-send --session --type=method_call  --print-reply --dest='org.asamk.Signal' /org/asamk/Signal org.asamk.Signal.getGroupName    array:byte:139,22,72,247,116,32,170,104,205,164,207,21,248,77,185     
```
Alternatively, the groupId byte array can be obtained from the base64-encoded groupId that looks like `ixZI93QgqmjNpM8V+E25==` and can be found in signal-cli's config file, by default in `~/.local/share/signal-cli/data/<PHONE_NUMBER>`. To decode it to byte array, can use python:
```
python3 -c 'import base64; print(",".join(str(i) for i in base64.b64decode(b"ixZI93QgqmjNpM8V+E25==")))'
```

**Comment by exquo** [comment]
One dbus quirk here: it takes bytearrays as input (for `sendGroupMessage` and `getGroupName`) in the form `139,22,72,247,..`, but returns bytearrays (by `getGroupIds`) as space-separated hex digits `8b 16 48 f7 74 20 aa 68 cd a4 cf 15 f8 4d b9`. To convert one to the other:
```
python3 -c 'print(",".join(str(x) for x in bytes.fromhex("8b 16 48 f7 74 20 aa 68 cd a4 cf 15 f8 4d b9")))'
```

**Comment by hasdf** [comment]
Thank you for the detailed explanation! 

Stay healthy :)

**Comment by patcon** [comment]
Note that `/org/asamk/Signal` is now `/org/asamk/Signal/_15555555555` (where 15555555555 is your phone number on account)

If you don't do this, you will get error:

> Error org.freedesktop.dbus.errors.UnknownObject: /org/asamk/Signal is not an object provided by this process.

**Comment by exquo** [comment]
Thanks for the comment! I've added a note to my post above.
