### ISSUE TITLE
Question: signal-cli on maven repo

### ISSUE THREAD

**Issue by labero** [AsamK/signal-cli#274]
Hi!

Thank you for a great project! 

I can't seem to find signal-cli jar in any public maven site. Is the signal-cli jar published on any maven repo and if so, could you please point me to the repository? And is it possible to make this project more like a simple-to-use wrapper library over libsignal-server-java?

Best regards

**Comment by AsamK** [comment]
Hi, signal-cli is not published on any maven site. There a binaries available on github though: https://github.com/AsamK/signal-cli/releases

It would be possible to extract parts of signal-cli to a simple-to-use wrapper library, but it would be a lot of effort to create a really useful and maintainable API for it, so currently don't have any plans to do so.
