### ISSUE TITLE
question: change name of master device?

### ISSUE THREAD

**Issue by piramiday** [AsamK/signal-cli#275]
I have recently added a `signal-cli` instance to act as a second device.
```
user@two:~$ signal-cli link --name NEWDEVICE
```
my original/master device is another `signal-cli` client, which now shows:
```
user@one:~$ signal-cli -u +NUMBER receive
[...]
user@one:~$ signal-cli -u +NUMBER listDevices
Device 1 (this device):
 Name: null
 Created: [...]
 Last seen: [...]
Device 2:
 Name: NEWDEVICE
 Created:  [...]
 Last seen:  [...]
```
which is great.

question: is there a way for me to specify a new name to my master device, so that it's not `null`?
(the master device was installed a couple of years ago, maybe before the default device name was `cli` as specified in the man page.)
thanks!

**Comment by AsamK** [comment]
The name of the master device is always null and as far as I know it can't be changed.
