### ISSUE TITLE
question: link previews?

### ISSUE THREAD

**Issue by piramiday** [AsamK/signal-cli#276]
is it possible to use `signal-cli` to send a message with link preview, like it was written from a standard mobile or desktop application? e.g. youtube links.

**Comment by AsamK** [comment]
It's possible, but not implemented yet.
Link previews could be added to a `MessageBuilder` with the `withPreviews` method.
Each `LinkPreview` needs a url, title and thumbnail image attachment.
The tricky part would probably be to automatically get a website thumbnail.

**Comment by piramiday** [comment]
> The tricky part would probably be to automatically get a website thumbnail.

in general it's relatively easy, but then again I could easily script it outside of `signal-cli`.

in particular, though, I was imagining the same that Signal does, that is, passing the request to its own proxy service so as to fetch the thumbnail anonymously.
at present, Signal supports anonymous link previews only for a strict selection of high-traffic and highly popular websites* -- they will not implement non-anonymous link previews nor, understandably, scale up their proxy service to service the entirety of the Internet.

*: maybe more will be added in the future?
https://community.signalusers.org/t/enable-link-previews-for-more-sites/7517

**Comment by piramiday** [comment]
on a slightly different note: is it possible to use `signal-cli` to send messages that _look like_ link previews? that is, messages that not only attach a picture, but also provide a title and a domain preview? for example:

- thumbnail = image
- title = **People Try Walking Their Cats**
- domain = www.youtube.com
- message = ...

e.g. from https://support.signal.org/hc/en-us/articles/360022474332-Link-Previews:
![link-previews-catwalk](https://user-images.githubusercontent.com/48775554/78578580-92f4ff80-77e4-11ea-9d07-6e821ed581e7.jpg)

if it's not possible, then that would be a great enhancement for `signal-cli`!
actual link previews would probably be high effort (and low gain) for this project.
as usual, thanks!

**Comment by piramiday** [comment]
I don't know whether this can be helpful, but Signal Desktop implemented full (that is, not whitelist-based) link previews, too!

https://github.com/signalapp/Signal-Desktop/releases/tag/v1.37.1
https://github.com/signalapp/Signal-Desktop/commit/dd57963dab9dc516550fb939a62213e3e3d19539

**Comment by soleous** [comment]
IS there any news on this?
