### ISSUE TITLE
question: GPG signatures?

### ISSUE THREAD

**Issue by piramiday** [AsamK/signal-cli#279]
hi there, I am kind of confused -- why are there two different gpg signatures for each release?
talking about the current version, I can see that `signal-cli-0.6.4.tar.gz` can be verified by `signal-cli-0.6.4.tar.gz.asc`.
what is `v0.6.4.tar.gz.asc` supposed to verify?
thanks!

**Comment by AsamK** [comment]
`v0.6.4.tar.gz.asc` is the signature for the `Source code (tar.gz)`
