### ISSUE TITLE
question: Why I'm unable to leave group?

### ISSUE THREAD

**Issue by kiranparajuli589** [AsamK/signal-cli#280]
I've created a signal account using signal-cli v0.6.3
Now I've updated the signal-cli to `latest` and I've tried to run
```bash
signal-cli -u <my-phone-number> listGroups
```
or 
```bash
signal-cli -u <my-phone-number> listGroups -d
```
Signal-cli did not complain about anything and **there is no response in my terminal, nothing happens**
And how can I get `groupID` of group that I'm connected with?

How can I remove my account from all groups that I've been connected with?

**Comment by AsamK** [comment]
In signal all groups are decentralized and not stored on the signal server. The group state is only stored on the devices of the other group members. When one of those members sends a group message to you, signal-cli will request the group state from that member and after receiving it, the group will be listed by the listGroups command.
Unless a message is sent to one of the groups where you participate, signal-cli can't know about that group.
