### ISSUE TITLE
[question] Do you consider to upgrade dbus-java?

### ISSUE THREAD

**Issue by aanno** [AsamK/signal-cli#285]
Hello,

I'm using your project in conjunction with [secret-service](https://github.com/swiesend/secret-service). However, there is a twist: the other project is using the new `dbus-java` (`com.github.hypfvieh:dbus-java`). It is a little delicate to have both implementations in the classpath, hence: are you planning to upgrade?

Kind regards,

aanno

**Comment by AsamK** [comment]
I'll look into it, the hypfvieh dbus-java looks interesting.
Looks like it doesn't need a dedicated native lib to access the dbus socket but only uses libc for that, via jnr-unixsocket.
