### ISSUE TITLE
Unable to connect to the D-Bus system bus on FreeBSD

### ISSUE THREAD

**Issue by 0mp** [AsamK/signal-cli#287]
Hi,

I've recently packaged signal-cli for FreeBSD (https://www.freshports.org/net-im/signal-cli/).

The functionalities which do not require D-Bus to be involved are working fine (thanks your this wonderful piece of software BTW).

I cannot get signal-cli to authenticate against the `dbus` service running on my system, however. I've tried to connect to both the system bus and to the user one (I am not about the proper naming of things, D-Bus development/debugging is rather new to me).

I've started collecting my notes in a separate repo (https://github.com/0mp/freebsd-ports-signal-cli/) so that other interested developers could join the debugging efforts.

Currently, I am stuck with debugging at authentication against the system bus. Here's a snippet of the debug logs (the full log is in the repo I linked to earlier):

```
[org.freedesktop.dbus.Transport$SASL.auth()] AUTH state: 0
[org.freedesktop.dbus.Transport$SASL.send()] sending: AUTH

[org.freedesktop.dbus.Transport$SASL.auth()] AUTH state: 1
[org.freedesktop.dbus.Transport$SASL.receive()] received: REJECTED EXTERNAL
[org.freedesktop.dbus.Transport$SASL$Command.<init>()] Creating command from: [REJECTED, EXTERNAL]
[org.freedesktop.dbus.Transport$SASL$Command.<init>()] Created command: Command(3, 1, null, null)
[org.freedesktop.dbus.Transport$SASL.send()] sending: AUTH EXTERNAL 323438

[org.freedesktop.dbus.Transport$SASL.auth()] AUTH state: 1
[org.freedesktop.dbus.Transport$SASL.receive()] received: REJECTED EXTERNAL
[org.freedesktop.dbus.Transport$SASL$Command.<init>()] Creating command from: [REJECTED, EXTERNAL]
[org.freedesktop.dbus.Transport$SASL$Command.<init>()] Created command: Command(3, 1, null, null)
[org.freedesktop.dbus.DBusConnection.<init>()] java.io.IOException: Failed to auth
    at org.freedesktop.dbus.Transport.connect(Unknown Source)
    at org.freedesktop.dbus.Transport.<init>(Unknown Source)
    at org.freedesktop.dbus.DBusConnection.<init>(Unknown Source)
    at org.freedesktop.dbus.DBusConnection.getConnection(Unknown Source)
    at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:50)
    at org.asamk.signal.Main.handleCommands(Main.java:126)
    at org.asamk.signal.Main.main(Main.java:61)
```

Cheers!

**Comment by grembo** [comment]
Hi @0mp,

I ran into the same problem today trying to package signal-cli master (now I realized that I could've saved some of that effort - Duh!)

I'll send you a PM.

**Comment by 0mp** [comment]
> I'll send you a PM.

Cool! I'm waiting!

**Comment by grembo** [comment]
> > I'll send you a PM.
> 
> Cool! I'm waiting!

It basically comes down to hypfvieh/dbus-java not supporting FreeBSD (cmsgcred).

I sent you an email with details.

**Comment by grembo** [comment]
@0mp I implemented the missing bits in jnr-posix and dbus-java, I can now locally run signal-cli (and scli) successfully.

Pull requests:
https://github.com/jnr/jnr-posix/pull/149
https://github.com/jnr/jnr-posix/pull/150
https://github.com/hypfvieh/dbus-java/pull/105

**Comment by 0mp** [comment]
Nice, all the pending PRs were merged in those other repositories!

**Comment by grembo** [comment]
> Nice, all the pending PRs were merged in those other repositories!

Now all that's left to do is ask projects kindly to cut new releases ;)

**Comment by 0mp** [comment]
I'm facing the following problem now: https://github.com/jnr/jnr-ffi/issues/206

**Comment by grembo** [comment]
@0mp you were lacking jffi-native (so not a problem with signal-cli), I opened https://github.com/0mp/freebsd-ports-signal-cli/pull/1 to fix the port skeleton.

**Comment by 0mp** [comment]
signal-cli is now working just fine on FreeBSD! Thanks!

https://www.freshports.org/net-im/signal-cli
