### ISSUE TITLE
Use code as library

### ISSUE THREAD

**Issue by nickik** [AsamK/signal-cli#29]
In this project you provide a lot of stuff that everybody needs that wants to send messages from a desktop client. My idea to was to extract the functionality and offer it up as a java library.

My idea was to use this so that my system monitoring tool can send me messages.

I ran into a problem however. I constantly get:

Error loading state file "/Users/<user>.config/signal/data/<number>": javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

The strange thing is that if I use a freshly compiled version of signal-cli, this does not happen. They use the same security library and setup in general.

Have you run into this problem as well? Any hit of a solution?

**Comment by AsamK** [comment]
This is probably a problem with the trustStore. Make sure the file whisper.store is included in your resources.

**Comment by nickik** [comment]
Thank you. This helped.

I hope you don't mind if I ask you another question.

Now I get the error:
- javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair

I am using Java 8, but according to stackoverflow and co, this should be fixed in Java 8. When I'm compiling your project, it works on my machine with the same Java version. How is that possible?

Thank for your help.

**Comment by AsamK** [comment]
I haven't seen this error before.
