### ISSUE TITLE
Discover own safety number

### ISSUE THREAD

**Issue by camwebb** [AsamK/signal-cli#292]
How does one find one's own safety number to read out (or send to) to the other person during a trust exchange? I've looked in the config file, in the man page, through the issues, and in the code, but can't see how to do this. Sorry if I've missed something obvious.

**Comment by AsamK** [comment]
The safety numbers are different from a fingerprint, that you don't have your own safety number.
The safety number is always computed from the public key and phone number of two users.
So when "exchanging" safety numbers you and the other person have the same numbers.
