### ISSUE TITLE
Umlauts not UTF-8 encoded when sent as commandline parameter

### ISSUE THREAD

**Issue by Evil2000** [AsamK/signal-cli#297]
As the headline says, when sending umlauts as part of the message and passing it as command line parameter, they seem to be sent as ASCII to the recipient but not as UTF-8 as expected.
When the same message containing the umlauts is passed on STDIN to signal-cli, the message is correctly encoded and sent as UTF-8.

Example:
` ~ $ signal-cli -u +4xxxxxxx send -m "Überörtliche Ärztebehörde" +4xxxxxxxxx`
Gets:
![ksnip_20200413-200623](https://user-images.githubusercontent.com/697191/79147462-40a77600-7dc4-11ea-84a2-e21b6cf4cdfe.png)
But passing on STDIN seems to work correctly:
` ~ $ echo "Überörtliche Ärztebehörde" | signal-cli -u +4xxxxxxx send +4xxxxxxxxx`
![grafik](https://user-images.githubusercontent.com/697191/79147758-bca1be00-7dc4-11ea-85cf-88f88a414b64.png)

**Comment by Evil2000** [comment]
OK. That's it!
```
FordPrefect ~ $ echo $LANG
C
FordPrefect ~ $ export LANG="en_US.UTF-8"
FordPrefect ~ $ signal-cli -u +4xxxxxxx send -m "Überörtliche Ärztebehörde" +4xxxxx
1586888734865
```
... works as exprected :+1:

**Comment by steadfasterX** [comment]
just for ref: the above didnt helped on my system but using `dpkg-reconfigure locales` and ensuring the primary language is set to UTF-8 fixed it for me (I am using a systemd service if that matters)

**Comment by Louisonix** [comment]
Just for people still struggling with this kind of problem with signal-cli: 

I had set my LANG variable to de_DE.UTF-8. Emojis and Umlauts where still not displayed correct. Changing to en_US.UTF-8 fixed the problem.
