### ISSUE TITLE
Getting FingerPrint from android device to trust identity

### ISSUE THREAD

**Issue by MichaelBitard** [AsamK/signal-cli#30]
I'm not sure to understand, I have a user using signal-cli, communicating to another user using an android device.
I wanted to trust this user but I can't find it's fingerprint on the android device, the only thing I can get is the "safety numbers", but they dont match the fingerprint so I assume this is not the same thing.

Is there a way to get the user fingerprint from an android or a desktop application ?

**Comment by AsamK** [comment]
The android app recently switched from fingerprints to safety numbers. signal-cli has support for this, but only in master, not in the released version. You can try it, if you compile it yourself, otherwise you'll have to wait until I make a new release.

**Comment by MichaelBitard** [comment]
Ok Thanks a lot, I suspected something like that but I wanted to be sure.
