### ISSUE TITLE
Register with voice call does not work

### ISSUE THREAD

**Issue by fraf1** [AsamK/signal-cli#300]
Hi,

I am trying to register a new number using voice call with:
signal-cli -u +41######## register --voice
The command itself works without errors (even $? returns 0), but I do not receive any phone call.
Version is 0.6.7
I have already linked the device using signal-cli with an existing account. Everything works in that case and I can send messages using signal-cli, so the installation itself, Java and everything else seems to be ok.
I tried to register a mobile phone number using an sms for the code, i.e. without the --voice option, and it worked. The sms arrived and I could verify the registration.

The only thing I do not manage to do is registering a new phone number (a landline number, so no sms possible) using voice call for the verification code.

Am I doing anything wrong, is the problem on signal side or is it something in signal-cli?

Thanks,
Francesco

**Comment by AsamK** [comment]
Maybe it's a country specific issue on signal side. The only thing that signal-cli does differently for voice verification is including the locale for the phone call and if that is invalid, the signal server responds in English.
You could also try sending the sms to the landline, some telecommunication providers have a service that read out sms that are sent to landline numbers.

**Comment by hb9tst** [comment]
@AsamK I guess the issue is on Signal side, but it affects multiple countries. I recently tried a few Swiss landlines with the same result (no call arriving), and a friend tried the same with the official Signal client on Android with the same result. I now just tried with two UK phone numbers (a landline and a mobile) on different networks, and didn't get any call either. SMS registration works, but that's not the point. Will try to get in touch with Signal support, I fear they don't have voice call routes to all countries.

**Comment by davemacrae** [comment]
I've just tried to register my landline in the UK.

If I try: `signal-cli -u +44131XXXXXXX register --voice` I get the response `Captcha invalid or required for verification (null)`

If I try: `signal-cli -u +44131XXXXXX register --voice --captcha "CAPTCHA"`, there is no error (exit code 0) but I don't get a call for voice verification :(

I also tried just `signal-cli -u +44131XXXXXX register --voice --captcha "CAPTCHA"` in the hope that the SMS to landline would work, but nothing came through.

**Comment by uwe-kr** [comment]
I have exactly the same problem as davemacrae with a german landline number (+49...).

**Comment by popokatapepel** [comment]
for me it works witch a german mobile phone number via sms... However using the `--voice` option returns  `Request verify error: Bad response: 400` any ideas or a way how to troubleshoot would be appreciated.

**Comment by AsamK** [comment]
See https://github.com/AsamK/signal-cli/discussions/628#discussioncomment-765501
Maybe you're LANG env variable needs to be changed.
