### ISSUE TITLE
getting messages from linked device

### ISSUE THREAD

**Issue by grauschnabel** [AsamK/signal-cli#306]
Hi there,

I linked my android device and, `listContacts` workes fine. But how can I now get a conversation from the andorid to my linux? I would like to save it in a file.  I cannot find any documentation for that, sorry, if I ask an easy question here.

Thanks,
Martin

**Comment by grauschnabel** [comment]
Hi there

Reading more and more of the signal-cli source and documentation, i guess it is not possible. Maybe it doesn't save received messages, am I right?

How is the official desktop client doing this? Is it supported by the api but not by the signal-cli? Are there alternatives?

**Comment by AsamK** [comment]
yes, signal-cli currently doesn't save message.

The signal protocol doesn't provide a way to synchronize old messages. Also the desktop client just receives new messages, but can't sync existing messages.
