### ISSUE TITLE
Cannot receive, session error

### ISSUE THREAD

**Issue by Vic3198** [AsamK/signal-cli#309]
Hi, I have a little problem for receiving messages from dbus-system.

I've just made a fresh install of signal-cli on a fresh Ubuntu 16.04, and setup the dbus-system service.
I can send and receive messages correctly. However, I have issues receiving messages from some phone numbers. It outputs the following error.

```
Envelope from: unknown source
Timestamp: 1589822009087 (2020-05-18T17:13:29.087Z)
Sent by unidentified/sealed sender
Exception: org.whispersystems.libsignal.InvalidMessageException: No valid sessions. (ProtocolInvalidMessageException)
Failed to decrypt message.
```

Resetting the session with the -e parameter works, but after one message, the bug reappears...

Any idea?

Thanks,
Vic

**EDIT: After further investigations, I have a more precise description of the bug.
After the session is reset, signal-cli can receive messages. But after you send a message via signal-cli, you won't be able to receive any message from this recipient. The above error is raised each time a message is received, until session reset. I think it has something to do with seal sender being enabled after the first message sent, but still can't find a way to fix it...**

**Comment by ofn1** [comment]
Yes, I also encountered this problem. To add two points, one is that this problem only occurs between the signal desktop version and the signal-cli, and this problem does not exist between the mobile app and signal-cli; the second is that this problem did not exist before the desktop version was upgraded to 1.34, that is, It is normal for version 1.33 to communicate with the signal-cli 0.6.7. 

The current solution to this problem is to install the desktop version 1.33, and do not upgrade.

**Comment by Vic3198** [comment]
In my case, it happens with both Desktop (v1.34.1) and mobile (v3.8.4.3 beta on iPhone) apps. The bug also happens for a friend of mine who hasn't a desktop or any slave Signal instance connected to his account...

**Comment by mqq2** [comment]
I tested it a few times and I found this problem occurs when the signal-cli receives the information from the desktop version 1.34.

**Comment by Vic3198** [comment]
I've removed all my linked devices from my Signal account, but the bug's still there. I need to reset the session everytime after a message is sent to my phone from signal-cli to be able to receive messages again...

**Comment by AsamK** [comment]
Looks like Signal-Desktop now sends messages with the user's uuid and no longer with its number.
Then signal-cli cannot map the uuid to the session it created with the phone number.
I guess signal-cli needs to request the uuids for phone numbers when sending messages ...

**Comment by AsamK** [comment]
I've pushed a commit to store the uuid in more cases. Can someone retest with the latest master?
After another session reset it should work normally again.

**Comment by Vic3198** [comment]
Ok I just built and installed the version with your new commits. Session reset wasn't enough, I had to completely delete the account data and register again but now it works like a charm! Thanks a lot!

**Comment by Vic3198** [comment]
Oh and btw, I'm quite new to GitHub and really don't know where to post that.
I made a little Python script to automate the installation of signal-cli, the setup of the DBus service and the registering procedure. It's certainly far from perfect, but worked for me and saved me a lot of time when reinstalling signal-cli on a new machine. I attach it there. Could you please tell me the best place to post it?

[InstallSignalEN.txt](https://github.com/AsamK/signal-cli/files/4667924/InstallSignalEN.txt)

**Comment by AsamK** [comment]
you could create a new repository or just a gist for it and if you want link to it from the signal-cli wiki (https://github.com/AsamK/signal-cli/wiki)

**Comment by kt8345953** [comment]
This issue is coming up for me for a few of my contacts. Working with the most current version and I tried unregistering and reregistering to no avail. Interestingly, I do receive messages from those contacts if there is an attachment.
