### ISSUE TITLE
Get timestamp for sent message

### ISSUE THREAD

**Issue by derricw** [AsamK/signal-cli#310]
When I receive messages with signal-cli, I get timestamps that I can use as ID's to reference read receipts and related events.
But I do not see a way to get the timestamp for a sent message. This means that I cannot send a message, then easily associate it with a later read or delivery receipt.
Is there a way I could get the `send` command to write the message timestamp?

**Comment by AsamK** [comment]
The latest signal-cli version already outputs the timestamp, after sending a message:
https://github.com/AsamK/signal-cli/releases/tag/v0.6.7

**Comment by derricw** [comment]
Thanks! I had been using 0.6.6!
