### ISSUE TITLE
dbus problem on OpenBSD

### ISSUE THREAD

**Issue by ghost** [AsamK/signal-cli#314]
Hello everyone

The `0.6.7` version of `signal-cli` worked. The command `dbus-run-session signal-cli -u [USER] daemon` threw no errors.

Now with version `0.6.8` I get: `org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus: Protocol not available`.

If I only run `signal-cli -u [USER] daemon` I get: `Exception in thread "main" java.lang.RuntimeException: Cannot Resolve Session Bus Address`

Thanks for any help!

**Comment by 0mp** [comment]
Potentially related to #287.

**Comment by johnfreed** [comment]
Now that #287 is closed (and fixed), is this still an issue @0mp ?

**Comment by 0mp** [comment]
@johnfreed Unfortunately, I have no idea. I'm not using signal-cli on OpenBSD... Issue #287 was related to FreeBSD.

**Comment by AsamK** [comment]
I've updated signal-cli to use the hypfview dbus-java 4.0 beta, which uses native java unix sockets, that should resolve at least some dbus issues.
If you still have issues with dbus, please open an issue on the [dbus-java project](https://github.com/hypfvieh/dbus-java)
If there are some known workarounds or additional steps, feel free to add it to the wiki: https://github.com/AsamK/signal-cli/wiki/DBus-service
