### ISSUE TITLE
dbus: How to get attachment filename from python

### ISSUE THREAD

**Issue by EmmanuelIT** [AsamK/signal-cli#316]
Using the python code for receiving messages through dbus
```python
from pydbus import SystemBus
from gi.repository import GLib

def msgRcv (timestamp, source, groupID, message, attachments):
   print("onMessageReceived:", timestamp, source, groupID, message, attachments)
   return

bus = SystemBus()
loop = GLib.MainLoop()

signal = bus.get('org.asamk.Signal')
signal.onMessageReceived = msgRcv
loop.run()
```
in **attachments** variable I get an array of strings, containing the absolute paths that the attachments reside on my filesystem. 
ex:
```['/opt/.../share/signal-cli/attachments/1309176955124639716', '/opt/.../share/signal-cli/attachments/2244858757840267913']```

How can I get the original filename of these attachments ?

The output of: 
```signal-cli --config /opt/..../share/signal-cli -u +991234567890 receive --json```
 contains a structure containing both the original (sender's) filename and the filename in my filesystem. But how can I get this structure in Python through dbus

**Comment by EmmanuelIT** [comment]
Hi AsamK,

I checked  ```signal-cli/src/main/java/org/asamk/Signal.java``` and I see that the attachments are passed to the MessageReceived method as List of strings. That would normally indicate that only one "kind" of filenames can be passed: Either local filepaths where the attachments are stored or the original (the sender's) filename.
 
So is this an enhancement I am asking for, or am I doing something wrong ?

**Comment by exquo** [comment]
I think this is a question to `pydbus` rather then to signal-cli, specifically on usage of the `pydbus.get(..).onMessageReceived()` function and why it has the arguments it does. Maybe you could try inspecting the dbus message objects to see what other attributes it can provide? 

Also, as you have mentioned, running
	`signal-cli -u +991234567890 daemon --json`
does have the "original" `filename` field, so you could also try parsing the json output rather then rely on pydbus.

Here's how one signal-cli client that I'm familiar with does it:
https://github.com/isamert/scli/blob/08219b56501d6139cdbdd50ba9402757ed4cfbf4/scli#L281

**Comment by EmmanuelIT** [comment]
Hi exquo,

You understood correctly. 

I know I can use signal-cli command line from within python in order to get the "original" filename, but I wanted to use the dbus mechanism for obvious reasons (performance, more clear code, etc).

That's why AsamK offered the dbus mechanism in the first place.

The problem is that AsamK used a List of Strings as a parameter to his **MessageReceived** callback Java method. This list of strings contains only the local filenames and not the "original" filenames. 

He could use either a List of "string pairs" for his **attachments** parameter. For example, **attachments** parameter could contain:
```python
 ['myPicture01.jpg', '/opt/.../share/signal-cli/attachments/1309176955124639716', 
  'myPicture02.jpg', '/opt/.../share/signal-cli/attachments/1309171234566938817']
```
Or he could use one more String List parameter to his method named, for example, **originalFilenames**, that would contain the original filenames in the same order as in the **attachments** parameter.

It seems that something is missing here, and I probably have to abort the whole dbus direction and turn to a "command line" implementation, something that I tried hard to avoid from the beginning.

**Comment by exquo** [comment]
I agree, in general it seems like a good idea to have consistency between the data signal-cli prints out on command line, and the data it passes through dbus. I think the scope of this ticket could broadened to include the data from *all* the fields that are printed out to also be sent through dbus. From what I see from dbus's docs, it supports sending dicts and structs, so one-to-one mapping between the json and the dbus data should be possible. 

Regarding the reasons for preferring dbus over stdout, I'm not sure if there are significant benefits for the dbus method. Performance-wise, it's certainly much better to *send* new messages through the signal-cli's dbus, rather then starting a new signal-cli process, which entails starting up a new JVM instance. But in terms of *receiving* messages I wouldn't be surprised if a simple unix pipe is actually faster then dbus. (I don't have any particular expertise in this matter though, it's just a 'common-sense' guess). Code clarity may be subjective, but parsing json with the `json` module shouldn't be any less clear then parsing dbus messages with `pydbus`. So, if not having access to the original filenames is a deal-breaker, extracting them from a json printout might not be such a bad idea. 
Finally, it looks like signal renames the photos and videos before sending. Those types make up the bulk of the attachments most people send, and their original names are not available on the receiving end anyway. Of course, might not be your use-case though.


On Thu-05:21, EmmanuelIT wrote:
> Hi exquo,
> 
> You understood correctly. 
> 
> I know I can use signal-cli command line from within python in order to get the "original" filename, but I wanted to use the dbus mechanism for obvious reasons (performance, more clear code, etc).
> 
> That's why AsamK offered the dbus mechanism in the first place.
> 
> The problem is that AsamK used a List of Strings as a parameter to his **MessageReceived** callback Java method. This list of strings contains only the local filenames and not the "original" filenames. 
> 
> He could use either a List of "string pairs" for his **attachments** parameter. For example, **attachments** parameter could contain:
> ```python
>  ['myPicture01.jpg', '/opt/.../share/signal-cli/attachments/1309176955124639716', 
>   'myPicture02.jpg', '/opt/.../share/signal-cli/attachments/1309171234566938817']
> ```
> Or he could use one more String List parameter to his method named, for example, **originalFilenames**, that would contain the original filenames in the same order as in the **attachments** parameter.
> 
> It seems that something is missing here, and I probably have to abort the whole dbus direction and turn to a "command line" implementation, something that I tried hard to avoid from the beginning. 
> 
> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/AsamK/signal-cli/issues/316#issuecomment-645982769

-------------------------------------------------
This free account was provided by VFEmail.net - report spam to abuse@vfemail.net
 
ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!

**Comment by johnfreed** [comment]
Thanks, exquo. Yes, #671 is precisely the issue raised in #316 (which I hadn't seen). The whole point is to demonstrate DBus use, so basically the argument that someone should start a subprocess and manually parse the JSON output doesn't apply (nor does it make sense to me, as the whole point of using DBus is to avoid just this).

**Comment by AsamK** [comment]
Attachment file names are now included in the new message extras of the dbus signal: https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/DbusReceiveMessageHandler.java#L200
