### ISSUE TITLE
Feature request : raw[ish] logging 

### ISSUE THREAD

**Issue by mooomooo** [AsamK/signal-cli#318]
I currently create text logs a la https://github.com/camwebb/signal-cli-wrapper -- this has a couple issues though:
- The output of signal-cli is pre-processed, causing some loss of data [ that may not necessarily be useful, but sometimes leads to issues like #184 ]
- Messages sent through signal-cli are not captured anywhere and must be manually added / matched to messages sent from other devices

Would it be possible to add a command line switch to enable a raw[ish] log to file of the packets immediately before sending and after receiving?  I suppose some exclusions of binary data [ i.e. attachments ] may be necessary.

Thanks, and of course, thanks for this tool!

**Comment by AsamK** [comment]
The signal-cli json output and new dbus signals should contain most interesting data now.
Logging the raw messages is not planned and would required changes in the libsignal-service library.
