### ISSUE TITLE
signal-cli fails to delete temp files

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#32]
Everytime i send a voice message from my droid, signal-cli receives a sync sent message with the audio attachment and complains that it failed to delete the temp file:

```
Failed to delete temp file: C:\Users\XXXXX\AppData\Local\Temp\ts_attach_90949199056035476364255783916527914059.tmp
Envelope from: ?Ich? +49XXXXXX462 (device: 7)
Timestamp: 1480025899101
Received a sync message
Received sync sent message
To:  , Message timestamp: 1480025899101
Message timestamp: 1480025899101
Body:
Group info:
  Id: txFIeGmfMS/OPlERkBK1sw==
  Name: #ARGS
  Type: DELIVER
Attachments:
- audio/aac (Pointer)
  Id: 9094919905603547636 Key length: 64 Relay:
  Size: 49340 bytes
  Stored plaintext in: C:\Users\Benni\.config\signal\attachments\9094919905603547636
```

**Comment by AsamK** [comment]
This is probably caused by a missing close(), fixed in c542fb87cb7c5ff7146c0853328189a5a1ebbb6d
I didn't notice this on Linux, because deleting a file is possible, even if it's still open.

**Comment by Trolldemorted** [comment]
PR #34 yields more information: `The process cannot access the file because it is being used by another process`. I assume that applies also to the same process (especially since we are talking about java processes), but i must admit i encountered some cases of stale java processes which i believe are spawned by signal-cli.

I guess it could also be [this one](https://github.com/Turasa/libsignal-service-java/blob/dde5c5efb9a168fbf4a269620e6beb5bf7baedbf/java/src/main/java/org/whispersystems/signalservice/api/crypto/AttachmentCipherInputStream.java#L205), and i think we now know why moxie uses file.deleteOnExit() instead.

**Comment by AsamK** [comment]
Stale processes shouldn't be an issue, as the temp file always gets a new random name. I'd like to avoid using deleteOnExit(), especially if for long running daemon processes. This leaks disk space for the runtime of the process, so the best solution is to close all open streams.

**Comment by AsamK** [comment]
is this still an issue in the new version?

**Comment by Trolldemorted** [comment]
nope, that did it, thanks!

may i delete the ~/.config/signal/data/+49XXXX.d folders?

**Comment by AsamK** [comment]
yes, currently this folder is only used to store messages until they're decrypted (msg-cache), so normally there shouldn't be any files inside.
I'm planning to move more stuff there, like the session state. So it won't always be safe to delete the folders.
