### ISSUE TITLE
Question: reading time stamp

### ISSUE THREAD

**Issue by spetztest** [AsamK/signal-cli#320]
Hi, how to read this timestamp 2020-06-05T08:11:48.401Z? what's the Z? is there a way to change it to local timezone?

**Comment by AsamK** [comment]
It's an ISO_8601 timestamp, the Z means UTC timezone.

https://en.wikipedia.org/wiki/ISO_8601

**Comment by spetztest** [comment]
Hi Asam, 

is there a way to change the timezone?
