### ISSUE TITLE
setPin exception in thread "main"

### ISSUE THREAD

**Issue by elburz** [AsamK/signal-cli#323]
Hi there, very useful tool, thanks for it. I had this issue when trying to use the setPin command. Looks like something to do with Java?

Everything worked so far for registration. Then I try to run:

`./signal-cli -u MY_NUMBER_HERE setPin MY_PIN_HERE`

And here's the error I get:

`Exception in thread "main" java.lang.RuntimeException: Not implemented anymore, will be replaced with KBS
	at org.asamk.signal.manager.Manager.setRegistrationLockPin(Manager.java:398)
	at org.asamk.signal.commands.SetPinCommand.handleCommand(SetPinCommand.java:27)
	at org.asamk.signal.Main.handleCommands(Main.java:181)
	at org.asamk.signal.Main.handleCommands(Main.java:132)
	at org.asamk.signal.Main.main(Main.java:64)`

Test system info:
- Xubuntu 20.04
- Everything up to date in the system
- Latest release: 0.6.8
- Followed the instructions on the wiki for setting up Ubuntu
- openjdk version "11.0.7" 2020-04-14

**Comment by AsamK** [comment]
Signal has implemented a new version of the pin lock functionality (called KBS).
signal-cli hasn't implemented support for this yet.

**Comment by elburz** [comment]
Thanks for confirming. I was looking around the libsignal-service-java and didn't see anything mentioned around KBS, am I correct in guessing the issue lies in that library not having added the functionality yet? If so, I can see if there's something I can do there to help move that along.

**Comment by AsamK** [comment]
libsignal-service-java supports it already, but doesn't provide all required functionality. I've already created a testing branch for it, but it's not complete. You can have a look at 

https://github.com/AsamK/signal-cli/issues/268#issuecomment-602234452
> I had a look at it, but didn't get it to work yet. Here's the work in progress branch: https://github.com/AsamK/signal-cli/commits/wip/kbs-pin-lock
> 
> One issue is that it uses the argon2 hashing algorithm. The android app is using a java wrapper around the native library, but I'd prefer a pure java implementation for easier deployment. The only library I found is incomplete and not production ready ...
