### ISSUE TITLE
Signal-cli can be a master for Signal-Desktop. Can it be a slave of Signal-Android?

### ISSUE THREAD

**Issue by octos** [AsamK/signal-cli#325]
I would like to be able to use Signal-cli with Signal-Android, and I didn't find a clear guide explaining the process.

The command below allowed me to register Signal-cli as the master (as if it were a phone), but it doesn't seem possible to then link to it using Signal-Android as a slave. In other words, it seems like Signal-Android must be a master.
    
    signal-cli -u "+15551238888"

Can Signal-cli link to Signal-Android as a slave the same way Signal-Desktop does? The following command generated a link (see below), which, after conversion to QR, I was able to link to Signal-Android successfully:

    signal-cli link
    tsdevice:/?uuid=cBqaDuQYqMtmG84mj6SgUg&pub_key=BaSfOYW9FvAx5fG9wz637nUkXOJL%2B2lehLnDLXKa2Tdw

...but every Signal-cli command complains with the following message:

    You need to specify a username (phone number)

...providing it fails with:

    Authorization failed, was the number registered elsewhere?

**Comment by Aagrueme** [comment]
Hava you tried deleting your config and then executing `signal-cli link` again?
Your config data is in most likely in `$HOME/.local/share/signal-cli/data`.

**Comment by octos** [comment]
Thank you. This time `signal-cli link` returned:

    Link request error: null

But `signal-cli -u "+ 15551238888" receive` worked as expected.

**Comment by AsamK** [comment]
Yep, that error can be ignored, will be fixed in the next version (#322)
