### ISSUE TITLE
dbus-send on the system bus failed

### ISSUE THREAD

**Issue by ofn1** [AsamK/signal-cli#326]
Follow the [instructions](https://github.com/AsamK/signal-cli/wiki/DBus-service) to run successfully on the system bus.
Now it is ok to send message by:
`signal-cli --dbus-system send -m <msg> <numbers>`
It will take about 2-3 seconds per message with high CPU usage.
So try to use dbus-send:
`dbus-send --session --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:'test' string:'+190xxxxxxxx'`
But failed with promption:

> The method `org.asamk.Signal.sendMessage does not exist on this object.

Can it be sent in this way? thank you very much!

**Comment by AsamK** [comment]
Yes that works.
Your call is just missing the second parameter (for attachments): `array:string:`

**Comment by ofn1** [comment]
> Your call is just missing the second parameter (for attachments): `array:string:`

Yes, now it works great!
Thanks!
