### ISSUE TITLE
Retrieve contacts' self-chosen nicknames

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#327]
For conversations with contacts whose numbers are not in phone's contact book, signal-android and signal-desktop show a nickname that person has chosen when registering next to (desktop) or instead of (android) the contact's phone number. 
It would be nice if signal-cli could make those nicknames available as one of the json fields in `contactStore : contacts` of signal-cli's data file (`~/.local/share/signal-cli/data/+XXXXXXXXXX`).

**Comment by exquo** [comment]
Is this a duplicate of #163? (which is itself marked as a duplicate of #98)

**Comment by AsamK** [comment]
The profile information, including the nickname, is now stored in `profileStore : profiles` in the data file.
Profiles are requested when sending a message to a recipient, there's no cli command yet to retrieve a profile.
