### ISSUE TITLE
Do not add group chat members to contactStore:contacts

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#328]
All the phone numbers of the members in a group conversation are added to `contactStore : contacts` of signal-cli's data file (`~/.local/share/signal-cli/data/+XXXXXXXXXX`) if they are not among the contacts already. This is inconvenient for programs using signal-cli that offer a list of contacts to the user. If I'm added to a group chat with many contacts who are not in my address book and with whom I have no previous one-to-one conversations, all their numbers would be presented alongside my 'regular' contacts, without a way of knowing which are which. [^]

I feel like their numbers should not be added to signal-cli's `contacts` list. But if they are, there should at least be a way of telling them apart from the 'regular' contacts, by e.g. having different values in some of their json fields, or having a special separate field to mark them as 'contacts coming from a group chat', so that the programs using signal-cli can choose to not display such contacts alongside with the regular ones.    

[^] Contacts added automatically from groups have `"name" : ""` or `"name" : null`, but so do any contacts that are not in in the phone's / master device's address book; those contacts can't be ignored by signal clients just on that basis. For instance, some people don't give signal-android access to their phone contacts, so all their contacts have empty names.

**Comment by exquo** [comment]
A follow-up question: what's the difference between `"name" : ""` and `"name" : null` in signal-cli's data file? (What kind of contacts get which value?) I can't see a pattern among my contacts.

**Comment by AsamK** [comment]
signal-cli currently stores the profile key in the contacts list, so for all group members that send their profile key, a contact entry is created. The profile key is necessary for sending unidentified messages. Those contacts are always created with `"name": null`, I'm guessing `"name": ""` are created with contacts syncs from a linked device.
The best solution would probably be to store the profile keys in a separate list (and maybe store a cached version of the profiles in the same section).

**Comment by exquo** [comment]
@AsamK, this makes sense. 
Maybe add the profile keys to the `recepientStore` structure? This would eliminate the need of creating a new data structure just for the profile keys. (I don't really know how signal-cli's handles its data internally, other then what I can see in its user data file; so this is just a guess)

**Comment by exquo** [comment]
Now (v0.6.9) that there is `profileStore` in signal-cli's data file, this can probably be fixed? I've just tried to add my signal-cli number to a new group from a phone that is not in signal-cli's `contactStore`, and it automatically created a new contact in `contactStore`, so that has not changed. Is that just a vestige of the old behavior, or is creating a new contact in `contactStore` still needed?

**Comment by AsamK** [comment]
yes, that could changed, the key is also stored in `profileStore` now.
The code would need to be adapted to create a new entry in the profileStore instead of adding it to the `contactStore` and existing keys would need to be migrated to the `profileStore` as well.

**Comment by exquo** [comment]
Quick question related to this issue:

Does `contactStore` in the data file now contain _only_ the entries corresponding to the contacts on the phone? (plus persisting others, per above, if version of signal-cli predating this fix had been used). Is it empty when signal-cli is a master device?

I have recently received a message from a phone number who is not in my contacts, and the number has not been added to `contactStore`, only to `profileStore`. Just wondering if that's what's supposed to happen.

**Comment by AsamK** [comment]
Yeah only contacts from the master device and contacts you add manually in signal-cli

**Comment by exquo** [comment]
Makes sense, thank you!
