### ISSUE TITLE
Q: Re-downloaded signal-cli works as is

### ISSUE THREAD

**Issue by spetztest** [AsamK/signal-cli#329]
Hi,

I accidentally deleted the signal-cli directory, so as easy as it is, I re-downloaded and immediately tested. The result is that I can read the messages and send messages as is using the same signal number i registered prior to deleting the whole directory, just like nothing happened. is this normal? anything I need to be aware of? I didn't even register the same number again.

**Comment by AsamK** [comment]
The account data is stored separately from the program files (in `$XDG_DATA_HOME/signal-cli/ ($HOME/.local/share/signal-cli/)`)
So as long as you don't delete those, your account data is not removed.
