### ISSUE TITLE
group info requests for unknown groups crash signal-cli

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#33]
There is a groupinfo-request my signal-cli's message queue for a group which is unknown to that signal-cli instance.

signal-cli now crashes every time i want to receive:

```
signal-cli -u +49XXXXXX072 receive
Exception in thread "main" org.asamk.signal.GroupNotFoundException: Group not found: Mm2pLHHApwBVxoBzoez/2Q==
        at org.asamk.signal.Manager.getGroupForSending(Manager.java:560)
        at org.asamk.signal.Manager.sendUpdateGroupMessage(Manager.java:687)
        at org.asamk.signal.Manager.handleSignalServiceDataMessage(Manager.java:942)
        at org.asamk.signal.Manager.handleMessage(Manager.java:1093)
        at org.asamk.signal.Manager.retryFailedReceivedMessages(Manager.java:1014)
        at org.asamk.signal.Manager.receiveMessages(Manager.java:1024)
        at org.asamk.signal.Main.handleCommands(Main.java:378)
        at org.asamk.signal.Main.main(Main.java:67)
```

Since the message is apparently not removed from the queue, it is the first to be retrieved the next time, and thus signal-cli crashes again.

**Comment by AsamK** [comment]
thanks, fixed

**Comment by Trolldemorted** [comment]
i have to thank you for the quick fix!

another odd thing:
I have now two phone numbers, both with signal-cli master instances.
One of them was missing a group, so it requested a group update from the other one.
The donor replied correctly, but i saw a "Updated the group."-message popping up in a signal-desktop linked to the donor. Since that was no "XYZ updated the group"-message (and it was displayed on the right side like messages from self), i assume it was definitely sent by the donor. I had a look at your sourcecode, but found nothing that would explain it. Afair Signal-Desktop complained about an unknown group message in the logs (which is reasonable since it does not support these sync messages yet i guess), unfortunately the log was lost in a crash.


I suppose removing groups from the groupStore and receiving a message from them could reproduce this (asking beforehand, i do not want to corrupt my master devices)?

**Comment by AsamK** [comment]
The "Updated the group" message in signal-desktop is to be expected. libsignal-service automatically sends a sync message to linked devices for all messages sent by signal-cli, including the group update message. Signal-Android will probably behave the same way, unless an additional method gets added to libsignal-service, that allows to not send the sync message.
Removing a group from the group store can be used to reproduce this.

**Comment by Trolldemorted** [comment]
Don't you think suppressing these sync-sent messages would be a good idea?

If the recipient is offline for a longer period, the donor will send a group update for every message he sent in the meantime, and all of his/her devices will drown in group updates.

**Comment by AsamK** [comment]
I agree, however I'd like to wait for stable versions of Signal-Android and -Desktop to get this feature, to see how they will handle this issue.
