### ISSUE TITLE
Registration fails 0.6.8

### ISSUE THREAD

**Issue by ognjen011** [AsamK/signal-cli#332]
Does anyone know why in 0.6.8  registration fails with 
          Error loading state file: null
The file with a telephone number exists ~/.local/share/signal-cli/data/+XXXXXXXXXXX
Is this related to the captcha issue in some of the threads?

**Comment by notbka** [comment]
I have read that this might happen when you try to register with a vps or server. You could try to register the number at home on local machine and then copy the Directory to your Server. I have the same issue with my digital ocean vm. I’ll try tomorrow and add my results here.

**Comment by derricw** [comment]
This also happens when registering on Windows WSL.

**Comment by AsamK** [comment]
closing old issue
