### ISSUE TITLE
Use Signal on Windows without a smartphone

### ISSUE THREAD

**Issue by szepeviktor** [AsamK/signal-cli#333]
Hello! I've hacked my way through using signal-cli instead of a smartphone+Signal app.

Please share my findings somewhere.
https://gist.github.com/szepeviktor/2c6a19cb91c4bb561369707f22bcf413

There could be users seeking help to start.

**Comment by AsamK** [comment]
You can put a link to it on the wiki page :)
https://github.com/AsamK/signal-cli/wiki

**Comment by szepeviktor** [comment]
Thank you.

Done.
