### ISSUE TITLE
Non-error messages printed to stderr

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#334]
Executing the `updateContact` command with
```
signal-cli -u +XXXXXXXXXXX updateContact +XXXXXXXXXXX -n 'New Name'
```
it prints to stderr:
```
Updating contact +XXXXXXXXXXXX name Old Name -> New Name
```
and returns successfully (exit code 0). Most other signal-cli commands don't write to stderr on success, so I'm guessing in this case it's unintentional.

Other instances of this I have found in the code, all of them in the `Manager.java` file:
```java
System.err.println("Add contact " + contact.number + " named " + name);
System.err.println("Updating contact " + contact.number + " name " + contact.name + " -> " + name);
System.err.println("Adding and " + (blocked ? "blocking" : "unblocking") + " contact " + address.getNumber().orNull());
System.err.println((blocked ? "Blocking" : "Unblocking") + " contact " + address.getNumber().orNull());
System.err.println((blocked ? "Blocking" : "Unblocking") + " group " + Base64.encodeBytes(groupId));
```
This was probably meant to be `out.println` instead of `err.println`.

**Comment by AsamK** [comment]
Yeah, I guess those shouldn't log to stderr.
If the command was successful, it should only print something if there's additional information.
Probably most of these could just be removed.
