### ISSUE TITLE
updateProfile does not appear to change anything

### ISSUE THREAD

**Issue by AetherUnbound** [AsamK/signal-cli#336]
Hello! First off, thanks for all the work and effort you've put into this tool. The extensive documentation you have made it incredibly easy to get going. I'm very excited to continue using it!

I've been trying to change profile information with the `updateProfile` command, and while it exits successfully, nothing changes for other contacts of the linked number (the profile has and continues to be just the phone number). The command I'm using:
```
./signal-cli -u +<number> updateProfile --name <name> --avatar <path/to/avatar.png>
```

This is getting exit code zero. Any thoughts?

**Comment by AsamK** [comment]
Looks like the upstream profile api has changed. I've updated libsignal (e6c1e03e212580989534b987deda27a2a7422549) and with the latest master version it should work again.

**Comment by AetherUnbound** [comment]
Awesome, thank you! I ended up using a physical device to change these attributes, but it's good to know this will work once again :slightly_smiling_face:

**Comment by AetherUnbound** [comment]
Would it be possible to release a new version to include this change?

**Comment by AetherUnbound** [comment]
Update: I'm still using v0.6.8, but this appears to be working now regardless!
