### ISSUE TITLE
Fail to send message via dbus daemon (dbus-send)

### ISSUE THREAD

**Issue by androbey** [AsamK/signal-cli#343]
Hi all, 

I am trying to send a message via signal-cli dbus daemon as described in the DBus dedicated wiki page using version 0.6.8.

I set up a user `signal-cli` and registered with this user.  

When running command
`dbus-send --session --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:'<MY_TEST_MESSAGE>' array:string: string:'<RECEIVER_NUMER>'`

I get following error:
`Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.asamk.Signal was not provided by any .service files` 

I don't know why or what causes this. 

My signal.service file looks like this:

```
[Unit]
Description=Send secure messages to Signal clients
Requires=dbus.socket
After=dbus.socket
Wants=network-online.target
After=network-online.target

[Service]
Type=dbus
Environment="SIGNAL_CLI_OPTS=-Xms2m"
ExecStart=/opt/signal-cli-0.6.8/bin/signal-cli -u <MY_NUMBER> daemon --system
User=signal-cli
BusName=org.asamk.Signal

[Install]
Alias=dbus-org.asamk.Signal.service
```

Sending a message with command  `signal-cli --dbus-system send -m "Message" <MY_NUMBER>` works without problems. 

Am I missing something? I did follow the steps as described on the wiki page. Aside adjusting signal.service file I did not do any changes.
I am running this on a Raspberry Pi 4 with latest Raspbian OS.

**Comment by AsamK** [comment]
You need to use `dbus-send --system` instead of `--session`, when signal-cli runs on the system dbus instance.
