### ISSUE TITLE
Failure to get recepient profile: 403 code from signal servers

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#345]
In v0.6.9, sending messages to some of the contacts return an error:

	Failed to get recipient profile: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: org.whispersystems.signalservice.api.push.exceptions.NonSuccessfulResponseCodeException: Response: Response{protocol=h2, code=403, message=, url=https://cdn.signal.org/profiles/XXXXXXXXXX-XXXXXXXXXXX}

The message nevertheless does get sent.

When I open the url above in the browser I get `SEC_ERROR_UNKNOWN_ISSUER`; and in `wget`: 

	ERROR: The certificate of ‘cdn.signal.org’ is not trusted.
	ERROR: The certificate of ‘cdn.signal.org’ doesn't have a known issuer.
	
This only happens for some of the contacts. I don't see a pattern distinguishing the kind of contacts for which there is an error and which exit without it. Initially, none of the contacts were in signal-cli's data file's `profileStore`. 

For the contacts affected by this, the 'delivered' `receiptMessage`s do not show up right: when sending the message goes without errors, the 'delivered' receipt message looks like this:

	{'source': '+XXXXXXXXXXX', 'sourceDevice': 1, 'relay': None, 'timestamp': 15997574XXXXX, 'isReceipt': False, 'dataMessage': None, 'syncMessage': None, 'callMessage': None, 'receiptMessage': {'when': 15997574XXXXX, 'isDelivery': True, 'isRead': False, 'timestamps': [15997572XXXXX]}}

For the messages sent with an error, the receipts are:

	{'source': '+XXXXXXXXXXX', 'sourceDevice': 1, 'relay': None, 'timestamp': 15997565XXXXX, 'isReceipt': True, 'dataMessage': None, 'syncMessage': None, 'callMessage': None, 'receiptMessage': None}

The 'read' `receiptMessage`s work normally for all contacts.

**Comment by AsamK** [comment]
The certificate error is to be expected, because signal uses its own self-signed certificate (in signal-cli the certificate is bundled in the `whisper.store` file). For wget you could use `--no-check-certificate` to ignore the check ...
signal-cli 0.6.9 now also fetches profile pictures and for some reason those seem to be failing with 403 in your case ... 

If signal-cli fails to download a profile, it can't send "unidentified sender messages" anymore and falls back to sending them normally. That explains the different delivered receipts. Unidentified sender messages trigger a receiptMessage on the receiving client and messages sent normally trigger a response envelope where the isReceipt flag is set. It would probably be a good idea to unify the signal-cli output so it doesn't depend on the underlying protocol implementation.

**Comment by exquo** [comment]
Ok that makes sense. It's not a certificate issue then. 

I didn't realize signal-cli always tries to send the "unidentified sender" messages (when it can), that's good to know. 

In #328 you've mentioned that what's needed to send an unidentified message is the profile key of the recipient. FWIW, contact's profile key is still available in the `contactStore`, although now that might not be intentional any more. So (for now) it could fall back on that if there is no `profileStore` entry.

I can open a separate issue for the unified envelope format for both unidentified and regular messages. Then this issue can be just about the 403 return code from the signal servers.

**Comment by AsamK** [comment]
The profile key itself is not enough, it also requires the profile itself to check if the recipient can receive unidentified sender messages (by checking the `unidentifiedAccess` property).
The first fix would be to ignore all errors when fetching the profile picture, so it can still return the rest of the profile.

Not sure how to debug the 403 ... can you check if there's a correlation between failing recipient profiles and recipients that have a profile picture?

**Comment by exquo** [comment]
I see. Then skipping the profile picture would be a sensible fallback. 

Seems like there's no correlation between getting the 403 code and the contact having a profile picture. Some contacts without the profile picture don't get the error, some do. I haven't yet gotten an error from a contact with a profile picture, but I just haven't texted the people much yet since installing the new version of signal-cli. Will post back with any new information.

**Comment by AsamK** [comment]
I've implemented skipping the profile picture in case of an error and released v0.6.10 .
With that version sending messages to those contacts should work again.

**Comment by exquo** [comment]
Oh yeah I see that in v0.6.10 while the messages to those problematic contacts do get code 403 from the server, they are sent with 'unidentified sender' (judging by their delivery receipts), like the non-problematic ones.

Update: I have stopped getting 403 codes after turning my phone on and bringing up signal on it. That phone (which is my signal master device) has not been online for a long while - I've been relying exclusively on signal on the laptop. I guess something got synced up (contacts sync?), because now after sending a message to a contact from signal-cli, I always get a new profile in `profileStore` and no errors. 

I'll close this issue since it seems resolved for me. I guess the moral of the story is: it might be a good idea to connect the master device to the internet once in a while.
