### ISSUE TITLE
signal-cli fails to correctly save received information

### ISSUE THREAD

**Issue by netthier** [AsamK/signal-cli#347]
This only happens in 0.6.9, 0.6.8 is not affected.
When linking to an existing device, and running "signal-cli -u "xxx" receive", I noticed a lot of 
```
"Error saving file: value is absent (through reference chain: org.asamk.signal.storage.profiles.ProfileStore["profiles"])"
```
When later trying to send a message, I got 
```
"Error loading state file: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (sun.nio.ch.ChannelInputStream); line: 393, column: 20])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 394, column: 3345]"
```
OS is Debian 10, with OpenJDK-11-JRE installed, downgrading to 0.6.8 fixed this issue, although I had to delete the file in ~/.local/share/signal-cli/

**Comment by AsamK** [comment]
I've pushed a commit, that should fix the issue. Can you test the latest master?
Profiles for users without internal uuids weren't handled properly. Also errors during saving shouldn't corrupt the account file anymore.
