### ISSUE TITLE
Updating to New Groups.

### ISSUE THREAD

**Issue by techtasie** [AsamK/signal-cli#354]
It would be realy great for some notification Bot Project if it would not only support legacy groups but the new Groups too.

**Comment by adrianheine** [comment]
The `libsignal-service-java` version used already supports groups V2, right? What would be necessary for supporting them in signal-cli?

**Comment by techtasie** [comment]
When you add the signal-cli user to a V2 group you get the message that it is still on V1 Groups and the Group will be V1. (Happend In my case at 0.6.9)

**Comment by orthello** [comment]
Accounts using the signal-cli client (including 0.6.11) are beeing considered as "old clients" causing this (signal-cli enabled) account not beeing able to be added to (new style) groups. It is not a problem to add signal-cli enabled accounts to legacy groups.
No error or log enties at Signal-cli side. Only a message in the client of the signal user who is trying to add the signal-cli enabled user to a new (not legacy) style group

Has to do with this change in the Signal platform:
https://support.signal.org/hc/en-us/articles/360007319331

Message: translated from Dutch: "1 groupmember does not support new groups, so this group will be setup as a legacy group"
![NewGroupIssue](https://user-images.githubusercontent.com/2169696/98377425-11e53b80-2045-11eb-9d2f-772bb101f9fd.png)

**Comment by AsamK** [comment]
I currently don't have enough time to investigate, what's necessary to support for v2 groups.
signal-cli is shown as not supporting v2 groups because it doesn't set the corresponding capability.
After enabling that capability, signal-cli accounts could probably be added to those groups, but it wouldn't be able to handle the group messages, as those are quite different from the old groups ...
libsignal-service-java should provide the basic support for v2 groups but integrating that would need additional code in signal-cli.

**Comment by kt8345953** [comment]
Would honestly be willing to contribute monetarily to make this happen...I love the command line tool but can no longer be added to any groups created in the new version :( If anyone has figured out a workaround I'm all ears

**Comment by AsamK** [comment]
I've implemented rudimentary support for sending/receiving Group V2 messages.
Creating or updating them isn't implemented yet.

The group v2 support in libsignal-service-java requires the native [libzkgroup](https://github.com/signalapp/zkgroup) library to work, which is currently only included for x86_64 Linux. For other architectures the library needs to be compiled and provided where java can find it.

**Comment by kt8345953** [comment]
Just a heads up, I tried re-registering using the most recent version of the code on this repository (which is ahead of 0.6.12 by a few commits) and got the following error: "Error loading state file: Cannot construct instance of `org.asamk.signal.storage.groups.GroupInfo` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.asamk.signal.storage.groups.JsonGroupStore["groups"])"

**Comment by elsehow** [comment]
Hey all - just to check, does 0.6.12 support sending/receiving Group V2 messages?

**Comment by AsamK** [comment]
The just released v0.7.0 has support for v2 groups.

**Comment by Atomic-Bean** [comment]
> Hey all - just to check, does 0.6.12 support sending/receiving Group V2 messages?

I am unsure about v0.6.12, but [the new v0.7.0](https://github.com/AsamK/signal-cli/releases/tag/v0.7.0) is able to both send and receive v2 group messages.

If you aren't on "linux x86_64" and don't have libzkgroup setup, [this](https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal) and [this](https://github.com/AsamK/signal-cli/discussions/380#discussioncomment-212235) have some information on setting it up.

**Comment by piramiday** [comment]
is there anything to do to accept a V2 group invitation?
I have invited the bot to a test V2 group, but it's not a member yet -- `listGroups` is yielding `Active: false` but I haven't seen a new `enterGroup` command. what should I do?

anyway, thanks for supporting groups V2 so fast!

**Comment by AsamK** [comment]
Accepting invitations is not implemented yet.
Apparently users can only be added to a group directly if they have set a profile and sent any message to the group creator (to share their profile key).
A profile can be created with signal-cli updateProfile.

**Comment by piramiday** [comment]
huh, but my bot does have a profile and messages me constantly. how come it did not enter the V2 group?
