### ISSUE TITLE
OpenJDK server warning

### ISSUE THREAD

**Issue by Protoncek** [AsamK/signal-cli#358]
Hello!
I have RPi4 and i just freshly installed Octoprint on it, including Signal Notifier plugin.  I also installed this Signal-cli. I also used "sudo apt-get install default-jre" for Java installing and installed Signal and needed numbers, PIn's ... as per insctructions. Signal works (it sends SMS), but at every command (in putty) i get following warning:

`OpenJDK Server VM warning: You have loaded library /tmp/resource5078850275409730450.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
`

Java version is 11. I tried to install older versions, but in version 8 and 9 signal gives error (compiled with more recent version)

I searched quite a lot and just can't find any solution for this. Any suggestions? How to "fix library"? Command "execstack" is unknown to Pi ,so i used "sudo apt-get install execstack" but fixing the library as suggested in warning gives "no file found" and  option -noexecstack is unknown to pi...

any clues?

Thanks!

**Comment by AsamK** [comment]
That warning can be ignored ... it's caused by the libzkgroup library, which is only provided as a x86 version by libsignal-service.
libzkgroup is a requirement for the new group v2 feature, which signal-cli doesn't support yet.

Related: #344

**Comment by Protoncek** [comment]
Great, thanks a lot for explanation! So, i guess that now i could uninstall "execstack"... 
And, thanks for great piece of software!

Best regards, Pavel
