### ISSUE TITLE
group updates are not sent to slave devices

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#36]
Steps to reproduce/prove:

- have 2 cli instances linked to 1 phone number
- create a new group on the master: `signal-cli -u +49XXXXXX072 updateGroup -n "test3"`
- receive on the other one `signal-cli -u +49XXXXXX072 receive`

Even though the group is properly saved into the master's groupstore, the creation/update is not sent to the slave, and neither are subsequent group updates.

[Edit: I guess i found [the culprit](https://github.com/AsamK/signal-cli/commit/8bfef24ef787be0e4dee0ca054e6c128afdf0c55#diff-3a15786ae5f2f4f973400cb09efa5808R678) - this method is also called for common group updates, so you should not always remove yourself]

**Comment by AsamK** [comment]
Group updates are sent to linked devices, if the group has at least one member, via a sync message. libsignal-service doesn't send the sync message, if there are no recipients of the update message. 
I have to exclude myself from the group update recipients, otherwise the linked devices will get the update twice, once directly and once via the sync message.

**Comment by Trolldemorted** [comment]
i assure you, i created a group without any explicit membesr (which should result in a group with only myself) and it was not sent to the sibling devices.

**Comment by AsamK** [comment]
that's what I meant to say, a group without other members, i.e. with only yourself, are not sent to linked devices. Fixing this would either have to modify libsignal-service to send sync messages, also if there is no recipient, or to send the update message to yourself, which would lead to duplicate update messages on the linked devices. I don't plan on fixing this, as a group with only yourself is not very useful.

**Comment by Trolldemorted** [comment]
Unfortunately this is the only way to send messages from Signal-Android to yourself at the moment.

Would you consider sending only the update message and no sync-sent message to all members, if libsignal progresses in that direction? Because that is what i would propose to [hide the sent group messages from recovery requests](https://github.com/WhisperSystems/Signal-Android/commit/6ae9db56b184d7ca87eb0e3ce643f9f8d78e7080#commitcomment-19978914).
