### ISSUE TITLE
Add option to trust unverified on send

### ISSUE THREAD

**Issue by iexos** [AsamK/signal-cli#360]
I have a bot that is sending messages to a group. Sometimes safety numbers change. Sending to the group after a change fails for the new device, which is good in principle.

However, I cannot verify these new safety numbers anyway. This makes the process of sending a message a lot more complex (and taking longer): I would have to check before every message if there are new untrusted keys in the group, remove or trust these identities, and then send.

My proposition: Add an option to `send` command, to trust new keys unverified. This is the practical behaviour with most Signal users anyway.

**Comment by adekloet** [comment]
I have the same issue, I moved signal to a new phone and now HA (signall add-on in supervised HA) does not trust and will not sent notifications. Where do I do the change with the Add new --trust-new-identities global parameter ?

Thanks very much for any pointers..

**Comment by kepi** [comment]
@adekloet you can change it in `/etc/default/signal-cli` (at least on Debian), just append it to  `SIGNAL_CLI_PARAMS` variable.
