### ISSUE TITLE
Cannot deserialize instance of `java.lang.String`

### ISSUE THREAD

**Issue by Ostropol** [AsamK/signal-cli#362]
I am rather new to the whole coding and Linux community, so excuse me for my lack of knowledge! I managed to get signal-cli working for sending messages, but I can't seem to get the daemon to run.

Every time I type the command: 
**signal-cli -u (+number) daemon**

It gives me the following error I can't seem to solve:
**Error loading state file: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.asamk.signal.storage.groups.JsonGroupStore["groups"]->org.asamk.signal.storage.groups.GroupInfo["members"]->java.util.ArrayList[0])**

Does anyone know what might be the problem here?

**Comment by AsamK** [comment]
Are you using an older version of signal-cli? That error would appear if you use a data file created by a recent signal-cli, with a version below 0.6.6.
You can check the version with `signal-cli --version`

**Comment by Ostropol** [comment]
I do appear to have version 0.6.11, but I don't know how that's possible since I git cloned this yesterday. I have managed to get the signal daemon running, but apps like scli and signal-curses don't seem to work. Scli keeps giving me the error: 'Couldn't find any linked device' and signal-curses sais 'Config file is in use by another instance, waiting..." for as long as I have the daemon running.
