### ISSUE TITLE
signal-cli enabled user can not be added to new style groups (legacy groups are no problem)

### ISSUE THREAD

**Issue by orthello** [AsamK/signal-cli#364]
Accounts using the signal-cli client (including 0.6.11) are beeing considered as "old clients" causing this (signal-cli enabled) account not beeing able to be added to (new style) groups. It is not a problem to add signal-cli enabled accounts to legacy groups.
No error or log enties at Signal-cli side. Only a message in the client of the signal user who is trying to add the signal-cli enabled user to a new (not legacy) style group

Has to do with this change in the Signal platform:
https://support.signal.org/hc/en-us/articles/360007319331

Message: translated from Dutch: "1 groupmember does not support new groups, so this group will be setup as a legacy group"
![NewGroupIssue](https://user-images.githubusercontent.com/2169696/98377425-11e53b80-2045-11eb-9d2f-772bb101f9fd.png)

**Comment by centromere** [comment]
See #354

**Comment by orthello** [comment]
Oh Sh**....   excuse me. I hadn't seen issue #354
