### ISSUE TITLE
Link (provisioning) fails on android side with "No device found"

### ISSUE THREAD

**Issue by blakehawkins** [AsamK/signal-cli#365]
Following directions at: https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)

After scanning generated QR code, signal (app) says "No device found" in a toast and then nothing else happens.

Using latest android signal update and using a fresh install of signal-cli from `master`

**Comment by yjeanrenaud** [comment]
how did you generate the qr code? the wiki is not quite correct. I found out that android needs version 10 and level high.
so

`signal-cli link -n "optional device name" | xargs -l qrencode -o /tmp/qrcode.png --level=H -v 10 & while [ ! -f /tmp/qrcode.png ]; do sleep 1; done; xdg-open /tmp/qrcode.png`

**Comment by blakehawkins** [comment]
Hey @yjeanrenaud thanks for letting me know - that's worked for me too!

**Comment by AsamK** [comment]
thanks, I've updated the wiki page.
