### ISSUE TITLE
Map preview, when sending location via signal-cli

### ISSUE THREAD

**Issue by 0dd1er** [AsamK/signal-cli#366]
How do my recipients get a nice preview map when sending a location?
When receiving a location (with preview) by signal-cli it basically includes a google map link.
But when sending a google map link, no preview map is displayed. Instead it contains the plain link address.

Any ideas?

**Comment by AsamK** [comment]
It looks like the signal app creates a preview map before sending the message and then just adds it as attachment.
So for signal-cli you'd need to create the preview image yourself and attach it.
