### ISSUE TITLE
Dropped support for java8, looking for an alternative

### ISSUE THREAD

**Issue by MichaelBitard** [AsamK/signal-cli#368]
Thanks for your amazing work on signal-cli, I use it daily in home assistant.

I saw that you recently upgraded the minimal jdk version to 11, and I understand why. The issue is, oracle dropped support for 32 bits system and I had signal-cli running on a raspberrypi 3, so armv7 32bits. That means I cannot use it anymore :(

I won't ask you if you could add back support for java8, I understand it's a really old version and it has been deprecated for quite some time now.

Do you know any alternatives to your project in another language?

**Comment by AsamK** [comment]
raspbian 10 (Buster) has a armhf 32bit openjdk build for java 11 and there's a generic openjdk build on adoptopenjdk.net:
https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot

**Comment by MichaelBitard** [comment]
Thanks, I'll have a look at it!
