### ISSUE TITLE
Recipient reinstalled signal, now messages sent to only this recipient are not received

### ISSUE THREAD

**Issue by Jehops** [AsamK/signal-cli#371]
Hi,

Thanks for writing signal-cli.  It's nice to be able to use signal with a minimal interface on a real keyboard.

I'm running signal-cli on FreeBSD 12.2.  I can send messages as usual to everyone except this one recipient.  The command `signal-cli -u +1xxx send -m "This is a test message." +1yyy` returns a timestamp, but when I look at the conversation on my phone, there is only one check mark and the recipient reports that he does not receive the message.  If I send the message from my phone, everything works.  I tried `signal-cli -u +1xxx receive` and `signal cli +1xx trust -v #### +1yyy` but no luck.

Am I missing something, or is this a bug?

**Comment by AsamK** [comment]
If the `send` command returns a timestamp and prints no error message then the message was sent correctly, but the receiver couldn't verify/decrypt it. You could try to reset the session with `signal-cli -u +1xxx send --endsession` and then send another message
