### ISSUE TITLE
Using the same number from multiple computers

### ISSUE THREAD

**Issue by gadric** [AsamK/signal-cli#372]
Hi, 

I am currently sending the Signal Messages using signal-cli from one of my servers. 

However, I would like to use the same number and signal-cli with multiple servers. However, I struggle to configure that. I was not be able to register 2 servers with the same number or configure the servers as „master“ and „slave“. 

Anyone has done this? Or is this not possible?

**Comment by cdpb** [comment]
It's possible via the `link` command.

https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)

**Comment by gadric** [comment]
Ah Thank you!
