### ISSUE TITLE
updateProfile required both name and avatar parts

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#377]
When using the updateProfile command, if I try to set just my name or just the avatar (Whether it be add or remove), but not both at the same time, then I get an error saying I entered invalid input.

It seems this command expects both the name and avatar fields even though having just one should make sense. This lines up with Asamk's comment in #227

**Comment by Atomic-Bean** [comment]
Looking at [the code](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/commands/UpdateProfileCommand.java), it seems name is used for setting the avatar on line 44 and hence used [here](https://github.com/AsamK/signal-cli/blob/6bfcba49406a3ac4f3d7fee51ca46c17e1a74680/src/main/java/org/asamk/signal/manager/Manager.java#L324) with the signal API call. Instead of this, can't it check the current name and use that rather than requiring a user to enter a name?

Similarly, I don't get why `signal-cli -u +XXXXXXXXX updateProfile --name cli2` shouldn't be allowed. I see the avatar is a required field and, although I'm not familiar with `try-with-resources` as used [here](https://github.com/AsamK/signal-cli/blob/6bfcba49406a3ac4f3d7fee51ca46c17e1a74680/src/main/java/org/asamk/signal/manager/Manager.java#L323), it appears like it should work if we also pass in the current profile picture.

Or maybe this is more complex than it needs to be and there are commands to update just the name or just the profile picture.

**Comment by AsamK** [comment]
The signal service API doesn't provide a way to set just the name or just the avatar, so both need to be set.
The current implementation in signal-cli could be improved but would then need to request the profile from the signal servers before updating them.

Currently to just set a name and no profile picture, the `--remove-avatar` switch needs to be used in addition to `--name`.
