### ISSUE TITLE
Verbose or Debug Mode with log function

### ISSUE THREAD

**Issue by gadric** [AsamK/signal-cli#379]
Hi, 

I want to integrate ```signal-cli``` to OMV in order to received everything send via email also via Signal. To do that, I aligned my approach with one that were used for the same purpose with Telegram: [guidelines on OMV forum](https://forum.openmediavault.org/index.php?thread/14919-guide-use-telegram-as-notification-service/). 

In accordance with the telegram guidelines, I have created a file with the following content: 

```
#!/bin/bash
sender="+00000000"
recipiant="+111111111"

echo -e "${OMV_NOTIFICATION_SUBJECT} on the ${OMV_NOTIFICATION_DATE} \n\n $(cat ${OMV_NOTIFICATION_MESSAGE_FILE})" | /usr/local/bin/signal-cli -u $sender send $recipiant
```

However, this script seems not to work. The same approach works with Telegram. 

**My question is now: How can I enable a debug mode or verbose mode in signal-cli in order to analyze the problem? 

And, does signali-cli require any kind of special environment variables?**

**Comment by Atomic-Bean** [comment]
What part doesn't work? Does it do nothing or produce an error, and if so what error does it give?

**Comment by gadric** [comment]
It does nothing. The Message ist not sent but I dont know why. That why I am asking if there is any kind of verbose or logging mechanism.

**Comment by Atomic-Bean** [comment]
Is "recipient" also another signal user? Has signal-cli been verified with the "sender" number? To test if you have a friend with Signal try manually running a command to send them something just so you know signal-cli is setup.
