### ISSUE TITLE
Multiple instances of signal-cli

### ISSUE THREAD

**Issue by MichaelBitard** [AsamK/signal-cli#38]
I'm writing a hubot adapter to communicate via signal, and I'm using signal-cli.

Is there a way to launch multiple signal-cli instances ? Right now I have one signal-cli receiving messages, but I need another instance to send back messages from the hubot.

I havent been able to use the daemon with oracle jvm and unix-java on debian (and I'm willing to put the hubot in a docker container) so I was wondering if you had an idea.

**Comment by AsamK** [comment]
I'm running the daemon OpenJDK 7 and the `libunixsocket-java` package. If you want to use the system bus for the daemon, you must configure your dbus permissions, there's an example in https://github.com/AsamK/signal-cli/blob/master/data/org.asamk.Signal.conf .

Multiple instances of signal-cli cannot run at the same time. It could be doable, but needs extensive changes to the config file and lock handling. signal-cli needs to save new identities and updated session data, when sending and also when receiving messages.

**Comment by MichaelBitard** [comment]
Thanks, I'll give it a try with the openjdk!
