### ISSUE TITLE
can't send messages anymore due to dbus-system trust not implemented

### ISSUE THREAD

**Issue by yjeanrenaud** [AsamK/signal-cli#382]
some recipients have changed their keys and thus they are untrusted now. But I can't trust them again so every time I try to send a message to them I get 
`Failed to send message: Untrusted Identity for "+NUMBER": Untrusted`

what's to do now? how can I force the dbus client to learn this identity again?

**Comment by yjeanrenaud** [comment]
I edited the storage manually:
`sudo systemctl stop signal.service
sudo cp /var/lib/signal-cli/data/+YOURNUMBER /var/lib/signal-cli/data/+YOURNUMBER.bak
sudo vi /var/lib/signal-cli/data/+YOURNUMBER
`
and there I removed all entries which included the numbers I knew that changed they keys. 
then obvioulsy 
`sudo systemctl stop signal.service`

a mess it is, but it works.

**Comment by AsamK** [comment]
You can use `signal-cli trust` to trust a new identity, though you also need to stop the signal-cli daemon for this.

**Comment by yjeanrenaud** [comment]
that does not work as the username is not registered to signal-cli but to --dbus-system.

**Comment by yjeanrenaud** [comment]
nope, still 'User is not registered'.

**Comment by cuu508** [comment]
It would be great if there was a more streamlined solution for this. Perhaps an optional "I don't care about security, please automatically trust" boolean parameter for sendMessage?

My use case (which I'm guessing should be fairly typical): I run a web service that delivers notifications via various channels, including Signal. It knows recipient's phone number, and that's it. If recipient changes their keys, it is not practical to contact them out of band and verify the security number. We still only have their phone number and want to send notifications to it. The contents of the notifications are private but not *particularly* sensitive. 

signal-cli runs as a daemon, and the web service sends messages via dbus. There are a couple problems with manually running `signal-cli trust`:

* Need to stop the daemon, run `signal-cli trust`, and start the daemon again. During this time, the web service cannot send messages
* For redundancy, the service runs on several machines concurrently (all registered as linked devices of the same Signal account). Need to repeat this procedure on each machine.
* My service has several hundreds of Signal recipients. I'm not sure how to keep track which ones have become unverified, and need to be trusted again.

**Comment by AsamK** [comment]
There's an open enhancement issue for a trust unverified option, see #360

**Comment by cuu508** [comment]
Thanks, yep, that's the same use case, subbed!

**Comment by yjeanrenaud** [comment]
as a workaround, I do use a cronjob with a script to trust all in the address book
