### ISSUE TITLE
Receive with JSON is missing reactions field

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#383]
If someone adds or removes a reaction, when you run `signal-cli -u +XXXXXXXXXX receive` then you'll see the emoji and its "Is remove" status, but if you run receive with `--json` enabled then there is no reaction information present.

Tested on latest signal-cli build in a 1-on-1 conversation.

**Comment by AetherUnbound** [comment]
Additionally, any new group info for V2 groups does not appear in the JSON output (though it does appear in the non `--json` output)

**Comment by Atomic-Bean** [comment]
Yeah I noticed that too, group stuff is just null as well as #151 (Which affects regular JSON mode, not just daemon).

**Comment by Atomic-Bean** [comment]
It seems that the problem for this issue and a bunch of related ones lies in [this file](https://github.com/AsamK/signal-cli/blob/4d17e50323bcce21718d0bc2406c9f63db0f6f73/src/main/java/org/asamk/signal/json/JsonDataMessage.java#L20)

That is the class that takes Signal's `SignalServiceDataMessage` (The thing with all the message fields, reactions, quotes, etc included) and converts it to a format ready for the `JsonMessageEnvelope` [here](https://github.com/AsamK/signal-cli/blob/44851887894ed9162006ad9b12309e732aa3e876/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java#L38) which is then turned into a POJO [here](https://github.com/AsamK/signal-cli/blob/4d17e50323bcce21718d0bc2406c9f63db0f6f73/src/main/java/org/asamk/signal/JsonReceiveMessageHandler.java#L38) and is finally used in the receive output logic [here](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/commands/ReceiveCommand.java#L165).

We can see its possible to get the same info in Json as the plain-text output because the plain-text output also uses `SignalServiceDataMessage` as seen [here](https://github.com/AsamK/signal-cli/blob/4d17e50323bcce21718d0bc2406c9f63db0f6f73/src/main/java/org/asamk/signal/ReceiveMessageHandler.java#L347)

And as for @AetherUnbound 's comment, I believe [this line](https://github.com/AsamK/signal-cli/blob/4d17e50323bcce21718d0bc2406c9f63db0f6f73/src/main/java/org/asamk/signal/json/JsonDataMessage.java#L23) is the reason. If I'm reading that right its only attempting to add v1 group info even though it could do v2 info

I could be wrong on this, I'm not familiar with the code of either signal-cli or signal's protocols, but I think this is the root of the problem.

**Comment by AsamK** [comment]
I've added the group ids also for v2 groups now (73db42b6918d5415f05d2e09e332c5a60df686db).
As you saw, the reactions and quoted replies are just not implemented yet ...

**Comment by Atomic-Bean** [comment]
I'd like to have a go at implementing reactions. ATM I've made some changes that allow it to partially work, but I don't have a good reference for the Signal-API/Protocol stuff. What do you refer to for that stuff?

**Comment by AsamK** [comment]
Nice.
There's no public reference, that I know of. Signal had some white papers, but only for the cryptography protocols.
I mostly look at how the Android clients does things.
https://github.com/signalapp/Signal-Android

**Comment by AsamK** [comment]
implemented in 58db3cbd53f3faec94ddfcd5e029865a380e6242
