### ISSUE TITLE
No group names in data file for V2 groups

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#386]
Thanks for implementing the support for the new groups! There seems to be an issue with the new groups though:

The group names are not shown in signal-cli's data file (`~/.local/share/signal-cli/data/+XXXXXXXXXXX`). The json record contains only this:

```
  "groupStore" : {
    "groups" : [ {
      "groupId" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=",
      "masterKey" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=",
      "blocked" : false
    }
		...
```

**Comment by AsamK** [comment]
The new groups are quite different, the authoritative group data is stored encrypted on the server and not only on each member's device, as with the old groups.
The groups also contain a lot more information (permissions, admin, requesting members, pending members, ...) so I decided to not store the group information in the json file.
Instead signal-cli stores the group information in separate files: `~/.local/share/signal-cli/data/+XXX.d/group-cache/GROUP_ID_IN_HEX`
The groups are stored as a `DecryptedGroup` protobuf message (defined in libsignal's `DecryptedGroups.proto`)

**Comment by exquo** [comment]
That makes sense, thank you! I'll extract the info from the protobuf file then.

**Comment by exquo** [comment]
Just a note here for others who might have the same question: 

If all you need is a group name, it can be obtained with signal-cli's own commands `listGroups` or a dbus `getGroupName` command. For other information about the new-style groups (e.g. group's avatar, #392), you would have to dig into the protobuf file as AsamK has mentioned. 

Below are some tips on dealing with protobuf files in hope they might be helpful.

---

The data included in protobuf is specified in this file:
https://github.com/signalapp/Signal-Android/blob/master/libsignal/service/src/main/proto/DecryptedGroups.proto
It also depends on the `Groups.proto` file in the same dir.

To interact with protobufs in your programming language, you will need to compile the above file with `protoc` (a release can be downloaded from [here](https://github.com/protocolbuffers/protobuf/releases/) or installed with a package manager, e.g. `protobuf-compiler` on Debian)

```
cd <...>/Signal-Android/libsignal/service/src/main/proto     
	# or wherever you've copied the two .proto files
protoc  --python_out=<PATH_TO_WHERE_YOU_WANT_GENERATED_BINDINGS_FILES>   ./{Groups,DecryptedGroups}.proto
```

The above example generates python bindings; use a different `--<LANG>_out` flag for another language.

Then you'll need to install protobuf bindings for your chosen language. For python, they can be downloaded from the 'releases' link above (or with `pip install protobuf`, or `apt install python3-protobuf`, etc).

To read the protobuf file with python:

```python
import DecryptedGroups_pb2
fo = open(
        '/home/user/.local/share/signal-cli/data/+XXXXXXXXXXX.d/group-cache/6d79de0fce6d7b4ddd23fa244a4d397dd3c12abf377588bdd9dda720bd3ce9f470',
        'br'
    )
bs = fo.read()
dg = DecryptedGroups_pb2.DecryptedGroup()
dg.ParseFromString(bs)
print(dg)
```

Put this file in the same dir as the generated `<..>_pb2.py` files.

Finally, a convenience function to get the hex representation of the group id (i.e. the `../group-cache/6d79de...` filename above):

```python
import base64
def b64_to_hex_str(group_id):
    return base64.b64decode(group_id.encode()).hex()
group_id = "bXneD85te03dI/okSk05fdPBKr83dYi92d2nIL086fRw="
print(b64_to_hex_str(group_id))
```

**Comment by exquo** [comment]
I've decided to reopen this as a feature request after all: to add to the data file all the group info that the old groups have (`name`, `members`, `archived` status etc) for the new (v2) groups too.

I imagine that many projects using signal-cli need that simple info and do not require the v2 stuff (`accessControl`, `pendingMembers`, etc). Since signal-cli already has the capabilities to query this info about v2 groups (with `getGroupName`, `getGroupMembers` commands), it would be more convenient to simply put this info in the data file. 

This avoids the need for all the downstream projects to require extra dependencies, figure out protobufs and bundle its build files with their projects. It would also present a uniform data structure for the (common types of) group info, regardless of whether it's old or new. Of course the projects that do require v2 type info would still need to use the protobuf file.

I don't think data duplication (between the group-cache/protobuf file and signal-cli data file) should be an issue: on group info "update" events, the protobuf file needs to be simply stored, and the data in data file updated just like for the old groups.

In the signal messenger interface I'm working on, the contacts data is loaded on startup and displayed right away, while signal-cli daemon is loading in the background. So querying the data from signal-cli daemon with `getGroupName` etc is not an option until the daemon has loaded. This can be worked around in some ways, but it would certainly be much simpler to use the existing groups data structure. That last sentiment is probably shared by other signal-cli users :)

**Comment by AsamK** [comment]
I've thought about it, but I won't store the duplicate data in the json file. Maybe you could cache the response from the getGroupMembers command to have it available before signal-cli has started.

And FYI I've changed the `group-cache` file names to match the avatar file names, i.e. base64 encoded with `/` replaced with `_`, instead of hex encoding

**Comment by exquo** [comment]
Understood. Thanks for letting me know! Yes, caching the group names & members is an option. For now I'm adding a callback hook when the daemon is initialized and send it those queries through dbus. And before the daemon loads, I can jury-rig the group names from the binary cache file. Not as straightforward as parsing the json data, but seems to work.
