### ISSUE TITLE
Received v2 group info in JSON is missing name/members fields

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#388]
First off, thanks for the quick update with v0.7.1. The features added are very useful 😄 

When I run the receive command in JSON mode I see something like this
```
{"envelope":{"source":"+XXXXXXXX","sourceDevice":2,"relay":null,"timestamp":1234567890,"dataMessage":{"timestamp":1234567890,"message":"SENDERS-MESSAGE-TEXT","expiresInSeconds":0,"attachments":[],"groupInfo":{"groupId":"[THE CORRECT GROUP ID]","members":null,"name":null,"type":"DELIVER"}},"syncMessage":null,"callMessage":null,"receiptMessage":null}}
```
The group Id is correct, but the name and members fields are missing. Running `listGroups -d` shows the full info for the group
```
Id: [THE CORRECT GROUP ID] Name: [THE CORRECT NAME]  Active: true Blocked: false Members: [+XXXXXXXXXX, +XXXXXXXXXX] Pending members: [] Requesting members: [] Link: -
```

Personally I don't think its worth bothering to print the members list here since for bigger groups that would just clutter the output and you can always use `listGroups -d` to see the full list (Also the plain-text print also doesn't show the members list either, which feels like a good choice). Either way its a low priority issue, the group ID is the important part and that's working perfectly

Using the latest build, v0.7.1 / 83d5d53 .

**Comment by AsamK** [comment]
I've thought about it and won't add group name/members to the receive message output.
The information also be obtained from the listGroups command.
