### ISSUE TITLE
Receiving message with 2+ quoted attachments only shows one attachment

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#390]
I am unsure if this is a signal-cli bug or a restriction of the Signal API, but if there's a message with two attachments and someone then replies to that, `signal-cli -u +XXXXXXXX receive` will only list the first attachment.

(Note that receiving the original message earlier did contain both attachments)

**Comment by AsamK** [comment]
this should work already, there was a small display issue so two attachments were hard to distinguis in the output ...
