### ISSUE TITLE
No v2 group avatar in avatar folder

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#392]
In the config/avatar folder I see avatar pictures for my contacts, but I don't see any for any (v2) groups I'm in. I see in `Manager` we have `createGroupAvatarAttachment()` which looks fine, but its only called in `sendGroups()` and only for v1 groups.

I'm not exactly sure on the purpose/format of `sendGroups()` is and hence not sure what needs to be done for `out.write()` to implement the v2 group saving.

**Comment by AsamK** [comment]
The avatar for v2 groups is currently only stored in the cached DecryptedGroup protobuf file in the group-cache folder.
To also store it as a separate file, the avatar bytes from that structure would need to be saved each time after downloading or updating new group information.

**Comment by exquo** [comment]
I've been tinkering with the protobuf file (see [#386](https://github.com/AsamK/signal-cli/issues/386#issuecomment-750862954)), and for groups that have the avatar set, the only info in the protobuf file seems to be:

```
avatar: "groups/<GROUP_ID>/XXXXXXXXXXXXXXXXXXXXXX"
```

where `<GROUP_ID>` has `/` in it replaced with `_` and the final `=` removed. What the `XXX..` stuff after the slash is, I don't know.

I'm guessing the protobuf file stores not the avatar picture itself, but a link to it on Signal servers.

**Comment by AsamK** [comment]
ah ok, this is just the path on the cdn where the avatar is stored.
Looking at `AvatarGroupsV2DownloadJob` in Signal-Android to download the file `SignalServiceMessageReceiver.retrieveGroupsV2ProfileAvatar` can be used and `GroupV2Operations.decryptAvatar` to decrypt it.
