### ISSUE TITLE
Cannot send Note to Self [zkgroup dependency]

### ISSUE THREAD

**Issue by Android-X13** [AsamK/signal-cli#397]
In the past I was able to send a message to myself without issues with some previous version of signal-cli. Now in 0.7.1 although I'm able to send messages to others via `signal-cli -u [NUMBER] send -m "MESSAGE" [NUMBER]`, I can't send to myself (i.e when both numbers are the same in the command). This is the error message I get:

> OpenJDK Server VM warning: You have loaded library /tmp/resource7807996408603656482.so which might have disabled stack guard. The VM will try to fix the stack guard now.
> It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
> [main] WARN org.asamk.signal.Main - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
> Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.signal.zkgroup.internal.Native

So I've built signal-cli according to the instructions, I removed the bundled lib from the jar file following [this](https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal), I downloaded `libzkgroup.so` from [here](https://github.com/signalapp/zkgroup/releases), I added the .so file to the java library path with [this ](https://stackoverflow.com/a/16233331)method, and then I executed the above signal-cli command to get the following error message:

> OpenJDK Server VM warning: You have loaded library /my/path/to/libzkgroup.so which might have disabled stack guard. The VM will try to fix the stack guard now.
> It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
> [main] WARN org.asamk.signal.Main - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
> Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.signal.zkgroup.internal.Native

The only difference being that it loads the downloaded .so file, but still throws the same error.

I also tried to compile libzkgroup for my system, but I couldn't install Rust correctly and `make libzkgroup` was throwing errors

> error: command failed: 'cargo'
> error: caused by: No such file or directory (os error 2)
> make: *** [Makefile:41: libzkgroup] Error 1

Although `$HOME/.cargo/bin` was added to `$PATH`. I accidentally found [this ](https://vercas.com/2019/11/05/wireguard-pbp.html) article about an unrelated Rust binary, according to which the right arch should be armhf when the device uses a 64bit kernel with 32bit userland (which applies to my device, Vero 4K). So in Rust installer I chose `armv7-unknown-linux-gnueabihf` instead of `aarch64-unknown-linux-gnu` and I was able to install Rust & `make libzkgroup` finally completed without errors. Then I followed [this ](https://github.com/AsamK/signal-cli/discussions/393) for the remaining steps, to complete the installation and... I still get the same errors.

Is it possible to solve this `libzkgroup` dependency issue? Or perhaps there's a simple way that I don't know of to send messages to myself without having to deal with libzkgroup?

3.14.29-160-osmc aarch64 GNU/Linux

**Comment by AsamK** [comment]
I've added a small workaround that should fix sending self messages if libzkgroup is not available.

**Comment by Android-X13** [comment]
Thank you very much @AsamK for your fast response. I've rebuilt signal-cli from scratch after your commit and I can confirm I'm now able to send messages to myself without issues.
