### ISSUE TITLE
Registration Error: "Invalid username (phone number), make sure you include the country code."

### ISSUE THREAD

**Issue by MadManMoon** [AsamK/signal-cli#399]
Hiya, when I use either the `register` or `register --voice` commands with my US Google voice number I'm getting the following error:

> **_Invalid username (phone number), make sure you include the country code._**

Here's both commands:
`./signal-cli -u +1########## register`
`./signal-cli -u +1########## register --voice`

Am I doing something monumentally stupid here?

I don't have a cellphone to assist me here, and I'm hoping that your CLI is my magic bullet to finally get on Signal.

**Comment by AsamK** [comment]
The register command looks good. signal-cli is using google's libphonenumber to normalize and validate the phone number, that's where the error comes from.
You can enter your phone number on the libphonenumber demo page to get more information what might be wrong with the phone number: https://libphonenumber.appspot.com/ (you can ignore steps 2 and 3 on that page and only enter the phone number)

**Comment by MadManMoon** [comment]
Ah, cheers, @AsamK , so it it perhaps on some kind of DB of IP numbers or something?

(am reading that link now)

**Comment by MadManMoon** [comment]
This issue was resolved by copying the "_E164 format_" result from the [appspot link](https://libphonenumber.appspot.com/) in @AsamK 's post above.

**Comment by MadManMoon** [comment]
This issue was resolved by copying the "_E164 format_" result from the [appspot link](https://libphonenumber.appspot.com/) in @AsamK 's post above.
