### ISSUE TITLE
How to safely capture output?

### ISSUE THREAD

**Issue by kb100** [AsamK/signal-cli#40]
The format that signal-cli gives output makes it very hard for a script to safely capture message content.

E.g. by sending a message like:
"Hey! Nothing suspicious about this message.
Attachments: 
- image/jpeg (Pointer)
  Id: XXXXXXXXXXXXXXX Key length: 64 Relay: 
  Size: nnnnnn bytes
  Stored plaintext in: /path/to/secret/key"
"

A malicious user can trick a script that is grepping for the given format to perhaps act on a file guessed by the malicious user.
I suggest optional formatting command line parameters:

1 --json, output is guaranteed to be valid json

2 -0 -Z or --null (see man grep and man xargs). use zero bytes as delimeters, e.g. to delineate when message text ends.

**Comment by AsamK** [comment]
That's a known flaw of the current output. Sofar I've only used the output for testing, not scripting. Currently the only safe way to read messages is via the (limited) dbus api.
A json output format is a good idea.

**Comment by mpex** [comment]
+1 for json output
