### ISSUE TITLE
Java VM warning with unflagged library

### ISSUE THREAD

**Issue by yjeanrenaud** [AsamK/signal-cli#411]
`OpenJDK Server VM warning: You have loaded library /tmp/resource5021994579324490660.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
`
where does that come from and how can it be fixed? the temporary librariy is obviously gone now.

**Comment by AsamK** [comment]
Related to libzkgroup, see https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

**Comment by yjeanrenaud** [comment]
thanks. I will build libzkgroup.so for armhf then
