### ISSUE TITLE
"receive" leads to empty contacts

### ISSUE THREAD

**Issue by inco8nit** [AsamK/signal-cli#412]
Hi!

I've been trying to link my existing Signal account with ``signal-cli`` to use it with one of the TUI programs referenced in the wiki.
Unfortunately after repeating the linking process multiple times the contacts remain empty.

```json
  "contactStore" : {
    "contacts" : [ ]
  }
```

When using ``signal-cli -u +[NUMBER] receive`` for the first time I get the following error multiple times:
```
[main] ERROR org.asamk.signal.manager.storage.SignalAccount - Error saving file: Cannot invoke "org.asamk.signal.manager.groups.GroupIdV2.serialize()" because "this.expectedV2Id" is null (through reference chain: org.asamk.signal.manager.storage.groups.JsonGroupStore["groups"]->org.asamk.signal.manager.storage.groups.GroupInfoV1["expectedV2Id"])
```
I tried reinstalling signal-cli and relinking the account multiple times but no luck so far. Other commands like ``signal-cli -u +[NUMBER] daemon`` work without a problem.

I've installed ``signal-cli`` via Homebrew and am currently running on macOS 11.1.

**Comment by AsamK** [comment]
There's indeed a bug in the current version that prevents saving after having received the synced v1 groups.
It's already fixed in the master branch (263fdceb94d8de0e355254446b26f9aff3e4c40a) and will be part of the next release.
