### ISSUE TITLE
Sending messages with signal-cli, the recipient doesn't see sender's name or avatar

### ISSUE THREAD

**Issue by cuu508** [AsamK/signal-cli#416]
I used the "signal-cli updateProfile" command to set the name and avatar. 

When sending messages, the recipient in the official Android app sees just sender's phone number, no name or avatar.

How do I get the name or avatar to show, do I need to do something extra?

Thanks!

**Comment by androbey** [comment]
Did you add the recipient to your contacts (via signal-cli updateContact command)? If not, recipient won't see your name and avatar.

**Comment by cuu508** [comment]
Ah, I did not. Thanks for the tip!

After running updateContact the name and avatar does indeed show up.

OK, so the recipient needs to be in the contacts for the name and avatar to be sent. Is this mandated by the protocol, or is this a design decision in signal-cli?

Can linked devices run the `updateContact` call? Or should just the master device do that?

For a little background, my use case is sending monitoring notifications from a SaaS monitoring service. For redundancy, there are multiple worker nodes that may want to send the notifications. The way I've set it up currently is, each worker node is a "linked device". Any worker node may be in the position to send the first message to a new recipient.

**Comment by AsamK** [comment]
In order for someone to see your profile, they need your profile key. The profile key can be sent to other users along with regular signal messages, signal-cli just includes the profile key for users in the contact list. Also the profile key is stored in the group info, so all members of a group can see your profile.
In the official clients only the master device updates the contacts and then sends the list to the linked devices.

**Comment by cuu508** [comment]
Thanks for the information, @AsamK! 

Is the presence/absence of profile key the same thing as "normal" vs "unidentified" messages in the source code?

For my use case, it would be a lot simpler if all messages included the profile key and I didn't need to explicitly add recipients to contacts, and then syncronize the contacts list. The privacy of the sender's name and avatar doesn't matter in my case. 

Is a "send profile key with all messages" feature something that you would potentially be interested in having in signal-cli as an option?

**Comment by AsamK** [comment]
no, those are different. Unidentified message means that the sender is encrypted and hidden from the signal server. Only the recipient can decrypt and verify the sender with an attached sender certificate.

It probably makes sense to just always include the key, I think that's what the apps do as well.

**Comment by Vic3198** [comment]
I have a problem with updating profile info too.
The situation is simple: signal-cli client is registered as master device with number1, and is in a group v2, along with my personal Signal account (number2).
I added number2 to my contacts  on signal-cli using `contactUpdate`, but on my phone, it still doesn't display the number1 profile on the group...

**Comment by cuu508** [comment]
> It probably makes sense to just always include the key, I think that's what the apps do as well.

I vote for that! :-)

Looking at [the bit that sets the profile key](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/manager/Manager.java#L1350), seems likee moving it outside the `if` statement would be trivial in itself. But  I have no idea if it could have any unintended consequences.

**Comment by cuu508** [comment]
Awesome, thank you! Just tested the master version, and the profile name & avatar indeed arrives with the first message now!

PS. Does this project accept donations?

**Comment by AsamK** [comment]
No, there's currently no way to donate to this project, but feel free to donate to the signal foundation:
https://signal.org/donate/
