### ISSUE TITLE
XMPP-Transport-Interface [feature-request]

### ISSUE THREAD

**Issue by hpmueller1971** [AsamK/signal-cli#42]
Hi everyone,

is there any chance that you could implement the [spectrum2 ](https://github.com/hanzz/spectrum2)transport gateway api, like [transwhat](https://github.com/stv0g/transwhat) does, or even the official [XMPP Component Protocol](http://xmpp.org/extensions/xep-0114.html) API, so signal-cli could be user via Jabber...? transwhat is a whatsapp-transport for jabber, so it also uses an e164-number as the identifier and should be fairly similar to signal...

Or, is there any way to use the d-bus api from a jabber-transport?

**Comment by AsamK** [comment]
I don't have the time (nor the need ;) to implement this. If someone wants to do it, go ahead.
The dbus api is probably too limited currently.
I've also started on a json output, that might be useful for this.

**Comment by thundergreen** [comment]
Im also interested

**Comment by streaps** [comment]
This would require json input/output in daemon mode.

**Comment by AsamK** [comment]
XMPP is out of scope for signal-cli.
However there's now a json rpc based api on master that could help with implementing this.
