### ISSUE TITLE
dbus: method sendMessage does not exist?

### ISSUE THREAD

**Issue by FransVeldman** [AsamK/signal-cli#420]
SOLVED. Still a bit weird the error message, but apparently this is what you get with an incorrectly formatted recipient. I now have array:string: string: '<number>' and that works. 

I'm trying to get it to work with dbus, following the procedure from the wiki, but not so much luck:

dbus-send --system --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:'Hello world' string:'+31619882xxx'

Error org.freedesktop.dbus.errors.UnknownMethod: The method `org.asamk.Signal.sendMessage' does not exist on this object.

If I'm not too confused, I think that the first time I did not get this error, although the message didn't get through. In the Syslog I could see that it received a few messages. On subsequent tries, no matter what, even after a stop and restart service, I get this "method does not exist".

Any ideas?

**Comment by joed74** [comment]
I have exactly the same problem, receiving ok - sending with signal-cli ok, but sending with dbus-send:

```
dbus-send --system --type=method_call --print-reply --dest="org.asamk.Signal" /org/asamk/Signal org.asamk.Signal.sendMessage string:MessageText array:string: string:+[mynumber]
Error org.freedesktop.dbus.errors.UnknownMethod: The method `org.asamk.Signal.sendMessage' does not exist on this object.

```
