### ISSUE TITLE
disappearing messages

### ISSUE THREAD

**Issue by Hinnack** [AsamK/signal-cli#421]
Hi,

I like to use signal for nagios / shinken / etc.
And I would like to enable the "disappearing messages" feature, as I do not want to keep the messages for a long time.

But if I set this feature for the sending user, a message send by signal-cli disables this again.

**Comment by AsamK** [comment]
the disappearing messages info is transfered via normal signal messages between the users. So before sending the message with signal-cli you need to first execute the `receive` command.
You can also use the `updateContact` command with signal-cli to set the expiration timer.

(please use github discussions for questions in the future)

**Comment by Henner** [comment]
hmm, I could not find that in the docs - so you may should reopen this as "fix the docs"
