### ISSUE TITLE
Attachments download api

### ISSUE THREAD

**Issue by jyothisjose** [AsamK/signal-cli#422]
We have registered a number using "register" api and we are able to sent message using "send" api.

Also we could fetch messages/attachments using "receive" api and we are getting the response as below.

For eg: [{"envelope":{"source":"+919xxxx","sourceDevice":1,"relay":null,"timestamp":1610517721588,"dataMessage":{"timestamp":1610517721588,"message":null,"expiresInSeconds":0,"attachments":[{"contentType":"image/jpeg","filename":null,"id":"**pwtcq-xxxx**","size":366267}],"groupInfo":null},"syncMessage":null,"callMessage":null,"receiptMessage":null}}]

But we would like to know how to get/download the image by using attachments id "**pwtcq-xxxx**".

Is there an api to fetch the attachments (image/video/pdf)?

**Comment by AsamK** [comment]
The attachments are downloaded by default and stored in the `~/.local/share/signal-cli/attachments` directory with the id as filename.
(please use github discussions for questions in the future)
