### ISSUE TITLE
Typing indicators in JSON mode

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#423]
When signal-cli is run in JSON mode

```
signal-cli -u +XXXXXXXXXXX daemon --json
```

The typing indicator envelopes are printed out, but (almost) all the envelope's values are set to `null`:

```json
{"envelope":{"source":"+XXXXXXXXXXX","sourceDevice":1,"relay":null,"timestamp":1610630000000,"dataMessage":null,"syncMessage":null,"callMessage":null,"receiptMessage":null}}
```

In non-JSON mode, the typing indicators' information is printed out fine:

```
Envelope from: unknown source
Timestamp: 161063XXXXXXX (2021-01-14TXXXXXXXXXXXXZ)
Sent by unidentified/sealed sender
Sender: “” +XXXXXXXXXXX (device: 1)
Received a typing message
 - Action: STARTED
 - Timestamp: 161063XXXXXXX (2021-01-14TXXXXXXXXXXXXZ)

Envelope from: unknown source
Timestamp: 161063XXXXXXX (2021-01-14TXXXXXXXXXXXXZ)
Sent by unidentified/sealed sender
Sender: “” XXXXXXXXXXXX (device: 1)
Received a typing message
 - Action: STOPPED
 - Timestamp: 161063XXXXXXX (2021-01-14TXXXXXXXXXXXXZ)
```

**Comment by Atomic-Bean** [comment]
That's odd. I would expect dataMessage and others to be non-null. Also note that `--json` is deprecated in the latest version, instead use this instead `signal-cli --output=json -u +XXXXXXXXXX daemon`

**Comment by exquo** [comment]
Thanks for the heads up with the command change! I'll update it in my code when this change makes it into a new release.
