### ISSUE TITLE
Remote delete message in JSON mode

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#424]
When a contact in conversation deletes a message ("Delete for everyone"), this shows up as a "Remote delete message" event in non-JSON mode:

```
Envelope from: unknown source
Timestamp: 161063XXXXXXX (2021-01-14TXXXXXXXXXXXXZ)
Sent by unidentified/sealed sender
Sender: “” +XXXXXXXXXXX (device: 1)
Message timestamp: 161063XXXXXXX (2021-01-14TXXXXXXXXXXXXZ)
Remote delete message: timestamp = 161063YYYYYYY
```

When signal-cli is run with `--json` flag, the envelope is printed, but gives no indication it's about a "remote delete" event:

```json
{"envelope":{"source":"+XXXXXXXXXXX","sourceDevice":1,"relay":null,"timestamp":1610630000000,"dataMessage":{"timestamp":1610630000000,"message":null,"expiresInSeconds":0,"reaction":null,"quote":null,"mentions":[],"attachments":[],"groupInfo":null},"syncMessage":null,"callMessage":null,"receiptMessage":null}}
```

**Comment by Atomic-Bean** [comment]
Ah yes, json mode is missing a few things from regular output. We can see in regular output we check for deleted messages [here](https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/ReceiveMessageHandler.java#L473), but there aren't any checks in [the json code](https://github.com/AsamK/signal-cli/blob/20681b8d89ebaf1d437c4f6b57fefeb83dc8de45/src/main/java/org/asamk/signal/json/JsonMessageEnvelope.java).

I'm a bit too busy at the moment to make a PR for this, but if you want you can take a shot.

**Comment by exquo** [comment]
I don't know any Java, but I might be able to ape it by looking around the code. This isn't a high priority though (not for me at least), it's just one of the discrepancies between the JSON and regular output.
