### ISSUE TITLE
DBUS: How to deal with multiple users (phone numbers)?

### ISSUE THREAD

**Issue by FransVeldman** [AsamK/signal-cli#425]
Hi,
I have succesfully running system-cli as a system DBUS service, with the username hard coded in the exec statement.

However, I have two numbers I want to use. I tried to get it working with multiple users, like 
systemctl start signal-cli@<YOUR NUMBER> but I'm doing something wrong.

There are several config files:
/etc/dbus-1/system.d/org.asamk.Signal.conf
/usr/share/dbus-1/system-services/org.asamk.Signal.service
/etc/systemd/system/signal.service

I started with creating a new file:
/etc/systemd/system/signal-cli@.service
I use %I instead of the phone number.
When loading it with
systemctl start signal-cli@<NUMBER> I got a complaint about a duplicate service. (Yes, I did STOP the previous service).

I then changed the BusName in the file, and did this in all the other config files, and renamed all of them to Signal > Signal-cli.

That didn't work either. When I try to start the service, it ends with a "timeout". In the log files I can see that it actually became active and received some messages.

So, I can do a lot more guessing, but I hope there is someone who can tell me what to rename and what not. There are filenames, busnames, and service names. As you guess, I'm a novice with dbus and associated services. But I have a feeling it must be very simple what I try to achieve...

**Comment by exquo** [comment]
Running multiple instances of signal-cli daemon *simultaneously* is not currently supported: #200, #38. There are pull requests for this, but they are not merged in yet: #187, #206.

If you are *not* trying to run the daemons *concurrently*, and are getting complaints about the duplicate service, check that signal-cli daemon is actually stopped before starting a new one:

```
dbus-send [--session] --type=method_call --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames  |  grep 'org.asamk.Signal'
```

Remove `--session` if you're running on system bus.

**Comment by FransVeldman** [comment]
Ok, thanks. So if I understand correctly, there is currently no way to use multiple users when using DBUS?
If I run a cron script for posting messages, could I stop the daemons for switching to a different user, without loosing the messages that are coming in for the stopped users?

**Comment by exquo** [comment]
If you stop the signal-cli daemon, and then restart with a different `--username`, there is no problem. A cron script like you describe should work fine. The messages would not be lost - they are stored on Signal servers until they are actually delivered to your device(s).

**Comment by FransVeldman** [comment]
Ok, this is confusing. If I run "systemctl stop signal.service", the process terminates nicely. If I very with: 
root@cloud:/home# dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1610744234.238257 sender=org.freedesktop.DBus -> destination=:1.7740 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "org.freedesktop.login1"
      string ":1.2508"
      string ":1.7740"
      string ":1.2509"
      string "org.freedesktop.systemd1"
      string ":1.2510"
      string "org.freedesktop.network1"
      string ":1.2557"
      string ":1.4"
      string "org.freedesktop.resolve1"
      string ":1.2559"
      string "org.freedesktop.Accounts"
   ]

So, the service is terminated, right?

Then, if I try this:
root@cloud:/home# systemctl start signal-cli@+15056580704

The result is this:
Jan 15 21:55:01 cloud systemd[1]: signal.service: Two services allocated for the same bus name org.asamk.Signal, refusing oper

More confusingly, after a while, just staring at config files, trying again, it worked. But now, if I want to revert to the previous service, I get the same problem. All services are stopped yet I get this "two services allocated for the same bus name".

This is not going to work well in a cron job. Is there anything else I can do to purge the system status so I can switch --username?

**Comment by AsamK** [comment]
I've implemented a way to deal with multiple users. You can test it in the current master: ca86c421ebb1a3930fa309a2d95a4090108c2e62
The `daemon` command can now be used without `-u` flag, in which case it will export all users in the data directory as separate dbus objects, instead of `/org/asamk/Signal` it will be exported as `/org/asamk/Signal/_15056580704` for example.

**Comment by AsamK** [comment]
About the two services issue, maybe systemd has still loaded the previous service, you could try to reset the state with `sudo systemctl reset-failed`
Version 0.7.3 has now been released which can expose multiple accounts as separate dbus objects.
