### ISSUE TITLE
[main] ERROR org.asamk.signal.Main - Error while checking account: Bad response: 502 

### ISSUE THREAD

**Issue by i0x71** [AsamK/signal-cli#426]
Messaging was working, but now all of a sudden im getting these errors for any command
Would this be an issue on the Signal servers ?

[main] ERROR org.asamk.signal.Main - Error while checking account: Bad response: 502 
Same request another try returns
[main] ERROR org.asamk.signal.Main - Error while checking account: Bad response: **500** 

Using version 0.7.2

**Comment by exquo** [comment]
There are some problems on signal's end, should be a temporary thing.
https://github.com/signalapp/Signal-Android/issues/10657
https://github.com/signalapp/Signal-Desktop/issues/4858

**Comment by AsamK** [comment]
yep, it's a server issue.

The status page now also says it's experiencing technical difficulties: 
https://status.signal.org/
