### ISSUE TITLE
issues contacting textsecure-service.whispersystems--perhaps a service issue, not signal-cli?

### ISSUE THREAD

**Issue by mmhere** [AsamK/signal-cli#427]
Is anyone else seeing this?  Output from signal-cli...send

`Error loading state file: java.net.UnknownHostException: textsecure-service.whispersystems.org: No address associated with hostname`

Sometimes manifests as:

`Error loading state file: java.net.ConnectException: Failed to connect to textsecure-service.whispersystems.org/127.0.0.1:443`

Attempting to ping textsecure-service.whispersystems.org sometimes succeeds sometimes does not.  Attempting to do a DNS lookup of the same hostname sometimes succeeds sometimes does not.

---

I know from other sources that Signal has recently been experiencing service pressure (thanks, Mr E.Musk...), but wanted to confirm whether there may be some configurationitis I may be missing on the single-cli side.  I have a pretty old installation of signal-cli as it is server stuff that I try to keep stable.

**Comment by aapeliv** [comment]
Seeing the same issue, either there's been a change upstream or there's a service issue.

**Comment by mmhere** [comment]
Thanks for that.  For those who don't want to link offsite to the twitter URL, the tweet reads:

```
Signal @signalapp
Signal is experiencing technical difficulties.
We are working hard to restore service as quickly as possible.
8:33 AM · Jan 15, 2021

```
Cheers

**Comment by mmhere** [comment]
Seems like this could be closed.  Unless the error messages above are specific to an older version of signal-cli [and I should be encouraged to upgrade ;-) ], I'll note that I failed to see a sibling issue here that itself is already closed.  That issue shows different error messages, but clearly describes the same service/capacity problems that the signal servers are currently suffering.

https://status.signal.org/ is informative.
