### ISSUE TITLE
Allow notes to self to trigger push notification

### ISSUE THREAD

**Issue by bemug** [AsamK/signal-cli#439]
AFAIK [this commit](https://github.com/AsamK/signal-cli/commit/24714454dd43fe2df8981d37c98bd5c4c1a69a45) remove the push notification when I send a note to myself.
Could we make this configurable?

I'd like to be notify on my phone when a command is ended for example:

```
very_long_build_command; echo "Command done" | signal-cli -u <me> send <me>
```
Any tips/help/idea on how to do this is also greatly appreciated.

**Comment by bemug** [comment]
My bad I just came across [this closed issue](https://github.com/AsamK/signal-cli/issues/373), sorry for the noise and thank you for the great work.

**Comment by michaelkebe** [comment]
You could register a new account just for notifications. You can even use a landline number and get a voice call for the verification code. VoIP services are mostly free for basic use.
