### ISSUE TITLE
Failed to send message: Rate limit exceeded: 413

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#44]
I am testing whether i can kill Signal-Android instances by sending them enough attachments so that they run out of file descriptors. Unfortunately, when sending too many attachments with one command, signal-cli responds:

`Failed to send message: Rate limit exceeded: 413`

Aren't multiple attachments wrapped into a single message, and should not cause rate limit hits?

**Comment by AsamK** [comment]
All attachments are linked to a single message, but each attachment is uploaded separately before, via HTTP.
There is probably a rate limit on the number of attachment uploads.

**Comment by Trolldemorted** [comment]
could we forge a message with just one upload and append the same pointer several times?

**Comment by AsamK** [comment]
That should work. You'd have to modify libsignal-service to do that.

**Comment by swedishjeff** [comment]
I'm getting a "Rate limit exceeded" error with one of my contacts, after reinstalling Signal for Desktop. No attachments are involved, but a Google search only brings up this page when I look for support. Is this issue related?

**Comment by AsamK** [comment]
If you're not sending a message with lots of attachments, it's not directly related.
You'd have to check the signal desktop logs to see which requests it's sending. I don't know the limit when the signal server starts rate limiting.
