### ISSUE TITLE
output=json unrecognized

### ISSUE THREAD

**Issue by tehCh0nG** [AsamK/signal-cli#445]
On version 0.7.3, running `receive --output=json` says:

> signal-cli: error: unrecognized arguments: '--output=json'

But using the previous JSON flag, --json, shows a depreciated warning:

> WARN ReceiveCommand - "--json" option has been deprecated, please use the global "--output=json" instead.

**Comment by AsamK** [comment]
The --output argument needs to be in front of the receive command, i.e. `--output=json receive`
