### ISSUE TITLE
cli interface + dbus interface in hybrid mode?

### ISSUE THREAD

**Issue by bbernhard** [AsamK/signal-cli#446]
Hi,

first of all, many thanks for all the hard work you are putting into this project! I've been following `signal-cli` for a while now and it's really great to see the steady improvements and new features every release. Many thanks for that - VERY much appreciated!

I am the maintainer of [signal-cli-rest-api](https://github.com/bbernhard/signal-cli-rest-api) which is a small REST API wrapper around your awesome tool. 

Right now I am spawning a new `signal-cli` process for every action. While this works, it is kinda slow due to the JAVA VM startup time (that's especially noticeable on the Raspberry Pi). I've already looked into some possible ways to improve the startup time (e.g by using [nailgun](https://github.com/facebook/nailgun)) but before I investigate further in that direction I wanted to give signal-cli's DBUS implementation a try. 

I've already played a bit with the DBUS interface and also got it working. But during my tests I stumbled across a limitation: As soon as I enable the DBUS mode, it's not possible anymore to use `signal-cli` cli interface (it blocks with `Config file is in use by another instance, waiting…`). 

I haven't looked into the implementation, but I guess it's to prevent a possible config file corruption when multiple processes are trying to write to the config? If so, would it maybe be possible to defer that check a bit and move it to the place in the code where the config file is accessed? 

What would be pretty cool is, if there would be the possibility to use the DBUS interface and the cli interface in some sort of hybrid mode (e.g configureable via config file) e.g: Only use the DBUS interface for sending messages and use the cli interface for everything else.

I know this is probably a pretty specific use case and I can totally understand if you don't want to implement such a thing (or if it's even possible to add). But before I am investigating other possible improvements (like using nailgun), I wanted to drop this idea in your repo. 

Thanks a lot for your time & have a nice day!

**Comment by bentolor** [comment]
Hi @bbernhard : If it is mostly the JVM startup times. Have you already looked into using [GraalVM Native Image](https://www.graalvm.org/) to compile it to a native binary? I'd assume this would be a better addition to this project.

**Comment by bbernhard** [comment]
> Hi @bbernhard : If it is mostly the JVM startup times. Have you already looked into using [GraalVM Native Image](https://www.graalvm.org/) to compile it to a native binary? I'd assume this would be a better addition to this project.

Thanks @bentolor - that looks awesome. Wasn't aware that such a thing exists!

In case anyone is interested, I've managed to compile signal-cli to a native binary and it also starts without problems (i.e I can see the help text), but as soon as I run a command it fails with: 

```
WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
Exception in thread "main" java.lang.IllegalStateException: missing metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_AT
	at com.google.i18n.phonenumbers.MetadataManager.getMetadataFromSingleFileName(MetadataManager.java:188)
	at com.google.i18n.phonenumbers.MetadataManager.getMetadataFromMultiFilePrefix(MetadataManager.java:116)
	at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:64)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:2232)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegionOrCallingCode(PhoneNumberUtil.java:1354)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3218)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3046)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3036)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.isPossibleNumber(PhoneNumberUtil.java:2674)
	at org.whispersystems.signalservice.api.util.PhoneNumberFormatter.isValidNumber(PhoneNumberFormatter.java:33)
	at org.asamk.signal.App.init(App.java:151)
	at org.asamk.signal.Main.main(Main.java:43)
```

Unfortunately, I do know next to nothing about the Java ecosystem and at the moment I do not have the time to dig deeper into that. (I'll maybe have a look at it again in a few days, but as I do not know the Java ecosystem that well I am not sure if I am able to fix the issues). In case anyone wants to have a look, I've created a fork with the [necessary changes](https://github.com/bbernhard/signal-cli/commit/5f3f417ccc6a4edae5720a3644d26c0147757df4). In order to try it out, do:

* download GraalVM 20.3.0 from [here](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-20.3.0) - newer versions didn't work fo me
* extract it somewhere
* run `git clone https://github.com/bbernhard/signal-cli`
* run `git checkout graalvm`
* open `build.gradle` and change the path to the `graalVmHome` directory (the `graalVmHome` directory is the path to the extracted Graal VM 20.3.0)
* run `./gradlew nativeImage`
* the build takes about ~3min on my machine and after that there's a binary called `my-native-application` inside the `build/bin` directory

If someone wants to have a look - any help is really appreciated!

**Comment by bentolor** [comment]
This Exception might be unrelated to GraalVM, @bbernhard . See https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

**Comment by bbernhard** [comment]
> This Exception might be unrelated to GraalVM, @bbernhard . See https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal

I am not sure. I ran into some linking issues with `zkgroup` when I upgraded the docker image to signal-cli 0.7.0, but I always only got the warning message and it never threw an excepton. Of course signal-cli could behave differently now with 0.7.4 - haven't tried to run that version without `zkgroup`. So maybe, it's really just a follow-up issue with the missing `zkgroup`. 

But not sure yet why the native image can't find `zkgroup`. For x86_64 `zkgroup` is provided with `signal-cli`, so I thought GraalVM would pick that up and link against it. But maybe I do need to explicitly specify that somehow when building the image with GraalVM :thinking:

**Comment by bbernhard** [comment]
@michaelkebe @AsamK I just saw that there's now experimental support for GraalVM. As a raspberry pi user I want to say: THANKS - very much appreciated! 

I'll definitely give that a try in the next few days. :+1:  

Just out of interest: Are there any known issues when using the native binary (in non-DBUS mode)?

**Comment by michaelkebe** [comment]
@bbernhard I would say register, verify and send works well.

However, you could use the Java Version for something that is broken in the experimental native binary.

Just try it out and please give a feedback in case something is not working.

**Comment by bbernhard** [comment]
> @bbernhard I would say register, verify and send works well.
> 
> However, you could use the Java Version for something that is broken in the experimental native binary.
> 
> Just try it out and please give a feedback in case something is not working.
> 
> I haven't tested anything with DBUS and the native binary.

Just played a bit with it on my dev system (x86-64) and so far everything is working fine (tried `listIdentities`, `listGroups`, `receive` and a bunch of other commands). Awesome work! Can't wait for the next signal-cli release to add support for that to the docker container.

**Comment by MarcelWaldvogel** [comment]
Am I missing something obvious or why are you not using `signal-cli --dbus [options]`?

I have a Docker image with `signal-cli daemon --system` running (after some trickery with the dbus configuration) and can issue `signal-cli --dbus-system send +1234567890` (and the other commands supported over dbus) without problems.

**Comment by bbernhard** [comment]
> Am I missing something obvious or why are you not using `signal-cli --dbus [options]`?
> 
> I have a Docker image with `signal-cli daemon --system` running (after some trickery with the dbus configuration) and can issue `signal-cli --dbus-system send +1234567890` (and the other commands supported over dbus) without problems.

There are mainly two problems: 

* the DBUS interface doesn't support all commands 
* the DBUS interface doesn't map that well to a REST API interface

What I want to avoid at all costs is to implement some local storage in order to store the received message via DBUS. I think that makes the whole implementation unnecessarily complicated and error prone (e.g if someone deletes a message, I probably need to delete the message also from my local storage). By mixing DBUS and normal cli commands I was hoping to get the best of both worlds. e.g: Send out messages fast via the DBUS interface and receive messages by polling the cli interface. 

I still need to test the native binary on an ARM based system, but I am hoping that the native image will improve the startup time quite a bit.

**Comment by MarcelWaldvogel** [comment]
Ah, ok, thanks for the clarification. In my case, I only need to perform `send` operations programmatically (after initial registration or linking), so I am totally happy with CLI (which I am using now as performance is not a problem, might switch to dbus later).

**Comment by AsamK** [comment]
There's now a new JSON-RPC based interface (not released yet), that might better suit your use case:
https://github.com/AsamK/signal-cli/discussions/679
