### ISSUE TITLE
signal.service fails to start User is not registered

### ISSUE THREAD

**Issue by chr1shaefn3r** [AsamK/signal-cli#45]
I'm trying to run signal-cli as system dbus service. My problem is that the signal.service keeps on failing to start and complaining about User is not registered:

```
$ systemctl start signal.service
Job for signal.service failed. See 'systemctl status signal.service' and 'journalctl -xn' for details.
$ systemctl status signal.service
● signal.service - Send secure messages to Signal clients
   Loaded: loaded (/etc/systemd/system/signal.service; enabled)
   Active: failed (Result: exit-code) since Sa 2017-01-21 16:55:09 CET; 1s ago
  Process: 12014 ExecStart=/usr/local/bin/signal-cli -u +4915151219921 --config /var/lib/signal-cli daemon --system (code=exited, status=1/FAILURE)
 Main PID: 12014 (code=exited, status=1/FAILURE)

Jan 21 16:55:08 hugo.christophhaefner.de systemd[1]: Starting Send secure messages to Signal clients...
Jan 21 16:55:09 hugo.christophhaefner.de signal-cli[12014]: User is not registered.
Jan 21 16:55:09 hugo.christophhaefner.de systemd[1]: signal.service: main process exited, code=exited, status=1/FAILURE
Jan 21 16:55:09 hugo.christophhaefner.de systemd[1]: Failed to start Send secure messages to Signal clients.
Jan 21 16:55:09 hugo.christophhaefner.de systemd[1]: Unit signal.service entered failed state.
```

I tried registering with the "signal-cli" user, so that "/home/signal-cli/.config/signal/data/" is populated, but that didn't help.
I also tried registering as root, so that "/root/.config/signal/data/" is populated, but that didn't help either.

Could someone tell me where he looks for the registration information?

Cheers,
Christoph

**Comment by AsamK** [comment]
By default signal-cli looks in `"$HOME/.config/signal"`, unless the `--config` commandline parameter is given. In the example systemd service file, that you are using, this parameter sets the config dir to `/var/lib/signal-cli`

**Comment by chr1shaefn3r** [comment]
Thank you very much! Thats what I was missing. Didn't make the connection between "--config" and registration keys :|

The service is now running!

(I still can't send messages via dbus, "Cannot Resolve Session Bus Address". Should I open an extra issue for that?)

**Comment by AsamK** [comment]
yes, with more information on which commands you ran.
