### ISSUE TITLE
Feature Request: Improve CLI help, documentation and usage guidance

### ISSUE THREAD

**Issue by bentolor** [AsamK/signal-cli#450]
Thanks for you tool, @AsamK, which I use on a regular base. 

I haven't looked into the code yet, but as a user I constantly struggle on finding out the correct usage. I especially struggle, because most commands do have command-specific arguments. If find my self daily visiting this Git repo and then searching `man/signal-cli.1.adoc`.

I would have various proposals:

- [ ] Expand the default help output. Describe & visually group command. Potentially: already mention the important flags here.
- [ ] Add a complete documentation to the readme (AsciiDoc `include::` or at least link)
- [ ] Provide command help: i.e. `signal-cli -u +123456 updateGroup` just causes NPEs
- [ ] Introduce a `help Command` command to detailed explore commands

I guess the current output is the default output of a CLI parsing tool?

**Comment by AsamK** [comment]
There's already a link from the README to the man page, I don't want to include the whole man page here to keep the README short.
> For more information read the man page and the wiki.

signal-cli uses `argparse4j` for its argument parsing.
Showing more information about the commands is already possible, with `-h` for global help or `someCommand -h` for command specific help.
Currently not all commands are self documenting, this could be improved by adding more `.help(...)` calls to the code, the text could probably be copied from the man page.

Which NPE do you get from the `updateGroup` command? That shouldn't happen in the latest version anymore.

**Comment by bentolor** [comment]
Thanks, @AsamK for your detailed response.

* Regarding doc link: It seems I overlooked and maybe rephrasing the sentence and putting it first under "Usage" would improve. I suggested a change in #xx. Please feel free to reject as it's really a matter of taste.
* The NPE has vanished in 0.7.4. Thanks! I also now returns detailed help on the arguments, which is great
* Why  not make `signal-cli -h` default? This page is so more helpful! If interested I could try to prepare a MR for this and extending the currently missing command hints like `{trust,updateProfile,listIdentities,link,…`

**Comment by euneuber** [comment]
Could you please include some examples like:
-  join a group when added by group admin
- create a group, add members and send messages to the group (when they have joined)

(my group id seems not to work...)

**Comment by euneuber** [comment]
And please add: your SIM must be reachable for SIGNAL to operate. :smirk:

**Comment by bentolor** [comment]
Awesome @AsamK  – great improvement! Thanks! :heart:
