### ISSUE TITLE
Sending emojis

### ISSUE THREAD

**Issue by lebon1089** [AsamK/signal-cli#457]
Hi there.

I use SIGNLA-CLI to send certain messages from an ERP system to the user.
I also use the return route to execute commands that are sent from the cell phone to the ERP server.

I would like to send emojis for outgoing messages that go to the cell phone. How do I pass the UNICODE in the message?

To create the outgoing message, I create strings concatenated with "&& echo".

**_while () {
$ alocversand. = '&& echo "'. $ countbb.".: ". $ row [0]." - ". $ row [4]. '"';
}_**

The $ row [x] array contains the record set of my SQL query.

And this is how I call the signal client to send:
_**exec ($ alocversand. '| ... \ bin \ signal-cli -u +4915140420887 send'. $ row [3]);**_

How do I transfer the emojis via UNICODE?

**Comment by AsamK** [comment]
signal-cli uses the java default charset to parse the message from stdin.
On most unix systems that should be utf-8.

**Comment by pblaas** [comment]
I am having difficulties to send emojis too. 
Both using send and sendReaction with the specific -e flag won't allow me to get them through. 
Does anyone have any  working examples I can take a look at?

**Comment by AsamK** [comment]
your terminal and locale need to support utf-8, then it's as simple as this: `signal-cli -u +XXX send +YYY -m 🦘`
check if your `$LANG` env variable ends with `.UTF-8`

**Comment by pblaas** [comment]
Hi AsamK, thank you for the LANG var pointer. Its working now.

**Comment by maryhernandez49** [comment]
Hello,
What about sending the emoji inside the text messages using DBus python? Any idea?
