### ISSUE TITLE
new group not being seen / synced

### ISSUE THREAD

**Issue by uqs** [AsamK/signal-cli#472]
Hi folks, just got started with signal-cli and I'm missing 1 group. I've ran `receive` a bunch of times, but listGroups does not show it.

- I have 2 old groups (short ID) that are years old, they show up fine
- I'm not the admin of the missing group, but it got created in December, so is rather new
- This group starts with the text `10km`, so I figured that leading digits would confuse things, but
- created my own group called `123test` and that is being sync'ed fine (it's ID is much longer than my 2 old groups)

So where do I go from here?

The missing group has not yet received any messages since I've started signal-cli, so is there a chance this will fix itself once messages start rolling in?

**Comment by pblaas** [comment]
Yes, I noticed this as well. Once someone else posts a message in the group it should show in the list.

**Comment by uqs** [comment]
Indeed, `scli` now showed: New message from NULL: "Mic test"
and restarting scli had the group show up fine.

listGroups now shows it too. So must be some lazy initialization for these new V2 groups.

Sorry for the noise.

**Comment by exquo** [comment]
For the record: the issue seems the same as #438.

The `NULL` contact and need to restart in scli is caused by https://github.com/isamert/scli/issues/71.
