### ISSUE TITLE
ELFCLASS64 error when building on Raspberry

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#478]
Hi, 
I tried to build signal-cli according to instructions with gradle on my Rapsberry4 (buster).
Build went fine, but when I try to run it I get
ERROR App - Error loading state file for user +49xxxxxxxxx: /tmp/resource8229847313344198991.so: /tmp/resource8229847313344198991.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)

The downloaded jars work without a problem (especially after I built and added the native zkgroup lib.so). Any special settings needed to build this?

Thx

**Comment by bublath** [comment]
I tried a couple of things. I put the native compiled libzkgroup.so into /usr/lib and removed it from the zkgroup jar file.
However the "gradle instDist" always gets the original one from somewhere and I assume that all the classfiles somehow are created using the "wrong" one as a dependency.
I really could use some help here? I somewhere read that there is a kind of mismatch on Raspbian that the Raspberry4 CPU is 64bit but the system still runs on 32bit. Can I somehow configure to build everything as 32bit?
I also don't understand why the library still gets copied to /tmp/resource.... (which one?) though I have a native one in /usr/lib

I crosschecked this with the downloaded packages (removing the lib from the jar) and that is working. Something is strange when building on the Rapsberry.

**Comment by AsamK** [comment]
signal-cli master uses a newer libsignal-service-java version, which requires another native library.
I've updated the wiki page: https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal#libsignal-client
Feel free to update it, if somethings missing.

**Comment by bublath** [comment]
Thanks. That helped. I added a hint about installing the protocol buffer compiler which at least on my system was missing and probably won't hurt others when making sure its there.
