### ISSUE TITLE
[DBus] send message to multiple numbers

### ISSUE THREAD

**Issue by bosgnoom** [AsamK/signal-cli#479]
Hello,

I don't know whether this is an issue, or that I should be asking this somewhere else...

I upgraded my raspberry pi from stretch to buster. Previously I used your (fantastic) program to send messages through Signal, using python's DBus system. Basic idea:

```
#!/usr/bin/python3

from pydbus import SystemBus
import sys

data = "test"
bus = SystemBus()
signal = bus.get('org.asamk.Signal')
signal.sendMessage(data, [], ['+316...', '+316...'])
```
However, now pydbus complaints about an TypeError: the phone number previously send as an list (of numbers) now needs to be a string.

How can I correct this, in order to send the same message to multiple phone numbers?

**Comment by bublath** [comment]
I just tried this on my buster Raspberry4 (freshly installed pydbus, since I did not use it before) and above program worked for me with two recipients and signal-cli 0.7.4. running as dbus systembus
So I guess its a config error on your end

**Comment by bosgnoom** [comment]
Thank you for confirming. Lesson learned: do not update stretch to buster ;-) 
In the mean time I am upgrading my pi2 to a pi3, including Signal messaging system.
Issue can be closed. Thank you for helping me!

**Comment by woifes** [comment]
Hello I seem to have the same problem. What kind of configuration is responsible for this? Signal-Cli V 0.8.5
