### ISSUE TITLE
receive --json vs. --output=json

### ISSUE THREAD

**Issue by hmr-it-jr** [AsamK/signal-cli#481]
Hey, thanks for this useful tool! I want to create a rest-api to send and receive Signal messages. I need to save the received messages in a db. The easiest way to do this is to use receive --json.

If I exec the command like this:
`./signal-cli -u +49XXXXXXXXXXX receive --json`

I get this response
`WARN ReceiveCommand - "--json" option has been deprecated, please use the global "--output=json" instead.`
```{"envelope":{"source":"+49XXXXXXXXXXX","sourceDevice":1,"timestamp":1612041718367,"dataMessage":{"timestamp":1612041718367,"message":"Hhji","expiresInSeconds":0,"viewOnce":false,"mentions":[],"attachments":[]}}}```

So I tried to exec the command like this:

`./signal-cli -u +49XXXXXXXXXXX receive --output=json`

But now it doesn't work anymore:

`Benutzung: signal-cli receive [-h] [-t TIMEOUT] [--ignore-attachments] [--json]
signal-cli: Fehler: nicht berücksichtigte Argumente: '--output=json'`

What am I doing wrong?

**Comment by exquo** [comment]
Just an argument parsing issue. Put the `--output` option before the `receive` sub-command:

	./signal-cli -u +49XXXXXXXXXXX --output=json receive
