### ISSUE TITLE
Register --voice parameter does not work

### ISSUE THREAD

**Issue by softsun-cz** [AsamK/signal-cli#487]
Register --voice parameter does not work.

I used this command: signal-cli -u +420XXXXXXXXX register --voice
... but it throws:
Captcha invalid or required for verification (null)

**Comment by jakob42** [comment]
How did you solve this? I'm at the same problem atm:
```
$ ./signal-cli -u +123456789 register --voice
Captcha invalid or required for verification (null)
```

**Comment by freddieleeman** [comment]
I get the same error without the `--voice` parameter.

**Comment by stormy-gh** [comment]
@jakob42 
$ ./signal-cli -u +123456789 register --captcha xxxxxxxxxxxxxxxxxxxxxx

To get the token, go to https://signalcaptchas.org/registration/generate.html Check the developer tools for a redirect starting with signalcaptcha:// Everything after signalcaptcha:// is the captcha token.

Details: 
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#register

**Comment by jakob42** [comment]
Worked for me, thanks!
