### ISSUE TITLE
Captcha invalid when nothing recieved at all in macOS

### ISSUE THREAD

**Issue by surelynottrue** [AsamK/signal-cli#489]
`WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
Captcha invalid or required for verification (null)
`
I get this error whenever I try to do the register step. Something I am missing?

**Comment by devstudent89** [comment]
I'm getting the same error message when trying to register a new user on Windows!

Following

**Comment by AsamK** [comment]
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#register
