### ISSUE TITLE
cannot link to existing android device

### ISSUE THREAD

**Issue by anarcat** [AsamK/signal-cli#49]
the [manpage](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.txt#L69) says this:

> link
> -----
> 
> Link to an existing device, instead of registering a new number.  This shows a
> "tsdevice:/…" URI. If you want to connect to another signal-cli instance, you can
> just use this URI. If you want to link to an Android/iOS device, create a QR code
> with the URI (e.g. with qrencode) and scan that in the Signal app.
> 
> *-n* NAME, *--name* NAME: Optionally specify a name to describe this new device.
> By default "cli" will be used.

I was assuming that I could link against an existing device out of the box, but instead I get a null pointer exception.

To reproduce, I have more or less followed the instructions in the README:

```
export VERSION=<latest version, format "x.y.z">
wget https://github.com/AsamK/signal-cli/releases/download/v"${VERSION}"/signal-cli-"${VERSION}".tar.gz
sudo tar xf signal-cli-"${VERSION}".tar.gz -C /opt
sudo ln -sf /opt/signal-cli-"${VERSION}"/bin/signal-cli /usr/local/bin/
```

Then ran the link command:

```
$ signal-cli link         
Exception in thread "main" java.lang.NullPointerException
	at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.connect(WebSocketConnection.java:81)
	at org.whispersystems.signalservice.internal.push.ProvisioningSocket.getProvisioningUuid(ProvisioningSocket.java:29)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getNewDeviceUuid(SignalServiceAccountManager.java:348)
	at org.asamk.signal.Manager.getDeviceLinkUri(Manager.java:363)
	at org.asamk.signal.Main.handleCommands(Main.java:175)
	at org.asamk.signal.Main.main(Main.java:68)
```

Did I do something wrong?

**Comment by Trolldemorted** [comment]
Doesn't look like your fault: `ProvisioningSocket` is calling the `WebSocketConnection` constructor without a `CredentialsProvider`, which is tried to be dereferenced in `connect()`.

If you need a quick solution i suggest you fall back to v0.5.2.

This is more of a [libsignal-service-java](https://github.com/Turasa/libsignal-service-java) issue, though.

**Comment by AsamK** [comment]
Fixed in libsignal-service master: https://github.com/Turasa/libsignal-service-java/commit/bdd19a69835cfb16b11553964feadd879dfb49aa
Will be fixed in signal-cli in the next release.

**Comment by anarcat** [comment]
@AsamK cool, thanks - can't wait!

**Comment by Trolldemorted** [comment]
Is there anything bigger planned for the next release?

If we can help, just let us know ;)
