### ISSUE TITLE
dbus mentions

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#491]
Is it possible to see if a person is mentioned via dbus?

**Comment by exquo** [comment]
Looks like it's a negative. I've just tried running `dbus-monitor`, sent myself a message with a mention, and it looked like this:

	signal time=1617000000.000000 sender=:1.2000 -> destination=(null destination) serial=33 path=/org/asamk/Signal; interface=org.asamk.Signal; member=MessageReceived
		 int64 1617000000000
		 string "+1234567890"
		 array of bytes [
				xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx xx 
				xx xx xx xx xx xx xx xx 
		 ]
		 string "￼ message text"
		 array [
		 ]

The mention should be before the "message text", where ￼ is. (somewhat related: #409)

So, this can be a feature request. Mentions are shown in JSON and regular output though.

**Comment by patcon** [comment]
From https://github.com/AsamK/signal-cli/issues/579#issuecomment-832024789, suggested change to accommodate this:

https://github.com/AsamK/signal-cli/blob/357e278f48a6e1b3e3ab58f2ae34053ab1933b96/src/main/java/org/asamk/signal/JsonDbusReceiveMessageHandler.java#L70-L75

to (with some other work):

```java
                        conn.sendMessage(new Signal.MessageReceived(objectPath,
                                message.getTimestamp(),
                                sender.getLegacyIdentifier(),
                                groupId != null ? groupId : new byte[0],
                                message.getBody().isPresent() ? message.getBody().get() : "",
                                JsonDbusReceiveMessageHandler.getAttachments(message, m), // returns json
                                JsonDbusReceiveMessageHandler.getMentions(message, m))); // NEW: returns json
```

**Comment by patcon** [comment]
PR for review linked above :)

**Comment by AsamK** [comment]
Mentions are now included in the new message extras of the dbus signal: https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/DbusReceiveMessageHandler.java#L134
