### ISSUE TITLE
Cannot add users to group, showing "Failed to send message: Conflict" error

### ISSUE THREAD

**Issue by koyin** [AsamK/signal-cli#492]
What I am trying to do is to add some users to an existing v2 group. I have two phone numbers so I will use Account A and B in the following content. Account B is the one used in signal-cli.

The v2 group that I am using is created with the Signal app on my phone using Account A, then I created a share link and make Account B join the group with the `joinGroup --uri` command. At this stage nothing is wrong, I try to send a message with Account B to the group using the `send` command and I can receive it on my phone with Account A.

The problem started when I tried to add another Account C to the group. When I add the account with `updateGroup -m +XXXX`, the action was not successful and the following error appears.

> 2021-02-03T23:12:10.596+0800 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: HK                       
Failed to send message: Conflict

I have tried different ways, such as joining the group with share link. But if Account C joins the group with the share link, although on the app with Account A I can see Account C has joined the group, such information cannot be seen with Account B, by using the `listGroups -d` command there is still only 2 users in the groups. At the moment, Account A and C can chat together in the group, but if I send a message to the group with Account B (signal-cli account), only Account A can receive the message, the Account C sees nothing. The same situation also appeared if I add Account C to the group with Account A by direct adding on the app. I have also tried to set the group to be invitation-only, and let Account C request joining the group using the share link. The join request can be seen on Account A, but nothing shows up on Account B, when I check it with `listGroups -d` command, Pending Members remains empty.

**Comment by AsamK** [comment]
you probably need to run the `receive` command to get the latest group state.
signal-cli hasn't implemented conflict resolution for updating groups yet, but if you call receive before trying to update the group, it should work.

**Comment by koyin** [comment]
> you probably need to run the `receive` command to get the latest group state.
> signal-cli hasn't implemented conflict resolution for updating groups yet, but if you call receive before trying to update the group, it should work.

Looks like it's working. However, I still cannot accept new users as "Pending Members" is still remain empty after using `receive`, but I can do it the other way by accepting users on the app and use `receive` to update group state, and I am able to send messages to all group members.

Thanks for your help!
