### ISSUE TITLE
Captcha invalid or required for verification (null)

### ISSUE THREAD

**Issue by EliseRemise** [AsamK/signal-cli#495]
I know this is the same as #489 However i think something is up. I get the same error on a ubuntu 20.04 box. I followed the instructions as provided at https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#register however i get nothing from https://signalcaptchas.org/registration/generate.html . This is not really a signal-cli problem but prevents registering a new device. Does anyone know a way around this?

**Comment by AsamK** [comment]
If you don't see anything on that page, ie. no recaptcha images, you probably need to allow all javascript and iframes on that page.

After filling the captcha, the site doesn't show the token but redirects to a signalcaptcha:// url that contains the token. On mobile devices that url is handled by the apps.
To see the URL you can open the browser dev tools (F12) before completing the captcha. There you should see the token in the console or network tab.

**Comment by EliseRemise** [comment]
Thank you for the clarification, I was obviously a bit clueless here. For people with a similar knowledge level: The code appeared in the console (firefox) as "Prevented navigation to “signalcaptcha://CODE" due to an unknown protocol." .  Which now makes complete sense.

**Comment by AsamK** [comment]
Great, I've added a wiki page for it. Feel free to update it if something's missing or unclear:
https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha

**Comment by RS-eco** [comment]
Thanks for the wiki, however I still struggle to find the "signalcaptcha://CODE" in the browser development tools. :/
All I can find using Firefox under Network is: signalcaptcha://" + token in the generate.html file. Could you maybe clarify in which file the code is located and how the CODE should look like, i.e. number of digits/letters, ...

Thanks a lot.

**Comment by Gargamehl** [comment]
within the body tag of that captcha-URL there is no code. I am stuck.
no idea about that data-sitekey..

```
<script src="https://www.google.com/recaptcha/api.js"></script>

<div class="g-recaptcha"
     data-sitekey="6LedYI0UAAAAAMt8HLj4s-_2M_nYOhWMMFRGYHgY"
     data-callback="onToken"
     data-size="invisible">
</div>

<script>

function onToken(token) {
  window.location = "signalcaptcha://" + token;
}

window.onload = function(e) {
  grecaptcha.execute();
}

</script>

```

**Comment by eracze** [comment]
Hello I have the exact same problem as @Gargamehl, the redirect link is nowhere to be found

**Comment by gcey** [comment]
Without the captcha parameter I get
```
Captcha required for verification, use --captcha CAPTCHA
To get the token, go to https://signalcaptchas.org/registration/generate.html
Check the developer tools (F12) console for a failed redirect to signalcaptcha://
Everything after signalcaptcha:// is the captcha token.
```
And with the captcha parameter I get

`Invalid captcha given.`

**Comment by Sgn-32** [comment]
I added a hint to the wiki https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha

**Comment by gcey** [comment]
> I added a hint to the wiki https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha

Is this an answer to my problem (see above)? Please help me. Many thanks in advance!

**Comment by Sgn-32** [comment]
@gcey Have you read the instruction in the link?

When you get the notification that captcha is necessary, you get the captcha from:
https://signalcaptchas.org/registration/generate.html

Activate the dev tools (F12) in Firefox.
In the dev tools go to "Console".
Enabled in the "Console Settings" (gear icon, right ) the "Persist logs"
Solve the puzzle
In the logs, something like `signalcaptcha://` should appear
Everything after `signalcaptcha://` is the captcha token.

**Comment by gcey** [comment]
Yes.
But I don't see any puzzle there, just a completely empty page.
Nevertheless `signalcaptcha://<some-very-long-string>` appears in the logs.
When I execute `signal-cli -u <my-phone-number> register --voice --captcha <some-very-long-string>`
I get `Invalid captcha given.`

**Comment by Sgn-32** [comment]
> If you don't see anything on that page, ie. no recaptcha images, you probably need to allow all javascript and iframes on that page.

Which level (Standard, Strict or Custom) are the "Privacy & Security" of Firefox?
Should be possible with "Standard" to see the captcha-puzzle.

> Invalid captcha given

Seems that the captcha-Code isn't activated, because the puzzle isn't solved.
But try it with additional `--verbose`

**Comment by gcey** [comment]
Level is "Standard", but even with "Custom" and nothing blocked the page is empty.
Also with Chrome it didn't work, but fortunately with Edge the puzzle is shown and everything works very well.
Many thanks!

**Comment by wayneworkman** [comment]
I added a helpful Python script to the wiki page for this, for Linux Firefox users. Perhaps works for others too.

**Comment by findell666** [comment]
It worked for me on Firefox in a private navigation window :)
