### ISSUE TITLE
Cannot Resolve Session Bus Address

### ISSUE THREAD

**Issue by rstoever** [AsamK/signal-cli#50]
Hi

I´ll instaled libmatthew-java-0.8 but I try to use signal-cli with daemon and return yet org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address

java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

variables
CLASSPATH="/usr/local/share/java:/usr/local/lib/jni:/opt/jdk1.8.0_121:/usr/local/share/java:/usr/local/lib/jni:/opt/jdk1.8.0_121"
JAVA_HOME="/opt/jdk1.8.0_121"
 PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/opt/jdk1.8.0_121/bin"

[signal-daemon.txt](https://github.com/AsamK/signal-cli/files/744987/signal-daemon.txt)

OS: CentOS Linux release 7.2.1511 (Core)
 3.10.0-327.el7.x86_64

**Comment by AsamK** [comment]
It seems like you don't have a user dbus session running. Starting of the user dbus is distribution specific.
For testing, you can start a session dbus daemon like this:
`$(dbus-launch)`

**Comment by ra-rock** [comment]
i'm running `dbus-launch` on ubuntu and still get the exception when trying to run `./signal-cli -u USERNAME daemon`

**Comment by kwshi** [comment]
Hi there, I'm having this same issue.  To my understanding, the following commands/output indicate that a DBus user session _is_ running:

```bash
[kshi@(none) signal-cli-0.7.1]$ ps aux | grep dbus | grep -- --session
kshi      1278  0.0  0.0   3432  1848 ?        Ss   09:30   0:00 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-address 7 --session
[kshi@(none) signal-cli-0.7.1]$ dbus-send --session --dest=org.freedesktop.DBus --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1608841679.436810 sender=org.freedesktop.DBus -> destination=:1.94 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "org.freedesktop.Notifications"
      string "org.mpris.MediaPlayer2.firefox.instance1721"
      string ":1.94"
      string ":1.9"
      string "org.a11y.Bus"
      string ":1.10"
      string ":1.57"
      string ":1.0"
      string ":1.36"
      string ":1.1"
      string "org.PulseAudio1"
      string "org.pulseaudio.Server"
      string "org.remmina.Remmina"
      string ":1.37"
      string ":1.3"
      string ":1.4"
      string "ca.desrt.dconf"
      string ":1.5"
      string ":1.6"
   ]
```

and yet

```
[kshi@(none) signal-cli-0.7.1]$ ./bin/signal-cli -u +1********* daemon
Exception in thread "main" java.lang.RuntimeException: Cannot Resolve Session Bus Address
	at org.freedesktop.dbus.connections.impl.DBusConnection.lambda$getConnection$1(DBusConnection.java:257)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:165)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:228)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:184)
	at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:51)
	at org.asamk.signal.Main.handleCommands(Main.java:190)
	at org.asamk.signal.Main.handleCommands(Main.java:141)
	at org.asamk.signal.Main.main(Main.java:65)
```
