### ISSUE TITLE
Feature request: remove someone from group

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#502]
We can add other people to a group and remove ourselves from a group, but we cannot remove other users from a group.

would be awesome if that option would exist as well

**Comment by chetbox** [comment]
This would be really helpful. Our use case is keeping group members in sync with users who have paid a subscription to our community.

**Comment by AsamK** [comment]
Implemented in a91e3f762e0e5d6a9cf9e208fe85207d7829e22d
