### ISSUE TITLE
register broken with captcha error

### ISSUE THREAD

**Issue by Sputnick85** [AsamK/signal-cli#503]
Hi there,

today i tried to implement the signal-cli but unfortunately every time i tri to register i get  this error:

singal-cli V0.7.4 on Ubuntu 18.04.5 LTS with openjdk 11.0.9.1 2020-11-04

```
./signal-cli -v -u +491XXXXXXXXXX register
Captcha invalid or required for verification (null)
```

any suggestions?

**Comment by AsamK** [comment]
https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha
