### ISSUE TITLE
Config file lock acquired

### ISSUE THREAD

**Issue by rstoever** [AsamK/signal-cli#51]
Hi,

I´m using signal-cli to messages from my monitoring to my client, but in test I get message from program
-> Config file is in use by another instance, waitingâ¦
-> Config file lock acquired.
When the program is execute in parallel.

Time to wait to execute is in range 2 to 15 seconds, is correctly ?

OS: CentOS Linux release 7.2.1511 (Core)
 3.10.0-327.el7.x86_64

**Comment by kb100** [comment]
If you are executing a receive command, there is a default wait time of 5 seconds before the program terminates. You can prevent this using the `receive --timeout=0`.

**Comment by rstoever** [comment]
Hi
But its time of 2 to 15 seconds is in to SEND messaage.
And problem of lock ?

**Comment by Trolldemorted** [comment]
you may have only one client running at a time, since signal is a stateful protocol and you don't want race conditions to corrupt your sessions.

**Comment by rstoever** [comment]
But I want to send many messages in same time. Or I can not?

**Comment by Trolldemorted** [comment]
The session state must be changed after every sent or received message, so you cannot send messages with full parallelism.

How many messages per second do you want to send? I integrated my signal-cli into nagios and i did not block on the lock for a long time.

**Comment by rstoever** [comment]
I don´t know how messages per second I will to send, but in past I already to many messages per second.
I just to test app to clarify my experience and dont have a headach with it.

Ok, tkz and it does not accord with my environment.

I will try to use the same telegram.

**Comment by kb100** [comment]
One thing you can do to reduce send times is to uses the session bus method of running signal-cli. On the other hand, the Signal servers themselves rate limit how many messsages you can send per second. I would imagine telegram does the same. This is to prevent denial of service attacks on the signal servers, essentially to prevent one person from using of all the bandwidth.
