### ISSUE TITLE
Extract and display received contacts from DataMessage

### ISSUE THREAD

**Issue by Atomic-Bean** [AsamK/signal-cli#512]
Signal's Data Message can contain [a list of contacts](https://github.com/signalapp/Signal-Android/blob/master/libsignal/service/src/main/java/org/whispersystems/signalservice/api/messages/SignalServiceDataMessage.java#L34). ATM this is not outputted in the receive command.

I'll probably make a PR for this eventually.

**Comment by Atomic-Bean** [comment]
So it seems there's two parts to this. The first is adding all the fields from the contacts to our output and the second is downloading the contact's avatar, if there is one (Which uses the same format as a normal attachment).

When we receive a contact/s message, I'm currently downloading any avatars to the attachments folder, but I think we'd probably want to do the Avatars folder instead. Where do you want it?

**Comment by AsamK** [comment]
I think storing it in the attachments folder is fine. The shared contacts are not persisted, so storing it in the avatars folder doesn't feel right.
