### ISSUE TITLE
Captcha invalid while registering number

### ISSUE THREAD

**Issue by nikkindev** [AsamK/signal-cli#513]
Registering a number on a new device returns with the error  

`Captcha invalid or required for verification (null)`  

The number was already registered on a VM, but the VM was deleted without de-registering (if that's even possible) So, tried registering on a new device and it returns with the above stated error. Any way to get around it?

**Comment by AsamK** [comment]
see https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha
