### ISSUE TITLE
updateGroup via Dbus: Cannot set large image as group avatar (or improve error message)

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#514]
While implementing the updateGroup functionality via Dbus in my Perl project, I'm struggling to get a picture set. I always get an error when I include a filename:
Error updating group:org.asamk.Signal.Error.Failure: Response: Response{protocol=h2, code=400, message=, url=https://cdn.signal.org/}

Just to add: I can create a new group, change group name or add members ok. I just can't set a group picture.

Any plans to bring the dbus interface to the same functionality level as the command line, btw?

Refers to signal-cli 0.7.4.

**Comment by bublath** [comment]
I found the issue. Actually I accidently took a pretty large jpg (6.7MB), after I resized it to 300K it worked.
So I guess the issue is rather about either handling large pictures or providing an accurate error message (image too large)

**Comment by johnfreed** [comment]
@AsamK  I believe this issue can be closed, as the error message now specifically warns about an oversized image file.
