### ISSUE TITLE
signal-cli link hangs and times out

### ISSUE THREAD

**Issue by gurucubano** [AsamK/signal-cli#515]
I have installed `signal-cli` from ports in my FreeBSD-13 CURRENT laptop. When I try to make a 'link' to use this with the `axolotl` in my Ubuntu BQ E4.5 mobile as a second device, it generates the URI and then it hangs and times out:

```
$ uname -a
FreeBSD c720-r368166 13.0-CURRENT FreeBSD 13.0-CURRENT #23 r368166M: Thu Dec 17 13:12:37 CET 2020     guru@c720-r368166:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
$ signal-cli -v
signal-cli 0.6.12

$ signal-cli  link -n freebsd-cli
tsdevice:/?uuid=dCLeTldDe-C79Z3GP89Vsg&pub_key=Be7gi8xrEn2XowTtXou8uLQgebSHb4toUEyKu5cdEqtP
Link request timed out, please try again.
```

And the URI does not work in the `axolotl` app in the mobile. What do I wrong? Is `signal-cli` waiting for some key input?

**Comment by bublath** [comment]
signal-cli is waiting for you to can the qrcode on your mobile device, if you don't do that for a while, it times out. Check the Wiki for details https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)

**Comment by gurucubano** [comment]
The procedure should be documented in the man page part of `link`. Thanks for the hint.
