### ISSUE TITLE
How can I create a groupInviteLink?

### ISSUE THREAD

**Issue by mhkhung** [AsamK/signal-cli#523]
It seems to be always null for groups created from the cli

**Comment by AsamK** [comment]
Advanced group editing, like enabling group links, configuring settings and admins and removing members are not implemented yet in signal-cli.

**Comment by mhkhung** [comment]
I got enabling group links working. Will you be accepting PRs?

**Comment by Atomic-Bean** [comment]
> I got enabling group links working. Will you be accepting PRs?

Can confirm that he's accepted multiple of my PRs and other peoples as well.

**Comment by AsamK** [comment]
Now implemented in 03589f858ba2cf52df4d85a9d68df3f3cda5cb74
