### ISSUE TITLE
Continuous receive mode

### ISSUE THREAD

**Issue by TheShanMan** [AsamK/signal-cli#525]
I have an enhancement request for keeping signal-cli running continuously in receive mode, redirecting to a text file as messages come in. My use case allows for running signal-cli on demand to get the latest messages, however it takes a significant amount of time to load the jvm and then receive the messages. If I could keep signal-cli running it would eliminate that "each time" overhead so my on demand message processing could be faster.

**Comment by Atomic-Bean** [comment]
Set timeout to a negative number, then it will keep receiving messages forever (Run `signal-cli -u +XXXXXXXXXX receive --help` for more info)

**Comment by rdtech2020** [comment]
> 

how to set ? could you write command
