### ISSUE TITLE
A simple batch sending script

### ISSUE THREAD

**Issue by n8fr8** [AsamK/signal-cli#53]
I've created a simple wrapper script for sending batch messages from an external text file

https://gist.github.com/n8fr8/9a4b693a6985ba97d5ce4632143f8994

It is very basic, but does provide value to people who have the use cases or needs I describe here:
https://nathan.freitas.net/2017/02/13/sending-secure-broadcast-messages-with-signal/

Otherwise, thanks for this amazing project and work. It is very useful for many things.

**Comment by AsamK** [comment]
I've added a link to the wiki: https://github.com/AsamK/signal-cli/wiki
