### ISSUE TITLE
updateGroup does not find an existing group

### ISSUE THREAD

**Issue by gurucubano** [AsamK/signal-cli#538]
Hello,

What do I wrong here:
```
$ echo Malepartus | base64 -e
TWFsZXBhcnR1cwo=
$ echo TWFsZXBhcnR1cwo= | base64 -d
Malepartus

$ signal-cli -u +49176xxxxxxxx updateGroup -g 'TWFsZXBhcnR1cwo=' -a malepartus.jpg
Failed to send message: Group not found: TWFsZXBhcnR1cwo=
```

**Comment by AsamK** [comment]
The groupid is a random number, not the group name. You can get the id with listGroups

**Comment by gurucubano** [comment]
Thanks for the explanation. The grouid is base64 encode, why does it not give any meaningful on decode:
```
$ signal-cli -u +49176xxxxxxxxx listGroups  
Id: bji01GIbZWF2Ld2inczMmA== Name: Malepartus  Active: true Blocked: false
$ echo 'bji01GIbZWF2Ld2inczMmA==' | base64 -d | od -tx1
0000000    6e  38  b4  d4  62  1b  65  61  76  2d  dd  a2  9d  cc  cc  98
```

**Comment by bublath** [comment]
There is a difference between groupID and group name.
Internally Signal uses the IDs and the hex string you decoded is probably just about right.
The name itself would not be unique - imagine how may people created a "Test" group

**Comment by gurucubano** [comment]
I tried to add a member to the group which failes, why?
```
$ signal-cli -u +49176xxxxx listGroups  -d
Id: bji01GIbZWF2Ld2inczMmA== Name: Malepartus  Active: true Blocked: false Members: [+49176xxxxxxx]
$ signal-cli -u +49176xxxxx updateGroup -g 'bji01GIbZWF2Ld2inczMmA==' --member +49170xxxxxx
Failed to send message: Unable to parse entity
```

**Comment by bublath** [comment]
In my system the groupID is much longer (at least twice as long).
Is that a V1 group? Maybe there is a mismatch between V1 and V2 groups?
Basically make sure you have the latest versions (signal-cli, app), that signal-cli is correctly using the native libraries and recreate a group
