### ISSUE TITLE
"No local users found, you first need to register or link an account"

### ISSUE THREAD

**Issue by CraigCaseyContreras** [AsamK/signal-cli#539]
Hi, sorry but I must be missing something. I am able to send and receive messages after installing signal-cli system-wide and by using daemon. I am trying to use the python code now but I keep getting a "timed out" error. I ran "systemctl status dbus-org.asamk.Signal.service" to see what is wrong and it returns the following:

● signal-cli.service - Send secure messages to Signal clients
   Loaded: loaded (/etc/systemd/system/signal-cli.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-02-24 13:36:23 EST; 4min 28s ago
 Main PID: 29590 (code=exited, status=1/FAILURE)

Feb 24 13:36:22 casey systemd[1]: Starting Send secure messages to Signal clients...
Feb 24 13:36:23 casey signal-cli[29590]: No local users found, you first need to register or link an account
Feb 24 13:36:23 casey systemd[1]: signal-cli.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 13:36:23 casey systemd[1]: signal-cli.service: Failed with result 'exit-code'.
Feb 24 13:36:23 casey systemd[1]: Failed to start Send secure messages to Signal clients.

I am guessing the issue is that I have to register or link an account, but how do I do this? I registered a phone number through Signal, but I guess that's not what this means? Any help is appreciated! Thank You!

**Comment by bublath** [comment]
Check the command line used to start the service (/etc/systemd/system/signal.service)
does --config point to the directory where you stored you configuration (needs to have a data directory containing a file with the phone number)?
Is there a User=<username> setting and does this user have read/write permissions to the config directory?

**Comment by CraigCaseyContreras** [comment]
I figured it out! I did not have a user name for the phone number. I just had to give it a name. It was Null
