### ISSUE TITLE
Identity is still listed as trusted when invalid due to App reinstallion and is listed twice

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#540]
Scenario: Contact reinstalls Signal and gets a new safety key.

Step 1) send a message
reply: Failed to send message: Untrusted Identity for xxxxxxx
Correct

Step 2) listIdentities
There are two entries now for the number - the old one (still trusted) and the new one (untrusted). 
I believe that is also correct. The new (untrusted one ) could be fake and the old one should remain.

Step 3) trust -v on the old entry (User accidentially used the first one in the list)
Reply: WARN Manager - Failed to send verification sync message: Untrusted identity key!
At this stage the old entry should be invalidated or even better deleted. It is clear now that it is no longer valid

Step 4) trust -v with the correct key
No reply. 
A success message would be nice. The identity is correctly trusted, but the old entry still remains (and still is trusted)
The old entry should be deleted since it is clear that only the new one is valid.

I have not experienced side effects of having two (trusted) identity entries for the same number, but I could anticipate that this can become the cause of other issues.

**Comment by AsamK** [comment]
I've improved the behavior to remove all old identities after trusting a new one.
In general signal-cli only outputs if there is something useful to print, otherwise success is signaled by a 0 status code.
