### ISSUE TITLE
Re-Use as java project - code exits with value 137

### ISSUE THREAD

**Issue by col-panic** [AsamK/signal-cli#544]
Hy there,

i am using all the libraries and stuff within your great tool, and try to rebuild it as Java project. Everything seems find, and signal-cli works as expected.

If I however execute the same thing out of the IDE, manually assembling the command, the code simply exits with return value 137. 

I don't seem to find where it gets killed, or whats leading to it.

Is there any kind of embedded protection that prevents me from doing so - or is there just something I am missing on my site? Just glad for some feedback here, such that I don't waste time when this kind of usage is not meant for!

thanks!

**Comment by AsamK** [comment]
There's no embedded protection in the code.

**Comment by col-panic** [comment]
To follow up:

The 137 was caused by a wrong native installation of the `libsignal_jni.dylib`, which led to a
`'/Library/Java/JavaVirtualMachin…' terminated by signal SIGKILL (Forced quit)` by the OS! 
This was not shown within Eclipse! I fixed the native lib installation - now it works! 

Thanks for your response on this!
