### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Lurleneeth** [AsamK/signal-cli#545]
Hello there
I'm not sure what the the problem is...

$ ./signal-cli -u +"$NUM" register
ERROR App - Error loading or creating state file: null
$ ./signal-cli -u +"$NUM" register
ERROR App - Error loading state file for user +44... : Incorrect file format: expected parameter password not found

Can you tell?

**Comment by AsamK** [comment]
Hm, not sure ... can you try removing the state file (`~/.local/share/signal-cli/data/+$NUM`) and run the register command again in verbose mode.
`signal-cli -u +"$NUM" --verbose register`
