### ISSUE TITLE
Windows 7: libzkgroup missing

### ISSUE THREAD

**Issue by Crypto-Bee** [AsamK/signal-cli#546]
Hello,
I used signal-cli until now succesfully. But now I need a newer signal-cli-version to use the V2Group-support. I would like to join a V2Group. But I got the message:

**WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup**

I did the following:

1. downloading "signal-cli-0.7.4" and "libzkgroup.dll" (v0.7.0)
2. rename the file "zkgroup-java-0.7.0.jar" in "zkgroup-java-0.7.0.zip"
3. delete "libzkgroup.so"
4. copy and paste "libzkgroup.dll"
5. rename the file "zkgroup-java-0.7.0.zip" back to "zkgroup-java-0.7.0.jar"
6. try using signal-cli, but the above ERROR appears

I use Windows 7 Professional, 64-Bit. What did I wrong? or Where is the bug?
Is the "libzkgroup.dll" inaccurate? Is in signal-cli something missing to support the "libzkgroup.dll"?

**Comment by Tsjippy** [comment]
See [This dicussion](https://github.com/AsamK/signal-cli/discussions/496)

**Comment by Crypto-Bee** [comment]
The solution for all Windows users inclusive the solution to use the new release 0.8.0:
### https://github.com/AsamK/signal-cli/issues/517#issuecomment-779326698
