### ISSUE TITLE
Contact and group names over dbus

### ISSUE THREAD

**Issue by thefinn93** [AsamK/signal-cli#55]
Are there plans to expose contact and group names over the dbus interface?

**Comment by AsamK** [comment]
I have no direct plans for this, but it's definitely wanted.
If someone wants to implement it, you're welcome to make a PR.

**Comment by thefinn93** [comment]
Great. I'm working on [a weechat plugin](https://github.com/thefinn93/signal-weechat) that uses signal-cli and that's one of the biggest problems I'm currently running into.

**Comment by thefinn93** [comment]
:/ disregard closure, hit the wrong button

**Comment by thefinn93** [comment]
Update: [I started working on this](https://github.com/AsamK/signal-cli/compare/master...thefinn93:names-over-dbus), also decided to make methods to set contact names. They don't seem to be sticking across restarts, any hints on what I should be doing to save contact names?

**Comment by thefinn93** [comment]
Closing as #62 is now open
