### ISSUE TITLE
unrecognized arguments: '--captcha'

### ISSUE THREAD

**Issue by c4lliope** [AsamK/signal-cli#551]
```bash
$ docker run -v $HOME/.signal:/home/gradle --rm -it bisentenialwrug/signal-cli -u +1616... register
Captcha required for verification (null)
```

Go see [wiki] and [signalcaptchas].

[wiki]: https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#commands
[signalcaptchas]: https://signalcaptchas.org/registration/generate.html

```bash
$ docker run -v $HOME/.signal:/home/gradle --rm -it bisentenialwrug/signal-cli -u +1616... register --captcha 03AG...o1sP
signal-cli: error: unrecognized arguments: '--captcha'
```

**Comment by AsamK** [comment]
looks like you're using an old version, --captcha was added in 0.6.12
`signal-cli --version`

**Comment by c4lliope** [comment]
ah-ha. `signal-cli 0.6.7`
I'll rebuild or repull the docker image, i suppose.
Much obliged on the quick help!

**Comment by c4lliope** [comment]
I guess it's concerning that:

`bisentenialwrug/signal-cli --version` is `signal-cli 0.6.7`
`kayvan/signal-cli --version` is `signal-cli 0.5.6`

Seems like there are no up-to-date images that are publicly pullable.
I'm curious if merging #94 or any other approaches could help,
we'd really like to use Docker on our machine.

**Comment by c4lliope** [comment]
Dang. I cloned this codebase and tried to compile using #94's Dockerfile (replacing `FROM` with `FROM gradle:6.8.3-jdk11`). 
No luck, seems like that code base's build process has expired.

I recommend closing #94 because the build will break if merged.

**Comment by bafu** [comment]
If you are not sure what is the content for the `--captcha` parameter, this comment is for you.

---
Steps to register with `--captcha`

1. Open a browser and go to https://signalcaptchas.org/registration/generate.html
    1. It's normal to see a blank page.
    2. If browser asks "Open xdg-open?", accept the request.
2. Open the browser's developer console, and you will see the `signalcaptcha://<captcha-token>`

    ![Screenshot from 2021-04-08 16-16-09](https://user-images.githubusercontent.com/292790/113993106-a8cd5280-9886-11eb-9380-4afe7b71482f.png)

4. Copy the `captcha-token` to the CLI command (w/o the leading `signalcaptcha://`) 

    ```
    $ signal-cli -u <your-phone-number> register --captcha <captcha-token>
    ```

5. If you do not get any error, the next step is to run the verify command.
