### ISSUE TITLE
modern Dockerfile

### ISSUE THREAD

**Issue by c4lliope** [AsamK/signal-cli#553]
Preceded by #551 and #94.

I was able to build `signal-cli` seconds ago using this Dockerfile.

```Dockerfile
FROM gradle:6.8.3-jdk11

LABEL maintainer "Kayvan Sylvan <kayvansylvan@gmail.com>"

COPY . /tmp/src
WORKDIR /tmp/src

USER root
RUN gradle build && gradle installDist && gradle distTar
RUN tar xf build/distributions/signal-cli-*.tar -C /opt \
  && ln -sf /opt/signal-cli-*/bin/signal-cli /usr/local/bin/ \
  && rm -rf /tmp/src

USER gradle
WORKDIR /home/gradle

ENTRYPOINT ["/usr/local/bin/signal-cli"]
```

Packages version 0.8.0

**Comment by maxcountryman** [comment]
This is interesting but I think it would be nice to be able to build in a build stage and then reference the build artifact in subsequent layers.

**Comment by Herohtar** [comment]
There's no need to run all three of those gradle commands; `gradle build` is sufficient.

Here's a super basic version that uses a separate build stage so you're not left with all the unnecessary Gradle stuff and source code sitting in your image. It also clones the repo during build so you don't have to do it yourself.
```Dockerfile
FROM gradle:jdk11 as build

RUN git clone https://github.com/AsamK/signal-cli.git \
  && cd signal-cli \
  && gradle build --no-daemon \
  && cd build \
  && tar -xvf distributions/*.tar

FROM openjdk:11-jre-slim

COPY --from=build /home/gradle/signal-cli/build/signal-cli* /app

ENTRYPOINT [ "/app/bin/signal-cli" ]
```

**Comment by technillogue** [comment]
If it helps anyone, the Dockerfile we use for native-image is roughly:

```Dockerfile
FROM ghcr.io/graalvm/graalvm-ce:latest as sigbuilder
ENV GRAALVM_HOME=/opt/graalvm-ce-java11-21.2.0/ 
SHELL ["/usr/bin/bash", "-c"]
WORKDIR /app
RUN microdnf install -y git zlib-devel && rm -rf /var/cache/yum
RUN gu install native-image
RUN git clone https://github.com/AsamK/signal-cli
WORKDIR /app/signal-cli
RUN ./gradlew assembleNativeImage

FROM ubuntu:hirsute
WORKDIR /app
COPY --from=sigbuilder /app/signal-cli/build/native-image/signal-cli  /app/
# for signal-cli's unpacking of native deps
COPY --from=sigbuilder /lib64/libz.so.1 /lib64
...
```

**Comment by morph027** [comment]
FYI, another ready to use docker image (amd64 + arm64) plus Debian packages can be found [here](https://gitlab.com/packaging/signal-cli/container_registry) ([Docs](https://packaging.gitlab.io/signal-cli/installation/docker/), [Repo](https://gitlab.com/packaging/signal-cli)).

**Comment by AsamK** [comment]
I'm not planning to add a Dockerfile to the repo, but I've created a wiki page, which links to morph027's repo: https://github.com/AsamK/signal-cli/wiki/Binary-distributions
