### ISSUE TITLE
signal-cli hash file released without the signal-cli package itself

### ISSUE THREAD

**Issue by crazy-matt** [AsamK/signal-cli#554]
The title is self-explanatory. This happened on the last release v0.8.1. 
Is this an intended behaviour specific to your release workflow?

**Comment by bublath** [comment]
The package is there as well, but just named v0.8.1.tar.gz.
Probably some mistake
@AsamK : Can you rename according to the old naming scheme?

**Comment by AsamK** [comment]
package should now be available.
