### ISSUE TITLE
JNI error

### ISSUE THREAD

**Issue by Crypto-Bee** [AsamK/signal-cli#557]
Hello,

i tried to use signal-cli. First I have to install Java Runtime Environment (JRE). The newest i found was JRE 8. But the following Error occured:

### Error: A JNI error has occurred, please check your installation and try again …

What to do? There isn´t a newer Version!?!  It took a very long time to find out where to get a newer JRE. You must now: you can´t get the newer JRE seperatly. You must download Java Development Kit (JDK). This includes the JRE!!!
https://www.oracle.com/java/technologies/javase-downloads.html

I think, some doesn´t know it. Perhaps you can add it in the README.md (Installation, System requirements)?

best regards
Crypto-Bee

**Comment by hoehermann** [comment]
signal-cli needs at least Java 9. Instead of relying on Oracle, you should probably https://adoptopenjdk.net/.

**Comment by Crypto-Bee** [comment]
Okay, next time I use it. Thank you for the information.
