### ISSUE TITLE
receive doesn't work with linked device

### ISSUE THREAD

**Issue by anarcat** [AsamK/signal-cli#56]
i can't seem to receive messages with a phone number that i *linked* (see #28 for my previous experience with this) with signal-cli. i can receive messages with a phone number that was *registered* with signal cli. an example would maybe help clarify this:

* phone number A was registered on an android phone and linked with the signal-cli program
* phone number B was registered directly with signal-cli (register -v + verify)

this works:

```
signal-cli -u A send B -mtest
signal-cli -u B receive -t -1
```

this doesn't work:

```
signal-cli -u B send A -mtest
signal-cli -u A receive -t -1
```

in the above, the Android device that registered A would see the message, but not `signal-cli receive`

i also tried with a friend's phone number (say C). in that case, C would see messages sent with signal-cli, but only the Android device would receive the answers.

any advice on how to debug this? is this normal behavior?

**Comment by anarcat** [comment]
note, btw, that i have tried turning off wifi on the android device to try and make the signal servers or whatever look the other way - no luck.

**Comment by Trolldemorted** [comment]
i just pulled the current master, and my slave cli was able to receive the messages i sent.

Did you try to reset the session?

**Comment by mkroman** [comment]
I'm running the current master branch linked to an Android phone which is the master device, and I'm also unable to receive messages using `signal-cli -u … receive -t -1` as well as `signal-cli --dbus-system receive`.

**Comment by AsamK** [comment]
Thanks for the report. I can reproduce this as well. I'm pretty sure this is an issue in libsignal-service, I'll try to debug this today.
Can you also confirm that receiving works with version 0.5.2? That's the version before a larger libsignal-service update.
