### ISSUE TITLE
docker/alpine (amd64) :: ERROR App - Missing required native library dependency: libsignal-client

### ISSUE THREAD

**Issue by 11notes** [AsamK/signal-cli#560]
`RUN apk add --update --no-cache \
                openjdk11-jre

        RUN apk add --update --no-cache --virtual .tmp \
                wget \
            && wget -qO - https://github.com/AsamK/signal-cli/releases/download/v${SIGNAL_CLI_VERSION}/signal-cli-${SIGNAL_CLI_VERSION}.tar.gz | tar xvzf - -C /tmp \
            && mv /tmp/signal-cli-${SIGNAL_CLI_VERSION} /opt/signal-cli \
            && ln -sf /opt/signal-cli/bin/signal-cli /usr/local/bin/signal-cli \
            && apk del .tmp`

If you run signal-cli you get
`WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
ERROR App - Missing required native library dependency: libsignal-client`
``

`-rw-r--r--    1 node     node      309.6K Nov 16 18:49 zkgroup-java-0.7.0.jar`

since its x86_amd64 and both the libraries are there in /opt/signal-cli/lib I'm at a loss why it is not working anymore. Worked with < 0.6.0

**Comment by AsamK** [comment]
The included native libs are for gnu libc, alpine uses musl libc, so you'll need to compile them for your system.

**Comment by 11notes** [comment]
> 
> 
> The included native libs are for gnu libc, alpine uses musl libc, so you'll need to compile them for your system.

Ah okay, sorry. I compiled it with musl and crt-static, but the client will not load the compiled libs for libsignal_jni.so nor libzkgroup.so. Any ideas why? I've removed your version from the .jar and added mine, but he still complains about the missing dependency. I've added them to the java.library.path, still nothing, same warning.

**Comment by Crypto-Bee** [comment]
>  I've added them to the java.library.path, still nothing, same warning.

At the moment you did this, have you removed the version in the .jar?
