### ISSUE TITLE
Updated profile name in App is not recognized by signal-cli

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#561]
If I changed my profile name via the app and sent a message to signal-cli, it is still showing the old name as sender.
Also tried updating trust with that sender - still same. Is the profile data only created at the first contact and never updated again?
Any way to force an update?

**Comment by AsamK** [comment]
Profiles are currently only updated when required. It's also only updated once every 24h.
Forcing an update is not possible at the moment, except manually deleting the profile from the data file ...
