### ISSUE TITLE
Output paramter --output=json not recognized

### ISSUE THREAD

**Issue by dechemist** [AsamK/signal-cli#566]
When trying to read messages via `signal-cli -u XXXXX receive --json`
One receives the warning 

> WARN ReceiveCommand - "--json" option has been deprecated, please use the global "--output=json" instead.

When using `--output=json` then, the parameter is not recognized
> usage: signal-cli receive [-h] [-t TIMEOUT] [--ignore-attachments] [--json]
signal-cli: error: unrecognized arguments: '--output=json<

kind regards

**Comment by exquo** [comment]
Duplicate of #481, #445.

Looks like this happens often enough. Maybe we can create a FAQ page in the wiki and add it there? @AsamK what do you think? 

Another common question is could be added there right away is performance / time delay / JVM startup when sending messages.

**Comment by dechemist** [comment]
Sorry I did not see those threads.
Solved.

**Comment by exquo** [comment]
No problem! I don't mean it's supposed to be common knowledge, only that we can try to make it more so :)

**Comment by AsamK** [comment]
Yeah, a FAQ page in the wiki sounds like a good idea.
