### ISSUE TITLE
unregister device - error message

### ISSUE THREAD

**Issue by bidaian** [AsamK/signal-cli#567]
I'm using signal-cli 0.8.1 on Linux (Debian 10).

I registered my number:

`signal-cli -u NUMBER register --captcha CAPTCHA`

got the SMS with the code, then verified it:

`signal-cli -u NUMBER verify CODE`

and then, after some tests I tried to unregister the number:

`signal-cli -u NUMBER unregister`

I get this error message:

`Unregister error: Authorization failed!`

The number is successfully unregistered, but the error message says otherwise.

**Comment by AsamK** [comment]
Thanks, the wrong error message is now fixed with 0091c1cf266de225f84d507bb473ac22582d3b15
