### ISSUE TITLE
unregister support

### ISSUE THREAD

**Issue by anarcat** [AsamK/signal-cli#57]
i have registered a test phone number for this... it would be nice if i could abandon it properly as well... as things stand, there's actually no way to do that, that i can think of at least...

**Comment by Trolldemorted** [comment]
https://whispersystems.org/textsecure/unregister/

**Comment by anarcat** [comment]
awwwwesome!!!

**Comment by anarcat** [comment]
hmm... i notice this is not documented in the README... maybe the instructions there should be removed to point solely to the manpage?

**Comment by AsamK** [comment]
That's a good idea. I'll leave only minimal instructions on how to get started in the readme and for the rest point to the man page.
