### ISSUE TITLE
pair new device: "Authorization failed!"

### ISSUE THREAD

**Issue by meejah** [AsamK/signal-cli#570]
(This may be related or similar to #518)

When trying to register a 4th device, I am now getting `Authorization failed!` errors. Since the last device I paired (successfully) I have definitely upgraded signal-cli and also upgraded my "profile" so I can use v2 groups (several of which I have successfully joined).

The traceback I get (when running `signal-cli --verbose .. addDevice --uri ..`) is:

```
org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1447)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1435)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1420)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1362)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1338)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getNewDeviceVerificationCode(PushServiceSocket.java:346)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getNewDeviceVerificationCode(SignalServiceAccountManager.java:621)
	at org.asamk.signal.manager.Manager.addDevice(Manager.java:408)
	at org.asamk.signal.manager.Manager.addDeviceLink(Manager.java:403)
	at org.asamk.signal.commands.AddDeviceCommand.handleCommand(AddDeviceCommand.java:27)
	at org.asamk.signal.App.handleLocalCommand(App.java:209)
	at org.asamk.signal.App.init(App.java:165)
	at org.asamk.signal.Main.main(Main.java:43)
```

I can provide more details if required.

Thanks!

**Comment by meejah** [comment]
The "device" I am pairing is a signal-desktop instance (as are all of the already-paired devices).

**Comment by jmcclelland** [comment]
I have the same problem. I had one primary device and 5 paired devices working using version 0.7.2. Then, one paired device crashed with the Authorization Failed message.

Attempting to restart it gives the same error message.

I upgraded the failing device to 0.9.2 and have the same problem.

I tried to re-pair the device and got the same message (listed in this ticket).

I delete the `~/.local/share/signal-cli` directory of the device that was failing to pair and tried to re-pair the devices, but got the same response listed in this ticket.

Lastly, I noticed that the fourth paired device was not running properly and I can't get it to start either (matybe it was never working?)

Maybe Signal limits the number of paired devices?

**Comment by jmcclelland** [comment]
According to [a terse sentence here](https://support.signal.org/hc/en-us/articles/360007320551-Linked-Devices): "Multiple mobile devices and Android tablets are not currently supported." So, I'm beginning to suspect that Signal is cracking down on more then a set number of devices.

**Comment by meejah** [comment]
More evidence towards the last comment: I used a completely new number, set up `signal-cli` on it and successfully paired a signal-desktop instance on the very device that is failing to pair to the "other" signal-cli instance. So, indeed, it seems something specific to my setup and not anything to do with signal-cli 0.9.0 with newest Signal Desktop...

**Comment by jmcclelland** [comment]
I just had the same experience. I used a new phone number and then successfully registered that number on the server that was getting an authorization failed error before. I went on to link three devices. When linking the last device I got a rate limit error. I waited 15 minutes and tried again and it was successful. At the moment at least, it seems that Signal limits us to one primary device and three linked devices.

I think the way to resolve this issue would be to edit the [wiki page on linking devices](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)) and add something like this to the top:

> signal-cli supports linking additional devices to your primary device. However, according to the [Signal Documentation](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)) "Multiple mobile devices and Android tablets are not currently supported." So you may be limited to a certain number of linked devices. If you exceed that limit, you may get an "Authorization failed" error when trying to link additional ones.

**Comment by AsamK** [comment]
Thanks for the analysis, I've updated the wiki page.
Also feel free to edit the wiki yourself :)

**Comment by exquo** [comment]
> At the moment at least, it seems that Signal limits us to one primary device and three linked devices.

Yes. Apparently, attempting to add a fourth device from a signal-cli primary gives the "Authentication failed". When attempting to add a fourth linked device using _Signal-Android_ as a primary, I think (IIRC) the last previously linked device gets replaced with the new (i.e. fourth) one. 

> according to the Signal Documentation "Multiple mobile devices and Android tablets are not currently supported." 

That is a somewhat different statement, not about the _number_ of the allowed linked devices. It effectively says: _no_ mobile device can be a _linked_ device (but can only be a primary device), and android tablets can't be _either_ linked or primary (i.e. can't run Signal app at all). I've removed that sentence from the wiki, leaving just the info on the number of allowed linked devices.
