### ISSUE TITLE
Device pairing issues

### ISSUE THREAD

**Issue by TrevorBenson** [AsamK/signal-cli#574]
Pairing of the signal-cli to the user works, but not to link mobile device back to the user.

1. Register signal-cli w/o captcha
2. Obtain the captcha from signalcaptchas.org
3. Register signal-cli w/ captcha
4. Receive the PIN on mobile device
5. Verify signal-cli with PIN
6. Generate a QR code from signal-cli + qrencode
7. Open mobile app (see unregistered message)
8. Go to settings, Linked Devices
9. Observe Network Error message preventing linking a device.

The error prevents linking the device, and the only way to get the signal mobile app working is to register it again, which then unregistered the user for the signal-cli app. Once the signal-cli app is unregistered the QR code generated does not work to link to the mobile device and commands from signal-cli confirm the user is no longer properly registered.

Apologies for re-posting the issue, I opened the original ticket under the wrong account.

**Comment by bublath** [comment]
I'm not sure if I understand what you're doing.
You either link signal-cli to a device (to get the message from your phone) or you register a device (to have its own number, which will unregister other devices that previously used that number) - why are you doing both?

**Comment by TrevorBenson** [comment]
I was actually following directions from [another repo](https://github.com/dadevel/alertmanager-signal-receiver) which described this process to connect a device, and mistakenly presumed they had documented valid steps.  Once you asked about link I looked again at `--help` and found link was in the subcommands list, but not with a descrition.  `signal-cli link --help` got me sorted out.

Thanks
