### ISSUE TITLE
signal-cli "forget" contacts 

### ISSUE THREAD

**Issue by mi-gri** [AsamK/signal-cli#575]
I'm using signal-cli 0.8.0 with scli 0.4.0 on Ubuntu Focal.
In scli I can only see my groups and my own contact.
If I edit the ~/.local/share/signal-cli/data/+[...] file and add my contacts to the ContactStore they are shown in scli.
Using signal-cli with the updateContact parameter also works and the contatc will be written in the file.
But after some time they disappear and if I look in the config-file all contacts except for my own number are deleted.

**Comment by maxcountryman** [comment]
I'm seeing this behavior as well. Specifically the `contactStore` property is disappearing.

**Comment by AsamK** [comment]
Are you using signal-cli as a master device (with `register` command) or linked to another device (with `link` command)?
If it's linked to another device, signal-cli get contact update messages from that device and then replaces its contactStore with those contacts.
As a master device it should never forget contacts, then it would be a bug.

**Comment by maxcountryman** [comment]
For me it's a linked device but the behavior you described sounds potentially dangerous: if somehow a linked device receives a blank sync (I suspect it's actually receiving the delta which will be blank if no new contacts have been added) then this is a destructive operation (!) which will result in erasing the local contacts.

What if the behavior instead were to merge with the sync?

**Comment by AsamK** [comment]
There's actually a flag in the message that says if it's a complete sync or a partial sync.
For partial sync signal-cli already performs a merge with the existing contacts.

**Comment by maxcountryman** [comment]
It seems like there's pretty clearly a bug here--contacts are becoming fully removed.

**Comment by mi-gri** [comment]
Same problem here. Maybe it is interesting for troubleshooting that the problem occurs only with contacts and not with groups.

**Comment by exquo** [comment]
One possible cause for this problem: signal app on the phone has not been given a permission to access the phone's contacts. In that case the signal app sees an empty contacts list, and that's what it sends to signal-cli in contacts-sync messages.

**Comment by mi-gri** [comment]
> One possible cause for this problem: signal app on the phone has not been given a permission to access the phone's contacts. In that case the signal app sees an empty contacts list, and that's what it sends to signal-cli in contacts-sync messages.

Not here: App on iPhone and Desktop app on MacOS both have access to cantacts and always shows them.

**Comment by exquo** [comment]
I've tried running signal-cli with a `--verbose` flag to see if it prints out the `CONTACTS_SYNC` data it receives from the servers. The printouts contained info only related to groups, not individual contacts. (I'm just experimenting with troubleshooting, I'm not experiencing the current issue myself - I do have individual contacts in my data file)

(To force issue a `CONTACTS_SYNC` message from signal-android: on the list of contacts, press the 'pencil' button in the bottom right, then in the new screen with contacts press three dots on the top right and click 'Refresh')

Another possibility for what's going on: full contacts sync had been lost, and subsequent partial syncs don't have any new information. On contacts sync the signal servers send only a partial update; if for some reason the full sync information has not been saved, then getting the new sync messages would not help in showing the contacts. I don't know if we can force a complete sync; maybe only through re-linking.

**Comment by 0mp** [comment]
I think I've been experiencing this behavior as well since I started using signal-cli and scli (which was around signal-cli 0.6.5 and before scli 0.1.0).

**Comment by AsamK** [comment]
I've reimplemented the contact storage and removed the code that deleted contacts before a full sync. So contacts shouldn't go missing anymore.
There's now also a new command `sendSyncRequest` to request a full sync, similar to the import contacts button in Signal-Desktop.
