### ISSUE TITLE
remove documentation from README

### ISSUE THREAD

**Issue by anarcat** [AsamK/signal-cli#58]
as discussed in #57, the README is now out of date. we should probably move all of that documentation to the manpage instead.

furthermore, it seems to me it would be better if the manpage was rendered directly on github - for this i believe it would be sufficient to rename it to `.asciidoc`, see the [asciidoc readme for an example](https://github.com/asciidoc/asciidoc/blob/master/README.asciidoc).

**Comment by pimotte** [comment]
Somewhat related: I can't seem to find how to get a group id in the first place. This might be a nice addition to the resulting asciidoc

**Comment by Trolldemorted** [comment]
@pimotte open signal-cli's config and ctrl-f for `groupId`

**Comment by AsamK** [comment]
The group id is shown when creating a group and when receiving a group message.
An additional listGroups command might be a good idea, to list all known groups with id and members.

**Comment by AsamK** [comment]
Done in 0744dcccf117064dcf6c8dbb1312565c0f3e15cb
The README now contains only basic information and links to the man page and the wiki.

Some thoughts, on how the documentation should be handled now:
* README: basic information, how to build, how to run first time, ...
* man page: Description of every command/parameter, some examples
* wiki: More detailed explanations and howtos
