### ISSUE TITLE
Error while receiving messages: Write failed!

### ISSUE THREAD

**Issue by i0x71** [AsamK/signal-cli#582]
UPDATE:
I re-registered and the problem went away, maybe someone will find this useful.

Hi.
I noticed that sometimes signal-cli is throwing errors:
./testRuntime/signal-cli-0.8.1/bin/signal-cli --config testRuntime/signalConf/ -u +1xxxxxxxx --output=json
receive -t -1
{"envelope":{"source":"+1xxxxxxxx","sourceDevice":1,"timestamp":1616773450819,"dataMessage":{"timestamp":1616773450819,"message":"Hffh","expiresInSeconds":0,"viewOnce":false,"mentions":[],"attachments":[],"contacts":[]}}}                                                              
{"envelope":{"source":"+1xxxxxxxxxx","sourceDevice":1,"timestamp":1616773451553,"dataMessage":{"timestamp":1616773451553,"message":"Ff","expiresInSeconds":0,"viewOnce":false,"mentions":[],"attachments":[],"contacts":[]}}}                                                                
Error while receiving messages: Write failed!

In this case there was a 3rd message sent by the client which is not printed here.

After further testing, it looks only about 40% of messages come through.
Most just never show up, and if you send them really fast from the android client, the above error is displayed.
So far the receive functionally in my case is unusable as most messages don't come through.

for some missing messages there are "typingMessage" messages which show up
{"envelope":{"source":"+1xxxxxxx","sourceDevice":1,"timestamp":1616776156545,"typingMessage":{"action":"STARTED","timestamp":1616776156545}}}
{"envelope":{"source":"+1xxxxxxxx","sourceDevice":1,"timestamp":1616776157375,"typingMessage":{"action":"STARTED","timestamp":1616776157375}}}
{"envelope":{"source":"+1xxxxxxxxx","sourceDevice":1,"timestamp":1616776158458,"typingMessage":{"action":"STARTED","timestamp":1616776158458}}}

I tried running updateAccount, but no difference

Version: 0.8.1
Java version: openjdk 11.0.9.1 2020-11-04

**Comment by AsamK** [comment]
The message `Write failed!` comes from libsignal-service-java, if it fails to send a message via the websocket connection.
So this might have been caused by network or server issues ...
