### ISSUE TITLE
receiving and sending using same config

### ISSUE THREAD

**Issue by i0x71** [AsamK/signal-cli#583]
Whats the best way to send and receive messages at the same time ?
It seems you cannot do both at the same time as signal cli complains that config file is in use.

**Comment by exquo** [comment]
You can run signal-cli in daemon mode 
	
	signal-cli daemon

Then add `--dbus` flag to subsequent commands, e.g.

	signal-cli --dbus send -m 'A message' +1234567890

See [man page](https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc#daemon) and [wiki](https://github.com/AsamK/signal-cli/wiki/DBus-service) for further info.

**Comment by i0x71** [comment]
Thanks,
In my case i am using containers and its a bit problematic to use dbus service.
Is there any way or linking 2 signal-cli instances ?

If i generate a link with one instance and try to link a fresh one with addDevice, i get No local users found, you first need to register or link an account

**Comment by i0x71** [comment]
Its rather problematic to use dbus in containers or docker, so i used linking instead.
Please close the ticket.
Thanks

**Comment by maxcountryman** [comment]
I'm curious about dbus within a Docker container as well. While linking is helpful, it doesn't mitigate the config lock problem within the container itself.

**Comment by waikiApp** [comment]
> I'm curious about dbus within a Docker container as well. While linking is helpful, it doesn't mitigate the config lock problem within the container itself.

What ive done is create 2 separate config folders within the container, 1 is used for sending, another is used to receiving.
Dealing with services such as systemd and dbus in container environment is a nightmare at times.

**Comment by i0x71** [comment]
What ive done is create 2 separate config folders within the container, 1 is used for sending, another is used to receiving.
Dealing with services such as systemd and dbus in container environment is a nightmare at times.

**Comment by maxcountryman** [comment]
> What ive done is create 2 separate config folders within the container, 1 is used for sending, another is used to receiving.
> 
> Dealing with services such as systemd and dbus in container environment is a nightmare at times.

I just did this last night and it indeed works. I think this setup probably doesn't work for everyone since your attachments etc will be in one path and not in the other config path. All things considered not too big of an issue but worth pointing out.

**Comment by i0x71** [comment]
As nice as it is to have dbus, it would be ever better to have something that didnt depend on other services to interact with a daemon.

**Comment by maxcountryman** [comment]
> As nice as it is to have dbus, it would be ever better to have something that didnt depend on other services to interact with a daemon.

Fully agree with this. Dbus is cool but not practical in all deployment environments.

**Comment by exquo** [comment]
FWIW, there are a few pull requests (currently unmerged) that implement communication via sockets instead of dbus: #330, #396, #419.

**Comment by maxcountryman** [comment]
Thanks, @exquo—that looks like it would suit my needs pretty well. It would be great if some kind of socket implementation made it into mainline.

**Comment by technillogue** [comment]
Thank you! systemd/dbus is so annoying, Unfortunately I haven't had the time to do the merge correctly since a lot of the features i was taking a stab at were implemented elsewhere. If anyone felt up to helping with #396 that would be very lovely.

**Comment by AsamK** [comment]
I've now implemented a json API based on JSON-RPC, see #679
