### ISSUE TITLE
how can I set message expiration

### ISSUE THREAD

**Issue by bosdla** [AsamK/signal-cli#585]
Thanks for this great peace of software.
Can anybody advise how to setup an expiration time for messages in a group?
Or is it just not implemented yet.

thanks,
bosdla

**Comment by AsamK** [comment]
That's not implemented yet, but if another member in the group sets the expiration time signal-cli will also use that.

**Comment by piramiday** [comment]
I have been successful so far in directly modifying the Signal config file to set expiration messages for groups.
you can try to overwrite the `messageExpirationTime` value to whatever you want, e.g. `604800` for a week.

**Comment by AsamK** [comment]
Now implemented in 7170a68571f2d612f908e5293c15850ba726f35d
