### ISSUE TITLE
`register --voice --captcha` always get a Bad response 400

### ISSUE THREAD

**Issue by etlweather** [AsamK/signal-cli#587]
I tried to register a number with this tool and I always get:

```
Request verify error: Bad response: 400
```

Version is 0.8.1.

I tried with --verbose but no additional data show up.

Would like to provide more data but I don't know where to look.

**Comment by etlweather** [comment]
I don't have this verified yet, but I think I figured it out. You have to do `register` without captcha, then you're asked to do a captcha so you get one and `register` again with the captcha... I unfortunately forgot to put `--voice` on this last try so I can't confirm yet

**Comment by Encke** [comment]
I was able to register with --voice

You have to remember to Open Captcha Website on ANY DEVICE and verify visually (https://signalcaptchas.org/registration/generate.html).

I found phones work best for this process and had issues on desktop browsers.

encke

**Comment by etlweather** [comment]
Thanks.

What I found is that it seems you must do first a `register` without captcha. Then register again with `--captcha`. That worked when I do it this way.

**Comment by KithorasCarzyl** [comment]
@etlweather @Encke 

So first you entered

`
./signal-cli -u NUMBER register --voice
`

then

`
./signal-cli -u NUMBER register --voice --captcha CAPTCHA
`

This didn't work for me

**Comment by AsamK** [comment]
See https://github.com/AsamK/signal-cli/discussions/628#discussioncomment-765501
Maybe you're LANG env variable needs to be changed.
