### ISSUE TITLE
Parallel message sending

### ISSUE THREAD

**Issue by maxcountryman** [AsamK/signal-cli#588]
It seems that sending holds a file lock which means that sending in parallel is not really possible. A potential workaround might be to clone the config. N-many configs might allow parallelism of N. However this is cumbersome. It would be nice if there were an alternative which works well in a containerized environment, like Docker.

**Comment by exquo** [comment]
If I understand correctly, this is a sub-issue of #583: make signal-cli daemon run in Docker.

**Comment by AsamK** [comment]
yes, currently the only way to send/receive in parallel is by using the dbus daemon
