### ISSUE TITLE
Unable to link to signal client dll on windows

### ISSUE THREAD

**Issue by Baccanno** [AsamK/signal-cli#590]
Hi,
I tried replacing the .so file with the .dll file in the jar with the exact same name (.dll instead of .so that is), tried override java library path with external dll, tried to put dll in path, but nothing does, it can't resolve de native library
```
2021-04-04T15:25:53.050+0200 [main] INFO LibSignal - [libsignal-client]: rust\bridge\jni\src\logging.rs:173: Initializing libsignal-client version:0.3.4
Missing required native library dependency: libsignal-client
```

Any suggestion here ?
Best

**Comment by Crypto-Bee** [comment]
The file must be namend signal_jni.dll. The dll AND the so must not to be in the jar. See this comment and the following:
https://github.com/AsamK/signal-cli/issues/517#issuecomment-779326698

**Comment by Baccanno** [comment]
> You have to use the version 0.2.3 and not 0.3.4.

I'll look into this, it might be what I'm missing

**Comment by Baccanno** [comment]
Added the 0.2.3 compiled "signal_jni.dll" into "signal-client-java-0.2.3.jar", but having the same issue. I'll dig a bit more into the link you provided

**Comment by Baccanno** [comment]
> The dll AND the so must not to be in the jar

I misunderstood, I thought you said there should be only one of them is the Jar !
I additionally done this : https://github.com/AsamK/signal-cli/issues/517#issuecomment-779326698

it seems to work :)

```
bin/signal-cli register
No local users found, you first need to register or link an account
```
