### ISSUE TITLE
Netherlands number: WARN LibSignal - [PhoneNumberFormatter]: Failed isPossibleNumber()

### ISSUE THREAD

**Issue by mfld-pub** [AsamK/signal-cli#596]
I have a Dutch number +31970102XXXXX that I am unable to use - it seems to think the number doesn't pass input validation or something ?!

```
signal-cli --verbose -u +31970102XXXXX register
2021-04-07T08:07:18.590Z [main] **WARN LibSignal - [PhoneNumberFormatter]: Failed isPossibleNumber()**
Invalid username (phone number), make sure you include the country code.
```
+31 097 number CAN have 11 digits.

I can call and text the number from Skype and traditional cellphones so the number is valid. Is this a signal-cli issue or the underlying protocol ?

**Comment by AsamK** [comment]
This is a general issue with libphonenumber, which libsignal-service-java uses for phone number validation.
Signal-Android is also affected by this: https://github.com/signalapp/Signal-Android/issues/9005
