### ISSUE TITLE
Extraneous characters in contacts names

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#599]
Several users have reported in https://github.com/isamert/scli/issues/115 that since recently some names in `contactStore` in signal-cli data file (`~/.local/share/signal-cli/data/+PHONENUM`) contain non-printable UTF characters at the start and end of names:

	<U+2068>John Doe<U+2069>

Have there been any changes in signal-cli that could have caused this? It could also be some change on the signal servers side.

**Comment by exquo** [comment]
P.S. For a quick diagnostic, [here](https://gist.github.com/exquo/16554acef775e5c41e66b5ee1e695b24) is a short script that lists all the contact names in `contactStore` with non printable characters.

**Comment by AsamK** [comment]
Nothing has changed on signal-cli side, so it's probably a change in Signal-Android or iOS. In the android app they have recently made changes to how they get the contact names from the device address book, it might be related to that.
signal-cli just takes the `String` it gets from the contact sync message and stores it.

Looks like those are chars for text directions:
https://www.w3.org/International/questions/qa-bidi-unicode-controls.en#basedirection

**Comment by exquo** [comment]
Thank you very much for the info! This must indeed be a change on signal mobile clients. Closing as not-a-bug.
