### ISSUE TITLE
Local `updateContact` changes reverted after syncing with master device

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#600]
After renaming a contact using the `updateContact` command, the changes persist until receiving a `CONTACTS_SYNC` messages from the master device. Then the contacts' names revert back to names on the master. Is there a way to make the local renames persist through syncs with the master? If not, maybe this short warning could be added to `updateContact`'s documentation: "local changes get overwritten during periodic syncs with the master device".

**Comment by AsamK** [comment]
In the Signal apps the master device is exclusively responsible for the contact list, so I'd like to keep in line with that.
Mentioning it in the documentation is a good idea, maybe it would also make sense to forbid the `updateContact` command for linked accounts...
