### ISSUE TITLE
add support for sending typing indicators

### ISSUE THREAD

**Issue by piramiday** [AsamK/signal-cli#602]
it would be useful to be able to **send typing indicators from the bot**.

in such a way, a command sent to the bot via a Signal message could be showing in a natural way if it is still executing, e.g.:
- user sends command to bot,
- bot receives command,
- bot sends START typing,
- bot crunches whatever it has to,
- bot sends command output,
- bot sends STOP typing.

would that be difficult to implement?
if I was a Java guy, I would try it myself.

thanks to everybody for helping out! :smiley:

**Comment by AsamK** [comment]
Shouldn't be hard to implement
Just a question how the command should look like, maybe `sendTypingIndicator [--stop]` ...
Also the START indicator needs to be resent periodically by the bot, as there's a time out in the apps that hide the typing indicators automatically after some seconds.

**Comment by piramiday** [comment]
oh, I did not know about having to periodically send the START indicator -- how long does it take for a single ping to expire?
in any case, whether it's 10 seconds or 3 minutes, I think that is something for the developer to do in the workflow.

sure, `sendTypingIndicator` works! I think it would be useful in leveraging Signal's features for a more intuitive approach.

(I am currently making my bot react to the user's command with different emojis based on whether the command is executing, or has failed or succeeded.)

**Comment by AsamK** [comment]
On the receiver side, Signal-Android hides the typing indicator after a 15 seconds timeout.
On the sender side it resends the indicator every 10 seconds, if the user is still typing.
