### ISSUE TITLE
suggestion: add Feature Matrix

### ISSUE THREAD

**Issue by piramiday** [AsamK/signal-cli#603]
I think it would be REALLY useful if this project had a summary of features in each case, a "feature matrix" if you will.
at present, as far as I know, the capabilities of:
1. the normal `signal-cli` command, classic output,
2. the normal `signal-cli` command, json output,
3. the `dbus signal-cli` feature,

are different and somewhat confusing.
note: I am not familiar with the dbus command, but I guess there might be some difference in the plain vs. json output formats there, as well.

a **feature matrix** explains clearly the various supported features, e.g. (random example, not necessarily factual!):

v feature \ command > | plain signal-cli | json signal-cli | dbus signal-cli
-|-|-|-
read typing indicators | ✅ | ✅ | ❌
send typing indicators | ❌ | ❌ | ❌
send replies | ❌ | ❌ | ❌
send reactions | ✅ | ✅ | ❌

and so on.
one could also add some Github issue links to missing features so that a user could readily go and subscribe to the relevant threads to stay updated on the feature's development!

such feature matrix would deserve to be in plain sight in the main readme, or in the first page of the wiki!
hope this might come as a welcome suggestion. cheers!

**Comment by exquo** [comment]
This would be really useful! A separate page on the wiki is probably the best place for it, so as not to have to create a pull request for every edit.

Note that there are differences between signal-cli's _output_ formats:
- plain-text: `signal-cli receive` / `signal-cli daemon`
- JSON: add `--output=json`
- dbus: output from e.g. `dbus-monitor` while signal-cli daemon is running

and _input_ commands:
- 'standalone': `signal-cli send`
- to daemon using `--dbus` flag: `signal-cli --dbus send`
- to daemon using dbus tools: `dbus-send ... org.asamk.Signal.sendMessage`

For the "command" features (e.g. "send typing notifications"), it's not meaningful to have a JSON field, as there is no JSON "input". Instead a "built-in" vs "external" dbus interface comparison might be useful, as there might be discrepancies between the two (however rare). We can have two tables, for 'receive' and 'send' features. Still, there are features that won't fit into either (e.g. downloading contacts' avatars) or would be relevant to both (e.g. supporting new style groups). In the latter case, rows could be added to both tables; in the former, we can add a third 'table'. 

Alternatively, we can maintain a check-box list like this: https://github.com/tulir/mautrix-signal/blob/master/ROADMAP.md. I do like me a good table though :). Other columns / fields that would be useful: links to relevant issues, like you've mentioned; maybe 'notes', although those might be less intrusive as foot-notes.

**Comment by piramiday** [comment]
> This would be really useful! A separate page on the wiki is probably the best place for it, so as not to have to create a pull request for every edit.

I'd say the opposite, that is, this should not be a community-edited wiki, but it should be part of each pull request implementing the feature.
just like the man page, it should be inside the repo and be kept as updated as possible!

> Note that there are differences between signal-cli's _output_ formats:
> [...]
> and _input_ commands:
> [...]
> For the "command" features (e.g. "send typing notifications"), it's not meaningful to have a JSON field, as there is no JSON "input". Instead a "built-in" vs "external" dbus interface comparison might be useful, as there might be discrepancies between the two (however rare).

of course. good point.

> We can have two tables, for 'receive' and 'send' features. Still, there are features that won't fit into either (e.g. downloading contacts' avatars) or would be relevant to both (e.g. supporting new style groups). In the latter case, rows could be added to both tables; in the former, we can add a third 'table'.

sure, that would work. some command-agnostic and output-agnostic table for general features, and a more refined output comparison table.

> Alternatively, we can maintain a check-box list like this: https://github.com/tulir/mautrix-signal/blob/master/ROADMAP.md. I do like me a good table though :). Other columns / fields that would be useful: links to relevant issues, like you've mentioned; maybe 'notes', although those might be less intrusive as foot-notes.

thanks for pitching in, but I do think that long checklist fails in being clear and concise. matrix ftw!

:D

**Comment by exquo** [comment]
> this should not be a community-edited wiki, but it should be part of each pull request implementing the feature.
> just like the man page, it should be inside the repo and be kept as updated as possible!

In an ideal world - definitely! (Well, in an ideal world there would be no un-implemented features :) Official source is great, _assuming_ it's perfectly maintained. In practice it will often be out of step with the code. For instance:
- When closing an issue, the commiter would have to check the 'features list' file, and modify it accordingly.  
	Pull requests are easier: a reminder can be added to github's PR template. For straight-to-trunk commits by AsamK, he'd have to remember each time, which won't always work (assuming he signs up for it in the first place). So we'll end up with regular additional pull requests to slightly edit the 'features list' file.
- Requesting a new feature would now entail opening a new issue _and_ a new pull request to add it to the 'features list' document. 

Would be great if a github [action](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues) triggered by closing an issue could edit the list appropriately. No idea if this can be made to work with a wiki page.

> long checklist fails in being clear and concise. matrix ftw!

Yes, that's often the case. Whatever the info layout, it would need to be readable. (Colored checkmarks help! :) 

Feature matrix makes sense when there is a set of 'tools', each of which might posses some subset of 'features' (2d-product). Here, JSON vs dbus vs plain-text are not so much tools, rather than different interfaces that should all have the same set of features (in an ideal world, again), and for the most part they actually do. In such table there will be many rows with all three columns check-marked or all three crossed. It might be simpler to just add a (foot)note when there is a difference. Still, a table might be sensible, with columns for e.g. issues links, notes, etc.

Whether a list or a table, it can be broken up into logical sections with appropriate headings to help with clarity. [Here](https://community.signalusers.org/t/wiki-in-depth-feature-comparison-between-private-messaging-apps/12238) is a table comparing various messengers' features, split up in sections (although the headings could be more prominent).

**Comment by piramiday** [comment]
I still think the feature matrix should stay in the repo, not the wiki, but of course it will be AsamK's call.
regarding automation, sure, that would be cool, but it might not be worth the effort to code it down, so I'd say it's best to manually update the table, even if that produces a couple of straightforward PRs which can be reviewed in a second.

regarding the feature matrix, the point is that signal-cli in its user non-dbus mode has quite a few differences between plain and json output (think about attachment filenames, or mentions, etc).
a user approaching the project for the first time should be able to take a quick glance at the table and understand whether it's better to code a bot around the plain output, or around the python one.
ideally, they should be equivalent, being equal to the dbus mode as well, but the project is not quite there.
since lots of people post issues about this or that (another example? setting expiration times in groups), a feature matrix in plain sight would help newcomers and avoid multiple issue posting.

on the other hand, I think there should also be an exhaustive "dictionary" of all possible outputs and formats of all possible messages.
e.g.: how does a read receipt look like in plain output? how does it look like in json? etc.
but that is yet another story.

anyway, I've made my point, and you've made several interesting arguments, but now I'll wait and see if AsamK agrees. :smile:

**Comment by AsamK** [comment]
I think it's a good idea, especially for new users.
I'd like to keep the README rather short, so a new wiki page would be a good starting point.
When the table is complete, we can reconsider if it makes sense to move it to a separate file in the repo or just add a wiki link to the README and CONTRIBUTING files.

**Comment by patcon** [comment]
Started a feature matrix wiki page here :)
https://github.com/AsamK/signal-cli/wiki/Feature-Matrix

**Comment by lkwg82** [comment]
so this could be closed, r8?

**Comment by piramiday** [comment]
as of now, no further revisions have been made to the Feature Matrix on the wiki, so I believe this issue keeps being actual.
(unfortunately at present I am unable to contribute, plus I have never used the JSON nor the DBUS "modes"...)
furthermore, the Feature Matrix is quite tricky to find, as I said -- I still think it should go in the repo and the main README.

of course, if AsamK deems this issue should be closed then I will lay it to rest! :smile:

**Comment by johnfreed** [comment]
I have expanded what @patcon started, further refinements/corrections welcome

**Comment by piramiday** [comment]
@johnfreed no words, just wow. :rocket:
