### ISSUE TITLE
Install signal-cli @Windows Server 2019

### ISSUE THREAD

**Issue by lebon1089** [AsamK/signal-cli#605]
I cannot install the current signal-cli on Windows Server 2019. 

D:\temp\signal\bin>**signal-cli -u +491703288726 register**
**_WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
ERROR App - Missing required native library dependency: libsignal-client_**

What am I doing wrong?

I don't get any further with the documentation for the two new DLLs used.

My Java used: 

D:\KISTERS\BelVis\JRE\bin>**java --version**
**_openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)_**

**Comment by AsamK** [comment]
https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal
I can't provide more information for windows...

**Comment by Crypto-Bee** [comment]
@lebon1089
I don´t know if Windows Server and Windows Client behave equal. But perhabs this comment and the following comments keeps helping you:

https://github.com/AsamK/signal-cli/issues/517#issuecomment-779326698

There you find the required signal_jni.dll and zkgroup.dll and how to use it.

**Comment by lebon1089** [comment]
Hi Crypto-Bee

Saw the # 517. I've tried everything so far, but it doesn't work in my area. I'm running an older version on another 2019 server without Group v2. It works.
