### ISSUE TITLE
Running the App with java application

### ISSUE THREAD

**Issue by hanunggulmp** [AsamK/signal-cli#611]
I can run the application successfully from the terminal command. but can the application run inside java program by using IDE?
for example there are main class which call registration() function to verify phone number and sendMessage() function to send the message. so, I only input the parameter like captcha, phone number, message, etc.

any idea? or did I miss something? thx

**Comment by AsamK** [comment]
I'm not exactly sure what you want to do.
You can run signal-cli inside an IDE by running the main class `org.asamk.signal.Main` and specifying the program arguments, e.g. in the run configuration dialog in IntelliJ.

**Comment by hanunggulmp** [comment]
> I'm not exactly sure what you want to do.
> You can run signal-cli inside an IDE by running the main class `org.asamk.signal.Main` and specifying the program arguments, e.g. in the run configuration dialog in IntelliJ.

this maybe a stupid question. but is there any documentation to use it in Main class? like how input/call the command.
e.g. I want register my phone and what I have to change/add on this case
```
public static void main(String[] args) {
        installSecurityProviderWorkaround();

        // Configuring the logger needs to happen before any logger is initialized
        configureLogging(isVerbose(args));

        var parser = App.buildArgumentParser();

        var ns = parser.parseArgsOrFail(args);

        int status = 0;
        try {
            new App(ns).init();
        } catch (CommandException e) {
            System.err.println(e.getMessage());
            status = getStatusForError(e);
        }
        System.exit(status);
    }
```

**Comment by AsamK** [comment]
args contains the arguments separately, so ["-u", "MY_PHONE_NUMBER", "register"]
