### ISSUE TITLE
Request verify error: Bad response: 400

### ISSUE THREAD

**Issue by usrstephan** [AsamK/signal-cli#623]
I have a problem with registering:
I previously used this number on another vm (which is deleted now) and secured it with a pin.
After 10 days of waiting (to get the pin resolved) I always get a bad response (even with the use of captchas):
Request verify error: Bad response: 400
Can anyone help me?

**Comment by AsamK** [comment]
Not sure what's going on there. Does running the verify command with `--verbose` output more information?

**Comment by usrstephan** [comment]
Thanks for your reply - I think it was some sort of firewall /rights management problem. With a new ct it works flawlessly
