### ISSUE TITLE
Cannot run from Windows even after installing dependencies

### ISSUE THREAD

**Issue by PeacefulPotato** [AsamK/signal-cli#624]
I somehow managed to build from scratch the signal_jni.dll file and copy it to the root of the signal-client-java-0.2.3.jar folder, while removing the .so file that was there. I then took the libzkgroup.dll file and copied it to the root of zkgroup-java-0.7.0.jar, while removing the .so file that was there. I then ran signal-cli, and still got the following errors:
WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
Missing required native library dependency: libsignal-client
This was on Windows 10 version 20H2.
Pictures of the jar files are shown below.
![signalclient](https://user-images.githubusercontent.com/57071692/118533255-d921cf80-b715-11eb-9a2c-df506c02dd18.png)
![zkgroup](https://user-images.githubusercontent.com/57071692/118533279-e0e17400-b715-11eb-9933-85f1a2745a32.JPG)

**Comment by Crypto-Bee** [comment]
See this comment and the following 2 comments:
https://github.com/AsamK/signal-cli/issues/517#issuecomment-779326698
