### ISSUE TITLE
Register with Captcha gives no verification code

### ISSUE THREAD

**Issue by joo4mart** [AsamK/signal-cli#629]
I have started the command as said in https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha and the registration with captcha seems to be fine (no error):

> signal-cli -u MYNUMBER register --captcha "MYCAPTCHA"

But I don't get any verification code, no call. How can I verify my phone number without verification code?

**Comment by itsmichaelk** [comment]
So you used it like this for voice!?
`signal-cli -u +XXXXXXXXXX register --voice --captcha "MYCAPTCHA"`

Otherwise.. did you tried to use `--verbose` after signal-cli to get more output?

**Comment by joo4mart** [comment]
Thank you for the hint: I haven't known that '--voice' is needed, too. Really I have tried four hours without success!

It would be nice, if this hint would be inside the README or manpage as example.

**Comment by itsmichaelk** [comment]
I'm happy that I was able to help you! :) 
It's actually referenced in the Repo's wiki, but more as a side note ([click me](https://github.com/AsamK/signal-cli/wiki/Quickstart#set-up-an-account))

**Comment by joo4mart** [comment]
Thank you for the link. But it was not obvious for me that I need '`--voice --chapta`' together for a call.
