### ISSUE TITLE
PHP Wrapper for Signal-cli

### ISSUE THREAD

**Issue by merlinthemagic** [AsamK/signal-cli#631]
Hi,

This is a great project, thank you for building it. 

[I built a wrapper for PHP](https://github.com/merlinthemagic/MTM-Signal), in case anyone needs it (Linux only for now). 

The basic functionality is there: register, verify, send, receive. But there is not full parity yet.

**Comment by AsamK** [comment]
Hi, feel free to add it to the list in the wiki:
https://github.com/AsamK/signal-cli/wiki
