### ISSUE TITLE
receive json vs plain-text

### ISSUE THREAD

**Issue by dwblmo** [AsamK/signal-cli#633]
The receiving output plain-text shows some more information than the json output
**plain-text:**
```
Envelope from: unknown source
Timestamp: 1622305335006 (2021-05-29T16:22:15.006Z)
Sent by unidentified/sealed sender
Sender: “FirstName LastName” +49xxxxxxxxx (device: 2)
Server timestamps: received: 1622305333913 (2021-05-29T16:22:13.913Z) delivered: 1622305342526 (2021-05-29T16:22:22.526Z)
Message timestamp: 1622305335006 (2021-05-29T16:22:15.006Z)
Body: Feldversuch
Profile key update, key length: 32
```

**json:**
`{"envelope":{"source":"+49xxxxxxxx","sourceDevice":2,"timestamp":1622305455535,"dataMessage":{"timestamp":1622305455535,"message":"Feldversuch","expiresInSeconds":0,"viewOnce":false,"mentions":[],"attachments":[],"contacts":[]}}}`

I wonder if it is possible to add the sender name into the json output as well.

**Comment by AsamK** [comment]
Implemented in #663
