### ISSUE TITLE
DBUS receive with multiple accounts - how to differentiate ingress messages?

### ISSUE THREAD

**Issue by merlinthemagic** [AsamK/signal-cli#635]
Hi,

When multiple accounts are registered i can either start the dbus service with a user specified or not. When a user is specified only messages for that user are received, if not then all messages are broadcast to all receivers. 

Is it possible to use the daemon with multiple users and know who was the intended recipient for each message?

Example:
```
## signal-cli.service
ExecStart=/path/to/bin/signal-cli  --config /var/lib/signal-configs daemon --system

## all receivers get all messages
/path/to/bin/signal-cli --dbus-system --config "/var/lib/signal-configs/" -o json -u '+12134567890' receive
/path/to/bin/signal-cli --dbus-system --config "/var/lib/signal-configs/" -o json -u '+13102345678' receive
```

**Comment by AsamK** [comment]
Yes, that's possible. The receiver needs to filter for a specific object.
I just fixed the signal-cli dbus client to only subscribe to signal for a single user.

**Comment by merlinthemagic** [comment]
Compiled fresh, works as expected now. Thank you.
