### ISSUE TITLE
Exception: org.whispersystems.libsignal.DuplicateMessageException

### ISSUE THREAD

**Issue by ionwerz** [AsamK/signal-cli#636]
Some strange exception I'm getting sometimes:
`Exception: org.whispersystems.libsignal.DuplicateMessageException: message with old counter 2 / 1 (ProtocolDuplicateMessageException)
Failed to decrypt message.`, after that incoming messages do not receive, need to restart the process.

**Comment by piramiday** [comment]
I've noticed the same error messages reappear, too, after having solved the old issues with #361.

**Comment by AsamK** [comment]
I've seen this as well, but for me receiving still works afterwards. When I saw it the sender had actually sent the message twice, possibly because he has bad internet connection ...
When you see it again please check if another message with the same timestamp has already been received.

**Comment by MR-Bagga** [comment]
I'm getting this in signal app and using signal 6.12.0 version and libsignal client version 0.22 anyone knows in which they solve duplicate message exception error
