### ISSUE TITLE
updateGroup missing admin option which is defined in manpage

### ISSUE THREAD

**Issue by i0x71** [AsamK/signal-cli#637]
Hi
It looks like updateGroup is not recognizing some of the options show in this doc
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli.1.adoc

For example --admin
signal-cli: error: unrecognized arguments: '--admin'

Running version 0.8.3

**Comment by AsamK** [comment]
These options will be released in the next version

**Comment by i0x71** [comment]
Thanks, What about -r --remove-member ?
