### ISSUE TITLE
deleting old groups

### ISSUE THREAD

**Issue by i0x71** [AsamK/signal-cli#638]
Hi
Its there a way to delete old group ?
After running quitGroup, they still show up when listGroups command is ran.

Example
Id: xxxxxxxxxxxxx Name:   Active: false Blocked: false Members: [] Pending members: [] Requesting members: [] Link: -

Running version 0.8.3

Thanks

**Comment by AsamK** [comment]
Not implemented yet
Could probably be added as a parameter to quitGroup, to quit and delete a group.
Maybe `quitGroup -g GROUP_ID --delete`
