### ISSUE TITLE
uploading a file hangs

### ISSUE THREAD

**Issue by anarcat** [AsamK/signal-cli#64]
using the latest release (0.5.5), sending a file to a contact fails:

```
[1079]anarcat@curie:signal-cli-0.5.5130$ ./bin/signal-cli -u +191392928 send +1938928992 -a ~/snaps/snap.png
```

it just hangs there (2 minutes and counting). the file is not large (200KB) and should upload in a few seconds...

not sure how to diagnose this further...?

**Comment by AsamK** [comment]
Every message needs a message text. Add `-m ""` to the command to set an empty text.
If the parameter is not given, signal-cli  expects the text on stdin and waits indefinitely for it.

**Comment by anarcat** [comment]
couldn't this be changed to not require a text if there's an attachment?

**Comment by AsamK** [comment]
It could, but it could break existing clients, that expect signal-cli to always use stdin, if -m is not given. A bigger warning in the readme might make sense.

**Comment by anarcat** [comment]
right, okay...
