### ISSUE TITLE
RE: Sending with Bash script

### ISSUE THREAD

**Issue by jjhiza** [AsamK/signal-cli#640]
Thank you for this amazing tool! I really appreciate all the hard work that has gone into creating it. I'm running into a unique issue that I haven't seen addressed in the issues tracker, nor can I find a solution on various forums. 

I'm writing a Bash script that uses 'read' to prompt users to input the recipient's number as well as their desired message. The script looks like this:

```
#!/bin/bash

read -p "Recipient: " recipient
read -p "Message: " message

directory="cd /usr/local/bin"
sendString="./signal-cli -u +1xxxxxxxxxx send -m "

messageString=$message
whitespace=" " 
fullSend=$sendString$messageString$whitespace$recipient

$directory
$fullSend
```

Everything works as expected until I try to pass in a message string that contains multiple words, and I can't figure out why. I've tried to format the message string in multiple ways, but nothing works. A single word message sends perfectly fine, but I cannot - for the life of me - get Bash to pass off whitespace-respecting strings to the signal-cli client successfully. Is this Bash-related, or is there something I can tweak in the source code in order to get this to work? Thanks again for all the hard work!

```
java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.00.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.00.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

```

**Comment by dwblmo** [comment]
Multiple word message should be send with quotations marks, either single or double

`./signal-cl -u +1xxxxxxxxxxx send -m "my message to you" +1xxxxxxxxxxxx`

so your code needs another variable

```
whitespace=" " 
quotation="'"
fullSend=$sendString$quotation$messageString$quotation$whitespace$recipient
```
