### ISSUE TITLE
Release as maven library

### ISSUE THREAD

**Issue by micw** [AsamK/signal-cli#641]
Hello,
I try to write a matterbridge api client to bridge to signal. I found a lot of code that is required to actually use signal-service-java in this project. Would you mind to release the project (especially the lib/* part) as maven library, so that it can be used a lib in other projects?
Thank you in advance!
Michael.

**Comment by AsamK** [comment]
The library is not yet in a good shape to be released. I might release it as a separate maven library eventually.
