### ISSUE TITLE
signal-cli 0.8.4.1 build issue

### ISSUE THREAD

**Issue by chenrui333** [AsamK/signal-cli#649]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure</summary>

```
==> zip -d /usr/local/Cellar/signal-cli/0.8.4.1/libexec/lib/signal-client-v0.8.1.jar libsignal_jni.so
	zip warning: /usr/local/Cellar/signal-cli/0.8.4.1/libexec/lib/signal-client-v0.8.1.jar not found or empty
	zip warning: name not matched: libsignal_jni.so
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/2871398237
relates to Homebrew/homebrew-core#79849

---

Btw last release and this release, we did notice that the `libsignal-client` version scheme got changed.

**Comment by AsamK** [comment]
That's a homebrew issue, you need to adapt the filename.

**Comment by carlocab** [comment]
Indeed, this is a problem with our formula. Apologies for the noise on your issue tracker!
