### ISSUE TITLE
Sign release binaries

### ISSUE THREAD

**Issue by thefinn93** [AsamK/signal-cli#65]
I'm working on a tool that will allow signal-cli to be used with weechat and it would be nice if it could automatically download and update signal-cli, but the releases aren't signed and I don't feel comfortable automatically downloading and running completely unsigned code. Would you be willing to eg GPG sign the release binaries?

**Comment by stevemcquaid** [comment]
@thefinn93 I am very interested in this - was going to start building myself. Do you have keybase or Signal?

**Comment by thefinn93** [comment]
I have both. My keybase is the same as my Github, @thefinn93. Email me (finn@finn.io) for my signal number. I don't have one that I'm ready to use for public communication yet.

**Comment by AsamK** [comment]
FA10826A74907F9EC6BBB7FC2BA2CD21B5B09570

**Comment by thefinn93** [comment]
I am unable to find that key on any keyserver or anything... where should I look?

**Comment by AsamK** [comment]
https://pgp.mit.edu/pks/lookup?op=vindex&search=0x2BA2CD21B5B09570

**Comment by thefinn93** [comment]
Ah, must not have propagated much yet. Thanks.
