### ISSUE TITLE
Missing required native library dependency: libsignal-client

### ISSUE THREAD

**Issue by derchrisuk** [AsamK/signal-cli#651]
Hi,

if I'm correct, and looking at the content of the release files and the JAR files in the archive, the releases from here should work out of the box.
I was using 0.8.1 before, and tried running 0.8.4.1
The app itself seems to run, but when I try to run with one of the commands, like send I get this error:

Missing required native library dependency: libsignal-client

As mentioned I checked the signal-client-java-0.8.1.jar file, and it has the libsignal_jni.so file included

The error is not happening with the previous 0.8.1 version.
This is on Debian 10.10 btw

**Comment by dwblmo** [comment]
maybe same problem as in #643

**Comment by derchrisuk** [comment]
Yes, with self build signal-client lib it is working
I guess this can be closed then, and continue in the other case.
