### ISSUE TITLE
Missing JNI dependency: libsignal-client (macos/m1)

### ISSUE THREAD

**Issue by kelas** [AsamK/signal-cli#660]
Hey @AsamK,

Great work, keep it up.

I've seen that some folks recently reported `Native code library failed to load` with self-built native libraries on Linux (#657 #655 #643).

FYI, I've stumbled into the same error on macOS/arm64. What really helped was adding a full exception dump to `ServiceConfig.isSignalClientAvailable()`. Currently, you're quietly re-throwing `UnsatisfiedLinkError` as `UserErrorException`, which suppresses useful clues from underlying `dlopen()`.

In my case, the problem was Oracle JDK:

```
$ java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

$ signal-cli ...
java.lang.UnsatisfiedLinkError: dlopen(libsignal_jni.dylib, 0x0001): mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')
```

If it helps anyone, switching to the latest OpenJDK from homebrew seems to work out of the box on M1. 

Cheers,
k.

**Comment by taich001** [comment]
I have Ubuntu 18.04 with all updates and still get this error.

```
java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

```
ubuntu:~ # signal-cli -u +43677xxxxxxx register
Missing required native library dependency: libsignal-client
```

**Comment by piechologist** [comment]
> Missing required native library dependency: libsignal-client

@taich001: check out [#643](https://github.com/AsamK/signal-cli/issues/643).

I'm currently running signal-cli v0.8.3 on Debian 10. This should be working on Ubuntu 18.04, too.

**Comment by taich001** [comment]
#643 did not change anything.

Still can't get it run.

**Comment by taich001** [comment]
I think signal-cli does not run with openjdk-11. In ubuntu 18.04 openjdk 11 is the highest avaliable version. That's why I get ths error.
I tried it with 20.04 and 21.04 where I can use openjdk 14 and 17 and there it works fine.

**Comment by kelas** [comment]
> @taich001I think signal-cli does not run with openjdk-11. In ubuntu 18.04 openjdk 11 is the highest avaliable version. That's why I am getting ths error.
> 
> `Missing required native library dependency: libsignal-client`

As explained above, you're getting a generic error thrown by signal-cli code, which masks away the actual underlying problem.
