### ISSUE TITLE
DBus interface inconsistent with normal interface

### ISSUE THREAD

**Issue by johnfreed** [AsamK/signal-cli#671]
First, I want to add my thanks to the many who have already given them.

I have rewritten pippcat's "signalbot" program, naming mine signalmail (https://github.com/johnfreed/signalmail), to use DBus and to focus exclusively on forwarding Signal messages via email. However, the onMessageReceived function does not provide the same functionality as the main signal-cli program.

Specifically, the attachments list now consists solely of a comma-separated list of filenames. In the main program, it consists of a dictionary with more information. I know that MessageReceived *could* provide the information, because I see the following on my terminal screen when DBus is working:

  Content-Type: image/jpeg
  Type: Pointer
  Id: G8g7mvT48JAL8CSUz_ir Key length: 64
  Upload timestamp: 1627417872372 (2021-07-27T20:31:12.372Z)
  Size: 147081 bytes
  Dimensions: 1104x1472

The Id I can deduce from the filename, and the file size I suppose I could get via stat (though I would obviously like to avoid that if possible). I cannot, however, deduce the Content-Type without resorting to magic number guesswork. This is unfortunate, because that information is provided by Signal.

You may feel free to add my program to your wiki as an example of using the DBus interface.

Thanks,

John

**Comment by exquo** [comment]
Cf. #316

**Comment by johnfreed** [comment]
I have taken this on and would like any feedback before proceeding further. (See [https://github.com/johnfreed/signal-cli](https://github.com/johnfreed/signal-cli))

I started with the notion of retaining as much information as possible from the Signal servers, which `signal-cli` could then pass along to any end-user program like `signalmail`. I created a new data type, `DbusAttachment`, to distinguish this from the list of file names passed into `signal-cli` from the command line (I changed that data to `List<String> attachmentNames`).

Along the way I realized that the `attachmentNames` would also presumably work with arbitrary URLs, so I added in that feature and it does indeed work. So syntax like `signal-cli -u +33123456789 -a "http://my-site.com/pic.png" -m "" +440123456789` works as expected.

Conceptually, in this proposal, `signal-cli` takes attachment information from the Signal servers, packages it into a dBusAttachment, and sends that to the DBus, where it can be retrieved by the end-user program. It is important that the attachment information is guaranteed to be in a particular order, which guarantee is provided by the `Struct` class in `org.freedesktop.dbus.annotations.Position`

On the way back, the end-user program can package its information in the same order and pass it to `signal-cli`, which can then pass it to the Signal servers after any appropriate processing.

I have already used this feature in the `signalmail` program to correctly receive the remote filename from Signal and send it along as an email attachment to an arbitrary recipient. (Signal strips the filename from image/* MIME types, but it retains it for other attachment types, such as PDF files.) `signalmail` tests what it receives from DBus to see if it's just a list of filenames or a list of complete DbusAttachments, and acts appropriately. On the way back, it has the ability to send an autoreply with an autoattachment. 

I'm an experienced programmer but not an experienced Java programmer, so I'm open to any other suggestions. In particular, I imagine that the `convertJsonAttachmentToDbus` method can be written as a single line of code with some sort of mapping function.

I can also submit this as a pull request if you think this might be useful. On the todo list, in particular, there is some more information (the `preview` for example) that the Signal server provides but that the `DbusAttachment` type does not use.

**Comment by johnfreed** [comment]
@AsamK I have not seen any feedback on this but in the meantime I have implemented two DBus methods (isRegistered and setExpirationTimer). This is an extension of an existing interface, and I see you are busy with a new interface (Json Rpc) so perhaps you don't have time to examine, but to simplify things I am trying to keep up with the latest master branch (which just changed a few hours ago). It appears that I can't create a pull request here, so I created one in my own repository [https://github.com/johnfreed/signal-cli/pull/1](https://github.com/johnfreed/signal-cli/pull/1)

track attachment data (#671 and #316)
create new DbusAttachment type
add sendNoteToSelfMessageWithDBusAttachments
add sendGroupMessageWithDBusAttachments
add sendMessageWithDBusAttachments

implement setExpirationTimer() for DBus
implement isRegistered() for DBus
allow URLs for --attachment option

**Comment by AsamK** [comment]
Additional attachment details are now included in the new message extras of the dbus signal: https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/DbusReceiveMessageHandler.java#L200
