### ISSUE TITLE
regain the keys

### ISSUE THREAD

**Issue by ofn1** [AsamK/signal-cli#672]
On a system where the server is the master device, when the system is reinstalled, only a file named with the registration number is backed up, and other data such as signed-pre-keys were lost.
Now all the contacts’ messages can’t be Decrypted. Apart from re-registering, is there any way to let signal-cli regain the keys of all contacts?

**Comment by AsamK** [comment]
If the data is not backed up, it cannot be restored.
Reregistering shouldn't be an issue, as the identity key is stored inside the main config file.
After registering, the prekeys will be recreated, though the individual sessions will have to be reset manually or reinitiated from the server side.
