### ISSUE TITLE
Example Bash scripts for interactive use

### ISSUE THREAD

**Issue by meribold** [AsamK/signal-cli#68]
I wrote two bash scripts to simplify interactive use of signal-cli: one creates desktop notifications for received messages and the other one is a wrapper for sending messages.

They are at: https://github.com/meribold/signal-cli.bash.

There's probably a lot wrong with them, but maybe someone finds them useful, wants to adapt them for themselves or can give me some feedback.

**Comment by AsamK** [comment]
I've added a link to the wiki: https://github.com/AsamK/signal-cli/wiki
