### ISSUE TITLE
Identity key issues when recipient changes device

### ISSUE THREAD

**Issue by matuskosut** [AsamK/signal-cli#686]
This might be related to change done in v0.8.2 - Only one identity key is stored per recipient and updated from profile (to match app behavior)

After we updated to v0.8.3 (from <=0.8.0) we noticed that when message recipient replaces phone (same number) new identity was not listed. listIdentities return only one old identity which had correct status TRUSTED_VERIFIED. Before it used to list more, including unverified one that we were able to check and set as trusted.

Attempts to send a message were failing with `Exit code 4`: Sending failed due to untrusted key

I had to manually delete identity data file based on the id: 
`signal-cli/data/${phone}.d/identities/${id}`

Then I created a contact, and tested listing identities. New identity successfully appeared and I was able to set it as trusted.

Is there a different approach how to handle such use case correctly? Or is this rather a bug?

**Comment by AsamK** [comment]
Sounds like a bug

**Comment by matuskosut** [comment]
thanks! 😊

**Comment by AsamK** [comment]
Thanks for reporting👍
