### ISSUE TITLE
Use under Ubuntu

### ISSUE THREAD

**Issue by mh-g** [AsamK/signal-cli#69]
Hello,

I am experienced with C++, but have only very basic Java knowledge. Thus, I was happy to be able to download a binary version of signal-cli. However, there seems only to be a source version of libsignal-service-java. When I execute its gradle script, I get "A problem occurred configuring project ':android'." How do I change the configuration to something that fits Ubuntu?

Sorry for being somewhat off-topic, but signal-cli without libsignal-service-java won't work, or will it?

Thanks,
mh-g

**Comment by AsamK** [comment]
All necessary libraries are included in the tar.gz file that you can download here:
https://github.com/AsamK/signal-cli/releases

You only need to extract it and run the bin/signal-cli script

**Comment by pimotte** [comment]
If at some point you would want to compile that particular library, install the Android SDK, or remove the : android target from the build file.

**Comment by mh-g** [comment]
Thanks a lot AsamK. After stumbling over the JRE Security issue -- which was solved as given in the README -- all works right now.

I did not expect that signal-cli contains everything itself, but expected it to use the library provided by Open Whisper Systems. I just wonder how you keep signal-cli compatible with the Signal API?

Great piece of software and fine manuals as well, it's easy to get everything up and running easily. Maybe you add a note that signal-cli is completely self-contained? The first sentence "signal-cli is a commandline interface for libsignal-service-java." misled me.

**Comment by AsamK** [comment]
signal-cli uses a fork of the official libsignal-service, that I keep up to date with upstream, for some additional features. The signal-cli source code doesn't contain this lib, only references it, but the binary release contains this lib and all other necessary libs.
