### ISSUE TITLE
Missing configs in data for dbus?

### ISSUE THREAD

**Issue by pseudocoder** [AsamK/signal-cli#697]
I have command line sending working, but trying to set up DBUS I don't have the mentioned config files in my ~/.local/share/signal-cli/data folder

Am I looking in the right place, is there something necessary to generate them?

**Comment by piechologist** [comment]
You'll find them in the data folder of the git repo: 

https://github.com/AsamK/signal-cli/tree/master/data

**Comment by pseudocoder** [comment]
Doh, why didn't I check there? Thx.
