### ISSUE TITLE
Failed to send message: [413] Rate limit exceeded: 413

### ISSUE THREAD

**Issue by pseudocoder** [AsamK/signal-cli#698]
I set up and registered as a new account and device on a new number, and the registration seems to be OK.

But when I try to send or receive from any number other than my own it fails with a 413 error. I haven't (afaik) sent more than a few messages ever from this machine.

I linked a desktop version to the account, and it works fine sending and receiving to other numbers.

I can send and receive from my own number (note-to-self), but any other gives the 413. Both my own number and the target are trusted on both sides.

As a test I also set everything up as a linked device on an existing number (in a different linux user) and it works fine, so it doesn't look like my installation is wrong.

At the moment I'm just using command line.

**Comment by rattzv** [comment]
I have the same problem. Signal-cli is launched on the home computer, but gives error 413 or 404. Why is this happening, is there any suggestion?
I cannot write to anyone but myself. Register new account does not solve the problem, the account immediately receives a ratelimit error

**Comment by AsamK** [comment]
Can you try if the behavior is different with the latest development version?
You can get it from the build artifacts here: https://github.com/AsamK/signal-cli/actions/runs/1170700387

**Comment by pseudocoder** [comment]
Unfortunately I haven't managed to get it working without the native library in the jar, or really understand the instructions for that in the wiki, so I can't get that build to work.

**Comment by pseudocoder** [comment]
I checked the content of signal-client-java-0.8.3.jar and saw it does have the native library in it.

But as it had an older native library than signal-client-java-0.8.1.jar I swapped the newer one into the jar and now it runs without native library error.

But it still gives [413] Rate limit exceeded: 413 on almost all operations.

**Comment by pseudocoder** [comment]
Actually now it works :-)

I think I needed to send it something from another number, now it seems to be fine.

The only thing I've found which gives 413 is verify, but even so it seems to do the verification.

**Comment by m3dus444** [comment]
Hi, just got the same problem. I was developping a bot everything worked fine, and suddenly i got this error.
My account is registered, my contact is TRUSTED_VERIFIED. If it can help, it  started happening to me just after removing a contact ( and its keys with --forget ) and sending him a message right after.
I've JRE 17.0.1 and libsignal-cli 0.10.2. Debian latest stable version.

Thanks!
