### ISSUE TITLE
Registration with signalcaptcha:// protocol installed

### ISSUE THREAD

**Issue by Florian7843** [AsamK/signal-cli#701]
Hey,

I just noticed that if you have the Signal desktop client installed, you do not see the failed redirect, and it's quite confusing.
There should be a hint in the helper message, maybe even a fix.

Kind regards
Florian

**Comment by bublath** [comment]
Are there any best practices how to easily get the Captcha string?
I'm providing a Perl based Interface for the home automation system FHEM and the best I could come up to far is to provide a documentation to users, where they can find the string e.g. in the Developer Tools in Chrome.

**Comment by Florian7843** [comment]
The signalcaptchas.org website is provided by the official Signal implementation? Then I am not sure if there is any possibility for you to properly integrate this.

I managed to find a workaround for this but, it's a bit hacky... 
Keep in mind that this workaround is for Windows, and I have no idea if Linux even supports URL protocols.

I managed to get around this problem by going into the Registry Editor using `regedit` and deleting the `Computer\HKEY_CLASSES_ROOT\signalcaptcha` folder. Another possibility would likely be to uninstall Signal Desktop completely...

It would probably be possible to create a .reg file which overrides the official implementation and just opens a text editor with the string or just plain copies into your clipboard.

I might actually look into it.

**Comment by bublath** [comment]
I actually do not use Signal Desktop at all here.
Your solution with the Windows registry hack sounds interesting. It is more straight forward than digging deep into the data from the Developer Tools.
While the actual software runs on Linux, it is used over a web interface and I believe many people will access it from a Windows box. So it would probably be helpful for a significant subset of users.
Maybe it would even be possible to embedd the captcha string into an URL and create a kind of call back to the FHEM webserver which might be able to feed the data into the tool automatically.

Appreciate your help here.

**Comment by Florian7843** [comment]
Ok, so I managed to create a .reg file which does override the default to either copy the captcha string into the clipboard or open GitHub.com (could of course be changed to any website).

The content of the .reg file would be:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\signalcaptcha]
@="URL:signalcaptcha"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\signalcaptcha\shell]

[HKEY_CLASSES_ROOT\signalcaptcha\shell\open]

[HKEY_CLASSES_ROOT\signalcaptcha\shell\open\command]
@="powershell.exe Set-Clipboard (\\\"\"%1\"\\\" -replace '^signalcaptcha:\\/\\/(.*)\\/$','$1')"
```
Or to open a website, replace the last line with:
```
@="powershell.exe Start-Process -FilePath www.github.com"
```
You could of course combine the first part with the 2nd to point the URL to your FHEM webserver and use the captcha string as a GET argument or whatever.

But so far I could not manage to make hide the PowerShell window.

I also didn't manage to find a way to backup the original signalcaptcha URL, because it's an installation specific endpoint.

**Comment by bublath** [comment]
Thx. Will try it out.
For calling the webserver I just hope the captcha token contains no chars that need to be escaped.

**Comment by bublath** [comment]
Works like a charm - after confirming the start of PowerShell, the window opens for a second and then the Webpage is called with the token using:

@="powershell.exe Start-Process -FilePath powershell.exe Start-Process -FilePath http://x.x.x.x:8083/fhem?cmd=set%%20SignalBot%%20captcha%%20%1"

With this I can even trigger to call registerWithCaptcha  (which unfortunately still has issues) in my module right away. 
Once this works, I just need to show a request to enter the PIN and the registration process becomes almost user friendly.

Now it would of course be interesting to know if something similar is possible with Linux as well.

**Comment by Florian7843** [comment]
While doing my Windows hack, I found out that there is a similar feature on Linux called URI schemes. But there doesn't seem to be a lot of "documentation" online...

**Comment by bublath** [comment]
On Linux it partially works like this (only with Firefox - Chromium seems to try to handle this internally and might require a different appraoch):
Create a file _~/.local/share/applications/signalcaptcha.desktop_ with the following content
`[Desktop Entry] `
`Name=Signalcaptcha`
`Exec=xdg-open http://x.x.x.x:8083/fhem?cmd=set%%20SignalBot%%20captcha%%20%u`
`Type=Application`
`Terminal=false`
`StartupNotify=false`
`MimeType=x-scheme-handler/signalcaptcha`

xdg-open helps to call a web page with the default browser, you can of course call any other program - %u gets replaced by the captcha string

To active this you need to execute this command from a shell (with the normal desktop user):
`xdg-mime default signalcaptcha.desktop x-scheme-handler/signalcaptcha`

**Comment by technillogue** [comment]
Similarly as bublath, I use https://github.com/forestcontact/message-in-a-bottle/blob/main/signal-captcha.desktop with `echo $@ | cut -c (echo "signalcaptcha://"|wc -c)- > /tmp/captcha` in /opt/save_signal_captcha. Thanks for the tip about `xdg-mime default`, I was just appending to /usr/share/applications/mimeinfo.cache.

It would be pretty cool if signal-cli could install itself to handle x-scheme-handler/signalcaptcha. Maybe a command where you specify the user/config location? Or a flag on the register command, and the verify command removes the handler to avoid conflict (though it's not like signal desktop does anything signalcaptcha://...)

**Comment by cuu508** [comment]
The following seems to work for copying the CAPTCHA solution into clipboard (from Chrome, on Ubuntu 22.04, running under Wayland, with `wl-clipboard` installed):

`~/.local/share/applications/signalcaptcha.desktop`:

```
[Desktop Entry]
Name=Signalcaptcha
Exec=wl-copy %u
Type=Application
Terminal=false
StartupNotify=false
MimeType=x-scheme-handler/signalcaptcha
```

`~/.local/share/applications/mimeapps.list`:

```
[Default Applications]
x-scheme-handler/signalcaptcha=signalcaptcha.desktop
```

And I then ran:

```
update-desktop-database ~/.local/share/applications
```

**Comment by Lukom** [comment]
By registering another handler for `signalcaptcha://` you break captcha logic for signal app itself.

There is another way to automate - just modify https://signalcaptchas.org/challenge/generate.html page and host it locally. Critical changes are going to be made here:

```html
...
<div id="container">
  <div id="captcha"></div>
</div>

<script>
  function onloadHcaptcha() {
    let action = "challenge" ;
    let siteKey = "..."; // get this value from https://signalcaptchas.org/assets/js/bundle.js script

    hcaptcha.render("captcha", {
      sitekey: siteKey,
      theme: "light",
      callback: (token) => {
        let captchaName = 'signal-hcaptcha';
        let captchaUrl = `signalcaptcha://${captchaName}.${siteKey}.${action}.${token}`;

        // ... pass captchaUrl to signal-cli, that's it
      },
    });
  }

  let scriptTag = document.createElement("script");
  scriptTag.async = true
  scriptTag.defer = true
  scriptTag.src = "https://js.hcaptcha.com/1/api.js?onload=onloadHcaptcha&render=explicit"
  document.body.appendChild(scriptTag);
</script>
</body>
</html>
```

This way human solves captcha on this custom page (could be in iframe), then captcha library calls `callback`, where captcha solution value is composed, which can be passed to `signal-cli` command.

**Comment by AsamK** [comment]
Actually there's no workaround necessary anymore, now a link with the token is shown after solving the captcha.
https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha#get-captcha-token
