### ISSUE TITLE
zkgroup fails to find libzkgroup.dylib

### ISSUE THREAD

**Issue by neomsg-git** [AsamK/signal-cli#709]
### Platform
M1 MacBook

### Steps to reproduce
As suggested, I removed libzkgroup.so from the jar file:
`zip -d zkgroup-java-0.7.0.jar libzkgroup.so`

Then I tried adding a pre-compiled libzkgroup.dylib library file:
`zip zkgroup-java-0.7.0.jar libzkgroup.dylib`

Now I tried registration and verification, but the native zkgroup library could not be found and it fails.

Then I thought if it does not want to find it inside the jar file, why not putting it inside java.library.path.
So I compiled this source code:
```
import java.util.Properties;
import java.util.Enumeration;

public class Main {
  public static void main(String args[]) {
    if( args.length == 0 ) {
      Properties p = System.getProperties();
      Enumeration keys = p.keys();
      while (keys.hasMoreElements()) {
        String key = (String)keys.nextElement();
        String value = (String)p.get(key);
        System.out.println(key + " : " + value);
      }
    }
    else {
      for (String key: args) {
        System.out.println(System.getProperty( key ));
      }
    }
  }
}
```
The result was the following:
`/Users/myusername/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.`
So I copied libzkgroup.dylib into one of those folders:
`cp libzkgroup.dylib Library/Java/Extensions/`
And of course I removed the zkgroup.dylib file from the jar file again:
`zip -d zkgroup-java-0.7.0.jar libzkgroup.dylib`
But it still cannot find libzkgroup.

**Comment by neomsg-git** [comment]
### Errors / warnings
Warning when attempting to register:
`WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup`
Error message when attempting to verify:
```
WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
WARN Manager - Failed to retrieve profile, ignoring: [404] Not found
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.signal.zkgroup.internal.Native
	at org.signal.zkgroup.profiles.ProfileKey.getProfileKeyVersion(ProfileKey.java:47)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.setVersionedProfile(SignalServiceAccountManager.java:791)
	at org.asamk.signal.manager.Manager.setProfile(Manager.java:421)
	at org.asamk.signal.manager.RegistrationManager.verifyAccount(RegistrationManager.java:183)
	at org.asamk.signal.commands.VerifyCommand.handleCommand(VerifyCommand.java:32)
	at org.asamk.signal.App.handleRegistrationCommand(App.java:201)
	at org.asamk.signal.App.init(App.java:166)
	at org.asamk.signal.Main.main(Main.java:51)
```

**Comment by AsamK** [comment]
Looks like it's probably the wrong dylib for you architecture ...
The verify should now also succeed if libzkgroup is missing and there should be a more detailed error message why libzkgroup is not found/accepted.
You can build the latest master or use the artifact from the build: https://github.com/AsamK/signal-cli/actions/runs/1214436012
