### ISSUE TITLE
Can't be added to 'Admin posts only' groups

### ISSUE THREAD

**Issue by derd3000** [AsamK/signal-cli#714]
Hey!
Signal-CLI users can not be added to groups which have the new group permission "Only posts by admins".
When adding the Signal-CLI users Signals says on iPhone:

"This user can't be added to the group until they upgrade Signal."

Using: 0.8.5 with libsignal-client 0.9.2

**Comment by AsamK** [comment]
This is already implemented in signal-cli and will be available in the next version.
