### ISSUE TITLE
Extend output for messages send via dbus

### ISSUE THREAD

**Issue by rkaminsk** [AsamK/signal-cli#715]
If a message is sand via dbus, the following json object appears in the log:

```json
{"envelope":{"source":null,"sourceName":null,"sourceDevice":null,"timestamp":1631450054454},"error":{"message":null}}
```

Would it be possible to add what was actually send to the object? I am writing because I am using `scli` and would like to restore the message history from the `signal-cli`'s logfile. This works nicely except for messages that were send via dbus.

**Comment by exquo** [comment]
Are you sending the messages through `scli` or manually through `signal-cli`'s dbus interface? If the latter, can you provide the actual command?

`scli` can save the message history with the `--save-history` flag.

**Comment by rkaminsk** [comment]
I am starting signal-cli with something like this:
```bash
nohup signal-cli -o json -u +123456 daemon 1>> daemon.stdout 2> daemon.stderr &
```
For scli I am then using a custom daemon command:
```bash
#!/bin/bash

tail -f -n +1 /home/kaminski/.local/share/signal-cli/daemon.stderr > /dev/stderr &
err=$!
tail -f -n +1 /home/kaminski/.local/share/signal-cli/daemon.stdout > /dev/stdout &
out=$!

trap "kill $out $err" EXIT

wait
```
Since signal-cli is my master I get a *nice backup/history* of my messages like this. Just what I send via scli is lost. I am not using scli's save-history flag because anything that it does not read from the log is lost.

In any case, it is not a big issue because right now I am simply not using scli to send messages but use the desktop client.

**Comment by exquo** [comment]
IIUC, the idea is to save all of signal-cli daemon's input and output in a history file. The output part is trivial, but the input less so.

By "the log" do you mean the resulting `daemon.stdout` file? 
This file will not contain the messages _sent_ with `signal-cli`. When you send a message through a _different_, linked client, like signal-desktop, signal-cli _receives_ those as sync messages and prints them on its stdout (which you successfully save in a file). But when you send a message with `signal-cli …` or `dbus-send …` command, signal-cli does not print anything to stdout (i.e. does not "echo" the sent message).
The envelope in your original comment comes, I suspect, from some unrelated event. 

To add the _sent_ messages to the history file along with the received ones, you need to manually append them to the history file on every send, perhaps making them look as the received sync'ed envelopes (depending on what you want to do with the history file later).

**Comment by rkaminsk** [comment]
> IIUC, the idea is to save all of signal-cli daemon's input and output in a history file. The output part is trivial, but the input less so.

Yes, and I find it makes the most sense on the master because linked clients loose the link after a month. (Which happens to me quite often because I travel a lot.)

> By "the log" do you mean the resulting `daemon.stdout` file?

Exactly.

> This file will not contain the messages _sent_ with `signal-cli`. When you send a message through a _different_, linked client, like signal-desktop, signal-cli _receives_ those as sync messages and prints them on its stdout (which you successfully save in a file). 

Yes, and right now I am using another linked client as you say.

> But when you send a message with `signal-cli …` or `dbus-send …` command, signal-cli does not print anything to stdout (i.e. does not "echo" the sent message). The envelope in your original comment comes, I suspect, from some unrelated event.
> To add the _sent_ messages to the history file along with the received ones, you need to manually append them to the history file on every send, perhaps making them look as the received sync'ed envelopes (depending on what you want to do with the history file later).

Yes, but therefore I would have to modify scli (and it would require some way to combine the output of the two different processes). In any case, I just had the idea that it might be nice to log this message. This is also not a  bug report. Maybe this would even create problems for clients like scli or others relying on the current behavior.

**Comment by exquo** [comment]
Yes, you can modify `scli` to do this, I think it would amount to just  adding a `write()` inside a `send_message()`. 
Alternatively, you can run `signal-cli` with a `--verbose` flag, and watch for the `sendMessage` log lines, formatting them as envelopes and appending to the history file. 
Writing to a single file from multiple processes [should be fine](https://unix.stackexchange.com/questions/346062/concurrent-writing-to-a-log-file-from-many-processes) as long as it's opened in an append mode (i.e. with `>>`).
But the easiest solution is probably what you are doing already: using a linked device / program to do all the sending, and record the sent message when they are received as sync's. I don't think it matters which one is master and which is linked: IIRC the messages are kept on signal servers for a month and sent to any account device when it connects to the server.

"Echo"-ing the sent messages to stdout would indeed create problems for existing signal-cli clients who do not expect it. I think the assumption is that signal-cli prints out on stdout only the messages it receives from the signal servers. I think all the logging signal-cli can be expected to do, it already does, on a 'debug' level, written to stderr.

**Comment by rkaminsk** [comment]
Alright, then I just close this. Thanks for your time!
