### ISSUE TITLE
NPE when used via DBus

### ISSUE THREAD

**Issue by mathisdt** [AsamK/signal-cli#717]
When used via DBus interface (started with arguments `daemon --system`), signal-cli suffers an exception when a message arrives:

```
Sep 12 21:38:17 debian systemd[1]: Starting Send secure messages to Signal clients...
Sep 12 21:38:50 debian signal-cli[34036]: INFO DaemonCommand - Exported dbus object: /org/asamk/Signal/_49123456780
Sep 12 21:38:50 debian systemd[1]: Started Send secure messages to Signal clients.
Sep 12 21:40:27 debian signal-cli[34036]: Envelope from: unknown source
Sep 12 21:40:27 debian signal-cli[34036]: Timestamp: 1631475625769 (2021-09-12T19:40:25.769Z)
Sep 12 21:40:27 debian signal-cli[34036]: Sent by unidentified/sealed sender
Sep 12 21:40:27 debian signal-cli[34036]: Sender: “XYZ” +49123456789 (device: 1)
Sep 12 21:40:27 debian signal-cli[34036]: Server timestamps: received: 1631475626554 (2021-09-12T19:40:26.554Z) delivered: 1631475626555 (2021-09-12T19:40:26.555Z)
Sep 12 21:40:27 debian signal-cli[34036]: Message timestamp: 1631475625769 (2021-09-12T19:40:25.769Z)
Sep 12 21:40:27 debian signal-cli[34036]: Body: Test
Sep 12 21:40:27 debian signal-cli[34036]: Profile key update, key length: 32
Sep 12 21:40:31 debian signal-cli[34036]: Exception in thread "DBus Worker Thread-4" java.lang.NullPointerException
Sep 12 21:40:31 debian signal-cli[34036]:         at org.freedesktop.dbus.messages.Message.appendone(Message.java:569)
Sep 12 21:40:31 debian signal-cli[34036]:         at org.freedesktop.dbus.messages.Message.append(Message.java:841)
Sep 12 21:40:31 debian signal-cli[34036]:         at org.freedesktop.dbus.errors.Error.<init>(Error.java:87)
Sep 12 21:40:31 debian signal-cli[34036]:         at org.freedesktop.dbus.errors.Error.<init>(Error.java:27)
Sep 12 21:40:31 debian signal-cli[34036]:         at org.freedesktop.dbus.errors.Error.<init>(Error.java:98)
Sep 12 21:40:31 debian signal-cli[34036]:         at org.freedesktop.dbus.connections.AbstractConnection.handleException(AbstractConnection.java:703)
Sep 12 21:40:31 debian signal-cli[34036]:         at org.freedesktop.dbus.connections.AbstractConnection$2.run(AbstractConnection.java:843)
Sep 12 21:40:31 debian signal-cli[34036]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Sep 12 21:40:31 debian signal-cli[34036]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Sep 12 21:40:31 debian signal-cli[34036]:         at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by mathisdt** [comment]
This problem only occurs on 0.9.0 - on version 0.8.4.1 this worked.

**Comment by JtheSaw** [comment]
I experienced the same issue. But I found out that it depends on what I do inside the `onMessageReceived` callback.

If I forward the incoming message to another API it will throw the exception above, if I comment out this request everything is fine. Are you doing something similar?

Still I also need that to be fixed, but I could not find out what's different to version 0.8.5 which worked fine with the code below.

```
import os
import requests
from pydbus import SystemBus
from gi.repository import GLib

endpoint_to_forward = os.environ.get("FORWARD_ENDPOINT")

def msgRcv (timestamp, sender, group_id, message, attachments):
    data = {
        "timestamp": timestamp,
        "sender": sender,
        "group_id": group_id,
        "message": message,
        "attachments": attachments
    }
    r = requests.post(endpoint_to_forward, json=data)
    return

bus = SystemBus()
loop = GLib.MainLoop()

signal = bus.get('org.asamk.Signal')

signal.onMessageReceived = msgRcv
loop.run()
```

**Comment by bublath** [comment]
I'm using signal-cli 0.9.0 on a Raspberry (only difference is that I self-compiled libsignal_jni.so and libzkgroup.so) and don't see that issue.
I'm also using Perl (Protocol::DBus) to communicate with the daemon, but the error above probably should be independant of the consumer.

Have you e.g. tried to self-compile those libraries to make sure there are no platform specific issues with the binary libs that are provided as standard? E.g. I noticed that due to the glibc version, the provided libs require Ubuntu 20.04+ (they fail on Ubuntu18.04, though that is already preventing the start).

**Comment by JtheSaw** [comment]
I tried both using the release version and building it myself (`make libzkgroup`) but I still get the same error...

**Comment by JtheSaw** [comment]
I had the same error but I found my problem now. It depends on how you call the `sendMessage` DBUS function. See here:

```python
# ❌ phone number as single string is ending in NPE
signal.sendMessage(message, attachments, "+49123456789")

# ✅ phone number as list of strings is working fine
signal.sendMessage(message, attachments, ["+49123456789"])
```

Hope this is also solving your problem @mathisdt

**Comment by mathisdt** [comment]
Strangely this also solved my problem. I write "strangely" because on another server, I also upgraded signal-cli and *had* to use the method signature `signal.sendMessage(message, attachments, "+49123456789")` because I would get an exception using a list as third parameter (which I had used before). So I updated the python script there, and it worked (and still works). When I made the same change (list of string to only a string) on the other system, I got the exception.

But now it works on both systems - as I said, strangely with different method signatures used. Thanks @JtheSaw!

**Comment by morph027** [comment]
Might be related: https://github.com/AsamK/signal-cli/issues/807#issuecomment-1003523909

**Comment by greenpines65** [comment]
Hello @mathisdt @JtheSaw,
Please be careful while using `sendMessage()`. If the recipient is passed as single string -- you may occasionally experience a "message hang" which is actually several attempts to send your message to invalid numbers. See my comment here: https://github.com/AsamK/signal-cli/discussions/1302#discussioncomment-9104254
