### ISSUE TITLE
Suggesting newer version of zkgroup

### ISSUE THREAD

**Issue by neomsg-git** [AsamK/signal-cli#719]
Any user on a M1 system [has to compile the libraries themselves](https://github.com/exquo/signal-libs-build/issues/1). Currently signal-cli uses the version 0.7.0 of zkgroup, which [cannot be compiled without some modification](https://github.com/signalapp/zkgroup/issues/17). This however is [fixed by using a newer version of the rust toolchain](https://github.com/signalapp/zkgroup/commit/d5f191e341b9e522f2180186c2dd7556b3a4e3cc). So my suggestion is to update to a newer version of zkgroup for the next release of signal-cli.

**Comment by exquo** [comment]
While updating software dependencies' is generally a good idea, I think it's not _required_ in this case, just to build `zkgroup` on M1.

The key is to not use the makefile provided in the zkgroup repo, but to set up the rust nightly 'manually', and do the cargo build with the command extracted from that makefile:
	
	rustup toolchain install nightly --profile minimal
	rustup default nightly
	cargo build --release -C link-arg=-s

I don't have M1 to test this on, but that's essentially what the [build workflow](https://github.com/exquo/signal-libs-build/blob/main/.github/workflows/) I use does (except that the rust toolchain is set up with a [GitHub action](https://github.com/actions-rs/toolchain)).

Also, macos-11 runner is now available in GH Actions, so I might be able to provide pre-built versions for it in the future.

**Comment by neomsg-git** [comment]
For me manually changing the file `rust-toolchain` file to `nightly` and calling `make libzkgroup` worked. But in the future I would be happy to install signal-cli using [brew](https://formulae.brew.sh/formula/signal-cli#default). Running brew with the flag `--build-from-source` however fails, because version 0.7.0 of zkgroup is by default not compatible with M1.

**Comment by AsamK** [comment]
Please take this to the brew formula maintainers, those aren't provided by signal-cli.
