### ISSUE TITLE
Invalid username (phone number), make sure you include the country code.

### ISSUE THREAD

**Issue by straussmaus** [AsamK/signal-cli#721]
I am probably doing something very stupid, so this is probably not a bug.  But I have tried several things so I am reporting as though it is one.  Sorry if I am being stupid.

I am trying to register.  I am using:

`/path/to/signal-cli -u 12125551111 register`

Obviously this is not the true number but it is a US number and if I dialed within the US I would dial 1-212-555-1111.

I have also tried:

1-212-555-1111
001-212-555-1111
0112125551111

But I always get the same error: 

`Invalid username (phone number), make sure you include the country code.`

So am I entering something wrong, or is the error message not accurate?

**Comment by AsamK** [comment]
you need to a plus sign (+) in front of the country code, to get the international E164 number

`/path/to/signal-cli -u +12125551111 register`

**Comment by straussmaus** [comment]
Thank you I would never have guessed this.
