### ISSUE TITLE
Using signal-cli with local server

### ISSUE THREAD

**Issue by Ra1issa** [AsamK/signal-cli#722]
Hi, 

Thanks for this awesome repo. Im a researcher at BU. I was wondering if you have any directions on how to configure 
signal-cli with a custom/local signal server. 

Thanks !

**Comment by AsamK** [comment]
Hi, I can't help you with setting up a local server.
But to use signal-cli with an alternative server you need to adapt the LiveConfig file: https://github.com/AsamK/signal-cli/blob/master/lib/src/main/java/org/asamk/signal/manager/config/LiveConfig.java
All URLs and server specific keys are configured in there.
