### ISSUE TITLE
DBUS, can't run it...

### ISSUE THREAD

**Issue by DangerD1024** [AsamK/signal-cli#723]
```
root@videoprocess2:/home/dangerd/signal# systemctl start signal-cli.service
Failed to start signal-cli.service: Unit signal-cli.service has a bad unit file setting.
See system logs and 'systemctl status signal-cli.service' for details.
root@videoprocess2:/home/dangerd/signal# systemctl status signal-cli.service
● signal-cli.service - Send secure messages to Signal clients
     Loaded: bad-setting (Reason: Unit signal-cli.service has a bad unit file setting.)
     Active: failed (Result: exit-code) since Sat 2021-09-18 23:36:07 UTC; 47s ago
   Main PID: 341242 (code=exited, status=217/USER)

Sep 18 23:36:07 videoprocess2 systemd[1]: Starting Send secure messages to Signal clients...
Sep 18 23:36:07 videoprocess2 systemd[341242]: signal-cli.service: Failed to determine user credentials: No such process
Sep 18 23:36:07 videoprocess2 systemd[341242]: signal-cli.service: Failed at step USER spawning /home/dangerd/signal/bin/signal-cli: No such process
Sep 18 23:36:07 videoprocess2 systemd[1]: signal-cli.service: Main process exited, code=exited, status=217/USER
Sep 18 23:36:07 videoprocess2 systemd[1]: signal-cli.service: Failed with result 'exit-code'.
Sep 18 23:36:07 videoprocess2 systemd[1]: Failed to start Send secure messages to Signal clients.
Sep 18 23:36:18 videoprocess2 systemd[1]: /etc/systemd/system/signal-cli.service:11: Failed to resolve unit specifiers in '%dir%/bin/signal-cli': Invalid slot
Sep 18 23:36:18 videoprocess2 systemd[1]: signal-cli.service: Unit configuration has fatal error, unit will not be started.
Sep 18 23:36:19 videoprocess2 systemd[1]: /etc/systemd/system/signal-cli.service:11: Failed to resolve unit specifiers in '%dir%/bin/signal-cli': Invalid slot
Sep 18 23:36:19 videoprocess2 systemd[1]: signal-cli.service: Unit configuration has fatal error, unit will not be started.
```
how i can register and add logged in config to it?

**Comment by bublath** [comment]
Check this out:
https://github.com/bublath/FHEM-Signalbot/tree/main/package
Here are all the files (except signal-cli itself, see readme.txt files) in the right directories to run signal-cli as system service including the DEBIAN files to create and .dev package. It should give you enough hints how to change your config files to make them run.
Check the pre/post install scripts for additional information about file permissions.

Or just check out the "package directory and rename it to e.g.
_signal-cli-dbus_0.9.0-1_armhf_
and execute
_dpkg-deb --build --root-owner-group signal-cli-dbus_0.9.0-1_armhf_
to create a debian package that you can install with
_apt-get install -f ~/dpkg-deb --build --root-owner-group signal-cli-dbus_0.9.0-1_armhf_

signal-cli is built with native libraries for amd64 (so you need to change every armhf string to amd64 in filenames and the DEBIAN/control file. For ARM (Raspberry) you need to replace the native libraries in the .jar 

This starts signal-cli in "registration-mode" and you can use dbus-send commands like "register" and "verify" to setup accounts.

**Comment by DangerD1024** [comment]
Thank you, that hepled.
