### ISSUE TITLE
Captcha instructions fail and solution

### ISSUE THREAD

**Issue by straussmaus** [AsamK/signal-cli#724]
Registering with 

`/path/to/signal-cli -u +12125551212 register`

I get:

```
Captcha required for verification, use --captcha CAPTCHA
To get the token, go to https://signalcaptchas.org/registration/generate.html
Check the developer tools (F12) console for a failed redirect to signalcaptcha://
```

Same as https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha, I am told to look at developer tools for a `signalcaptcha://` URI.  But there is none there.

My browser asks me to open the file.  So my solution was to create a script capturecaptcha.sh that captures the url, then I manually add:

```
#!/bin/bash

echo $1 > signalcaptchaURL
```

Then I proceed using the captcha string in `signalcaptchaURL`.

**Comment by bublath** [comment]
Also check this thread where we discussed a couple of solutions to automate retrieval of the captcha:
https://github.com/AsamK/signal-cli/issues/701
