### ISSUE TITLE
dbus onMessageReceived, how i can get attachment name with extension?

### ISSUE THREAD

**Issue by DangerD1024** [AsamK/signal-cli#731]
When i receive message with attachment i get list of file paths:
`["/var/lib/signal-cli/attachments/QsmyA36MzkzG66JHsMJx"]`
How i can get their names?

**Comment by exquo** [comment]
Duplicate of #316

**Comment by DangerD1024** [comment]
So it's fixed and need to recompile it from source?

**Comment by exquo** [comment]
No, it's not yet implemented.
