### ISSUE TITLE
DBus updateGroup How to remove members from group?

### ISSUE THREAD

**Issue by DangerD1024** [AsamK/signal-cli#739]
`updateGroup(byte[] groupId, String name, List<String> members, String avatar)`

How i can remove member from group?

**Comment by bublath** [comment]
Currently this is not possible.
There is a PR #732 that is adressing this gap

**Comment by DangerD1024** [comment]
Are you planning to merge it? Because i need also group update notification

**Comment by AsamK** [comment]
There's now a dbus group interface, where each group is exported as a separate dbus object. Among other things that object provides a `removeMembers` method.
