### ISSUE TITLE
send messages on "enter" when reading from stdin

### ISSUE THREAD

**Issue by anarcat** [AsamK/signal-cli#74]
it would make it almost a complete commandline client if messages would be flushed on newline in "send" mode... the way i use signal-cli right now is this:

```
$ signal-cli -u +XXXXXXXXXX daemon &
$ signal-cli --dbus receive -t -1 &
$
```

Then I send messages like this:

```
$ signal-cli --dbus send +YYYYYYYYYY
hello
^D
```

And i see the responses on the terminal. Instead of typing `control-d` there, it would be nice if i could just keep on typing in that `send` command without having to send a EOF character - that way i wouldn't have to "up-arrow" ... maybe that would be a different command though?

or should i write some sort of wrapper? i know that the weechat people are working on integration, but i'm not ready to make that switch just yet (e.g. https://github.com/thefinn93/signal-weechat/issues/8 and https://github.com/thefinn93/signal-weechat/issues/3)...

**Comment by AsamK** [comment]
This could be a new command (like `interactive`), which displays incoming messages and allows sending multiple messages.

**Comment by AsamK** [comment]
Out of scope for signal-cli itself, can be implemented by wrapper scripts.
