### ISSUE TITLE
[Question] Disappearing messages state set in master device gets changed

### ISSUE THREAD

**Issue by open-recipes-app** [AsamK/signal-cli#750]
Hi,

Although disappearing messages is set to something(timed) in master device when sending via signal-cli disappearing messages  gets disabled, is this normal or am I doing something wrong.

Thanks,

**Comment by AsamK** [comment]
You need to set the disappearing messages setting in the app and then run `signal-cli -u +XXX receive` so that signal-cli knows about the setting.
