### ISSUE TITLE
Event when user accepts new group request (DBus)

### ISSUE THREAD

**Issue by DangerD1024** [AsamK/signal-cli#751]
I there any way to receive callback after user accepts invite request to group?
`signal-cli[699]: INFO IncomingMessageHandler - Ignoring a group message from an unauthorized sender (no member or admin): 9fc291e1-94db-4da7-ad6c-a684658ca17a 1632860480347`
After accepting invite i have this string in log.
The problem is that after creating new group and add some people to it, messages sent before acepting are lost, so i want to track that and resend message after user accepts invite.

**Comment by AsamK** [comment]
With the latest master you should now get a group update message when someone accepts a group invite.
Related:  #501

**Comment by DangerD1024** [comment]
Why it's duplicate???
I have latest master that i updated 2 days ago... User already accepted invite request before and can write to group and signal-cli will receive it, but if i'll restart service messages will be not received from this user anymore with this error...
