### ISSUE TITLE
dbus: Syntax for updateProfile

### ISSUE THREAD

**Issue by condemnedmeat** [AsamK/signal-cli#754]
I can't seem to get it right, keep getting `Error org.freedesktop.dbus.errors.UnknownMethod: The method org.asamk.Signal.updateProfile does not exist on this object.`

Using 0.9.0. The daemon is started anonymously. I'm using signal-cli as the primary device, no linked devices and there is only one account in use.

These are the instructions:
`updateProfile(givenName<s>, familyName<s>, about<s>, aboutEmoji <s>, avatar<s>, remove<b>)`

This is what I'm trying:
`dbus-send --session --print-reply --type=method_call --dest=org.asamk.Signal /org/asamk/Signal org.asamk.Signal.updateProfile string:device string: string: string: string: boolean:false`

Could someone guide me on what I'm doing wrong please?

Thank you.

**Comment by bublath** [comment]
Did you start the daemon with -u ?
If not you need to send to /org/asamk/Signal/_phonenumber

**Comment by condemnedmeat** [comment]
You're right, it says that in the man page. I hadn't thought about that as I only have the one account.

Is the rest of the command I was trying correct?

**Comment by bublath** [comment]
Have you compiled the current source or are you using 0.9.0 release.
Since the release does only have
updateProfile(name<s>, about<s>, aboutEmoji <s>, avatar<s>, remove<b>)

**Comment by condemnedmeat** [comment]
You are right, I'm getting confused. Sorry. Next time I'll try again and report if I have any issues.

Thank you.
