### ISSUE TITLE
[Feature Request] Respect request to hide number in groups

### ISSUE THREAD

**Issue by condemnedmeat** [AsamK/signal-cli#755]
There is a flag in [Android](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/util/FeatureFlags.java#L294) and I guess ios that allows a user to stop their number being shared. `See my number` can be set to `Nobody`.

Signal-cli appears not to respect this and will share a users number when acting as a linked device. For example, sending a typing indicator in the cli immediately changes the users profile - from the perspective of other group members - from no number to having a number visible.

Wondering of the possibility that signal-cli might be adjusted in the near future to respect this setting.

Thank you.

**Comment by DangerD1024** [comment]
+1 i also need such feature!

**Comment by AsamK** [comment]
The functionality is still behind a feature flag in the Android App, signal-cli will eventually support this as well.
It's partially implemented already, if you compile it yourself, you can have a look at SignalAccount.java

**Comment by piramiday** [comment]
hey @condemnedmeat, how does this feature work in Android?
could you guide us through the steps in the GUI to accomplish this?
