### ISSUE TITLE
Invalid Captcha

### ISSUE THREAD

**Issue by cyzuer** [AsamK/signal-cli#765]
When i try to register my landline i always get `Invalid captcha given`

i use
`~/signal-cli-0.9.0/bin $ sudo ./signal-cli -u +49xxxx4071 register --voice --captcha 03AGdBq...........a6rSaz1A`

i think i use the correct way to get the captcha token, because it worked earlier on an different mobile number. 

Is there a problem with signals https://signalcaptchas.org/registration/generate.html
I use the version for Raspberry Pi by [Dutch Foreigner](https://github.com/DutchForeigner/signal-cli_rpi/releases)

**Comment by Rusty77** [comment]
I'm having the same feedback "Invalid captcha given", and have tried both of the captcha URLs as a soruce, both in image-mode which yields shorter captchas and text-mode which are longer!

### My setup
* I'm running headless Home Assistant OS, 
* where i've [installed the signal add-on](https://github.com/haberda/hassio_addons/tree/master/signal_messenger)
* ...which gives me the signal REST API](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md) 
* i can then  opened SSH to my HA, executed a bash session in the docker container running the add-on, and call signal-cli directly
* i'm running a web browser on my laptop to obtain the captcha, and pasting them into SSH

### What i've tried
1. HTTP requests to the REST API provided by the Signal add-on
```
curl -X POST -H "Content-Type: application/json" -d '{ "use_voice": false, "captcha": "signal-hcaptcha-short.5fad97ac-***wJr54" }' 'http://homeassistant.local:8080/v1/register/+44<my land line>'
{"error":"Invalid captcha given.\n"}
```

2. signal-cli calls in the docker container
```
# docker exec -it  addon_1315902c_signal_messenger bash
WARNING: signal-cli-rest-api runs as signal-api (not as root!)
Run 'su signal-api' before using signal-cli!
If you want to use signal-cli directly, don't forget to specify the config directory. e.g: "signal-cli --config /config"
root@1315902c-signal-messenger:/# su signal-api
signal-api@1315902c-signal-messenger:/$ signal-cli -v --config /config -a +44<my land line> register --captcha signal-hcaptcha.5fa***k-AglD9TE34Dg77G0

[main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
[main] DEBUG org.asamk.signal.App - Starting signal-cli 0.13.11
[main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@50fe837a
[main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[main] DEBUG o.a.s.m.util.NumberVerificationUtils - No registration session, creating new one.
[main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
[main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Invalid captcha given.
```

**Comment by Rusty77** [comment]
Persistence pays off!   I've tried several times over several days; I reckon there was some incompatibility with the https://signalcaptchas.org/registration/generate site, because a new type of captcha interaction there has allowed me to register my number and send a test message.
