### ISSUE TITLE
Add desktop app as linked device?

### ISSUE THREAD

**Issue by steveredden** [AsamK/signal-cli#775]
Using the cli as a primary device, is there a way to add the desktop app as a secondary device?  That way I can provide a GUI method of checking messages...  (I used a spam Google Voice number to auth...)

I checked out [Linking-other-devices-(Provisioning)](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)), but since the Desktop app is the one granting the QR, I wasn't sure if there was a way to get it to work.

![image](https://user-images.githubusercontent.com/35814432/137217003-4b17cf46-759d-4ce1-8adb-a6e2da028bfc.png)

**Comment by AsamK** [comment]
Yes, the point "Add another device" is relevant for you on that page.
