### ISSUE TITLE
Disappearing messages timeout causes crash on iPhone app

### ISSUE THREAD

**Issue by rakypz** [AsamK/signal-cli#78]
I was able to produce the bug on an iPhone 6s IOS 10.3.1 by doing the following: 

* Added a linked signal-cli device to the iPhone app
* Sent a message to myself via signal-cli 
* Opened the message in the iPhone app and set the disappearing messages setting to 1 minute
* Ran a signal-cli -u USERNAME receive
* Confirmed signal-cli now had the correct timeout value in the config data
* Sent a message again from the signal-cli to myself
* When attempting to view the message in the iPhone app the iPhone app will immediately crash

EDIT: After removing the disappearing timeout setting in the iPhone app and sending a message via the signal-cli, it will work again. So something with the disappearing timeout setting is making it crash. 

Tested with different message texts and can confirm all will cause a crash.

There are situations (such as server alerts etc) where I'd want to send messages to myself, so it would be great to be able to set the disappearing timeout setting in the signal-cli command if possible, rather than having to rely on a conversation having to be started from the mobile app (or web app). 

Love this project though, thanks and well done.

**Comment by Trolldemorted** [comment]
you should open an issue at the Signal-iOS repo since this does not sound like a cli issue

**Comment by rakypz** [comment]
Ah, am sorry - will do. Thanks for the prompt response.
