### ISSUE TITLE
signal.sendMessage hangs

### ISSUE THREAD

**Issue by Tsjippy** [AsamK/signal-cli#787]
I have a script that uses python3.9 and signal-cli v 0.9.2 to send messages:
`signal = bus.get('org.asamk.Signal')
signal.sendMessage("Good morning", [],'somephonenumber')`

but it hangs, it never returns, so no error code as well.
Receiving messages works fine.

The command `/usr/local/bin/signal-cli --dbus-system send -m "Message" somenumber` works fine.

What  can I do?

**Comment by morph027** [comment]
Might be related: https://github.com/AsamK/signal-cli/issues/807#issuecomment-1003523909

**Comment by greenpines65** [comment]
Hello @Tsjippy,
The "message hang" that you experience is actually several attempts to send your message to invalid numbers. See my comment here: https://github.com/AsamK/signal-cli/discussions/1302#discussioncomment-9104254
