### ISSUE TITLE
Behind a proxy

### ISSUE THREAD

**Issue by saptarshiguha** [AsamK/signal-cli#79]
Hello,
Im runnin signal 0.5.5 behind a proxy. but i get this error

signal-cli -u +NUMBER register
Request verify error: java.net.SocketTimeoutException: connect timed out

Is there a way around this?

**Comment by AsamK** [comment]
Unfortunately libsignal-service-java doesn't support proxies, so that's not possible.

**Comment by youknow0** [comment]
libsignal-service-java seems to have proxy support. It can be configured using `http.ProxyHost` and `http.ProxyPort`. Just set `JAVA_OPTS` accordingly:

`export JAVA_OPTS="-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8080"`
