### ISSUE TITLE
Why switch to Java 17?

### ISSUE THREAD

**Issue by DerOetzi** [AsamK/signal-cli#791]
I just noticed in changelog.md that there is planed to change to Java Version 17. Just want to ask the reason for this change, because it will break my integration to some containers running other programms with Java version 11. Thanks for the answer.

**Comment by exquo** [comment]
Just wanted to mention that the current signal-cli master still builds successfully with Java version 11. Also the one built with Java 17 (seems to) run fine on a system with Java 11. 

Of course, this may change in the future. Even the current built-with-17-but-run-on-11 version, though seems to work, may break on calling some particular functionality.

**Comment by AsamK** [comment]
That shouldn't work ... signal-cli master uses quite a lot of newer java features.
When running the java 17 build on java 11, I get an error:
> java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by exquo** [comment]
Oops, I've been accidentally building the latest release instead of master. Sorry for the noise!

**Comment by bublath** [comment]
I also just noticed the push to Java17. As my application typically runs on Raspberry Pi or older stable systems (use case is home automation) where installing Java 17 is not straight forward, it looks like I will be stuck on 0.9.2. for the forseeable future. 
@AsamK : I understand the motiviation to move to Java 17, but I believe you will lose a lot of users by doing this so early. I would ask you to rethink that decision
