### ISSUE TITLE
Fatal error on send

### ISSUE THREAD

**Issue by babarnazmi** [AsamK/signal-cli#796]
It looks like virtualization/CPU flags related issue not your code, but I am unable to find the solution.
Please suggest? Tried latest version with latest openjdk on two different machines with same fatal error, different version of QEMU and different CPU/Hosts

INFO ManagerImpl - The Signal protocol expects that incoming messages are regularly received.

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f04901c81aa, pid=231151, tid=231161

 JRE version: OpenJDK Runtime Environment (17.0.1+12) (build 17.0.1+12-39)
 Java VM: OpenJDK 64-Bit Server VM (17.0.1+12-39, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 V  [libjvm.so+0x5191aa]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<598116ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 598116ul>::oop_access_barrier(void*)+0xa

 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /home/bshafiq/signal-cli/bin/hs_err_pid231151.log

 If you would like to submit a bug report, please visit:
   https://bugreport.java.com/bugreport/crash.jsp

Abort
[hs_err_pid231151.log](https://github.com/AsamK/signal-cli/files/7476690/hs_err_pid231151.log)
[cpu-info.txt](https://github.com/AsamK/signal-cli/files/7476523/cpu-info.txt)
ed

**Comment by AsamK** [comment]
Which signal-cli build do you use and did you compile the `libsignal_jni.so` file yoursef?
In that case make sure you're using version 0.9.7.

**Comment by babarnazmi** [comment]
I was using latest version of signal-cli and latest version (0.9.8) of libsignal_jni.so, build myself.
As you suggested, downgraded libsignal-client to 0.9.7 and signal-cli starts working fine now.

Thanks a lot !!
