### ISSUE TITLE
How to set group avatar picture with new Dbus property methods?

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#797]
Just tried to understand which changes I would need to make to avoid the deprecated methods handling groups.
I believe there is a gap for the avatar. While you can add the picture with createGroup, I currently see no other method than the deprecated updateGroup method to change/add it later.
Should the avatar be added as a property for Properties.Set?
Any plans on how long the deprecated method will remain supported (since I use them heavily)?

**Comment by AsamK** [comment]
There's a write only dbus property on the group object to set a new avatar:
`    @DBusProperty(name = "Avatar", type = String.class, access = DBusProperty.Access.WRITE)`

There are no immediate plans to remove the deprecated methods. They'll remain for the next few versions at least.
