### ISSUE TITLE
[Question] Voice feasible?

### ISSUE THREAD

**Issue by hpmueller1971** [AsamK/signal-cli#80]
Hi all,

now what Signal is WebRTC-only (no more proprietary servers&protocols) for Voice, is it feasible to connect signal-cli with a WebRTC-aware PBX like asterisk...? Would this just involve some sort of URI beeing passed to asterisk, and it would handle WebRTC, RTP, codecs, encryption etc, or would you have to implement a complete voip-stack...?

edit: I didn't mean to imply "go, and implement a voip-stack", just to clarify ;). That would IMHO be way out of scope for a cli-tool ;). I mean, is WebRTC a complete, selfcontained protocol with session-handling etc, or is it just a protocol to connect two endpoints, and the application has to do the whole work...

**Comment by AsamK** [comment]
I haven't looked at the WebRTC implementation in signal yet, so I don't know if this is possible or how difficult it would be.
This needs more investigation.

**Comment by Geremia** [comment]
Is there a way for `signal-cli` to make another device place a call?

**Comment by NemesisHubris** [comment]
Any updates on this?
