### ISSUE TITLE
Dbus: WARN ManagerImpl - Connection closed unexpectedly, reconnecting in 100 ms

### ISSUE THREAD

**Issue by groupnet** [AsamK/signal-cli#800]
I'm running signal-cli via dbus. The systemd logs fill with the following warning:
```signal-cli[...]: WARN ManagerImpl - Connection closed unexpectedly, reconnecting in 100 ms```

Any idea where this warning comes from?

JRE 17
signal-cli v0.9.2

**Comment by AsamK** [comment]
That warning appears when the websocket connection to the Signal Server is interrupted.
signal-cli will attempt to reconnect after initally 100ms, if there's no follow up log message 200ms the reconnection was successful.
