### ISSUE TITLE
UnregisteredUserException Causes Registered Users to Fail [and doesn't print failure information]

### ISSUE THREAD

**Issue by muad-dumb** [AsamK/signal-cli#803]
When attempting to send a message to many recipients at once (bulk-send), if there is one or more numbers which are improperly registered (with Signal) then Signal-CLI returns the error:

'Failed to send message: null (UnregisteredUserException)'

And subsequently Signal-CLI will fail to successfully send messages to correctly registered users (contacts) in that same bulk-message. 

After failure, Signal-CLI does not print information about which numbers did or did not receive messages, it prints the above message and doesn't identify the unregistered user.

This issue appears to apply to cause failures to registered users at random; in a bulk-send, a handful of contacts will sometimes not receive messages, and during other attempts will receive them. During a bulk-send at any later time, contacts who failed to receive the previous bulk-send will receive the second bulk message, and contacts who received the first message will fail to receive the second message; so, the failure applies to contacts in a bulk-send at random, per attempt.

Absolutely love this project, so I hope this is helpful!

**Comment by AsamK** [comment]
Thanks for creating the issue, this should indeed be improved.
The failed message should either be sent to no recipient or to all still registered recipients.

**Comment by exquo** [comment]
Related: #348, for _group_ messages.

Maybe also fixed by the latest commit.

**Comment by muad-dumb** [comment]
Hello! This issue just re-occurred tonight; the issue and outcome were the same (exactly) as what's detailed in my original post.

I'm not sure if there was an update to attempt to create a printout with more information after this type failure, but I didn't see one.
