### ISSUE TITLE
[dbus] sendMessage recipient parameter

### ISSUE THREAD

**Issue by woifes** [AsamK/signal-cli#807]
Hello I have a small project where I bridge signal-cli with mqtt via python [repo](https://github.com/woifes/mqtt-signal-cli-gateway) Some time ago a got a pullrequest stating that for him/her the ````sendMessage``` function needs to have it as list of recipients in order to work. I did not really care so checked the pr on my side and was surprised for me it is the other way round. I get
```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pydbus/subscription.py", line 52, in <lambda>
    callback = (lambda con, sender, object, iface, signal, params: signal_fired(sender, object, iface, signal, params.unpack())) if signal_fired is not None else lambda *args: None
  File "/home/pi/.local/lib/python3.7/site-packages/pydbus/proxy_signal.py", line 15, in signal_fired
    callback(*params)
  File "./main_test.py", line 61, in _onSignalMsg
    self._signalCommands[cmd]["fn"](timestamp, source, args[1:])
  File "./main_test.py", line 71, in _onSignalHelp
    self._sendSignalMsg(m, source)
  File "./main_test.py", line 49, in _sendSignalMsg
    self._signal.sendMessage(message, [], [to])
  File "/home/pi/.local/lib/python3.7/site-packages/pydbus/proxy_method.py", line 74, in __call__
    self._iface_name, self.__name__, GLib.Variant(self._sinargs, args), GLib.VariantType.new(self._soutargs),
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 172, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 150, in _create
    builder.add_value(self._create(dup, i))
  File "/usr/lib/python3/dist-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
TypeError: Must be string, not list
```
I am really no dbus expert so I tried to google/search myself. I found this issue here for this repo #479 but it was closed. The participants seemed to know what was the problem but I do not.
Can you maybe bring some light into the dark? Can it be detected beforehand whether is should be a list or a plain string?

**signal-cli 0.8.5**
```
uname -a                                                                                           
Linux Rpigateway 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
```

**Comment by AsamK** [comment]
The Python dbus lib doesn't seem to be handling method overloads correctly, maybe different versions hm behave differently?
https://github.com/AsamK/signal-cli/issues/787#issuecomment-953181876

**Comment by morph027** [comment]
Came across this issue and found a way to specify the overloaded method using legacy python dbus binding:

```python
from dbus import SystemBus
bus = SystemBus()
signal_cli_dbus = bus.get_object("org.asamk.Signal", f"/org/asamk/Signal/_ACCOUNT")
signal_cli_dbus.sendMessage("Message", [], ["recipient"], signature=sasas)
```

From the [docs](https://dbus.freedesktop.org/doc/dbus-python/tutorial.html#data-types)

> D-Bus has an introspection mechanism, which dbus-python tries to use to discover the correct argument types. If this succeeds, Python types are converted into the right D-Bus data types automatically, if possible; TypeError is raised if the type is inappropriate.
> 
> If the introspection mechanism fails (or the argument’s type is variant - see below), you have to provide arguments of the correct type. dbus-python provides Python types corresponding to the D-Bus data types, and a few native Python types are also converted to D-Bus data types automatically. If you use a type which isn’t among these, a TypeError will be raised telling you that dbus-python was unable to guess the D-Bus signature.
