### ISSUE TITLE
Base64 information

### ISSUE THREAD

**Issue by ofn1** [AsamK/signal-cli#809]
Can signal-cli support base64 processed information?  
eg: 
`signal-cli -u xxx  send -m --base64 xxx xxx`
`dbus-send --session --type=method_call --print-reply --dest='org.asamk.Signal' /org/asamk/Signal org.asamk.Signal.sendBase64Message string: array:string: string:`

Because some information is relatively long and contains special characters, it is easy to be misunderstood by the command line and cause various errors

**Comment by AsamK** [comment]
No, if escaping the arguments is too cumbersome for your use case you could consider a more advanced programming language than bash, like python.
Our maybe use the base64 command: (untested)
`signal-cli send -m "$(base64 -d <<<Xxxxxxxx)"`
