### ISSUE TITLE
Sending typing indicator with dbus?

### ISSUE THREAD

**Issue by AlexIsOK** [AsamK/signal-cli#810]
is there any way to send the typing indicator (to the other user) using dbus?  making a bot of sorts and would like it to have an indicator for commands that take a long time to execute.

does this exist using dbus (or at all)?  couldn't find it on the dbus wiki page anywhere, might've just missed it though.

**Comment by Tsjippy** [comment]
signal.sendTyping(source,False)

Currently sendTyping for DBus does not support groups, but I think this will be solved in the next release
