### ISSUE TITLE
Issue with previous config when using latest master

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#812]
Despite the issues with Java17, I wanted to try it, since I recently had issues with captcha registration via DBus (and some of my users as well).
Anyway: When starting the latest master with my current config I get
 WARN App - Ignoring +49xxxxx: Error loading state file for user +4989xxxx: failed to deserialize zkgroup::api::server_params::ServerPublicParams (IllegalArgumentException)

Using Java17 from https://adoptium.net/ for linux/arm32 on Raspberry Pi4. To enable Java, I have just changed JAVA_HOME (and PATH for building) to where I unpacked that version.
Though I rather suspect this to be caused by the switch to the new libsignal-client lib that now includes zkgroup.

Also even with latest master (as well as with 0.9.0 and 0.9.2) I get
Error org.freedesktop.dbus.exceptions.DBusExecutionException: Error Executing Method org.asamk.Signal.registerWithCaptcha: null
on some systems when trying to register.

**Comment by AsamK** [comment]
Yeah, looks like an issue with libsignal-client ... did you build the native lib version 0.10.0?

**Comment by bublath** [comment]
I took the latest version - looks like that's V0.11.0 - can this be the problem?

**Comment by AsamK** [comment]
Yes there can be incompatible changes between versions. There have also already been breaking changes between minor versions...

**Comment by bublath** [comment]
You're right - checking out 0.10.0 solved the problem
