### ISSUE TITLE
Using multiple devices with one account

### ISSUE THREAD

**Issue by Aendrew87** [AsamK/signal-cli#815]
Hi there,

i installed signal-cli an a linux server and could send messages without problems.
After hat i installed to more servers and copied the config files from the first server.

Now i could only send messages from server 2, server 1 und server 3.
To send the message i use `signal-cli -u +49xxxxxxxxxxx send -m "Server x" +49xxxxxxxxxxx`.

On the shell i could see no error even with `--verbose` there is no error message.

How could i send messages from all servers using one account?
Is linking another device (`addDevice`) the right way?

Regards
Aendrew

**Comment by Aendrew87** [comment]
Got it....

On the master (at the moment server 2) execute `signal-cli listDevices` to get all devices.

To connect a new device remove the stored configuration on the new server and execute `signal-cli link -n "device name"`.
Use the output of this command on the master to execute `signal-cli addDevice --uri "tsdevice:/?uuid=..."`.
Now you could use `signal-cli listDevices` and see all devices.

Repeat this steps on the last server and you could use all servers to send messages.

**Comment by AsamK** [comment]
Yes to use the same account on multiple devices you need to use the link command.
Just copying the data files isn't supported by the protocol.

**Comment by rdtech2020** [comment]
I tried the below command 
''' signal-cli --dbus-system link -n +xxxxxxxxx | tee >(xargs -L 1 qrencode -t utf8) '''
but I am getting below error - 
IOException Failed to decrypt public key

but, without daemon mode It is working fine.
