### ISSUE TITLE
Unable to add signal-cli account to group

### ISSUE THREAD

**Issue by bitboy85** [AsamK/signal-cli#819]
I've installed signal-cli long time ago and it was working fine until mid 2021.
To repair it, i installed a new version and ans also created a new signal-cli user. Registering with captcha worked fine so far, no error displayed.

I'm trying to add this account via signal app on the phone to a group using phone number but it always fails with error that the signal-cli is not able to join groups of the new type.

I'm using the pre compiled version 0.9.0 for rpi.

**Comment by AsamK** [comment]
Were any warnings or errors shown when registering the user?
You could try setting a profile for this user, with updateProfile command, which is required for new groups.
Normally signal-cli should do this automatically but maybe it failed for some reason.

**Comment by bitboy85** [comment]
Thx for reply, i already did that.

It worked after i send a single message from cli to my phone (and verified it). Then i was able to add it to the group.

**Comment by AsamK** [comment]
Ok.
Then the app converted the group to a v2 group, which have longer ids. Signal-cli has some compatibility code to still recognize the v1 id but that code might eventually be removed in the future.
