### ISSUE TITLE
listGroups gives empty output

### ISSUE THREAD

**Issue by akaihola** [AsamK/signal-cli#82]
I cloned and installed the current master (78518e0 2017-05-07) and used the `link` command to link to my existing Signal account on my Android phone. I also successfully sent a test message to another user.

When I execute the `signal-cli -u '+<phonenumber>' listGroups` command, I get no output (with or without the `-d` option). However, both on my phone and in the Chrome extension, I belong to a group I've previously created.

Is there a step I'm missing, or is this functionality still incomplete? Is there a way to find out the ID of the group I've created?

**Comment by Trolldemorted** [comment]
you can look up your groups in signal-cli's storage:

- open `~/.config/signal/data/YOURPHONENUMBER`
- search for `groupStore`
- all your groups signal-cli knows about are listed there, including their ID

**Comment by akaihola** [comment]
In `~/.config/signal/data/MYPHONENUMBER`, I have

    "groupStore" : {
        "groups" : [ ]
    },

even though I do have and regularly communicate using a group on the Android app.

**Comment by Trolldemorted** [comment]
That is odd.

Even if the signal-cli device missed a group update, it should™ notice that when it receives a message for an unknown group, and send a group info request to the sender, who responds with a group update.

Is the output from signal-cli indicating any of this, or are errors/exceptions displayed?

Are the group members on more or less up-to-date versions of signal-android?

Did it sync the contacts correctly?

**Comment by AsamK** [comment]
Just to make sure, have you executed the receive command?

        signal-cli -u XXX receive

**Comment by mh-g** [comment]
After taking all steps given above, I confirm this behavior.

**Comment by thijskuilman** [comment]
I am facing the same problem. I have tried the solutions in this thread, but the output keeps being empty.

**Comment by Trolldemorted** [comment]
Does signal-cli print received group messages as it should? Is your group store empty too?

**Comment by bitboy85** [comment]
I can confirm this issue. Is there another way to get the group id?

**Comment by AsamK** [comment]
I've updated the wiki, that the receive command is necessary after linking was successful.

**Comment by Atomic-Bean** [comment]
I've linked the cli as a slave, I have run receive and got both messages from a group chat and from private DMs, but `listGroups` still has an empty output. "groupStore" in the config file is also blank.

**Comment by ibrahimsoliman97** [comment]
How do you get libzkgroup working? @Atomic-Bean

**Comment by Atomic-Bean** [comment]
> How do you get libzkgroup working? @Atomic-Bean

AsamK and I made [this wiki page](https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal) that details how to do it. Let me know if you have any issues with it and I'll update it.

**Comment by ibrahimsoliman97** [comment]
It works, Thanks @Atomic-Bean

**Comment by chetbox** [comment]
I tried using the pre-built `libsignal_jni.dylib` for macOS aarch64 from https://github.com/exquo/signal-libs-build/ but I still get nothing when I run the `listGroups` command. Where should I look for more information about any errors? This just seems to fail silently.

**Comment by kmille** [comment]
I still have the issue with the current signal (0.11.7). The `listAccounts` output is empty, even after running`receive`. Sending a direct message works fiine.
