### ISSUE TITLE
Send not working anymore

### ISSUE THREAD

**Issue by heikone** [AsamK/signal-cli#822]
Suddenly faced, that I don't get any message anymore from my command:

`/opt/signal/bin/signal-cli --dbus-system  send -m "MyMesssageTextHere" +491515111111111`

Signal-cli just reporting:
`The method 'org.asamk.Signal.getSelfNumber' does not exist on this object.`

Can anybody give advice how to fix this?

Best regards
Heiko

**Comment by AsamK** [comment]
Either the daemon is running an older version, getSelfNumber was added in v0.9.1, or the daemon was started without the `-u` flag.

**Comment by heikone** [comment]
Dear AsamK,

thanks for your reply, but for me, it looks like it is running the right version, as per dump of the service status:

```
● signal.service - Send secure messages to Signal clients
     Loaded: loaded (/etc/systemd/system/signal.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-12-11 08:40:59 CET; 2min 53s ago
   Main PID: 291280 (java)
      Tasks: 40 (limit: 38311)
     Memory: 148.3M
        CPU: 12.592s
     CGroup: /system.slice/signal.service
             └─291280 java -Xms2m -classpath /opt/signal/lib/**signal-cli-0.9.2.jar**
...
```

But could you provide more help how to properly start the daemon with "-u flag" ?
I would appreciate, if you can post an example.

Gruß
Heiko

**Comment by AsamK** [comment]
signal-cli -u +sending_Phonenummer daemon

Alternatively the -u flag could also be added to the send command
