### ISSUE TITLE
NullPointerException during profile retrieval

### ISSUE THREAD

**Issue by MichaelBitard** [AsamK/signal-cli#833]
Version: 0.10.0

I have a bunch of these messages:
`WARN ProfileHelper - Failed to retrieve profile, ignoring: java.lang.NullPointerException: Cannot invoke "java.util.Locale.getLanguage()" because "locale" is null` if my env var $LANG is not defined.

It does not seems to break things though :)

**Comment by AsamK** [comment]
Thanks for reporting!

**Comment by MichaelBitard** [comment]
You're welcome, I wanted to do the PR, but you were too fast!
