### ISSUE TITLE
Sending non-emoji reactions: exit code

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#834]
Using a non-emoji string for an emoji argument in a `sendReaction` call:

	signal-cli  [--dbus]  sendReaction  --emoji 'non-emoji-str' -a "+12345678" -t 1630000000000    "+12345678"  ;  echo $?

	1631111111111
	0

does not send the reaction (at least it's not delivered to the recipient). But the process returns an exit code `0` (success). 
Can it be made to return non-zero to indicate failure?

**Comment by AsamK** [comment]
The message is actually sent and if you send it from one signal-cli account to another signal-cli account you should see the incoming message. The official apps have code to ignore non-emoji reactions so it appears to not be delivered.
e.g in Signal-Android:
```java
    if (!EmojiUtil.isEmoji(reaction.getEmoji())) {
      Log.w(TAG, "Reaction text is not a valid emoji! Ignoring the message.");
      return null;
    }
```

**Comment by exquo** [comment]
I see, thanks!

IIRC, the official clients had in the distant past allowed receiving non-emoji reactions too, although they did not provide any UI to send them.

I'll implement some checks for this before sending a reaction. Thanks for the code reference!
