### ISSUE TITLE
DBus Group ID and base64.b64encode

### ISSUE THREAD

**Issue by DangerD1024** [AsamK/signal-cli#835]
I used manual from here: (https://github.com/AsamK/signal-cli/wiki/DBus-service) to encode Byte array group id to base64:
`python3 -c 'import base64; print(base64.b64encode(bytearray([139,22,72,247,116,32,170,104,205,164,207,21,248,77])))'`
The result is: `ixZI93QgqmjNpM8V+E0=`
Now i need to call DBus:
`/org/asamk/Signal/_12345678/Groups/ixZI93QgqmjNpM8V+E0=`
and i'm getting error:
**Invalid object path '/org/asamk/Signal/_12345678/Groups/ixZI93QgqmjNpM8V+E0=': contains invalid character '+'**

How can i convert it properly?

**Comment by AsamK** [comment]
You can use the listGroups method to get the group object path:
https://github.com/AsamK/signal-cli/blob/master/man/signal-cli-dbus.5.adoc
Basically you just need to replace all special chars with underscores _
