### ISSUE TITLE
Signal desktop warning, "This person isn´t using Signal"

### ISSUE THREAD

**Issue by tjswe** [AsamK/signal-cli#836]
A heads up! Got this, today on my desktop client where i receive messages from a signal-cli only user.

No issue right now, but could be if Signal decides to ban non-official clients.

"This person isn’t using Signal
Signal Desktop does not support messaging non-Signal contacts. Ask this person to install Signal for a more secure messaging experience."

![image](https://user-images.githubusercontent.com/26895402/146325124-0170811f-a0b9-4bd6-979a-2b9aded413b6.png)

**Comment by Delan168** [comment]
Same issue on the Windows-desktop client and on the Android one. No issue on the Linux one (so far).
Not possible to send message from those client to the signal-cli user, Android proposes to use Signal as text service instead. Sending a message from signal-cli allows to re-send messages for a while, but it returns to previous state after closing the app...

**Comment by AsamK** [comment]
interesting, haven't seen this before.
Signal-Desktop shows that message for users where it doesn't know the uuid or where it thinks the user is unregistered. Both are things the server controls, I don't know yet what signal-cli does differently here ...
```typescript
export function isConversationSMSOnly(
  conversation: MinimalConversationType
): boolean {
  const { e164, uuid, type } = conversation;
  // `direct` for redux, `private` for models and the database
  if (type !== 'direct' && type !== 'private') {
    return false;
  }

  if (e164 && !uuid) {
    return true;
  }

  return conversation.discoveredUnregisteredAt !== undefined;
}
```

**Comment by ionwerz** [comment]
The same, on Android client it does not see the signal-cli users

**Comment by AsamK** [comment]
- When and with which signal-cli version did you register the users?
- Which signal-cli versions do you currently use?
- Which Desktop/Android versions do you use?

**Comment by ionwerz** [comment]
Signal-cli user was registered with version 0.5.6
Right now using 0.8.3

**Comment by ionwerz** [comment]
iOS Cient 5.26.5 seems not to be affected, I'm still able to send messages to signal-cli client

**Comment by ionwerz** [comment]
if I register new user with signal-cli and try to send a message from Android client I get next error:
```
Exception: org.whispersystems.libsignal.InvalidMessageException: Message from +MYPHONENUMBER:1 failed to decrypt; sender ratchet public key 9c7dd03ca663f9c3b7de1ac554cbbd5c956cf05c831eed6f5
Dec 16 12:12:42 signal-enc signal-cli[50936]: Candidate session 0 failed with 'invalid ciphertext message', had 0 receiver chains (ProtocolInvalidMessageException)
Dec 16 12:12:42 signal-enc signal-cli[50936]: Failed to decrypt message.
```

**Comment by tjswe** [comment]
Signal-cli was probably registered with 0.5.6 and later moved to a new server. I found an old question i asked here regarding moving from 0.5.6. Plausible registration between version 0.5.6 Jun 16, 2017 and version 0.6.0 May 03, 2018.
Running signal-cli 0.6.8
Windows desktop 5.26.0

**Comment by ionwerz** [comment]
Why messages from iOS is ok? Only the android is affected

**Comment by Delan168** [comment]
Account created using signal-cli 0.5.* or 0.6.* (I think, maybe around December 2020), now using 0.6.12 (java is a pain to update on ARMv6 on which I use signal-cli :see_no_evil: )
Signal Desktop 5.23.1 on Fedora 35 fully updated
Signal Desktop 5.27.0-beta on Windows 10 fully updated
Signal 5.28.5 on Android 11 fully updated

**Comment by AsamK** [comment]
Hard to say what's wrong here, maybe it's related to the server's account migration a while back, but that's just a guess ...
Could you try running the `updateAccount` command, older signal-cli versions don't run it automatically.

**Comment by Delan168** [comment]
I already tried `unblock` my number* (although it wasn't blocked), re-`trust` my number*, `updateAccount`, `updateContact` (after `listConstacts` them, they were ok, not blocked and now with a name), all of these without success. "my number" stands for my personal Signal account, registered on Android.
After sending a message from signal-cli, the signal-cli contact is available again as long as the app keeps running.
Edit: I've just tried to kill the Android app and restart it: signal-cli account seems to remain accessible now. Did you perform any update of the server on your side?

**Comment by ionwerz** [comment]
Unfortunately for me updatecontact has no effect, also killing the android app do not help. Can it be the problem because of AWS outage? For example ubiquity unifi cloud does not work because bof AWS

**Comment by AsamK** [comment]
There is no server part from me, signal-cli talks directly to the official Signal servers.
Could be that the official apps take a while before they refresh the registration state, after you used the `updateAccount` command ...

**Comment by tjswe** [comment]
Chekced now and message was gone. Restarted the client and sent a few test messages but looking ok. Also ran a `updateAccount` after that.

**Comment by Delan168** [comment]
After a reboot of the phone, it's still possible to send messages to the contact. On my side the problem appears to be gone and as far as I'm concerned, the issue can be closed.
Thank you for the swift answers!

**Comment by AsamK** [comment]
it appears this was a signal server issue: https://old.reddit.com/r/signal/comments/rhokck/cannot_use_signal_anymore_with_some_contacts_it/
