### ISSUE TITLE
jdk 17: Abstract sockets are not supported by transport org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport

### ISSUE THREAD

**Issue by ofn1** [AsamK/signal-cli#837]
Hi,

After upgraded to 0.10.0, daemon mode error:

> root@server:~# signal-cli -u +17111111111 daemon
> java.lang.UnsupportedClassVersionError: org/asamk/signal/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

So have to upgraded to jdk 17:
```
add-apt-repository ppa:linuxuprising/java -y
apt update
apt install oracle-java17-installer oracle-java17-set-default
```

Then the error of "Abstract sockets are not supported" appears:

> root@server:~# signal-cli -u +17111111111 daemon
> INFO DaemonCommand - Starting daemon in single-account mode for +17111111111
> java.lang.UnsupportedOperationException: Abstract sockets are not supported by transport org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport
>         at org.freedesktop.dbus.connections.transports.AbstractTransport.<init>(AbstractTransport.java:47)
>         at org.freedesktop.dbus.connections.transports.AbstractUnixTransport.<init>(AbstractUnixTransport.java:11)
>         at org.freedesktop.dbus.transport.jre.NativeUnixSocketTransport.<init>(NativeUnixSocketTransport.java:38)
>         at org.freedesktop.dbus.transport.jre.NativeTransportProvider.createTransport(NativeTransportProvider.java:22)
>         at org.freedesktop.dbus.connections.transports.TransportBuilder.build(TransportBuilder.java:334)
>         at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:154)
>         at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:351)
>         at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:136)
>         at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:214)
>         at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:160)
>         at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:340)
>         at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:277)
>         at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:131)
>         at org.asamk.signal.App.handleLocalCommand(App.java:252)
>         at org.asamk.signal.App.init(App.java:202)
>         at org.asamk.signal.Main.main(Main.java:53)

**Comment by ofn1** [comment]
This problem disappears (jdk keeps the new version of 17) if I rolled back the signal-cli to the old version, so it doesn’t look like a problem with jdk itself.

**Comment by AsamK** [comment]
signal-cli 0.10.0 uses the native java unix sockets, which don't support abstract unix sockets, which are Linux specific.
Which distribution are you using? You probably need to adapt your dbus server to use file based unix sockets.
https://openjdk.java.net/jeps/380

**Comment by ofn1** [comment]
I use Ubuntu 20.04 and get environment variables like this:
```
apt install dbus-x11
dbus-launch --sh-syntax > env.sh
. env.sh
signal-cli -u +17111111111 daemon
```

**Comment by ofn1** [comment]
> signal-cli 0.10.0 uses the native java unix sockets, which don't support abstract unix sockets, which are Linux specific. Which distribution are you using? You probably need to adapt your dbus server to use file based unix sockets. https://openjdk.java.net/jeps/380

Signal-cli for me now in abstract unix sockets which generated from dbus-x11 and distribution is ubuntu 20.04.
How can I use file based unix sockets? It seemd hard to google the answer.
I would be very grateful if you can provide some suggestions.

**Comment by AsamK** [comment]
You could either use the systemd provided dbus.socket file for the user session or system bus. Or start the dbus-daemon manually:
```sh
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$UID/test-dbus"
DBUS_SESSION_BUS_PID=$(dbus-daemon --fork --print-pid --session --address="$DBUS_SESSION_BUS_ADDRESS")
```

**Comment by lindes** [comment]
I know this is closed, but... It would be really nice if the default behavior of signal-cli was to do something that worked.  I haven't done anything at all manually with dbus, and I get this error as well... I'd rather not manually do dbus configuration if I don't have some other dbus-specific reason for doing so.  Is there the way this could be at the very least considered as a feature request to either have a default that works, or at least give a more useful error message?
