### ISSUE TITLE
Feature request: option to log DEBUG to file but INFO to stderr

### ISSUE THREAD

**Issue by technillogue** [AsamK/signal-cli#845]
I want to keep detailed logs, but not always get spammed with phone number formatting checks in large groups, etc. It would be great to log it to a file.

**Comment by AsamK** [comment]
Could maybe be implemented with a parameter for the --verbose flag, i.e. `--verbose=/var/log/signal-cli`.
Would need to check if the slf4j simplelogger supports this or if another logger would need to be added.
