### ISSUE TITLE
libsignal-client: Identity key is not trusted for remote address

### ISSUE THREAD

**Issue by exquo** [AsamK/signal-cli#849]
I have encountered this on signal-cli `v0.10.0`: trying to set `trust` for a contact with 

	signal-cli trust -a +1234567890

would not set the contact as trusted - sending the messages would still fail. Running the same command with `--verbose` printed

	...
	2021-12-25T11:00:00.000Z [main] WARN LibSignal - [libsignal-client]: rust/protocol/src/session_cipher.rs:99: Identity key d0f0ff00f00000000b00000fdb0e000e00e0bdff0be00f0c00f000dffd0f0c00 is not trusted for remote address 0d00fd00-e0d0-00ff-fce0-0d0000f00000.0

After messaging that contact from signal-desktop, I was able to send messages from signal-cli as well.

I can no longer invoke this reproducibly now, after signal-desktop has set the contact to "trusted". So, not sure how useful this report is, but maybe it contains some hints.

**Comment by exquo** [comment]
I've just had this happened with another contact. If there is something I can do to troubleshoot this before I set the contact to trusted through signal-desktop, please let me know.

To add to the above description: running the command

	signal-cli trust -a +1234567890

produces no output and the exit code is `0`, but the contact is not set to 'trusted'.

**Comment by AsamK** [comment]
I've had a look at the code and can't say how this could happen.
I've added some additional logging.
If you still (or again) have the issue, you can run the latest master with additional verbosity (`--verbose --verbose`) and post the log here.

**Comment by exquo** [comment]
Looks like I don't have other contacts exhibiting this, so can't currently reproduce it any more. Feel free to close this issue; it can be reopened if this reoccurs.

**Comment by AsamK** [comment]
Alright, thanks for the follow-up.
