### ISSUE TITLE
It is still possible to switch to staging server?

### ISSUE THREAD

**Issue by CrookedCrane** [AsamK/signal-cli#856]
There's an [old issue](https://github.com/AsamK/signal-cli/issues/193) back in 2019 stating that you can change a URL in `src/main/java/org/asamk/signal/manager/BaseConfig.java` to make signal-cli work with the staging server. However this file is currently deleted (by a refactor in the 2 years between then and now I presumed). 
It is still possible to make signal-cli work with staging server and how do I do it? I need it to register standalone device for Signal Desktop (the captcha on Signal Desktop's development branch so far is still scuffed)

**Comment by AsamK** [comment]
Yes, there's now a command line flag for it: `--service-environment=sandbox`
https://github.com/AsamK/signal-cli/blob/master/src/main/java/org/asamk/signal/App.java#L89
But it seems to be missing in the documentation ...

**Comment by CrookedCrane** [comment]
Work likes a charm, in hindsight it does appears in the help
