### ISSUE TITLE
Callback when messages are received

### ISSUE THREAD

**Issue by KY-7** [AsamK/signal-cli#858]
Happy new year!

Is it possible to provide a callback url as part of the registration process so that it can be called when messages are received?

The system using the signal-cli to send messages, would be notified automatically when some replies are received.
This avoids regularly calling signal-cli for eventual received messages.

Thanks!

**Comment by AsamK** [comment]
No, the signal servers don't provide that functionality.
To be notified of new messages the servers supports GCM/Firebase for Android, APNs for iOS and websocket connections for everything else.
In theory I guess you could use GCM to be notified of new messages. You'd need to implement the GCM client yourself and then add a small addition to signal-cli to set the GCM id on the Signal account.
Another solution would be to run signal-cli in daemon mode to have a persistent websocket connection listening for new messages.
