### ISSUE TITLE
Please improve dbus service wiki / help with dbus usage

### ISSUE THREAD

**Issue by kb100** [AsamK/signal-cli#86]
I'm interested in using the signal-cli dbus interface in my project https://github.com/kb100/signal-authenticator. Currently, my authenticator first calls signal-cli to receive messages (possible session resets, etc), and then calls signal-cli again to send a one-time token to the user trying to log in. This works great except that there appears to be a just-long-enough-to-be-annoying overhead in calling signal-cli. I think that the dbus interface can solve the issue: 

- have a long-running autostarted signal-cli daemon instance running as the signal-authenticator user

- send messages to the already running instance via signal-cli dbus.

For my application it is important that

- the long-lived signal-cli daemon is run as the signal-authenticator user, and this user is the only user that may send or receive information through the dbus

- the long-lived signal-cli daemon does not interfere with any other potential signal-cli instances or daemon's running on the system

Note that the signal-authenticator user is a system user that does not have a dbus session running by default, e.g. running `signal-cli -u $username daemon` as this user results in

    org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address
        at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:267)
        at org.asamk.signal.Main.handleCommands(Main.java:584)
        at org.asamk.signal.Main.main(Main.java:68)

I can at least get the daemon running with `dbus-run-session signal-cli -u $username daemon`.

From the C side, I just need to call signal-cli with the dbus option, but having never done anything with dbus before, I'm lost in figuring out how I can setup this long-lived signal-cli service with the desired properties. Could you perhaps comment on what would be the best way to do this and/or expand upon the dbus service wiki page?

**Comment by AsamK** [comment]
You can use the dbus system bus, with `signal-cli daemon --system` and `signal-cli --dbus-system send`. There's a description of which file you need to configure a dbus activated system service in the wiki https://github.com/AsamK/signal-cli/wiki/DBus-service. You can adapt the `org.asamk.Signal.conf` dbus config file to allow access only to the signal-authenticator user.
I've added a bit of explanation what the config files are needed for.

**Comment by kb100** [comment]
Added dbus feature to signal-authenticator, significant speedup. Thanks
