### ISSUE TITLE
Expose a way to retrieve a user profile avatar pic

### ISSUE THREAD

**Issue by idifrancesco** [AsamK/signal-cli#869]
I easily wrote by myself a new  `JsonRpcLocalCommand` calling: https://github.com/AsamK/signal-cli/blob/4ffb93129d4db8327c37f9383b55d5cd5b2f3ac9/lib/src/main/java/org/asamk/signal/manager/ManagerImpl.java#L319
to achieve the goal in the title.
However it could be useful that the feature be supported by developers.

**Comment by AsamK** [comment]
I've extended the `listContacts` command to include more profile information in json mode.
The avatar is not included there, but is just stored in the signal-cli config directory (`avatars/profile-NUMBER`).

In json-rpc mode would you just need the filename to the avatar or the actual avatar image in base64 encoding?

**Comment by idifrancesco** [comment]
Just filename only would be great.

**Comment by idifrancesco** [comment]
Calling `listContacts` with any `recipient` then retrieving the avatar file into `avatars/profile-NUMBER` directory is what i need. Thanks.
