### ISSUE TITLE
Sending messages with special characters

### ISSUE THREAD

**Issue by gean-xyz** [AsamK/signal-cli#871]
Hello,

I have the issue for sending messages in utf-8 with special characters like "ä", "ö", "ü" or "ß".
Tested with current version 0.10.2

`./signal-cli -u +43123456 send -m "Täst" +43234567`

![Capture](https://user-images.githubusercontent.com/30174236/151070219-1ad8e50c-8794-42ec-8fbb-992a92c1edbc.JPG)

Docker Image: debian:latest 

Docker environment variables:
`...
LANG=de_DE.UTF-8
LANGUAGE=de_DE.UTF-8
LC_ALL=de_DE.UTF-8
TZ=Europe/Vienna`

JRE Version: openjdk-17-jre-headless:amd64 17.0.2+8-1~deb11u1

Kind regards,
Gean

**Comment by AsamK** [comment]
The `LANG` variable looks ok, maybe something wrong with the outer terminal or the docker image.
What do you get when you do this:
```sh
$ echo Täst > test
$ file test

**Comment by gean-xyz** [comment]
Hmm.. also looks ok
```
# echo Täst > test
# file test
test: UTF-8 Unicode text
# cat test
Täst
#
```

**Comment by AsamK** [comment]
Dies piping the message work? Decoding from stdin is handled by signal-cli, decoding the commandline arguments is done by Java directly.

`echo Täst | ./signal-cli -u +43123456 send +43234567`

**Comment by gean-xyz** [comment]
Got the same result :-\  

![image](https://user-images.githubusercontent.com/30174236/151219569-168d74ae-4238-40b1-83bb-18ab1f1fe68b.png)

**Comment by AsamK** [comment]
hm, then you could try setting the java encoding explicitly, before calling signal-cli: `export JAVA_OPTS='-Dfile.encoding=UTF-8'`

**Comment by gean-xyz** [comment]
great! that worked! 
thank you very much!

**Comment by gean-xyz** [comment]
By the way.. now sending with decoding from stdin works, but not with the parameter "-m".

works:
```
echo Täst | ./signal-cli -u +43123456 send +43234567
```

same error as before (even with env parameter set)
```
./signal-cli -u +43123456 send -m "Täst" +43234567
```
