### ISSUE TITLE
GraalVM native build: register fails via JSON RPC

### ISSUE THREAD

**Issue by morph027** [AsamK/signal-cli#876]
Registering a new account fails using native GraalVM builds w/ JSON-RPC:

```
{'jsonrpc': '2.0', 'error': {'code': -32600, 'message': 'Failed to access RecordComponents of type `org.asamk.signal.commands.RegisterCommand$RegistrationParams`\n at [Source: UNKNOWN; byte offset: #UNKNOWN]', 'data': None}, 'id': '63674cdd-0d30-4233-95e0-41a7c83b30e5'}
```

It does work with JRE version.

**Comment by AsamK** [comment]
seems to be a bug in graalvm nativeimage: https://github.com/oracle/graal/issues/3984

**Comment by morph027** [comment]
Ah, thanks, forgot to have a look at GraalVM itself, thought it was something in the reflection config which i overlooked.

Not a big deal for now, as JRE versions runs fine and native version ist stil experimental ;)

Subscribed to the issue and will update this one if there's movement.

Have a nice weekend! :beers:
