### ISSUE TITLE
MessageReceivedV2 adds two non printable characters

### ISSUE THREAD

**Issue by c0llapsar** [AsamK/signal-cli#877]
Hi everyone,

First of all, thank you for the amazing work your doing with signal-cli.

I'm trying the new `MessageReceivedV2` added in f39983f78acf438049cd709c17ddb3e9ccefedef, and found out there are two non printable characters in the message at the mention location.

if a user send `**@someone**Test` in signal, where there is no space between `@someone` and Test, signal-cli will send the message like this: `[239 191 188 32 84 101 115 116]::￼ Test`

for comparison this is without mentions: `[84 101 115 116]::Test`

Is this intentional?

**Comment by AsamK** [comment]
That's a Unicode object replacement char. It's not added by signal-cli but by the sender of the message, signal-cli just passes it along.
The char is intended to be replaced with the mention text when displaying it to the user.
