### ISSUE TITLE
Man page behavior on failure and exit status specification needed

### ISSUE THREAD

**Issue by kb100** [AsamK/signal-cli#88]
For my signal-authenticator project, it is very important that signal-cli acts as I would think it would when something goes wrong. These seem obvious so forgive me, but can you confirm that:

1. If a Signal user gets a new key, signal-cli will refuse to send messages encrypted to the new key until the new key is marked trusted (manually).
2. In (1.) signal-cli exits with a nonzero exit status

Ideally the man page should include a section about how signal-cli behaves in some common failure modes such as this.

Also, exit statuses in these failure situations should be unique (and specified in the man page) so that one can programatically deal with the different error cases that might show up. In my situation, I want to be able to tell the user to contact their sysadmin if their 2FA failed because their new key is not yet trusted.

**Comment by AsamK** [comment]
1. yes, when the key has changed, no messages are encrypted or decrypted, until the key is manually marked as trusted

2. Currently signal-cli has three exit codes, 1 for invalid user input, 2 for unexpected errors, 3 for network and encryption errors
exit status 3 could be split to distinguish untrusted identity errors
