### ISSUE TITLE
DBusException: Connection ":1.10" is not allowed to own the service "org.asamk.Signal" due to security policies in the configuration file

### ISSUE THREAD

**Issue by jonowo** [AsamK/signal-cli#882]
| Thing | Version |
|---|---|
| Ubuntu (WSL 2) | 20.04 |
| OpenJDK | 17.0.1 |
| signal-cli | 0.10.3 |

I followed the instructions in the [README](https://github.com/AsamK/signal-cli#install-system-wide-on-linux) and the [DBus service wiki page](https://github.com/AsamK/signal-cli/wiki/DBus-service#System-bus) to install signal-cli. I linked an account and created a user `signal-cli`.

I also ran `export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket` to fix the error `Cannot Resolve Session Bus Address` raised when I ran `signal-cli -a [PHONE_NUMBER] daemon` the first time.

I encounter this error instead:
```
$ signal-cli -a [PHONE_NUMBER] daemon
INFO  DaemonCommand - Starting daemon in single-account mode for [PHONE_NUMBER]
ERROR DaemonCommand - Dbus command failed
org.freedesktop.dbus.exceptions.DBusException: Connection ":1.10" is not allowed to own the service "org.asamk.Signal" due to security policies in the configuration file
        at org.freedesktop.dbus.connections.impl.DBusConnection.requestBusName(DBusConnection.java:498)
        at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:348)
        at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:284)
        at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:132)
        at org.asamk.signal.App.handleLocalCommand(App.java:292)
        at org.asamk.signal.App.init(App.java:211)
        at org.asamk.signal.Main.main(Main.java:58)
Dbus command failed
```

Not sure what configuration file it is referring to, but I don't see any config related to security policies in `~/.local/share/signal-cli/data`.

On a fresh installation of the same machine I ran [this script](https://gist.github.com/jonowo/b33c9c41fa3ca1776cf3420c6cf4c360) instead of manually installing `signal-cli`. I also got the error above when I ran `signal-cli daemon`. However, `signal-cli --dbus-system send -m "test" [PHONE_NUMBER]` was successful on this machine, but failed with `No local users found, you first need to register or link an account` on the previous one.

On both machines, I was able to send messages using `signal-cli -a [PHONE_NUMBER] send -m "message" [PHONE_NUMBER]` and receive messages using `signal-cli receive`.

**Comment by AsamK** [comment]
You're pointing the dbus **session** bus address to the system dbus socket. To use the system bus, you need to give the signal-cli user permission, the example files mentioned in the wiki can be found here: https://github.com/AsamK/signal-cli/tree/master/data
Alternatively you can use a session bus, if none is running you can start one prior to running signa-cli: https://github.com/AsamK/signal-cli/issues/837#issuecomment-999447092

> On a fresh installation of the same machine I ran [this script](https://gist.github.com/jonowo/b33c9c41fa3ca1776cf3420c6cf4c360) instead of manually installing signal-cli. I also got the error above when I ran signal-cli daemon. However, signal-cli --dbus-system send -m "test" [PHONE_NUMBER] was successful on this machine, but failed with No local users found, you first need to register or link an account on the previous one.

The script you link to already installs a system wide signal-cli service and starts it.
On you're previous one you may have to use `signal-cli --dbus-system -a ACCOUNT_NUMBER send`, that depends on whether the daemon was started with an `-a` account parameter or not.
