### ISSUE TITLE
sendTyping JSONRPC

### ISSUE THREAD

**Issue by cacko** [AsamK/signal-cli#883]
does the sendTyping works on jsonrpc, or it is just me that can't figure it out.

so I have a daemon running on some socket let's say /signal/test, to which I send jsons, send works fine, sendTyping though doesn't seem to do anything for me:
`                  { "jsonrpc": "2.0",
                    "method": "sendTyping",
                    "id": uuid4().hex,
                    "params": message_params,}`

an example json I'm sending in params there is `"groupId": receiver`

as I said, send is working fine, so ... am I doing it wrong or it is just not supported.

thanks

using: 0.10.3 on
`[    0.000000] Linux version 5.10.94-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1518 SMP PREEMPT Thu Jan 27 14:55:19 GMT 2022
[    0.000000] random: fast init done
[    0.000000] Machine model: Raspberry Pi 4 Model B Rev 1.4`

if that matters with `openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Debian-1deb11u1, mixed mode, sharing)`

**Comment by AsamK** [comment]
Yes, sendTyping command should work.
```json
{"jsonrpc":"2.0","id":"id","method":"sendTyping","params":{"groupId":"BASE64_ID"}}
```
