### ISSUE TITLE
0.10.3 listNumbers not even listed as DBUS command?

### ISSUE THREAD

**Issue by rotdrop** [AsamK/signal-cli#891]
Hi,

I have setup signal-cli with (system-)DBUS and can receive messages and send messages out. So that basic setup seems to work.

If I try to use `listNumbers` via DBUS as replacement for the unimplemented `listContacts` I receive the following error message:
```
signal-cli@mail:~$ signal-cli -a +XXXXX  --dbus-system listNumbers
usage: signal-cli [-h] [-v] [--verbose] [--log-file LOG_FILE] [-c CONFIG] [-a ACCOUNT]
                  [-o {plain-text,json}] [--service-environment {live,staging,sandbox}]
                  [--trust-new-identities {always,on-first-use,never}] [--dbus |
                  --dbus-system]
                  {addDevice,block,daemon,getUserStatus,joinGroup,jsonRpc,link,listAccounts,listContacts,listDevices,listGroups,listIdentities,listStickerPacks,quitGroup,receive,register,remoteDelete,removeContact,removeDevice,removePin,send,sendContacts,sendReaction,sendReceipt,sendSyncRequest,sendTyping,setPin,submitRateLimitChallenge,trust,unblock,unregister,updateAccount,updateConfiguration,updateContact,updateGroup,updateProfile,uploadStickerPack,verify}
                  ...
signal-cli:  error:  invalid  choice:  'listNumbers'  (choose  from  'addDevice',  'block',
'daemon', 'getUserStatus', 'joinGroup', 'jsonRpc',  'link', 'listAccounts', 'listContacts',
'listDevices', 'listGroups', 'listIdentities',  'listStickerPacks', 'quitGroup', 'receive',
'register',   'remoteDelete',   'removeContact',   'removeDevice',   'removePin',   'send',
'sendContacts', 'sendReaction', 'sendReceipt',  'sendSyncRequest',  'sendTyping', 'setPin',
'submitRateLimitChallenge',    'trust',    'unblock',     'unregister',    'updateAccount',
'updateConfiguration',       'updateContact',        'updateGroup',        'updateProfile',
'uploadStickerPack', 'verify')
```
It is indeed v0.10.3:
```
signal-cli@mail:~$ signal-cli --version
signal-cli 0.10.3
```

Is this expected (and hence a bug in the documentation) or am I doing something wrong?

**Comment by AsamK** [comment]
`listNumbers` is only available as a method on the DBUS object, not as a cli command.
In the next version the `listContacts` command will work at least in a minimal fashion.

**Comment by rotdrop** [comment]
Thank you for the quick reply! Actually, I thought that `signal-cli --dbus-...` would simply forward everything to `dbus-send` or something similar. Using `dbus-send` I get the behaviour described in the feature-matrix. It is maybe a little bit unclear from the documentation that you get not the full set of commands described in the feature-matrix when using the `--dbus...' switches.

Nice program. I just hacked singalmail to make it work again and forward some traffic to a mailing list :)
