### ISSUE TITLE
How to save user messages and other info from logs

### ISSUE THREAD

**Issue by elveegit** [AsamK/signal-cli#895]
Hello!
Thanks a lot for the development this library!

I dont understand the principle of saving messages with using Dbus. In console, i see logs, where I can see who sent the message, who authorized and else...
But... How do I save messages and other logs, or how do I access them so that I can keep a history of communication.

I am trying to make a chat application using python

Sorry for my bad english. Thanks!

**Comment by AsamK** [comment]
You can connect to the dbus service and register a listener for the MessageReceived event.
There are also some examples on the wiki: https://github.com/AsamK/signal-cli/wiki
