### ISSUE TITLE
continously receive mode is enable in daemon mode

### ISSUE THREAD

**Issue by rdtech2020** [AsamK/signal-cli#899]
I did set up signal-cli in daemon. but after register account, continously receive command are executing. how to stop it.
I tried with ```signal-cli --config /var/lib/signal-cli -u +xxxxxxx receive -t -1```
but I am getting --> INFO  SignalAccount - Config file is in use by another instance, waiting…

**Comment by AsamK** [comment]
Running two signal-cli instances at the same time is not possible.
When running the signal-cli daemon, you can receive messages via dbus or the json-rpc socket.
For dbus you can e.g. run `signal-cli --dbus receive -t-1`

**Comment by rdtech2020** [comment]
thanks
