### ISSUE TITLE
javax.net.ssl.SSLException: java.security.ProviderException: Could not derive key

### ISSUE THREAD

**Issue by dieterhatnkleinen** [AsamK/signal-cli#9]
Im having the same issue on multiple devices:
`javax.net.ssl.SSLException: java.security.ProviderException: Could not derive key`

OpenJDK seemed to fix it, but I dont want to use openjdk, it performs a lot worse than oracle and I have multiple java projects running

**Comment by nrizzio** [comment]
Try using JDK 7. JDK 8 isn't working for some people.

**Comment by AsamK** [comment]
Please try again, it seems the used spongycastle library in combination with oracle jdk had problems with some SSL connections. I switched to the original bouncycastle library now, which works here.
