### ISSUE TITLE
isRegistered takes 0 positional argument

### ISSUE THREAD

**Issue by elveegit** [AsamK/signal-cli#903]
Hello!
I see this error when i check if user is registered.
`TypeError: org.asamk.Signal.isRegistered takes 0 positional argument(s) but 1 was/were given`

I use dbus with python.
`signal = bus.get('org.asamk.Signal', object_path='/org/asamk/Signal/' + account)`
`status = signal.isRegistered(phone)`
`if status is True:`
                `signal.sendMessage(self.message['message'], self.message['photos'], phone)`

How can i use this command?

**Comment by bublath** [comment]
Are you sure "phone" is interpreted as a string? (not sure how Python handles that)
isRegistered exists in 3 variants - no arguments, string argument and list of strings.
The error message looks like it got matched against isRegistered() instead of isRegistered(string)

**Comment by AsamK** [comment]
You probably need to specify the method signature manually, to select one of the 3 variants.

See also https://github.com/AsamK/signal-cli/issues/807#issuecomment-1003523909
