### ISSUE TITLE
Broken Unicode characters in contact names

### ISSUE THREAD

**Issue by panzi** [AsamK/signal-cli#904]
My last name is Panzenböck, though when I use the D-BUS method `getContactName` on my Signal account I get `Panzenb��ck`. And `recipients-store` actually also really contains my name in that broken encoding.

I suspect somewhere in the code where the contact name is read it is erroneously interpreted as ASCII even though it is UTF-8 (where ö is encoded in two bytes). Thus the "illegal" character values are replaced with the Unicode replacement character (U+FFFD).

(Normal messages containing ö and similar work fine.)

signal-cli version: 0.10.4
OS: Fedora Linux 33 x86_64

**Comment by panzi** [comment]
I tried to find where in the code this is handled, but couldn't. It seems to be done in `org.whispersystems.signalservice.api.services.ProfileService`, but I couldn't find where this class is defined or how the contact name string is parsed from the transfer encoding.

**Comment by AsamK** [comment]
UTF-8 characters should just work, maybe java uses the wrong encoding (wrong LANG env variable)?
you can check the java encoding with this command:
`java -XshowSettings:properties -version 2>&1 | grep encoding`

**Comment by panzi** [comment]
That gives me this output:
```bash
$ java -XshowSettings:properties -version 2>&1 | grep encoding
    file.encoding = UTF-8
    sun.io.unicode.encoding = UnicodeLittle
    sun.jnu.encoding = UTF-8
```

**Comment by AsamK** [comment]
That looks correct. Did you set the contact name with the `updateContact` command or was it synced from the linked main device?

**Comment by AsamK** [comment]
In can reproduce this, but only when the signal-cli is running with a non-UTF-8 locale (like LANG=en_US).
I assume at some point your locale was set to a non UTF-8 one. I'd suggest setting the name again.

**Comment by panzi** [comment]
Setting the name again? Since it's the name of a contact and not the name of the bot, which files can I safely delete for signal-cli to reaquire the name?-------- Originalnachricht --------Betreff: Re: [AsamK/signal-cli] Broken Unicode characters in contact names (Issue #904)Von: Sebastian Scheibner An: AsamK/signal-cli Cc: Mathias Panzenböck ,Author 
In can reproduce this, but only when the signal-cli is running with a non-UTF-8 locale (like LANG=en_US).
I assume at some point your locale was set to a non UTF-8 one. I'd suggest setting the name again.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/AsamK/signal-cli/issues/904#issuecomment-1138574830",
"url": "https://github.com/AsamK/signal-cli/issues/904#issuecomment-1138574830",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AsamK** [comment]
If your signal-cli instance is a linked device, you can use the `sendSyncRequest` command to request the contacts list again from the primary device. Otherwise use the `updateContact` command.
