### ISSUE TITLE
[Upgrade from 0.10.3 to 0.10.4 and 0.10.4.1] Error from Main Device on Regularly executed `receive` Command

### ISSUE THREAD

**Issue by rfrederick** [AsamK/signal-cli#905]
Environment: A signal-cli install as the "main" device with another signal-cli install (same version) as a linked device

After upgrading both installs from 0.10.3 to either 0.10.4 or 0.10.4.1 the following error is observed when the "main" device runs its `receive` command via cron:

WARN  SendHelper - Failed to send message due to IO exception: Unsupported sync message!

The "main" device and the linked device are set to run the `receive` command every five minutes, with the linked device configured to run `receive` one minute after the "main" device.

**Comment by AsamK** [comment]
Thanks for reporting, this warning can be safely ignored for now.
It appears, when signal-cli attempts to send the new PNI identity to linked devices. The PNI identity sync message implementation in libsignal-service is not complete yet. This also affects Signal-Android and I assume it will be fixed when they continue with the PNI implementation.

**Comment by AsamK** [comment]
Fixed in d27a12a6cfcf9afca362a8d359ee808b1507e0b3
