### ISSUE TITLE
captcha format changed, no longer works?

### ISSUE THREAD

**Issue by islandtrail** [AsamK/signal-cli#906]
Hi everyone,

I'm unable to register. After successfully completing a CAPTCHA in a browser, and copying the `signalcaptcha://...` URL from the console, I get 'Invalid captcha given' when including it in the signal-cli command.

I notice that the format of the `signalcaptcha://` URL has changed.

It used to be something like `signalcaptcha://<long string that looks like base64>`

Now it is more like:
`signalcaptcha://signal-recaptcha-v2.<first short string of characters>.registration.<second much longer string of characters>`
...and I notice that the first of these strings is always the same across all my attempts to make it work. I also notice that the second string usually includes not just underscores but also hyphens.

Suggestions:
1) are the hyphens mucking up the parsing of the `--captcha` parameter from the command line?
2) have signal changed the format of their captcha strings, so that I should include a different set of characters instead of everything after `signalcaptcha://` as I've been doing?
3) have signal switched to a different version of captcha that requires a different set of options to be submitted when sending the token, and signal-cli is still sending the old options?

Things I've tried:
1) Looking the latest Signal-android code. As far as I can tell from a very quick look, it still seems to be treating everything after `signalcaptcha://` as the 'token'.
2) Getting the captcha from `https://signalcaptchas.org/challenge/generate.html` instead of `https://signalcaptchas.org/registration/generate.html`. The result is that I get a token in which the word `registration` has been replaced with `challenge`. But they still don't work! I still get 'Invalid captcha'.
3) Passing the command line parameter using `--captcha="tokengoeshere"` instead of `--captcha tokengoeshere`
Doesn't seem to make a difference.
4) Treating everything after the string `registration.` (ie after the full stop) as the token. Result: I get http error 400 (bad request).

Can someone help?

Even just knowing whether others are seeing the same problem or are still able to register using the old method (ie passing everything after `signalcaptcha://` using the  `--captcha TOKEN`) would help!

Do I need to make sure I'm using the latest signal-cli? Have there been relevant changes in the last few months?

**Comment by islandtrail** [comment]
OK, I can confirm I've now tried this with the latest version of signal-cli (0.10.4.1) and still have this problem.

I was really hoping that upgrading to latest version would solve it :(

Every single time I get 'Invalid captcha given', even when it's only taken me seconds to transfer the token to the command line.

I should mention that I'm using Tor, temporarily fixing the exit node for both the browser that I use to solve the reCAPTCHA, and for signal-cli, so that Signal's servers will see the same IP throughout.

This is a method that HAS worked fine for me in the past, as recently as Dec 2021.

Can someone confirm whether registration captcha handling is still working fine in signal-cli? And whether it's still working for folks registering via Tor?

Any help or feedback really appreciated!

**Comment by AsamK** [comment]
The new captcha format is still working for me.
`register --captcha 'signal-recaptcha-v2.6XXX.registration.XXX'

**Comment by islandtrail** [comment]
Thanks, that proves it isn't just me including the wrong bit of the string or something similar.

I've tried again, this time using single quotes on the command line as you did above. Still doesn't work. I made 3 or 4 attempts, got the same 'Invalid captcha given' message every time.

Any advice for how I can debug this further? Tried passing verbose flag but didn't get any extra info back.

When I have a chance I will also try again with a much wider variety of exit nodes, in case Signal has decided to completely refuse/invalidate all reCAPTCHAs from certain exits, even when they have been filled out correctly. But that will be time consuming and frustrating so I'm not able to fit it in today.

**Comment by AsamK** [comment]
From signal-cli side there's not much to debug, either the server accepts the captcha or it doesn't.
You could take a look at the signal server source code to see if they do any additional validation there ...

**Comment by suciokhan** [comment]
This is giving me a headache as well. According to the quickstart guide (https://github.com/AsamK/signal-cli/wiki/Quickstart) there is no mention of a captcha for registration.

When I go to the captcha link, it wants to open up my Signal desktop app, and it doesn't give me any token. Then when I force it to open using firefox, it gives me a token but when I put it in, it says `Invalid captcha given`.

Please update the quickstart guide.

**Comment by AsamK** [comment]
It's a wiki, feel free to update the guide with your experiences :)
