### ISSUE TITLE
Better handling of decryption errors and finger print verification

### ISSUE THREAD

**Issue by kbin76** [AsamK/signal-cli#91]
When a contact has new encryption keys (eg. because of reinstall) and messages are received from that person without trust having been "updated", the json error message looks like this with nothing indicating what the actual error was (decryption failure):

> {"error":{"message":null},"type":"message","envelope":{"source":"+1234","sourceDevice":1,"relay":null,"timestamp":1498116750564,"timestampISO":"2017-06-22T07:32:30.564Z","isReceipt":false,"dataMessage":null,"syncMessage":null,"callMessage":null}}

Textual output from "receive" command at least says (so obviously it is possible to determine the actual cause of the decryption failure):

> Envelope from: +1234 (device: 1)
> Timestamp: 1498116835060 (2017-06-22T07:33:55.060Z)
> The user’s key is untrusted, either the user has reinstalled Signal or a third party sent this message.
> Use 'signal-cli -u +4567 listIdentities -n +1234', verify the key and run 'signal-cli -u +4567 trust -v "FINGER_PRINT" +1234' to mark it as trusted
> If you don't care about security, use 'signal-cli -u +4567 trust -a +1234' to trust it without verification
> Failed to decrypt message.

Also, in both cases it would be good if the actual key fingerprint of the keys of the incoming message could be printed, otherwise it is hard to use the "-v FINGER_PRINT" option? (or am I missing something)

  --Kalle

**Comment by AsamK** [comment]
Yes, that should be added to the json output. You can use the `listIdentities` identities command with `-n NUMBER` to view the fingerprint/safety number.
