### ISSUE TITLE
libsignal-client issue

### ISSUE THREAD

**Issue by bavtan** [AsamK/signal-cli#917]
Hello,

I did recently installed v0.10.4.2  but keep getting the below error even though i changed the /opt/signal-cli-0.10.4.2//lib/signal-client-java-*.jar with libsignal_jni.so-v0.12.3  ( i did compiled myself and also tried the one under https://github.com/exquo/signal-libs-build/releases/tag/libsignal-client_v0.12.3 but same result still says missing) 

`WARN  ServiceConfig - Failed to call libsignal-client: /tmp/resource15116117356455579488.so: /tmp/resource15116117356455579488.so: failed to map segment from shared object
Missing required native library dependency: libsignal-client`

System info:
```
x86_64
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by derogab** [comment]
I have the same problem.

**Comment by AsamK** [comment]
libsignal-client extracts the native library to the temp directory and then tries to open it. Looks like this isn't working on your machine, you could check the /tmp mount options, if those contain `noexec`, which would be a problem.
Alternatively you could try to remove the native library from the jar file and instead put it into `/usr/lib`, which libsignal-client will use as a fallback.

**Comment by bavtan** [comment]
> libsignal-client extracts the native library to the temp directory and then tries to open it. Looks like this isn't working on your machine, you could check the /tmp mount options, if those contain `noexec`, which would be a problem. Alternatively you could try to remove the native library from the jar file and instead put it into `/usr/lib`, which libsignal-client will use as a fallback.

Hello, thanks for fast reply, yes indeed /tmp was locked so i removed the original jar file and put the modified one to /usr/lib now i get this errors:

```
java.lang.NoClassDefFoundError: org/signal/client/internal/Native
        at org.asamk.signal.manager.config.ServiceConfig.isSignalClientAvailable(ServiceConfig.java:51)
        at org.asamk.signal.App.init(App.java:144)
        at org.asamk.signal.Main.main(Main.java:58)
Caused by: java.lang.ClassNotFoundException: org.signal.client.internal.Native
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 3 more
```

**Comment by AsamK** [comment]
Ah, the jar file needs to stay where it was, so java can still find the class files. Instead you need to delete the .so file from the jar file and instead put the .so file into /usr/lib

**Comment by octopode-us** [comment]
Hello I have almost the same problem except I am on Windows 10 x64, and my error says exactly : 

WARN  ServiceConfig - Failed to call libsignal-client: C:\Users\arthu\AppData\Local\Temp\resource16959984520170724752.so: Can't load this .dll (machine code=0x0) on a AMD 64-bit platform
Missing required native library dependency: libsignal-client

I used the 10.4.2 version for a while, until I had an issue with the "device link failed" at the last step (linking with QR code link to my computer). I then get the latest version 10.5 but ran into this new issue I didn't experimented before.

Thanks a lot for all your work!

**Comment by bavtan** [comment]
> Hello I have almost the same problem except I am on Windows 10 x64, and my error says exactly :
> 
> WARN ServiceConfig - Failed to call libsignal-client: C:\Users\arthu\AppData\Local\Temp\resource16959984520170724752.so: Can't load this .dll (machine code=0x0) on a AMD 64-bit platform Missing required native library dependency: libsignal-client
> 
> I used the 10.4.2 version for a while, until I had an issue with the "device link failed" at the last step (linking with QR code link to my computer). I then get the latest version 10.5 but ran into this new issue I didn't experiment with before.
> 
> Thanks a lot for all your work!

For me /tmp was locked so after mounting it properly everything was ok, just make sure you properly replaced the .so file for v 10.5 and /tmp is accessible,
