### ISSUE TITLE
libsignal-client v0.15.x incompatible with signal-cli v0.10.4.2

### ISSUE THREAD

**Issue by vaporwave9** [AsamK/signal-cli#918]
```
WARN  ServiceConfig - Failed to call libsignal-client: 'void org.signal.client.internal.Native.Logger_Initialize(int, java.lang.Class)'
Missing required native library dependency: libsignal-client
```

Had to use ```libsignal-0.14.0```, did not test ```libsignal-0.15.0``` but ```libsignal-0.15.1``` did definitely not work. I am on armhf and built with rust nightly.

Probably a major change on their end. [They admit breakage.](https://github.com/signalapp/libsignal/releases/tag/v0.15.0)

**Comment by AsamK** [comment]
Not a signal-cli issue, I'll have to wait for Signal-Android to update to the new version.

**Comment by vaporwave9** [comment]
No problem, I don't really know Java and where the renamed artifacts and packages have to be updated.
Have a great weekend, enjoy your CLI package lots over kdbus!
