### ISSUE TITLE
Support replies/quotes

### ISSUE THREAD

**Issue by gediminasel** [AsamK/signal-cli#919]
Add an optional parameter to `sendMessage` and `sendGroupMessage` methods specifying a message id to quote.

The resulting message should be displayed like this in the Signal-Desktop client:
![image](https://user-images.githubusercontent.com/21194519/160136770-bf3041b4-cd07-4d0f-a42f-8328fff8a3ab.png)

**Comment by AsamK** [comment]
duplicate of #875
