### ISSUE TITLE
Change fingerprint to safety numbers

### ISSUE THREAD

**Issue by kb100** [AsamK/signal-cli#92]
For some time it has not been possible anymore to view your fingerprint in Signal-Android. Only a safety number for a given conversation can be viewed in the app now. Therefore the signal-cli verify command should be updated accordingly.

**Comment by AsamK** [comment]
signal-cli already understands the safety numbers, the `listIdentities` command also displays them. But you're right, the fingerprint should be renamed to safety number in the output.
