### ISSUE TITLE
Supports attachment filenames with non-ascii characters

### ISSUE THREAD

**Issue by 5139** [AsamK/signal-cli#922]
Hi,

After signal-cli upgraded from v0.9.2 to v0.10.4.2, I found that attachments no longer support filenames with non-ascii characters. 
test:

files exists:
```
root@server:~# ls -l /root/测试.txt
-rw-r--r-- 1 root root 5 Apr  3 11:44 /root/测试.txt
root@server:~# ls -l /root/test.txt
-rw-r--r-- 1 root root 5 Apr  3 11:46 /root/test.txt
```

This command will succeed on both versions:
```
dbus-send --session --type=method_call --print-reply --dest='org.asamk.Signal' /org/asamk/Signal org.asamk.Signal.sendMessage string:test array:string:/root/test.txt array:string:+12341111111
method return time=1649127143.43544 sender=:1.0 -> destination=:1.6 serial=16 reply_serial=2
   int64 1649127143437
```

Only In v0.9.2 this command will succeed. Failed in v0.10.4.2:
```
dbus-send --session --type=method_call --print-reply --dest='org.asamk.Signal' /org/asamk/Signal org.asamk.Signal.sendMessage string:test array:string:/root/测试.txt array:string:+12341111111
Error org.asamk.Signal.Error.AttachmentInvalid: Invalid attachment: /root/测试.txt: /root/测试.txt (No such file or directory)
```

Can the attachments support filenames with non-ascii characters again?

**Comment by AsamK** [comment]
UTF-8 characters should still work, maybe java uses the wrong encoding (wrong `LANG` env variable)?
you can check the java encoding with this command:

`java -XshowSettings:properties -version 2>&1 | grep encoding`

**Comment by 5139** [comment]
looks like no problem:

```
root@server:~# java -XshowSettings:properties -version 2>&1 | grep encoding
    file.encoding = UTF-8
    native.encoding = UTF-8
    sun.io.unicode.encoding = UnicodeLittle
    sun.jnu.encoding = UTF-8

root@server:~# cat /etc/default/locale
LANG="en_US.UTF-8"
```

**Comment by AsamK** [comment]
In can reproduce this, but only when the `signal-cli daemon` command is running with a non-UTF-8 locale (like `LANG=en_US`).
In that case signal-cli can't find the file because java converts it to `??`.
Maybe the dbus-java library used in older signal-cli versions behaved differently ... but the current behavior looks correct.
Please check that the signal-cli service itself is running with the correct locale.
