### ISSUE TITLE
deleteGroup (via DBus) can leave group in inconsistent state

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#924]
I have been playing around a bit in implementing the new group methods in my program.
One thing I tried:
- create a group via signal-cli
- add my mobile as an additional member
- delete the group via signal-cli

As a result, my mobile was still member of that group and also showing signal-cli as a member, while in signal-cli the group was gone somehow (no longer listed in the groups interface, though I believe it later reappeared. I created the same group with the same name again, and ended up having two identical groups on my mobile). 
I believe the deleteGroup should either automatically remove all members before deleting or block the deletion if it still has members.

**Comment by AsamK** [comment]
Indeed deleteGroup just deletes the local group information. For actually leaving the group, the `quitGroup` method needs to be called first.
I think it would make sense for the deleteGroup method to return an error in case the user is still a member of the group.
