### ISSUE TITLE
Error (failed to send) when using updateGroup to create new group via Dbus

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#925]
Reproducer:
dbus-send --system --dest=org.asamk.Signal --type=method_call --print-reply /org/asamk/Signal/_49xxxx org.asamk.Signal.updateGroup array:byte: string:newone array:string: string:
Error org.asamk.Signal.Error.Failure: Failure: Failed to send message:

The group "newone" however is created and usable.

**Comment by bublath** [comment]
Further experimenting: it also happens with the createGroup method
It however does not happen, when members are added right away

**Comment by AsamK** [comment]
Thanks for reporting!
There was a small bug in the code which checks if there was a send failure. It only affected the dbus interface.
