### ISSUE TITLE
Failed to send message due to untrusted identities

### ISSUE THREAD

**Issue by jarrah31** [AsamK/signal-cli#927]
I recently had to restore my iPhone which resulted in me having to re-register the signal app. Signal-cli is associated with my landline, so now when I try to send a message to the iPhone, it gives the following error:
```
signal-api@signal:/$ signal-cli --config /home/.local/share/signal-cli --output json -a +0123456789 send -m "This is a message" +987654321
{"results":[{"recipientAddress":{"uuid":"removed","number":"+987654321"},"type":"IDENTITY_FAILURE"}],"timestamp":1649268636461}
Failed to send message due to untrusted identities
```
When I run the `listIdentities` command, my iPhone shows up as:
```
"trustLevel": "UNTRUSTED",
```
How do I remove the existing identity so that I can start sending messages to the phone again please?

I'm running signal-cli 0.10.4.1

**Comment by AsamK** [comment]
you can trust the new identity with the `trust` command

**Comment by jarrah31** [comment]
Hi @AsamK, thanks for pointing me in the right direction. Looking at the wiki it seems this is the command to run, but what is the SAFETEY_NUMBER please? Is this a number on my iPhone Signal app somewhere? I've searched through the repository but can't find any definition for it.
`signal-cli -u USERNAME trust -v SAFETEY_NUMBER NUMBER`
Thanks.

**Comment by jarrah31** [comment]
aha, found it: https://support.signal.org/hc/en-us/articles/360007060632-What-is-a-safety-number-and-why-do-I-see-that-it-changed-
