### ISSUE TITLE
daemon mode should support --json option

### ISSUE THREAD

**Issue by kb100** [AsamK/signal-cli#93]
Currently, json output can only be achieved with a receive command, but it seems natural that the same option be available when in daemon mode.

**Comment by kbin76** [comment]
I've made a fork that perhaps accomplished what you're looking for ("JSON API"):
https://github.com/kbin76/signal-cli

It starts a loop and receives messages and spits out JSON on stdout. It also listens for JSON objects on stdin, so it's also possible to send messages using the same method. Note, it can't be combined with dbus. 

some (sparse) docs on this:
https://github.com/kbin76/signal-cli/blob/master/README.jsonevtloop.txt

I've already submitted a pull request with this...

**Comment by Riamse** [comment]
issue #127

**Comment by AsamK** [comment]
implemented in  #128
