### ISSUE TITLE
Error linking Signal-Desktop to signal-cli master

### ISSUE THREAD

**Issue by obraunsdorf** [AsamK/signal-cli#930]
I can start Signal-Desktop, get a QR-Code (respectively the URL behind the QR code) and then use `signal-cli -u <NUMBER> addDevice --uri "sgnl://..." to link the Signal-Desktop as a secondary device to my signal-cli master instance.
Signal Deskop shows that linking was successful and prompts for a device name. If I enter the device name and klick "finish linking", Signal Desktop shows "Synchronizing Contacts and Groups" for approx. 1 second and then "An unexpected error has occured".
Is this a known problem? I do not have any contacts configured for signal-cli on my bare Linux device. Is there some config file I need to change before adding a new device? 

Tested for Signal-Desktop on Windows and Linux and signal-cli on Linux

**Comment by AsamK** [comment]
Not a known problem. Maybe the Signal-Desktop debug log has more information: View -> Debug log

**Comment by obraunsdorf** [comment]
Same for me, the debug log of Signal-Desktop does not show any error.

**Comment by AsamK** [comment]
I guess this is the error:
> INFO  2022-04-11T17:11:28.460Z PUT (REST) https://chat.signal.org/v2/keys?identity=pni
INFO  2022-04-11T17:11:28.745Z PUT (REST) https://chat.signal.org/v2/keys?identity=aci 204 Success
INFO  2022-04-11T17:11:28.746Z AccountManager.confirmKeys(ACI): confirming key 1
ERROR 2022-04-11T17:11:29.056Z PUT (REST) https://chat.signal.org/v2/keys?identity=pni 403 Error
INFO  2022-04-11T17:11:29.057Z WebAPI: finishing registration
ERROR 2022-04-11T17:11:29.058Z account.registerSecondDevice: got an error HTTPError: promiseAjax: error response; code: 403

Will check what signal-cli needs to do differently here.

**Comment by obraunsdorf** [comment]
works like a charm! thank you very much for being so responsive :)

**Comment by k4rst3ns** [comment]
Thanks from my side as well :) That was super fast.
It didn't sync my contacts and groups ^^'
But I guess this is a different issue.

**Comment by octopode-us** [comment]
Hey, sorry my question might be dumb, but I have the exact same issue and I didn't get how I could fix it here... What is the manipulation you guys dide exactly?

Thanks a lot
