### ISSUE TITLE
cl switch to suppress INFO on send

### ISSUE THREAD

**Issue by GuidoBo** [AsamK/signal-cli#932]
Hello!
Sending works as expected, but: before I get the id of the message sent I am (sometimes) getting this:
"INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received."
I am in deed aware of this. How do I suppress this message?

**Comment by AsamK** [comment]
That message is only shown for accounts, that have never attempted to receive messages. It doesn't appear sporadically.
It can be suppressed by running the `receive` command.
You could also redirect stderr, to only see the timestamp: `signal-cli ... 2>/dev/nulll`
