### ISSUE TITLE
WARN Manager - Message action failed

### ISSUE THREAD

**Issue by PhilipMott** [AsamK/signal-cli#936]
Hi,

I've been using signal-cli for a while now without any problems, but upon updating the Signal Desktop app it then failed to reload successfully (the app didn’t even get as far as the modal appearing), and instead I ended up with a Signal process thread stuck on 100% CPU usage.  I checked the version number at the time in the About modal, and it said 5.37.0 (1).  When I ran the signal-cli daemon it displayed a series of messages like the following:

```
WARN Manager - Message action failed.
org.asamk.signal.manager.UntrustedIdentityException: Untrusted identity: bb3cdc2f-91f6-42b8-bfac-a47041d8191b
	at org.asamk.signal.manager.helper.SendHelper.sendRetryReceipt(SendHelper.java:175)
	at org.asamk.signal.manager.actions.SendRetryMessageRequestAction.execute(SendRetryMessageRequestAction.java:53)
	at org.asamk.signal.manager.Manager.handleQueuedActions(Manager.java:947)
	at org.asamk.signal.manager.Manager.receiveMessages(Manager.java:885)
	at org.asamk.signal.commands.DaemonCommand.lambda$run$1(DaemonCommand.java:133)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I tried restarting my laptop and reinstalling the desktop app, but that didn't help.  I even tried installing older versions of the app, and that didn't help initially, but then after trying a significantly older version I got a warning along the lines of "incompatible database - are you using an old version of Signal?", and when I then tried installing the latest version it magically worked...  All of which didn't make much sense, but I was just glad that it was working again and left it at that - however I did notice that the version number was now 5.37.0, not 5.37.0 (1), so I wondered whether the (1) bit meant that something had gone wrong with the update.

Anyway, that was a couple of weeks ago.  Today, I updated the desktop app again (I had updated it successfully in-between), and I ran into the same issue with the same warning from the signal-cli daemon.  This time, the new version number was 5.39.0 (1), so the (1) was there again.  The workaround I used last time of trying to install a sufficiently old version to generate a database compatibility error and then reinstalling the latest version worked again this time, and the (1) has now disappeared from the version number.

Are you able to help me understand the meaning of these signal-cli warnings and how to resolve them properly?  I'm using signal-cli 0.10.4.2 on macOS 12.3.1.

Many thanks,

Philip

**Comment by AsamK** [comment]
No idea what's wrong with Signal-Desktop.
The signal-cli warning above is from a recipient that has changed safety numbers.
You can see the identity with `listIdentities -n bb3cdc2f-91f6-42b8-bfac-a47041d8191b` and change the trust level with the `trust` command.
