### ISSUE TITLE
Do not include the release number in the release files

### ISSUE THREAD

**Issue by KingUdo** [AsamK/signal-cli#937]
Hi,
I really like the project and have included it in multiple of my on projects. Most of those are docker container which get build on a regular basis to ensure that they are up to date. For that reason I would also like to automatically upgrade the signal-cli / odwnlaod the latest released version. Theoretically github can do that via https://github.com/AsamK/signal-cli/releases/latest/download/signal-cli-Linux.tar.gz but as the version number is also induced in the filename no automation can be established easily. 

Would it be possible to not include the version number in the files of future releases so an automatic upgrade can be done?

Thanks!

**Comment by exquo** [comment]
You can use [GitHub API](https://docs.github.com/en/rest/reference/releases#get-the-latest-release) and a little scripting to download the latest release files. For instance, to get the latest version number:

	curl -s https://api.github.com/repos/AsamK/signal-cli/releases/latest |  jq -j '.tag_name'

See some similar usage in [this script](https://github.com/exquo/signal-libs-build/blob/1ac43d28c5e1fa2356d6fc16ae1a0e6de42246fc/util.sh#L22).

**Comment by KingUdo** [comment]
I do agree, but wouldn't it be easier to use the native GitHub methods?

**Comment by AsamK** [comment]
I think it's a good idea to have the version name in the file names
Makes it clearer and prevents confusion when downloading the files manually.
