### ISSUE TITLE
Couldn't create QR code: no data to encode

### ISSUE THREAD

**Issue by RadovanPelka** [AsamK/signal-cli#938]
![image](https://user-images.githubusercontent.com/29738200/163726262-0e9f7677-d5f0-42c4-b2ec-dcd246a49139.png)

Re-link: https://github.com/bbernhard/signal-cli-rest-api/issues/231#issuecomment-1100622408

**Comment by samsungderdull** [comment]
Got the same issue here with exact output. Thanks.

**Comment by AsamK** [comment]
No idea what's wrong here, I don't think it's an issue in signal-cli.
It's either a problem with the network or the signal servers ...

**Comment by jrmgx** [comment]
I have the same issue, it worked well for some time and now I have that message.
Is there a fix or anything to do? I see this issue is closed but I can not find a solution.
If there is an error with signal server, what it is? More info would be really appreciated.
Thank you for your help :)
