### ISSUE TITLE
Missing required native library dependency: libsignal-client on windows 10 64

### ISSUE THREAD

**Issue by octopode-us** [AsamK/signal-cli#945]
Hello, I was using the signal-cli in 0.10.4.2 version and I switched to 0.10.5 to solve an  issue. Unfortunately, I am not able to use it now and I get this issue report saying "Missing required native library dependency: libsignal-client"

If you have any idea ...

Thanks a lot

**Comment by exquo** [comment]
When replacing the library in the `.jar` file, you need the right version. For signal-cli v0.10.5 (current), the version of libsignal-client should be v0.15.0. See [this section in the wiki](https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal#determine-the-required-libsignal-client-version).

But you shouldn't need to replace the file manually: the [package in the release](https://github.com/AsamK/signal-cli/releases/download/v0.10.5/signal-cli-0.10.5-Windows.tar.gz) should just work.
