### ISSUE TITLE
does signal-cli also suffer from Signal-Android/issues/6734?

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#95]
Signal-Android issue: https://github.com/WhisperSystems/Signal-Android/issues/6734#issuecomment-308909306
libsignal-fix: https://github.com/WhisperSystems/libsignal-service-java/commit/089b7f11239eaa475a78ae064c6df22b5b88b74f

**Comment by AsamK** [comment]
Probably, though signal-cli doesn't offer an unencrypted fallback.

**Comment by Trolldemorted** [comment]
Just experienced it, if i understand it correctly this unables us from sending messages to someone who re-registered and now has fewer slave devices than before.

Sent you a PR for libsignal-service-java that should do the trick.

**Comment by Trolldemorted** [comment]
fixed by 9b56aa625959f3bc8d0fa6bedc4be52b4862b053 i suppose
