### ISSUE TITLE
Missing UnregisteredUserException when sending message to multiple recipients via D-BUS

### ISSUE THREAD

**Issue by jokebattle3** [AsamK/signal-cli#957]
I'm running signal-cli 10.0.6 on a linux debian server.

When sending a single message via the D-BUS interface to a single number (which is not registered at signal) it throws the exception UnregisteredUserException, which I'm able to catch when doing the call to the D-BUS.

However when sending a single message via the D-BUS to multiple numbers, lets's say two valid numbers and one number which is not registered at signal it does not thrown any exception UnregisteredUserException.

How it is possible to detect for which number the sending fails and accordingly is an invalid number?

Thank you for any help and for your effort in this project.

**Comment by AsamK** [comment]
That's a limitation of the current dbus interface. It can only return an error or success state, but no detailed send result.
An alternative is the JSON-RPC interface, which provides a detailed result when using the send command.

**Comment by jokebattle3** [comment]
Alright, then I will switch over to the RPC-Interface then. Thank you for your quick reply @AsamK.
