### ISSUE TITLE
Receive emoji reactions through the DBUS interface

### ISSUE THREAD

**Issue by opensource25** [AsamK/signal-cli#963]
I use the signal-cli with python via the DBUS interface to code a bot. Now I want to react to emoji reactions like thump up, but I can't find that or how this is possible. So when I don't was to blind to find it, this is a feature request.

**Comment by bublath** [comment]
I'm getting a signal via MessageReceived and MessageReceivedV2 whenever I do a reaction. 
The field "extras" in MessageReceivedV2 contains an entry "reaction" which again contains an entry "emoji" with the unicode of the reaction emoji.
I'm doing this in Perl, so I don't know how it will look like in python, but the data is there.
