### ISSUE TITLE
Invalid captcha given

### ISSUE THREAD

**Issue by mkintzel** [AsamK/signal-cli#968]
Trying to register a number with the required captcha string.  I think your instructions are good and easy to follow but I keep getting the same error: "invalid captcha given" - can you see from the strings below what I'm missing?

```
mark@chocolate:~/signal $ curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/register/+13168385710'
{"error":"Captcha required for verification, use --captcha CAPTCHA\nTo get the token, go to https://signalcaptchas.org/registration/generate.html\nCheck the developer tools (F12) console for a failed redirect to signalcaptcha://\nEverything after signalcaptcha:// is the captcha token.\n"}mark@chocolate:~/signal $ 
mark@chocolate:~/signal $ 
mark@chocolate:~/signal $ 
mark@chocolate:~/signal $ curl -X POST -H "Content-Type: application/json" -d '{"captcha":"signal-recaptcha-v2.6LfBXs0bAAAAAAjkDyyI1Lk5gBAUWfhI_bIyox5W.registration.03AGdBq26e2QkZIVcE2g8agAihNb09CXOlAnKKmiXk_1Uu41kagGbTbzqhFSPgyNI1hZk5Lhkowqi2J39xL2Xh3dqQh1iUybm25rJ2AnOF4nlCqbZN8rgU8f1DOSf8VEvKr_Y3O2Vh00lNC6-zh0gi7feI3R02KTVb09YvGW61D83oha_qwIa-e9nJFsNHMfE73Nux4se4VxYJ3417pFGlReBGx5aIkGaC4qcglWCdUEiuKOykeRsyuajznujJ0rIqLgRuMNarITBRydaokFc8l0qwG5HLPsxaPlQqVbHw3QqC-fS6r78IZphc2bzlv9FnZS1q14o41m6QAwNP63dwVR9AUiqMM97wvRWluzy509VbuWcVT5clTyqaaRblF3Ycc-kdrKK1GfylqXC578sfpnkfEfMEck211mdtFz25185sfzhN5r8vBaOcNLhLG05Vh5iontDQkezaZA7CxdMplG7oQr5aRJYuKtaCFhGYh0tdzrPcxnJ6UoX7jBovca88Bk05S6-dVfO29IFqrjNp-xPHcN8dHSD6RKAUidaIbB0oQbNaMjiTUKtbCtHkAN2IX6cfQxbCDZUzhPYOCOj21na8J44yz80Kzs7KSk1YOCrdxQCiqXrV5zgNPBuP0ETDgA1PDKuMHcWfsPRpnGFzlI13-xXaY5L4MxkKQ1LQzWyJzGwwqVx4hiKhUkwxlbTXbzTeg6b9Y13m-s6354B0H7_dOVmY0qv6rBUwJTQqcWXpM2hs_tn2jVZbw6gc205ChuoVD5ZTS_QrMrF0kGkopL4p3c9ZNxpRz5-dooIARBi1p_wAHur1X35Zfp3Qh40aED1SLlo3W8tzOjuwK1g_rv_gjaD6D7FyrZH78vxRf_EVXd_u0Zw"}' 'http://127.0.0.1:8080/v1/register/+13168385710'
{"error":"Invalid captcha given.\n"}mark@chocolate:~/signal $

**Comment by AsamK** [comment]
That looks correct, just make sure that a captcha can only be used once and has a time limit.
There's also a second page for creating captchas, maybe it works with that one: https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha

**Comment by MatzFan** [comment]
@mkintzel I take it you are using the [REST API](https://github.com/bbernhard/signal-cli-rest-api) in Docker.

In that case shouldn't the captcha data sent just be the token - in your example above beginning `03AGdB..`

Grab a new captcha & lose the `signal-recaptcha-v2.6LfBXs0bAAAAAAjkDyyI1Lk5gBAUWfhI_bIyox5W.registration.` part?

**Comment by mkintzel** [comment]
Thank you both - I am getting a different error message now (equest verify error: StatusCode: 400).  tried both the original captcha page and the new one listed in the link above.  Also, noticed the same comment as @MatzFan mentioned to start with the 03.... part.
Here is the current message:
curl -X POST -H "Content-Type: application/json" -d '{"captcha":"03AGdBq27Q6f5FEQ7QtUaTiFlqaqHtEEVCdwbP1CNSnPRBGLfgoSKaS5dHj3NAOxLWxzBefg5NHzT8iYfTjaz74L5DSfcljqgYU1HQYps2PFq0SpFrO9RyUjCbXbiRrze8gHwAnNubJMs0r4RFqm9BCYVDwEIf0voYUjycXFiH8pWWG08aGcMl0qI5ZBqlh0ei0OXRyScH-OetR9geV-cn599HTud1_Jgrvn2hssb8q9OFRH70po_eMVemiiovGTIksw2uHs8wkcPlFUOs9ZcWljp8oxmnxt7kFI-TFcInLFI4txG1QvsZvuFUUK-UQATqEkTMs_beGsXI4tka7lNWde5dkiBm54ksutfXU1nuJHkPhTKxZ8EEQO_STCfh9Qg9wjL4FqTV6gRzIrraNzwbICh3fKMeHtGt8MfTZ7_FR3A6nZRUScYtAB1qJsy8TDEgEx2xj1eYmt07QKrdgSxd7wseSgJCo17120aqMRN4LS8hz94boxNoj5PquogJ4rqvf0_ZNCVRztlogyz2h8gIXfP4Yqfvyb_GpYKmYuPk119s7l25folYPydFGeKdmAlUtk9cr96hbI6LIefFPuFg_R3zHuOHNtdNq_Rn4z8gGNQeyMXJtsU9N5doEGWeruAd_aLRqGG2ygMVLHWdoY3hqs-0zSm0ZvFdcihMgX3LoHV2xygsARur9hXV4S7i4nDanIanx-05b5LgEAdnwOIK2tRIHPkWeqr2xInBaNW7E-V951WmjaxO2CCtKVJNd3IuDMkFD3VKDhw24--s4mqm3PWzr7pa_55CLLmSvowwTFw_ju2TO8weli29g__CaHAqO-bSYjtkXqA9nYfzF17VPk1Kn1u1Hn2ZIVecnQ1SDTN00Gw_IPCz1U"}' 'http://127.0.0.1:8080/v1/register/+13168385710'
{"error":"Request verify error: StatusCode: 400\n"}

**Comment by MatzFan** [comment]
@mkintzel given the solution to #958, it appears I mislead you in my comment above. The arg you provided to `--captcha` looks correct. I've just successfully registered my landline with exactly such a string starting "signal-recaptcha-v2.6LfBXs0bAAAAAAjkDyyI1Lk5gBAUWfhI_bIyox5W.registration.\<token-here\>"

I did notice that your captcha token was 885 characters long, whereas the ones I'm getting from https://signalcaptchas.org/registration/generate.html are all just over 1,500 characters long. Hope this helps.

@AsamK thanks for the awesome app btw.

**Comment by DrOteonu-Nanquanu** [comment]
When registering with you have to provide a captcha code in some cases. The instructions on the github repository of signal-cli seem not up to date (or are not working for all browsers?) on how to do this. I found out the following way when using FireFox (version 100.0.2, on Linux): after having completed the captcha, press cancel on the pop-up that appears. Then press F12. Then select the tab "Inspector". Then enter in the search field "recaptacha-token" and hit enter. Then you'll see the code appearing. Double click the code, and with your right mouse button, select "copy". Do this quickly, because the code expires soon. If the code expires, this is shown on the webpage on which you made the captcha.

Can someone reproduce this successfully? Is this a valid way to retrieve the full captcha token with FireFox?

**Comment by DrOteonu-Nanquanu** [comment]
PS wouldn't it be an idea to write a javascript wrapper around [https://signalcaptchas.org/challenge/generate.html] that shows the captcha-token on the page, with a button to copy it for you to the clipboard? That would avoid a lot of confusion among signal-cli users...

Then the developers of signal-cli can keep it up-to-date with the newest captcha tool of Google, without having to change the manual for the signal-cli users. And it'll be the same for everyone, independent of the browser you use.

**Comment by MatzFan** [comment]
@DrOteonu-Nanquanu this should probably appear under #958 but you are right. The request which includes the captcha token (upon successful completion of the captcha challenge) is a POST  with the following path: https://www.google.com/recaptcha/enterprise/userverify. The _response_ includes just the captcha token in the json under key "1". The _request_ includes the 40 character site key for signalcaptchas.org which is 6LfBXs0bAAAAAAjkDyyI1Lk5gBAUWfhI_bIyox5W. See screen shots below.

As the whole of the string before the token itself is unchanging the best solution may be to simply refactor the code handling the `--captcha` flag to accept the token only and prepend the static part:
 "**signal-recaptcha-v2.6LfBXs0bAAAAAAjkDyyI1Lk5gBAUWfhI_bIyox5W.registration.**" on to the token string.

Note the screenshots in the wiki page https://github.com/AsamK/signal-cli/wiki/Registration-with-captcha appear to be out of date.

You should be able to get your account registered now by manually adding the part in bold in front of a valid token.

![userverify](https://user-images.githubusercontent.com/3764715/173195519-b69ae7c4-9817-4357-b687-007763ff7183.png)

![token](https://user-images.githubusercontent.com/3764715/173195531-f9f3a6aa-eeb0-4132-b1f9-26101b0a5f4d.png)

**Comment by AsamK** [comment]
I don't want to add the static part in the front to the signal-cli code. It could change at any time and would then need a program update.
I've updated the wiki page a bit, also feel free to edit that page.
