### ISSUE TITLE
cli / dbus command to getContacts(<phone number>) ?

### ISSUE THREAD

**Issue by vincib** [AsamK/signal-cli#97]
Hi everyone, 

this is a feature request for the (awesome) signal-cli : the Signal Protocol proposes a method accountManager.getContacts(<phone number>) that checks whether a phone number in our address book is using Signal or not. 

Api code here : https://github.com/WhisperSystems/libsignal-service-java/blob/master/java/src/main/java/org/whispersystems/signalservice/api/SignalServiceAccountManager.java#L200

It would be great if we could launch signal-cli (or use a dbus command) to ask for the verification of our contacts ?
(Thanks to that, any web service using SMS could choose whether they would contact someone via Signal or via a standard SMS ;) )

**Comment by vincib** [comment]
I wrote a crude but working version of it here : 

https://github.com/vincib/signal-cli/commit/b3be445865c5f80022685332c9c51803693b8de4

example: 
`  ./signal-cli -u +33612345678 getContact --number +33600000000`
will print the phone number only if it is using Signal (I know, horrible design) 

(disclaimer: last time I wrote some java code it was 1998...)

**Comment by AsamK** [comment]
Now implemented as `getUserStatus` command
