### ISSUE TITLE
Hide number

### ISSUE THREAD

**Issue by Gottarocket** [AsamK/signal-cli#973]
Any way to hide phonenumber as identifier when sending notifications?. I use [this](https://github.com/bbernhard/signal-cli-rest-api) to get notification. Created a issue there but they asked to confirm here. If its set on server we have physical access to then its not needed but storing phonenumber in json file in plaintext seems odd. Just wanted to know if it could be saved as hash and then called once setup is done. You can refer to the recent issue there.

**Comment by AsamK** [comment]
The phone number is required for the working of signal-cli, so it can't be stored as hash.
