### ISSUE TITLE
profile support

### ISSUE THREAD

**Issue by Trolldemorted** [AsamK/signal-cli#98]
The official clients can now set/view profiles :tada: - it would be great if the cli master could do that too!

**Comment by Atomic-Bean** [comment]
Setting is now possible, getting is an interesting one though. The result of getting the names would obviously be outputting it to stdout, but what exactly would getting the profile icon do? The individual user and group icons are already present in the config data so would the command just print the file path to stdout, or would it instead require an extra "path" variable from the user so signal-cli will copy the file to said path?

**Comment by Tsjippy** [comment]
Just getting the name would be awesome

**Comment by johnfreed** [comment]
I believe this can be closed, @AsamK .

Viewing arbitary profiles (at least the name, blocked status, and expiration timer) was implemented in the main program with the listContacts subcommand, and in the DBus daemon with the getContactName, IsContactBlocked, and listNumbers methods.

Setting these values for one's own profile can be done via the updateProfile subcommand and DBus method.

See the [Feature Matrix](https://github.com/AsamK/signal-cli/wiki/Feature-Matrix)

**Comment by AsamK** [comment]
The `listContacts` command now outputs all profile information in json mode (5f941004f5006b286690df2a93bc47ace3b59270).
