### ISSUE TITLE
In "Received a group v1 sync message" warning message, name the group.

### ISSUE THREAD

**Issue by brad2014** [AsamK/signal-cli#983]
I keep seeing this warning:

```
WARN  IncomingMessageHandler - Received a group v1 sync message, that can't be handled anymore, ignoring.
```

I'm not sure how to get rid of it, or understand *who* is sending me the old sync message.  Would it be possible to add that info to the error message, so one could leave/block old groups / old devices?

Perhaps:

```
WARN  IncomingMessageHandler - Received a group v1 sync message from (sender: 12345678912, group: XYZ), that can't be handled anymore, ignoring.
```

**Comment by AsamK** [comment]
The group v1 sync message is sent by the linked main device.
With version 0.10.8 those messages can be handled again and the message won't be shown anymore (e9e66e1005ce39684d9d128933bb7edaf99d8de1)
