### ISSUE TITLE
setPin return 404

### ISSUE THREAD

**Issue by yayo** [AsamK/signal-cli#985]
signal-cli-0.10.9-Linux.tar.gz

/usr/local/signal-cli/bin/signal-cli --config /tmp/signal-cli -a +WHATEVER_NUMBER setPin 123456 2>&1 | grep -e fe7c1bfae98f9b073d220366ea31163ee82f6d04bead774f71ca8e5c40847bfe

Set pin error: [404] Response: Response{protocol=http/1.1, code=404, message=Not Found, url=https://api.backup.signal.org/v1/token/fe7c1bfae98f9b073d220366ea31163ee82f6d04bead774f71ca8e5c40847bfe}

**Comment by AsamK** [comment]
Thanks for reporting the config for the signal pin storage (KBS) had changed.
