### ISSUE TITLE
signal-cli: error: too few arguments for trust-new-identities

### ISSUE THREAD

**Issue by rdtech2020** [AsamK/signal-cli#986]
`signal-cli --dbus-system -u ACCOUNT --trust-new-identities always`  I am getting error : signal-cli: error: too few arguments

**Comment by AsamK** [comment]
you're missing the command part, i.e. `receive`, `daemon`, ...
Also the `--trust-new-identities` flag should be given for the daemon call.
e.g. `signal-cli -u ACCOUNT --trust-new-identities=always daemon --dbus-system`
