### ISSUE TITLE
migration from signal-cli to phone possible?

### ISSUE THREAD

**Issue by sans-c** [AsamK/signal-cli#997]
Greetings,

the title probably says it all. I registered a number with signal-cli which curently acts as the master device. Is there any way to migrate to the official phone app without re-registering?

As a "workaroud" I tried to link the android app to signal-cli but that doesn't seem to work because there is no way to scan a QR-code with the freshly installed app, or is there?

I imagine this question must have been asked before but I couldn't find anything skimming through the man-pages, wiki or issues. Thank you in advance.

**Comment by AsamK** [comment]
it's not possible without re-registering.
The official mobile apps don't support linking to another device (except I think the iPad version).
Theoretically it would be possible to write a script that converts signa-cli data files to a Signal-Android backup file format, but I don't think anyone has done that.
